### PR TITLE
compiler: adjust init/_deploy method offsets during optimization

### LINKED ISSUE #1728: Can't deploy contract with `init()` and `_deploy()`
neo-go version 0.92.0-159-g71494e6a

If `init()` function contains `if` branch, then it is impossible to deploy contract with `_deploy()` method.

```go
package example
import "github.com/nspcc-dev/neo-go/pkg/interop/runtime"

func init() {
	if true { // useless if branch
	} else {
	}
}

func _deploy(_ interface{}, isUpdate bool) {
	runtime.Log("Deploy")
}
```

If you drop `if` branch or drop `_deploy()` function, contract will be deployed in the chain.

There are different error messages depending whether `if` branch contains `else` or not:
- with `else`: 
`failed to test-invoke deployment script: error encountered at instruction 1 (SYSCALL): error during call from native: error encountered at instruction 15 (STSFLD5): runtime error: index out of range [5] with length 0`
- without `else`: 
`failed to test-invoke deployment script: error encountered at instruction 1 (SYSCALL): error during call from native: error encountered at instruction 24 (RET): invalid return values count: expected 0, got 2`

Seems like `if` branch drops some values on stack that can't be handled correctly by `_deploy()` function.

### PR DESCRIPTION
**Pull request by fyrchik**
Close #1728 .

Because `_initialize` and `_deploy` methods encompass multiple
Go functions, their offsets are stored differently and need
special treatment.

### CODE REVIEW

File: pkg/compiler/codegen.go [hunk 1]
```diff
@@ -2011,28 +2011,41 @@ func (c *codegen) writeJumps(b []byte) ([]byte, error) {
 			}
 		}
 	}
+
+	if c.deployEndOffset >= 0 {
+		_, end := correctRange(uint16(c.initEndOffset+1), uint16(c.deployEndOffset), offsets)
+		c.deployEndOffset = int(end)
```
Comment (roman-khimov) [inline pkg/compiler/codegen.go:2017]: Why do you adjust `deploy` first and then `init`? Shouldn't it be the other way around (going through the script sequentially)?

Comment (roman-khimov) [reply pkg/compiler/codegen.go:2017]: Or it probably doesn't really matter here.

Comment (fyrchik) [reply pkg/compiler/codegen.go:2017]: At first it was so because `correctRange` expects `initEndOffset+1 = deployStartOffset` to be unchanged. However we don't really care use start offset here, so yes, it doesn't matter.

**Review by roman-khimov — APPROVED** [review]
