### PR TITLE
rpcsrv: fix findstorage if a contract state is not found

### LINKED ISSUE #3370: findstorage rpc response difference if state is not found
## Current Behavior
neo-go returns `null` for the `results` key if a contract state is not found. C# returns an empty list

## Expected Behavior
return an empty list

## Steps to Reproduce
```shell

curl --location 'https://rpc10.n3.nspcc.ru:10331' \
--header 'Content-Type: text/plain' \
--data '{
  "jsonrpc": "2.0",
  "method": "findstorage",
  "params": [-50,"", 0],
  "id": 1
}'
```
response
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "results": null,
        "next": 0,
        "truncated": false
    }
}
```

for C#
```shell
curl --location 'http://seed1t5.neo.org:20332' \
--header 'Content-Type: text/plain' \
--data '{
  "jsonrpc": "2.0",
  "method": "findstorage",
  "params": [-50,"", 0],
  "id": 1
}'
```
response
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "truncated": false,
        "next": 0,
        "results": []
    }
}
```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3370

### CODE REVIEW

File: pkg/services/rpcsrv/server.go [hunk 1]
```diff
@@ -1750,7 +1750,8 @@ func (s *Server) findStorageInternal(id int32, prefix []byte, start, take int, s
 	var (
 		i   int
 		end = start + take
-		res = new(result.FindStorage)
+		// Results is an empty list if a contract state is not found as it is in C# implementation.
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server.go:1753]: s/Results/res (if referring to a var) or s/Results is/Result is (if talking about generic operation result).

**Review by AnnaShaleva — COMMENTED** [review]
Otherwise LGTM.

**Review by AnnaShaleva — APPROVED** [review]
