### PR TITLE
core, vm: fix System.Contract.CallNative async callbacks and RET processing

### LINKED ISSUE #4514: Incorrect execution order of `System.Contract.CallNative` callbacks
**Describe the bug**
Looks like the execution order of native contract callbacks (methods like `onNEP17Payment` called by native Neo/Gas or `_deploy` called by native Management) is incorrect:
https://github.com/neo-project/neo/blob/3266fc0e7b04ce4d469a534e52e72c19c39037c5/src/Neo/SmartContract/Native/ContractManagement.cs#L67
The problem is that the callback execution starts only *after* `System.Contract.CallNative` instruction execution is finished (and the corresponding execution context is unloaded from the invocation stack). However, the callback should be executed *during* `System.Contract.CallNative` instruction processing, so that the end of `System.Contract.CallNative`
execution happens *after* callback execution, because the callback is a part of the `System.Contract.CallNative`.

**To Reproduce**
For example, take a look at transaction https://neotube.io/transaction/0x2e3ede68fc313e7f56b7751bc1934055f5d6adb243b5f3df37f92b960210705d. It deploys some contract (and, consequently, calls its `_deploy` method). I added a log to the C# VM's code that prints instruction and RC value *after* every instruction execution: https://github.com/AnnaShaleva/neo-vm/tree/rc-v2-with-log.

The resulting prettified instruction dump is:
```
[PUSHDATA2 <manifestBytes>]1    // pushing arguments of System.Contract.Call for `deploy`.
[PUSHDATA2 <nefBytes>]2
[PUSH2]3
[PACK]3
[PUSH15]4
[PUSHDATA1 6465706C6F79]5
[PUSHDATA1 FDA3FA4346EA532A258FC497DDADDB6437C9FDFF]6
[SYSCALL 627D5B52]2 // System.Contract.Call of native Management's `deploy`.
[PUSH0]3
[SYSCALL 1AF77B67]4 // the end of execution of System.Contract.CallNative of native Management's `deploy`.
[INITSSLOT 0D]17    // the start of contract's `_deploy` method execution.
[PUSHDATA1 B9FA24B949D84A8A023FABE9856AA8C543C5A65B]18 [STSFLD 0B]17 [PUSHDATA1 A05B4285FDFBBD66E80EAD00D732F8D4F6052304]18 [STSFLD0]17 [PUSHDATA1 0101]18 [CONVERT 30]18 [STSFLD 07]17 [PUSHDATA1 0102]18 [CONVERT 30]18 [STSFLD 09]17 [PUSHDATA1 0103]18 [CONVERT 30]18 [STSFLD 0A]17 [PUSHDATA1 0104]18 [CONVERT 30]18 [STSFLD4]17 [PUSHDATA1 0105]18 [CONVERT 30]18 [STSFLD 08]17 [PUSHDATA1 0106]18 [CONVERT 30]18 [STSFLD2]17 [PUSHDATA1 0107]18 [CONVERT 30]18 [STSFLD1]17 [PUSHDATA1 0201]18 [CONVERT 30]18 [STSFLD3]17 [PUSHDATA1 6173736574]18 [STSFLD 0C]17 [LDSFLD 0C]18 [SYSCALL 9BF667CE]19 [PUSH2]20 [PACK]20 [STSFLD5]19 [PUSH14]20 [STSFLD6]19 [RET]19 [INITSLOT 0002]19 [LDSFLD0]20 [LDSFLD1]21 [SYSCALL 9BF667CE]22 [SYSCALL E63F1884]19 [NEWARRAY0]20 [DUP]21 [LDSFLD1]22 [APPEND]21 [DUP]22 [LDSFLD0]23 [APPEND]22 [PUSHDATA1 4F6E4465706C6F79]23
[SYSCALL 95016F61]19
[RET]505
[RET]505
[RET]505 
```
I added the same log to the NeoGo node: https://github.com/nspcc-dev/neo-go/pull/4201, which gives us the following output:
```
[PUSHDATA2 <manifestBytes>]1    // pushing arguments of System.Contract.Call for `deploy`.
[PUSHDATA2 <nefBytes>]2
[PUSH2]3
[PACK]3
[PUSH15]4
[PUSHDATA1 6465706c6f79]5
[PUSHDATA1 fda3fa4346ea532a258fc497ddaddb6437c9fdff]6
[SYSCALL 627d5b52]2 // System.Contract.Call of native Management's `deploy`.
[PUSH0]3
        //  <-- pay attention, the end of System.Contract.CallNative syscall execution (SYSCALL 1af77b67) is not here, unlike with the C# node.
[INITSSLOT 0d]17 // the start of contract's `_deploy` method execution.
[PUSHDATA1 b9fa24b949d84a8a023fabe9856aa8c543c5a65b]18 [STSFLD 0b]17 [PUSHDATA1 a05b4285fdfbbd66e80ead00d732f8d4f6052304]18 [STSFLD0]17 [PUSHDATA1 0101]18 [CONVERT 30]18 [STSFLD 07]17 [PUSHDATA1 0102]18 [CONVERT 30]18 [STSFLD 09]17 [PUSHDATA1 0103]18 [CONVERT 30]18 [STSFLD 0a]17 [PUSHDATA1 0104]18 [CONVERT 30]18 [STSFLD4]17 [PUSHDATA1 0105]18 [CONVERT 30]18 [STSFLD 08]17 [PUSHDATA1 0106]18 [CONVERT 30]18 [STSFLD2]17 [PUSHDATA1 0107]18 [CONVERT 30]18 [STSFLD1]17 [PUSHDATA1 0201]18 [CONVERT 30]18 [STSFLD3]17 [PUSHDATA1 6173736574]18 [STSFLD 0c]17 [LDSFLD 0c]18 [SYSCALL 9bf667ce]19 [PUSH2]20 [PACK]20 [STSFLD5]19 [PUSH14]20 [STSFLD6]19 [RET]19 [INITSLOT 0002]19 [LDSFLD0]20 [LDSFLD1]21 [SYSCALL 9bf667ce]22 [SYSCALL e63f1884]19 [NEWARRAY0]20 [DUP]21 [LDSFLD1]22 [APPEND]21 [DUP]22 [LDSFLD0]23 [APPEND]22 [PUSHDATA1 4f6e4465706c6f79]23
[SYSCALL 95016f61]19 
[RET]2                // the end of contract's `_deploy` method execution.
[SYSCALL 1af77b67]505 // the end of execution of System.Contract.CallNative of native Management's `deploy`.
[RET]505
[RET]505 
```

So we see that the order of  `[SYSCALL 1af77b67]` and `_deploy` execution differs from the C# node.

**Expected behavior**

Native callbacks should be executed *before the end* of `System.Contract.CallNative` instruction processing.

**Platform:**
 - Version: 3.9.2.

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Closes https://github.com/neo-project/neo/issues/4514 via the following refactoring:

1. Execute asynchronous calls from native contracts in a standard way via pushing new context to invocation stack without immediate nested execution as in ref.: https://github.com/neo-project/neo/blob/43e66b82751bbc7f84689a68f4991b274174ddb5/src/Neo/SmartContract/ApplicationEngine.cs#L587
2. Bind continuation of parent's context execution to the spawned child's context: https://github.com/neo-project/neo/blob/43e66b82751bbc7f84689a68f4991b274174ddb5/src/Neo/SmartContract/ApplicationEngine.cs#L602
3. Execute parent's continuation on the child's context unloading: https://github.com/neo-project/neo/blob/43e66b82751bbc7f84689a68f4991b274174ddb5/src/Neo/SmartContract/ApplicationEngine.cs#L635-L640

Refactor RET handler to make the scheme above work properly and to follow presizely the reference RET behaviour:

1. Firstly, pop unloaded context from istack and copy the return values to the parent's context. Fix NeoGo VM bug where values were POPped from the child's context instead of PEEKing: https://github.com/neo-project/neo-vm/blob/ed0eb66359fd1d76ddb5be91cc5a703ddc714a18/src/Neo.VM/JumpTable/JumpTable.Control.cs#L540
2. After that, execute context unloading callbacks: https://github.com/neo-project/neo-vm/blob/ed0eb66359fd1d76ddb5be91cc5a703ddc714a18/src/Neo.VM/JumpTable/JumpTable.Control.cs#L544

### CODE REVIEW

**Comment by AnnaShaleva** [comment]
RC compatibility check is in progress.

File: pkg/core/native/native_test/neo_test.go [hunk 1]
```diff
@@ -967,7 +968,10 @@ func TestNEO_RegisterViaNEP27(t *testing.T) {
 	}
 
 	neoValidatorsInvoker.AddNewBlock(t, txes...)
-	for _, tx := range txes {
+	for i, tx := range txes {
+		aer, err := e.Chain.GetAppExecResults(tx.Hash(), trigger.Application)
+		require.NoError(t, err)
+		require.Equal(t, vmstate.Halt, aer[0].VMState, aer[0].FaultException, i)
```
Comment (roman-khimov) [inline pkg/core/native/native_test/neo_test.go:974]: Duplicating `CheckHalt`?

File: pkg/core/interop/contract/call.go [hunk 2]
```diff
@@ -174,34 +182,26 @@ func callExFromNative(ic *interop.Context, caller util.Uint160, cs *state.Contra
 		}
 		return nil
 	}
+	var onUnloadedF func(v *vm.VM)
+	if len(onUnloaded) != 0 {
+		onUnloadedF = onUnloaded[0]
+	}
 	ic.VM.LoadNEFMethod(&cs.NEF, &cs.Manifest, caller, cs.Hash, f,
-		hasReturn, methodOff, initOff, onUnload, whitelisted)
+		hasReturn, methodOff, initOff, onUnload, onUnloadedF, whitelisted)
```
Comment (roman-khimov) [inline pkg/core/interop/contract/call.go:190]: Two quick thoughts:
 * changing `vm.SyscallHandler` to something like `func(*VM, uint32) (func (), error)`, that is returning "pending context callback" right from the syscall handler, not loading it explicitly with the new NEF
 * doing the same implicitly with `for range`/`yield`, but I have not arranged a proper way, maybe an iterator can be returned from `SyscallHandler` as well to iterate in the same context (in `RET`? or before choosing the next instruction from the same context?), while new contexts loaded would be executed normally

File: pkg/core/native/management.go [hunk 3]
```diff
@@ -447,12 +449,14 @@ func (m *Management) updateWithData(ic *interop.Context, args []stackitem.Item)
 	if err != nil {
 		panic(err)
 	}
-	m.callDeploy(ic, contract, args[2], true)
-	err = m.emitNotification(ic, contractUpdateNotificationName, contract.Hash)
-	if err != nil {
-		panic(err)
-	}
-	return stackitem.Null{}
+	m.callDeployAsync(ic, contract, args[2], true, func(v *vm.VM) {
```
Comment (roman-khimov) [inline pkg/core/native/management.go:452]: Because I feel the pain here. It can work, but something like
```
yield callDeployCallback
// keep going
```
would be _so_ much better.

File: pkg/core/native/native_test/neo_test.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/core/native/native_test/neo_test.go:974]: Shouldn't be here, it's a remnant from debugging.

File: pkg/core/interop/contract/call.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go:189]: So far, if I understand the idea correctly, both approaches face difficulty when there's more than one `CallFromNative` in a `SyscallHandler`. In this case, `func(*VM, uint32) (func (), error)` is not enough; for two `CallFromNative` calls we need `func(*VM, uint32) (func (*VM) func(*VM), error)`, i.e. we need to return "pending context callback" that returns another callback for another child context. Given the example of `recoverFund` method, the resulting code will look like:
```go
	...
	cs, err := ic.GetContract(token)
	if err != nil {
		panic(fmt.Errorf("failed to get contract %s: %w", token.StringLE(), err))
	}
	if !cs.Manifest.IsStandardSupported("NEP-17") {
		panic(fmt.Errorf("contract %s does not support NEP-17", token.StringLE()))
	}
	err = contract.CallFromNative(ic, acc, cs, "balanceOf", []stackitem.Item{stackitem.NewByteArray(acc.BytesBE())}, true)
	if err != nil {
		panic(fmt.Errorf("failed to call balanceOf/%s: %w", token.StringLE(), err))
	}
	return func(v *vm.VM) func(v *vm.VM) {
		balance := v.Estack().Pop().BigInt() // pop the result of `balanceOf` from the parent context's stack.
		if balance.Sign() <= 0 {
			popArgsPushRes(stackitem.NewBool(false))
			return nil
		}
		err = contract.CallFromNative(ic, acc, cs, "transfer", []stackitem.Item{
			stackitem.NewByteArray(acc.BytesBE()),
			stackitem.NewByteArray(nativehashes.Treasury.BytesBE()),
			stackitem.NewBigInteger(balance),
			stackitem.Null{},
		}, true)
		if err != nil {
			panic(fmt.Errorf("failed to call transfer/%s: %w", token.StringLE(), err))
		}
		return func(v *vm.VM) {
			ok := v.Estack().Pop().Bool() // pop the result of `transfer` from the parent context's stack.
			if !ok {
				panic(fmt.Errorf("transfer/%s from %s to %s failed", token.StringLE(), acc.StringLE(), nativehashes.Treasury.StringLE()))
			}
			err = ic.AddNotification(p.Hash, "RecoveredFund", stackitem.NewArray([]stackitem.Item{stackitem.NewByteArray(acc.BytesBE())}))
			if err != nil {
				panic(err)
			}
			popArgsPushRes(stackitem.NewBool(true))
		}
	}
```
Is it better than the current approach?

Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go:189]: In the example above `popArgsPushRes` may probably be avoided (although we need to pass the result somehow), but the overall scheme still includes nested functions.

Comment (roman-khimov) [reply pkg/core/interop/contract/call.go:189]: OK, nothing obviously better now.

File: pkg/core/native/native_test/neo_test.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/core/native/native_test/neo_test.go]: Fixed.

File: pkg/vm/context.go [hunk 4]
```diff
@@ -48,9 +48,15 @@ type scriptContext struct {
...
 	invTree *invocations.Tree
-	// onUnload is a callback that should be called after current context unloading
-	// if no exception occurs.
+	// onUnload is a callback that should be called after the current context
+	// is removed from the VM's invocation stack and after return values are
+	// copied from the unloaded context estack to the parent's context estack.
+	// This method is called even if there's an uncaught VM exception.
 	onUnload ContextUnloadCallback
+	// onUnloaded is a callback that should be called after the current context
+	// is fully unladed from the VM's invocation stack iff there's no uncaught
```
Comment (roman-khimov) [inline pkg/vm/context.go]: s/unladed/unloaded/

File: pkg/vm/context.go [hunk 5]
```diff
@@ -79,8 +85,16 @@ type contextAux struct {
...
-// ContextUnloadCallback is a callback method used on context unloading from istack.
-type ContextUnloadCallback func(v *VM, ctx *Context, commit bool) error
+type (
+	// ContextUnloadCallback is a callback method used on context unloading from istack.
+	// It is called after the context is removed from the VM's invocation stack but
+	// before return values are copied from the unloaded context estack to the parent's
+	// context estack.
+	ContextUnloadCallback func(v *VM, ctx *Context, commit bool) error
+	// ContextUnloadedCallback is a callback method that is called after the context
+	// is fully unladed from the VM's invocation stack if no exception occurs.
```
Comment (roman-khimov) [inline pkg/vm/context.go]: Same

File: pkg/vm/stack.go [hunk 6]
```diff
@@ -175,10 +175,17 @@ func (s *Stack) InsertAt(e Element, n int) {
...
 func (s *Stack) Push(e Element) {
-	s.elems = append(s.elems, e)
+	s.PushNoRef(e)
 	s.refs.Add(e.value)
 }
 
+// PushNoRef pushes the given element on the stack without changing the reference
+// counter. Be super-careful when using it and only use it when you understand
+// what you're doing.
+func (s *Stack) PushNoRef(e Element) {
```
Comment (roman-khimov) [inline pkg/vm/stack.go]: Doesn't need to be exported.

File: pkg/vm/vm.go [hunk 7]
```diff
@@ -585,7 +586,8 @@ func (v *VM) step(ctx *Context) error {
 		v.state = vmstate.Fault
 		return newError(ctx.IP(), op, err)
 	}
-	return v.execute(ctx, op, param)
+	err = v.execute(ctx, op, param)
+	return err
```
Comment (roman-khimov) [inline pkg/vm/vm.go]: Useless change.

File: pkg/vm/vm.go [hunk 8]
```diff
@@ -1859,6 +1866,12 @@ func (v *VM) unloadContext(ctx *Context) {
 				panic(errors.New(errMessage))
 			}
 		}
+		if ctx.sc.onUnloaded != nil {
+			if v.uncaughtException != nil {
+				panic(fmt.Errorf("can't execute contract task continuation due to uncaught exception: %s", v.uncaughtException))
```
Comment (roman-khimov) [inline pkg/vm/vm.go]: Is it worth additional words?

File: pkg/core/interop/context.go [hunk 9]
```diff
@@ -184,8 +194,17 @@ type MethodAndPrice struct {
...
-	Func          Method
+	// Func is the synchronous method handler that doesn't contain any nested
+	// contract calls.
+	Func Method
+	// AsyncFunc is the method handler that contains a nested contract call, the
+	// result of which may (optionally) be required to continue execution of
+	// AsyncFunc. Depending on the latter, the execution of the contract's
+	// method handler may either be finished or scheduled to be finished later
+	// after the spawned child's context is unloaded from VM.
+	AsyncFunc     AsyncMethod
```
Comment (roman-khimov) [inline pkg/core/interop/context.go]: `ProlongedFunc`? I'm trying to find some better word since `Async` implies some goroutine to me which is not what's going on here. Optional, but I'm open for suggestions.

Comment (AnnaShaleva) [reply pkg/core/interop/context.go]: `FuncWithContinuation`, `DefferredFunc`, `FuncWithCb`?

File: pkg/vm/vm.go (hunk 8 above)
Comment (AnnaShaleva) [reply pkg/vm/vm.go]: A hint to a pour developer who'll be fixing exception-related RC diffs. Removed.

File: pkg/core/interop/context.go (hunk 9 above)
Comment (AnnaShaleva) [reply pkg/core/interop/context.go]: Let's decide and I rename afterwards.

Comment (roman-khimov) [reply pkg/core/interop/context.go]: `deferrable`?

Comment (AnnaShaleva) [reply pkg/core/interop/context.go]: Do we need to rename native methods as far?

Comment (roman-khimov) [reply pkg/core/interop/context.go]: Up to you. I'd expect some consistency.

**Review by roman-khimov — APPROVED** [review]

File: pkg/core/interop/context.go (hunk 9 above)
Comment (AnnaShaleva) [reply pkg/core/interop/context.go]: Let's rename, fixed.
