### PR TITLE
cli: add embedded node config

### LINKED ISSUE #3450: Supply VM console with default config
## Current Behavior

`neo-go vm` can't be started without node configuration since #2528. Although it's mandatory to have some configuration for it, we deliver NeoGo releases as a single executable, which results in:

```
anna@kiwi:~/Documents/GitProjects$ ./neo-go vm
config './config/protocol.privnet.yml' doesn't exist
```

## Expected Behavior
VM CLI should run properly even without configuration.

## Possible Solution
Provide default configuration hard-coded in the code to VM CLI during start (if no user-defined config specified).

### LINKED ISSUE #3459: Releases don't include the default configuration files
## Current Behavior
I've downloaded the latest version of Neo Go and tried to run it using the following command:
`.\neo-go-windows-amd64.exe node -m`. It didn't work: `config './config/protocol.mainnet.yml' doesn't exist.`

## Expected Behavior
Running `neo-go.exe -m` should work.

## Possible Solution
The `./config` should be shipped with the binaries, or the binary should create them if they don't exist (main net and test net).

## Steps to Reproduce

1. Download Neo Go
2. Run the binary using the `node -m` option.

## Context
It's not possible to run the node without the file. The configuration file is not small and can't be typed. Users must download it from the repository and store it in the config folder.

## Your Environment
* Version of the product used: Zephirantes
* Server setup and configuration files used: Windows Server

### PR DESCRIPTION
**Pull request by AliceInHunterland**
If `config-path` is not provided then the default config is used. If  `config-path` is provided but the directory does not contain a configuration file for the desired passed network and this directory isn't our default `./config`, the error "config '%s' doesn't exist" will be received.

Close #3450.
Close #3459.

### CODE REVIEW

File: cli/vm/vm.go [hunk 1]
```diff
@@ -24,13 +25,20 @@ func NewCommands() []cli.Command {
 }
 
 func startVMPrompt(ctx *cli.Context) error {
+	var (
+		cfg config.Config
+		err error
+	)
+
```
Comment (AnnaShaleva) [inline cli/vm/vm.go:32]: Not needed.

File: cli/vm/vm.go [hunk 2]
```diff
@@ -24,13 +25,20 @@ func NewCommands() []cli.Command {
...
 	if err := cmdargs.EnsureNone(ctx); err != nil {
 		return err
 	}
-
-	cfg, err := options.GetConfigFromContext(ctx)
-	if err != nil {
-		return cli.NewExitError(err, 1)
+	cfg = options.DefaultConfig
```
Comment (AnnaShaleva) [inline cli/vm/vm.go:36]:
```suggestion
	cfg := options.DefaultConfig
```

File: cli/vm/vm.go [hunk 3]
```diff
@@ -24,13 +25,20 @@ func NewCommands() []cli.Command {
...
+	if ctx.String("config-file") != "" || ctx.String("config-path") != "" {
+		cfg, err = options.GetConfigFromContext(ctx)
```
Comment (AnnaShaleva) [inline cli/vm/vm.go:38]:
```suggestion
		var err error
		cfg, err = options.GetConfigFromContext(ctx)
```

File: cli/vm/vm.go [hunk 4]
```diff
@@ -24,13 +25,20 @@ func NewCommands() []cli.Command {
...
+		if err != nil {
+			return cli.NewExitError(err, 1)
+		}
 	}
 	if ctx.NumFlags() == 0 {
```
Comment (AnnaShaleva) [inline cli/vm/vm.go:43]: This path must be removed, we have default config for that. It should use in-memory DB.

File: cli/options/config.go [hunk 5]
```diff
@@ -0,0 +1,48 @@
+package options
```
Comment (AnnaShaleva) [inline cli/options/config.go:1]: We need to move all configs to a separate package, maybe something like `neo-go/cli/config/`:
```
cli/config/
├── mainnet.go
├── mainnet_neofs.go
├── testnet.go
├── testnet_neofs.go
└── vm.go
...
```
These files should contain corresponding exported configurations. Then we need to create a separate CLI command (some `neo-go config generate`) that generates YAML config files in `neo-go/config` folder based on `neo-go/cli/config`. We also need to add a GA job that ensures that the content of `neo-go/config` matches the output of `neo-go config generate`.

Once it's implemented, we won't edit auto-generated YAML config files anymore. Instead, we will edit `cli/config` Go files and re-generate YAML configs.

@roman-khimov, ACK?

File: cli/options/config.go [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+
+import (
+	"github.com/nspcc-dev/neo-go/pkg/config"
+	"github.com/nspcc-dev/neo-go/pkg/core/storage/dbconfig"
+)
+
+var DefaultConfig = config.Config{
```
Comment (AnnaShaleva) [inline cli/options/config.go:8]: Exported structure needs to have a comment.

File: cli/server/server.go [hunk 7]
```diff
@@ -436,13 +436,21 @@ func mkP2PNotary(config config.P2PNotary, chain *core.Blockchain, serv *network.
...
+	)
+
 	if err := cmdargs.EnsureNone(ctx); err != nil {
 		return err
 	}
 
-	cfg, err := options.GetConfigFromContext(ctx)
-	if err != nil {
-		return cli.NewExitError(err, 1)
+	cfg = options.DefaultConfig
```
Comment (AnnaShaleva) [inline cli/server/server.go:448]: Can't be, the behaviour must not be changed, it should use privnet config by default. Let's address the previous conversation first, and then deal with the others.

File: cli/vm/vm.go (hunk 3 above)
Comment (AnnaShaleva) [reply cli/vm/vm.go:38]: And BTW, this code may be moved directly to `options.GetConfigFromContext`.

**Comment by AnnaShaleva** [comment]
> What is the default config? 

Default config for VM CLI is privnet + InMemory DB.

File: cli/config/config.go [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+func configGenerate(ctx *cli.Context) error {
+	if err := cmdargs.EnsureNone(ctx); err != nil {
+		return err
+	}
+
+	var filesToGenerate map[string]config.Config
+
+	if ctx.Bool("all") {
+		filesToGenerate = map[string]config.Config{
+			"protocol.mainnet.yml":               MainNetConfig,
```
Comment (AnnaShaleva) [inline cli/config/config.go:50]: Here and below it's `Mainnet`, `MainnetNeoFS` and etc. We're already in the `config` package.

File: cli/config/config.go [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+			filesToGenerate["protocol.privnet.docker.one.yml"] = PrivNetDockerOneConfig
+			filesToGenerate["protocol.privnet.docker.two.yml"] = PrivNetDockerTwoConfig
+			filesToGenerate["protocol.privnet.docker.three.yml"] = PrivNetDockerThreeConfig
+			filesToGenerate["protocol.privnet.docker.four.yml"] = PrivNetDockerFourConfig
+			filesToGenerate["protocol.privnet.docker.single.yml"] = PrivNetDockerSingleConfig
+		}
+	}
+
+	for fileName, cfg := range filesToGenerate {
+		if err := writeConfigToFile(cfg, filepath.Join("config", fileName)); err != nil {
```
Comment (AnnaShaleva) [inline cli/config/config.go:93]: For this you need a separate argument: target path to write config files to.

Comment (AnnaShaleva) [reply cli/config/config.go:93]: We have `--config-path` flag that is shared between all other commands, we need to reuse it.

File: cli/config/config.go [hunk 10]
```diff
@@ -0,0 +1,112 @@
...
+			return err
+		}
+	}
+	return nil
+}
+
+func writeConfigToFile(cfg config.Config, filename string) error {
+	file, err := os.Create(filename)
+	if err != nil {
+		return err
```
Comment (AnnaShaleva) [inline cli/config/config.go:103]: Here and below provide more detailed error, please.

File: cli/config/mainnet.go [hunk 11]
```diff
@@ -0,0 +1,127 @@
+package config
+
+import (
+	"time"
+
+	"github.com/nspcc-dev/neo-go/pkg/config"
+	"github.com/nspcc-dev/neo-go/pkg/core/storage/dbconfig"
+)
+
+// MainNetConfig is the configuration for the main network.
```
Comment (AnnaShaleva) [inline cli/config/mainnet.go:10]: ... for the Neo N3 mainnet.

File: cli/config/mainnet_neofs.go [hunk 12]
```diff
@@ -0,0 +1,96 @@
+package config
+
+import (
+	"time"
+
+	"github.com/nspcc-dev/neo-go/pkg/config"
+	"github.com/nspcc-dev/neo-go/pkg/core/storage/dbconfig"
+)
+
+// NeoFSMainNetConfig is the configuration for the main network.
```
Comment (AnnaShaleva) [inline cli/config/mainnet_neofs.go:10]: ... for the NeoFS mainnet.

Comment (AnnaShaleva) [reply cli/config/mainnet_neofs.go:10]: Fix here and below.

File: cli/config/privnet_docker.go [hunk 13]
```diff
@@ -0,0 +1,492 @@
+package config
+
+import (
+	"time"
+
+	"github.com/nspcc-dev/neo-go/pkg/config"
+	"github.com/nspcc-dev/neo-go/pkg/core/storage/dbconfig"
+)
+
+// PrivNetDockerOneConfig is the configuration for the first node in the private network.
```
Comment (AnnaShaleva) [inline cli/config/privnet_docker.go:10]: ...in the Dockerized private network.

File: cli/config/unit_testnet.go [hunk 14]
```diff
@@ -0,0 +1,146 @@
+package config
+
+import (
+	"time"
+
+	"github.com/nspcc-dev/neo-go/pkg/config"
+	"github.com/nspcc-dev/neo-go/pkg/core/storage/dbconfig"
+)
+
+// UnitTestNetConfig is the configuration for the unit test network.
```
Comment (AnnaShaleva) [inline cli/config/unit_testnet.go:10]: ...for the unit test network with four validators.

File: cli/config/vm.go [hunk 15]
```diff
@@ -0,0 +1,101 @@
+package config
+
+import (
+	"time"
+
+	"github.com/nspcc-dev/neo-go/pkg/config"
+	"github.com/nspcc-dev/neo-go/pkg/core/storage/dbconfig"
+)
+
+// VmConfig is the configuration for the VM.
```
Comment (AnnaShaleva) [inline cli/config/vm.go:10]:
```suggestion
// VM is a default configuration for the chain-backed VM CLI.
```

File: cli/config/vm.go [hunk 16]
```diff
@@ -0,0 +1,101 @@
...
+	},
+
+	ApplicationConfiguration: config.ApplicationConfiguration{
+		Ledger: config.Ledger{
+			SkipBlockVerification: false},
+		//LogPath could be set up in case you need stdout logs to some proper file.
+		//LogPath: "./log/neogo.log"
+		DBConfiguration: dbconfig.DBConfiguration{
+			Type: "inmemory",
+			// Other options: 'leveldb','boltdb'
```
Comment (AnnaShaleva) [inline cli/config/vm.go:41]: Here and above: something has happened with the comment indent.

File: cli/config/vm.go [hunk 17]
```diff
@@ -0,0 +1,101 @@
...
+		},
+	},
+
+	ApplicationConfiguration: config.ApplicationConfiguration{
+		Ledger: config.Ledger{
+			SkipBlockVerification: false},
+		//LogPath could be set up in case you need stdout logs to some proper file.
+		//LogPath: "./log/neogo.log"
+		DBConfiguration: dbconfig.DBConfiguration{
+			Type: "inmemory",
```
Comment (AnnaShaleva) [inline cli/config/vm.go:40]: We have a spacial enum for DB types.

File: .github/workflows/tests.yml [hunk 18]
```diff
@@ -150,6 +150,33 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
           verbose: true
 
+  check_config:
```
Comment (AnnaShaleva) [inline .github/workflows/tests.yml:153]: NeoVM submodules were changed, please, revert.

File: cli/options/options.go [hunk 19]
```diff
@@ -198,6 +199,9 @@ func GetConfigFromContext(ctx *cli.Context) (config.Config, error) {
 		configFile   = ctx.String("config-file")
 		relativePath = ctx.String("relative-path")
 	)
+	if ctx.String("config-file") == "" && ctx.String("config-path") == "" {
+		return config2.VmConfig, nil
+	}
```
Comment (AnnaShaleva) [inline cli/options/options.go:204]: It's not that easy, we use GetConfigFromContext not only for VM but also for other `node` commands.

Comment (AnnaShaleva) [reply cli/options/options.go:204]: We probably need an additional argument passed to `GetConfigFromContext`

File: cli/config/config.go (hunk 9 above)
Comment (AliceInHunterland) [reply cli/config/config.go:93]: reuse leads to import cycles and the `options.Config` flag description seems a little bit confusing "path to directory with per-network configuration files (may be overridden by --config-file option for the configuration file)"

Comment (AnnaShaleva) [reply cli/config/config.go]: Import cycles may be solved by moving it to a separate package. But the second argument is accepted, we need its own usage text for this flag, thus, let's create a new `--config-path` flag for this package.

File: README.md [hunk 20]
```diff
@@ -75,15 +75,28 @@ The resulting binary is `bin/neo-go.exe`.
 
 ## Running a node
 
-A node needs to connect to some network, either local one (usually referred to
-as `privnet`) or public (like `mainnet` or `testnet`). Network configuration
-is stored in a file and NeoGo allows you to store multiple files in one
-directory (`./config` by default) and easily switch between them using network
-flags.
+Before running a Neo node, you need to generate the necessary configuration files
```
Comment (AnnaShaleva) [inline README.md:78]: > a Neo node

a NeoGo node

Comment (AnnaShaleva) [inline README.md:78]: It's not necessary to generate. They may be taken from the repo (add a link).

File: README.md [hunk 21]
```diff
@@ -75,15 +75,28 @@ The resulting binary is `bin/neo-go.exe`.
...
+for the network you wish to connect to, such as a local network (`privnet`), or 
+a public network like `mainnet` or `testnet`. NeoGo stores network configuration
```
Comment (AnnaShaleva) [inline README.md:80]: Add a note about NeoFS networks.

File: README.md [hunk 22]
```diff
@@ -75,15 +75,28 @@ The resulting binary is `bin/neo-go.exe`.
...
 
-A node needs to connect to some network, either local one (usually referred to
-as `privnet`) or public (like `mainnet` or `testnet`). Network configuration
-is stored in a file and NeoGo allows you to store multiple files in one
-directory (`./config` by default) and easily switch between them using network
-flags.
+Before running a Neo node, you need to generate the necessary configuration files
+for the network you wish to connect to, such as a local network (`privnet`), or 
+a public network like `mainnet` or `testnet`. NeoGo stores network configuration 
+files in a directory (`./config` by default) and allows you to easily switch
```
Comment (AnnaShaleva) [inline README.md:81]: `NeoGo allows you to store multiple files in one directory` - this text shouldn't be removed.

File: README.md [hunk 23]
```diff
@@ -75,15 +75,28 @@ The resulting binary is `bin/neo-go.exe`.
...
-To start Neo node on a private network, use:
+### Initial Setup
 
+First, generate the configuration files for all available networks:
+
+```bash
+./bin/neo-go config generate --all
 ```
+
+This command will create configuration files for each network in
```
Comment (AnnaShaleva) [inline README.md:92]: > for each network

for public N3 and NeoFS networks and privnet.

File: README.md [hunk 24]
```diff
@@ -75,15 +75,28 @@ The resulting binary is `bin/neo-go.exe`.
...
+Before running a Neo node, you need to generate the necessary configuration files
+for the network you wish to connect to, such as a local network (`privnet`), or 
+a public network like `mainnet` or `testnet`. NeoGo stores network configuration 
+files in a directory (`./config` by default) and allows you to easily switch 
+between them using network flags.
 
-To start Neo node on a private network, use:
+### Initial Setup
 
+First, generate the configuration files for all available networks:
```
Comment (AnnaShaleva) [inline README.md:86]: Generate the configuration files for public networks:

File: cli/config/config.go [hunk 25]
```diff
@@ -0,0 +1,121 @@
...
+					UsageText: "neo-go config generate [--privnet | --mainnet | --testnet | --unit_testnet | --mainnet_neofs | --testnet_neofs | --docker | --all] [--config-path path]",
+					Action:    configGenerate,
+					Flags: []cli.Flag{
+						cli.BoolFlag{Name: "privnet, p", Usage: "generate private network configuration"},
+						cli.BoolFlag{Name: "mainnet, m", Usage: "generate mainnet network configuration"},
+						cli.BoolFlag{Name: "testnet, t", Usage: "generate testnet network configuration"},
+						cli.BoolFlag{Name: "unit_testnet", Usage: "generate unit test network configuration"},
+						cli.BoolFlag{Name: "mainnet_neofs", Usage: "generate mainnet NeoFS network configuration"},
+						cli.BoolFlag{Name: "testnet_neofs", Usage: "generate testnet NeoFS network configuration"},
+						cli.BoolFlag{Name: "docker", Usage: "generate Docker configuration"},
```
Comment (AnnaShaleva) [inline cli/config/config.go:33]: Docker privnet configuration

File: cli/config/config.go [hunk 26]
```diff
@@ -0,0 +1,121 @@
...
+						cli.BoolFlag{Name: "all", Usage: "generate all networks configurations"},
```
Comment (AnnaShaleva) [inline cli/config/config.go:34]: generate all supported configuration files

File: cli/config/config.go [hunk 27]
```diff
@@ -0,0 +1,121 @@
...
+						cli.StringFlag{Name: "config-path", Usage: "path to the directory where configuration files will be generated"},
```
Comment (AnnaShaleva) [inline cli/config/config.go:35]: > where configuration files will be generated

with per-network configuration files

File: cli/config/config.go [hunk 28]
```diff
@@ -0,0 +1,121 @@
...
+			"protocol.testnet.yml":               Testnet,
+			"protocol.testnet.neofs.yml":         TestnetNeoFS,
+			"protocol.unit_testnet.yml":          UnitTestnet,
+			"protocol.unit_testnet.single.yml":   UnitTestnetSingle,
+			"protocol.privnet.docker.one.yml":    PrivnetDockerOne,
+			"protocol.privnet.docker.two.yml":    PrivnetDockerTwo,
+			"protocol.privnet.docker.three.yml":  PrivnetDockerThree,
+			"protocol.privnet.docker.four.yml":   PrivnetDockerFour,
+			"protocol.privnet.docker.single.yml": PrivnetDockerSingle,
+			"protocol.privnet.yml":               Privnet,
```
Comment (AnnaShaleva) [inline cli/config/config.go:63]: These constants are duplicated several lines below. Can we move them under designated package-wide `const` definition?

File: cli/config/config.go [hunk 29]
```diff
@@ -0,0 +1,121 @@
...
+			filesToGenerate["protocol.privnet.docker.two.yml"] = PrivnetDockerTwo
+			filesToGenerate["protocol.privnet.docker.three.yml"] = PrivnetDockerThree
+			filesToGenerate["protocol.privnet.docker.four.yml"] = PrivnetDockerFour
+			filesToGenerate["protocol.privnet.docker.single.yml"] = PrivnetDockerSingle
+		}
+	}
+	configDir := ctx.String("config-path")
+	if configDir == "" {
+		configDir = "config"
+	}
```
Comment (AnnaShaleva) [inline cli/config/config.go:96]: You need a default value. Take a look at the existing code:
```
	var configPath = "./config"
	if argCp := ctx.String("config-path"); argCp != "" {
		configPath = argCp
	}
```

File: cli/config/config.go [hunk 30]
```diff
@@ -0,0 +1,121 @@
...
+	if err := os.MkdirAll(configDir, 0755); err != nil {
```
Comment (AnnaShaleva) [inline cli/config/config.go:97]: Why not `os.MkdirAll(configDir, os.ModePerm)`?

File: cli/config/mainnet.go [hunk 31]
```diff
@@ -0,0 +1,127 @@
...
+			"03cdcea66032b82f5c30450e381e5295cae85c5e6943af716cc6b646352a6067dc",
+			"02cd5a5547119e24feaa7c2a0f37b8c9366216bab7054de0065c9be42084003c8a",
+		},
+		ValidatorsCount:    7,
+		VerifyTransactions: false,
+		P2PSigExtensions:   false,
+		Hardforks: map[string]uint32{
+			"Aspidochelone": 1730000,
+			"Basilisk":      4120000,
+			"Cockatrice":    5450000,
```
Comment (AnnaShaleva) [inline cli/config/mainnet.go:47]: We have enums for them. Use enums where possible.

File: cli/config/mainnet.go [hunk 32]
```diff
@@ -0,0 +1,127 @@
...
+		SeedList: []string{
+			"seed1.neo.org:10333",
+			"seed2.neo.org:10333",
+			"seed3.neo.org:10333",
+			"seed4.neo.org:10333",
+			"seed5.neo.org:10333",
+		},
+	},
+
+	ApplicationConfiguration: config.ApplicationConfiguration{
```
Comment (AnnaShaleva) [inline cli/config/mainnet.go:58]: I don't see SkipBocksVerification here. It's default, but it would be nice to have this option here explicitly, exactly like it was specified in the YAML config.

File: cli/config/mainnet_neofs.go [hunk 33]
```diff
@@ -0,0 +1,96 @@
...
+			"morph1.fs.neo.org:40333",
+			"morph2.fs.neo.org:40333",
+			"morph3.fs.neo.org:40333",
+			"morph4.fs.neo.org:40333",
+			"morph5.fs.neo.org:40333",
+			"morph6.fs.neo.org:40333",
+			"morph7.fs.neo.org:40333",
+		},
+	},
+
```
Comment (AnnaShaleva) [inline cli/config/mainnet_neofs.go:45]: Useless line.

File: cli/config/mainnet.go [hunk 34]
```diff
@@ -0,0 +1,127 @@
...
+		},
+		SeedList: []string{
+			"seed1.neo.org:10333",
+			"seed2.neo.org:10333",
+			"seed3.neo.org:10333",
+			"seed4.neo.org:10333",
+			"seed5.neo.org:10333",
+		},
+	},
+
```
Comment (AnnaShaleva) [inline cli/config/mainnet.go:57]: Useless line.

File: cli/config/mainnet_neofs.go (hunk 33 above)
Comment (AnnaShaleva) [reply cli/config/mainnet_neofs.go:45]: Fix it everywhere.

File: cli/config/vm.go [hunk 35]
```diff
@@ -0,0 +1,101 @@
...
+
+import (
+	"time"
+
+	"github.com/nspcc-dev/neo-go/pkg/config"
+	"github.com/nspcc-dev/neo-go/pkg/core/storage/dbconfig"
+)
+
+// VM is a default configuration for the chain-backed VM CLI.
+var VM = config.Config{
```
Comment (AnnaShaleva) [inline cli/config/vm.go:11]: It is a part of the next commit.

File: cli/vm/vm.go [hunk 36]
```diff
@@ -27,10 +28,13 @@ func startVMPrompt(ctx *cli.Context) error {
 	if err := cmdargs.EnsureNone(ctx); err != nil {
 		return err
 	}
-
-	cfg, err := options.GetConfigFromContext(ctx)
-	if err != nil {
-		return cli.NewExitError(err, 1)
+	var err error
+	cfg := config.VM
```
Comment (AnnaShaleva) [inline cli/vm/vm.go:32]: Try to unify the style of declarations that are grouped. It's either `var` or `:=`.

File: cli/vm/vm.go [hunk 37]
```diff
@@ -27,10 +28,13 @@ func startVMPrompt(ctx *cli.Context) error {
...
+	if ctx.String("config-file") != "" || ctx.String("config-path") != "" {
+		cfg, err = options.GetConfigFromContext(ctx)
```
Comment (AnnaShaleva) [inline cli/vm/vm.go:34]: Good!

File: cli/vm/vm.go [hunk 38]
```diff
@@ -27,10 +28,13 @@ func startVMPrompt(ctx *cli.Context) error {
...
+		if err != nil {
+			return cli.NewExitError(err, 1)
+		}
```
Comment (AnnaShaleva) [inline cli/vm/vm.go:37]: Remove the condition below, it's not needed anymore since you have a default designated VM config with InMemory DB included.

File: cli/options/options.go [hunk 39]
```diff
@@ -205,7 +211,43 @@ func GetConfigFromContext(ctx *cli.Context) (config.Config, error) {
...
+	network := GetNetwork(ctx)
+	switch network {
+	case netmode.MainNet:
+		return getEmbeddedConfig(configFiles.MainnetConfig)
+	case netmode.TestNet:
+		return getEmbeddedConfig(configFiles.TestnetConfig)
+	case netmode.UnitTestNet:
+		return getEmbeddedConfig(configFiles.UnitTestnetConfig)
+	case netmode.PrivNet:
+		return getEmbeddedConfig(configFiles.PrivnetConfig)
```
Comment (AnnaShaleva) [inline cli/options/options.go:224]: This should be placed inside `func LoadFile(configPath string, relativePath ...string) (Config, error) {`. There you have a `configData, err := os.ReadFile(configPath)`, so this `configData` should be taken either from embedded files or from the real file depending on the `configPath`.

File: cli/options/options.go [hunk 40]
```diff
@@ -194,6 +196,10 @@ func GetRPCWithInvoker(gctx context.Context, ctx *cli.Context, signers []transac
 // GetConfigFromContext looks at the path and the mode flags in the given config and
 // returns an appropriate config.
 func GetConfigFromContext(ctx *cli.Context) (config.Config, error) {
+	if ctx.NumFlags() == 0 {
+		return getDefaultVMConfig()
+	}
+
```
Comment (AnnaShaleva) [inline cli/options/options.go:202]: Please, do not mix VM config with this, you don't need this change. VM CLI is perfectly OK with the existing code and embedded node config, it doesn't require any changes with the updated design.

File: cli/options/options.go [hunk 41]
```diff
@@ -205,7 +211,43 @@ func GetConfigFromContext(ctx *cli.Context) (config.Config, error) {
...
+	var cfgData = configFiles.PrivnetConfig
+
+	var cfg config.Config
+	err := yaml.Unmarshal(cfgData, &cfg)
+	if err != nil {
+		return cfg, fmt.Errorf("failed to unmarshal default config: %w", err)
+	}
+	cfg.ApplicationConfiguration.DBConfiguration.Type = dbconfig.InMemoryDB
+	return cfg, nil
+}
```
Comment (AnnaShaleva) [inline cli/options/options.go:241]: Remove it, it's not needed. This code is already in the VM CLI.

File: config/config_embed.go [hunk 42]
```diff
@@ -0,0 +1,19 @@
+package config
+
+import (
+	_ "embed"
+)
+
+// Embedding configuration files
```
Comment (AnnaShaleva) [inline config/config_embed.go:7]: Either make a multi-var declaration like:
```
    var (
        ...
    )
```
or add a corresponding comment to every variable.

File: config/config_embed.go [hunk 43]
```diff
@@ -0,0 +1,19 @@
...
+//
+//go:embed protocol.mainnet.yml
```
Comment (AnnaShaleva) [inline config/config_embed.go:9]: Have you tried to put it inside `cli/options`?

File: cli/options/config.go (hunk 5 above)
Comment (AnnaShaleva) [reply cli/options/config.go]: Decided to embed our `config/protocol.*config.yml` files.

**Comment by AnnaShaleva** [comment]
Linter and tests are failing.

File: config/config_embed.go [hunk 44]
```diff
@@ -0,0 +1,19 @@
...
+var MainnetConfig []byte
+
+//go:embed protocol.testnet.yml
+var TestnetConfig []byte
+
+//go:embed protocol.unit_testnet.yml
+var UnitTestnetConfig []byte
+
+//go:embed protocol.privnet.yml
+var PrivnetConfig []byte
```
Comment (AnnaShaleva) [inline config/config_embed.go:19]: We need to embed FS configs as far.

File: config/config_embed.go (hunk 43 above)
Comment (AliceInHunterland) [reply config/config_embed.go:9]: yes. It then needs a relative path but `Path must not contain '.' or '..' path elements nor begin with a leading slash`

Comment (roman-khimov) [reply config/config_embed.go:9]: Doesn't seem perfect, but looks like there are no other options. Hard links aren't compatible with git, symbolic links are prohibited by embed. The only other option is copy/autosync.

Comment (AnnaShaleva) [reply config/config_embed.go:9]: > The only other option is copy/autosync.

I don't quite like duplication, thus I think we're OK with this file being placed inside `neo-go/config`.

File: config/config_embed.go [hunk 45]
```diff
@@ -0,0 +1,35 @@
...
+
+// TestnetConfig is the Neo N3 testnet configuration.
+//
+//go:embed protocol.testnet.yml
+var TestnetConfig []byte
+
+// UnitTestnetConfig is the unit testnet configuration.
+//
+//go:embed protocol.unit_testnet.yml
+var UnitTestnetConfig []byte
```
Comment (roman-khimov) [inline config/config_embed.go:20]: Do we need this one, btw?

File: config/config_embed.go [hunk 46]
```diff
@@ -0,0 +1,35 @@
+package config
```
Comment (roman-khimov) [inline config/config_embed.go:1]: Add some package-level doc to explain what it's about, please.

File: config/config_embed.go [hunk 47]
```diff
@@ -0,0 +1,35 @@
...
+
+import (
+	_ "embed"
+)
+
+// MainnetConfig is the Neo N3 mainnet configuration.
+//
+//go:embed protocol.mainnet.yml
+var MainnetConfig []byte
```
Comment (AnnaShaleva) [inline config/config_embed.go:10]: It's `config.MainnetConfig` which is a bit duplicating. I'd suggest either make it `config.Mainnet` or `embedded.MainnetConfig` (since we already have a `pkg`-level `config` package). The first option seems to be slightly better for me.

File: pkg/config/config.go [hunk 48]
```diff
@@ -69,6 +70,9 @@ func (c Config) Blockchain() Blockchain {
 // config will be updated based on the provided relative path.
 func Load(path string, netMode netmode.Magic, relativePath ...string) (Config, error) {
 	configPath := fmt.Sprintf("%s/protocol.%s.yml", path, netMode)
+	if _, err := os.Stat(configPath); os.IsNotExist(err) {
+		return getEmbeddedConfig(netMode)
+	}
```
Comment (AnnaShaleva) [inline pkg/config/config.go:75]: I think it should be placed to `LoadFile`. We don't need code duplications between `Load` and `LoadFile`. See https://github.com/nspcc-dev/neo-go/pull/3477#discussion_r1655117101.

File: cli/server/cli_server_test.go [hunk 49]
```diff
@@ -43,9 +43,6 @@ func TestServerStart(t *testing.T) {
 	baseCmd := []string{"neo-go", "node", "--unittest", "--config-path", tmpDir}
 	e := testcli.NewExecutor(t, false)
 
-	t.Run("invalid config path", func(t *testing.T) {
-		e.RunWithError(t, baseCmd...)
-	})
```
Comment (AnnaShaleva) [inline cli/server/cli_server_test.go:48]: And this.

File: pkg/config/config.go [hunk 50]
```diff
@@ -77,7 +81,11 @@ func Load(path string, netMode netmode.Magic, relativePath ...string) (Config, e
 // be updated based on the provided relative path.
 func LoadFile(configPath string, relativePath ...string) (Config, error) {
 	if _, err := os.Stat(configPath); os.IsNotExist(err) {
-		return Config{}, fmt.Errorf("config '%s' doesn't exist", configPath)
+		if filepath.Dir(configPath) != DefaultConfigPath {
+			return Config{}, fmt.Errorf("config '%s' doesn't exist", configPath)
+		}
+		configBaseName := strings.TrimSuffix(filepath.Base(configPath), filepath.Ext(configPath))
```
Comment (AnnaShaleva) [inline pkg/config/config.go:87]: Remove it, it's an unnecessary action that may be avoided. Make the `getEmbeddedConfig` handle the whole path without any trims, i.e. compare with `fmt.Sprintf("%s/protocol.%s.yml", DefaultConfigPath, netmode.Mainnet)` and etc.

File: pkg/config/config.go [hunk 51]
```diff
@@ -111,6 +119,29 @@ func LoadFile(configPath string, relativePath ...string) (Config, error) {
 	return config, nil
 }
 
+// getEmbeddedConfig returns the embedded configuration based on the provided network mode.
+func getEmbeddedConfig(configName string) (Config, error) {
```
Comment (AnnaShaleva) [inline pkg/config/config.go:123]: Return `[]byte, error`.

File: pkg/config/config.go [hunk 52]
```diff
@@ -111,6 +119,29 @@ func LoadFile(configPath string, relativePath ...string) (Config, error) {
...
+	default:
+		return Config{}, fmt.Errorf("unsupported network mode: %s", configName)
+	}
+
+	var cfg Config
+	err := yaml.Unmarshal(cfgData, &cfg)
+	if err != nil {
+		return cfg, fmt.Errorf("failed to unmarshal embedded config: %w", err)
+	}
+	return cfg, nil
```
Comment (AnnaShaleva) [inline pkg/config/config.go:142]: Do not unmarshal here, there's already a spacial unmarshalling code inside the `LoadFile`.

File: pkg/config/config.go [hunk 53]
```diff
@@ -77,7 +81,11 @@ func Load(path string, netMode netmode.Magic, relativePath ...string) (Config, e
 // be updated based on the provided relative path.
 func LoadFile(configPath string, relativePath ...string) (Config, error) {
```
Comment (AnnaShaleva) [inline pkg/config/config.go:82]: We need a test for it. I'm not sure if it's possible, need to check: try to remove/rename the `config` directory in the start of the test (this change should be reverted in Cleanup) and then run the `LoadFile` with default config path and privnet config.

File: config/config_embed.go [hunk 54]
```diff
@@ -0,0 +1,35 @@
+// Package config contains embedded YAML configuration files for different network modes
+// of the Neo N3 blockchain. This includes configurations for the mainnet, testnet, and
+// private network environments. Additionally, it encompasses specific configurations
+// for NeoFS on both mainnet and testnet, providing a ready-to-use setup for various
+// network scenarios directly compiled into the binary.
```
Comment (AnnaShaleva) [inline config/config_embed.go:5]: BTW, is there something from chat-GPT?

Comment (AliceInHunterland) [reply config/config_embed.go:5]: its copilot

File: config/config_embed.go (hunk 45 above)
Comment (AliceInHunterland) [reply config/config_embed.go]: but we have it as hidden flag in cli.
`	cli.BoolFlag{Name: "unittest", Hidden: true}, `

**Comment by AnnaShaleva** [comment]
Please, fix the commit mesage: `If config-path is not passed...`.

File: pkg/config/config.go [hunk 55]
```diff
@@ -111,6 +116,24 @@ func LoadFile(configPath string, relativePath ...string) (Config, error) {
...
 }
 
+// getEmbeddedConfig returns the embedded config based on the provided config path.
+func getEmbeddedConfig(configPath string) ([]byte, error) {
+	switch configPath {
+	case fmt.Sprintf("%s/protocol.%s.yml", DefaultConfigPath, netmode.MainNet.String()):
+		return config.Mainnet, nil
+	case fmt.Sprintf("%s/protocol.%s.yml", DefaultConfigPath, netmode.TestNet.String()):
+		return config.Testnet, nil
+	case fmt.Sprintf("%s/protocol.%s.yml", DefaultConfigPath, netmode.PrivNet.String()):
```
Comment (AnnaShaleva) [inline pkg/config/config.go:126]: You don't need `String()`, there's already `%s` used.

File: pkg/config/config_test.go [hunk 56]
```diff
@@ -32,3 +32,25 @@ func TestUnknownConfigFields(t *testing.T) {
...
 	})
 }
+
+func TestLoadFileWithMissingDefaultConfigPath(t *testing.T) {
+	originalPath := DefaultConfigPath
+	temporaryPath := filepath.Join(filepath.Dir(originalPath), "missing-config")
+
+	if _, err := os.Stat(originalPath); os.IsNotExist(err) {
+		err = os.MkdirAll(originalPath, os.ModePerm)
+		require.NoError(t, err)
```
Comment (AnnaShaleva) [inline pkg/config/config_test.go:42]: You don't need this, it's always there. And if it's not due to the project refactoring, then just fail the test with the corresponding message.

File: pkg/config/config_test.go [hunk 57]
```diff
@@ -32,3 +32,25 @@ func TestUnknownConfigFields(t *testing.T) {
...
+		err := os.Rename(temporaryPath, originalPath)
+		require.NoError(t, err)
+	})
+
+	err := os.Rename(originalPath, temporaryPath)
+	require.NoError(t, err)
+
+	_, err = LoadFile(filepath.Join(DefaultConfigPath, "protocol.privnet.yml"))
+	require.Error(t, err)
+	require.Contains(t, err.Error(), "doesn't exist")
```
Comment (AnnaShaleva) [inline pkg/config/config_test.go:55]: Why error? It must load the embedded config, because the default config-path is used with a known config file.

**Review by AnnaShaleva — COMMENTED** [review]
Before re-requesting review, please, perform self-review and ensure that Linter and testing GA jobs pass.

File: pkg/config/config_test.go (hunk 56 above)
Comment (AliceInHunterland) [reply pkg/config/config_test.go]: > We need a test for it. I'm not sure if it's possible, need to check: try to remove/rename the config directory in the start of the test (this change should be reverted in Cleanup) and then run the LoadFile with default config path and privnet config.

so this test is equal to call LoadFile('./config.protocol.privnet.yml') in an empty directory (at least without './config')?

The `TestLoadFileWithMissingDefaultConfigPath` is in `pkg/config/config_test.go`  so from this point the `config` directory is not `./config` but "./../../config". We do not need to clean up or create a directory in this case.

Comment (AnnaShaleva) [reply pkg/config/config_test.go]: >  so from this point the config directory is not ./config but "./../../config"

OK, then we can't trigger embedded config usage from this test. Then this test is useless, thus let's just remove it.

Comment (AnnaShaleva) [reply pkg/config/config_test.go]: OK, I see you've adjusted it so now it just loads config from file. Let it be.

**Review by AnnaShaleva — COMMENTED** [review]
Please, add "Close #3459" to the commit/PR message.

Otherwise LGTM.

**Review by AnnaShaleva — APPROVED** [review]
Nice and simple.

File: config/config_embed.go (hunk 45 above)
Comment (AnnaShaleva) [reply config/config_embed.go]: I think it's only developers who use this option, and we always have the real config with us.
