### PR TITLE
*: fix GetExpectedHeaderSize for genesis block case

### LINKED ISSUE #3807: headerFetcher: the genesis header failing to be decoded
`2025-02-11T18:17:19.540+0300    ERROR   failed to decode object from stream     {"oid": "3Wzr6k8tv89fTJZpjNMiP4X8J1dAE1qX6WhXURZWBWi7", "error": "status: code = 2053 message = out of range"}
`
As it's the genesis block:
```
(base) ekaterinapavlova@MacBook-Air-4 neofs-node % ./bin/neofs-cli object head -r st4.storage.fs.neo.org:8080 -w /Users/ekaterinapavlova/Workplace/neo-go/panelwallet1.json --cid A8nGtDemWrm2SjfcGAG6wvrxmXwqc5fwr8ezNDm6FraT --oid 3Wzr6k8tv89fTJZpjNMiP4X8J1dAE1qX6WhXURZWBWi7

ID: 3Wzr6k8tv89fTJZpjNMiP4X8J1dAE1qX6WhXURZWBWi7
CID: A8nGtDemWrm2SjfcGAG6wvrxmXwqc5fwr8ezNDm6FraT
Owner: NVvY1FF67XJ2GTVhy9FqiZGC4jEQtvjmHt
CreatedAt: 28202
Size: 114
HomoHash: 1ca9c0cbdd053cb3518ec3c59e5457612b61753fcdb8dc7af418910e009e0c1413eca1e9d550a9d4bfab0a0cef7889fc0cc391c5cae9a828b3a3c4c9794eaa16
Checksum: 1f2acfb9610ccb112f6a9fabb985c5eb90623986fd069b5c3a452ab6a8e9ec4a
Type: REGULAR
Attributes:
  Block=0
  Primary=0
  Hash=9d3276785e7306daf59a3f3b9e31912c095598bbfb8a4476b821b0e59be4c57a
  PrevHash=0000000000000000000000000000000000000000000000000000000000000000
  BlockTime=1468595301000
  Timestamp=1734363074 (2024-12-16 18:31:14 +0300 MSK)
ID signature:
  public key: 03e1b6e1e570eff99b858acb0ae27db7d31224d4ab42b97395d403aa46a48b8465
  signature: 04234f012cd10abe728d84ee253494fe8aea3e632e37a49951db0c134bb5914400168dcfdb675ca5b6b86451d0e6eb88aa3caca7cc641988345fef5ef26a116e4e

```
## Current Behavior

Error
## Expected Behavior

Do not fetch the genesis block.
## Possible Solution

Skip the genesis block.
## Steps to Reproduce

Run node with `NeoFSStateSyncExtensions: true`.

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3807

### CODE REVIEW

File: pkg/services/blockfetcher/blockfetcher.go [hunk 1]
```diff
@@ -192,7 +192,9 @@ func New(chain Ledger, cfg config.NeoFSBlockFetcher, logger *zap.Logger, put fun
 
 func getHeaderSizeMap(chain config.Blockchain) map[int]int {
 	headerSizeMap := make(map[int]int)
-	headerSizeMap[0] = block.GetExpectedHeaderSize(chain.StateRootInHeader, chain.GetNumOfCNs(0))
+	// Genesis header size.
+	headerSizeMap[0] = block.GetExpectedHeaderSize(chain.StateRootInHeader, 0)
+	headerSizeMap[1] = block.GetExpectedHeaderSize(chain.StateRootInHeader, chain.GetNumOfCNs(0))
```
Comment (AnnaShaleva) [inline pkg/services/blockfetcher/blockfetcher.go:197]: And this particular change is not related to this commit, it's a separate bug.

>*: fix GetExpectedHeaderSize for genesis block case 

And it's not `*:`, it's `block:`.

File: pkg/services/blockfetcher/blockfetcher.go [hunk 2]
```diff
@@ -192,7 +192,9 @@ func New(chain Ledger, cfg config.NeoFSBlockFetcher, logger *zap.Logger, put fun
 
 func getHeaderSizeMap(chain config.Blockchain) map[int]int {
 	headerSizeMap := make(map[int]int)
-	headerSizeMap[0] = block.GetExpectedHeaderSize(chain.StateRootInHeader, chain.GetNumOfCNs(0))
+	// Genesis header size.
+	headerSizeMap[0] = block.GetExpectedHeaderSize(chain.StateRootInHeader, 0)
```
Comment (AnnaShaleva) [inline pkg/services/blockfetcher/blockfetcher.go:196]:
```suggestion
	headerSizeMap[0] = block.GetExpectedHeaderSize(chain.StateRootInHeader, 0) 	// genesis header size.
```

Usually separate-line comments are related to the following *block* of code, and this particular comment is related to a single line.

File: pkg/core/block/header.go [hunk 3]
```diff
@@ -238,6 +238,7 @@ func (b *Header) UnmarshalJSON(data []byte) error {
 }
 
 // GetExpectedHeaderSize returns the expected Header size with the given number of validators.
+// For calculation genesis block Header size numOfValidators should be 0.
```
Comment (AnnaShaleva) [inline pkg/core/block/header.go:241]: Either "For genesis block Header size calculation" or "To calculate genesis block Header size".

File: pkg/core/block/header.go [hunk 4]
```diff
@@ -250,6 +251,11 @@ func GetExpectedHeaderSize(stateRootInHeader bool, numOfValidators int) int {
 	// n = 1 bytes
 	// 5 for SYSCALL
 	size := expectedHeaderSizeWithEmptyWitness + (1+1+64)*m + 2 + numOfValidators*(1+1+33) + 2 + 5
+	// Genesis block case
```
Comment (AnnaShaleva) [inline pkg/core/block/header.go:254]: godot.

File: pkg/core/block/header.go [hunk 5]
```diff
@@ -250,6 +251,11 @@ func GetExpectedHeaderSize(stateRootInHeader bool, numOfValidators int) int {
...
+	if numOfValidators == 0 {
+		// 1 byte for the push opcode
```
Comment (AnnaShaleva) [inline pkg/core/block/header.go:256]: Ditto.

Comment (AnnaShaleva) [inline pkg/core/block/header.go:256]: It's `PUSH1 opcode`

File: pkg/core/block/header.go [hunk 6]
```diff
@@ -250,6 +251,11 @@ func GetExpectedHeaderSize(stateRootInHeader bool, numOfValidators int) int {
 	// n = 1 bytes
 	// 5 for SYSCALL
 	size := expectedHeaderSizeWithEmptyWitness + (1+1+64)*m + 2 + numOfValidators*(1+1+33) + 2 + 5
+	// Genesis block case.
+	if numOfValidators == 0 {
+		// 1 byte for the PUSH1 opcode.
+		size = expectedHeaderSizeWithEmptyWitness + 1
```
Comment (AnnaShaleva) [inline pkg/core/block/header.go:257]: I need a compatibility test. Create genesis block, serialize it and then compare the resulting size with GetExpectedHeaderSize.

And move `m` and `size` initialization to `else` case.

File: pkg/services/blockfetcher/blockfetcher.go [hunk 7]
```diff
@@ -192,7 +192,8 @@ func New(chain Ledger, cfg config.NeoFSBlockFetcher, logger *zap.Logger, put fun
 
 func getHeaderSizeMap(chain config.Blockchain) map[int]int {
 	headerSizeMap := make(map[int]int)
-	headerSizeMap[0] = block.GetExpectedHeaderSize(chain.StateRootInHeader, chain.GetNumOfCNs(0))
+	headerSizeMap[0] = block.GetExpectedHeaderSize(chain.StateRootInHeader, 0) // genesis header size.
+	headerSizeMap[1] = block.GetExpectedHeaderSize(chain.StateRootInHeader, chain.GetNumOfCNs(0))
```
Comment (AnnaShaleva) [inline pkg/services/blockfetcher/blockfetcher.go:196]: > blockfetcher: add to the headerSizeMap the genesis header size 

Usually it's vise-versa: `blockfetcher: add genesis header size to the headerSizeMap `

**Review by AnnaShaleva — COMMENTED** [review]
Otherwise LGTM.

**Review by AnnaShaleva — APPROVED** [review]
