### PR TITLE
interop/contract: fix state rollbacks for nested contexts

### LINKED ISSUE #3045: Mainnet state difference @3672783
```
state differs at 3672783, block b68b24d98006ee165f9b6f2719e9bb21af8559bb775e72b7aeeab77f5405ac53
transaction cd1249d5b1d13550534f0fbab48bea7df87ba103f487645084d44b69b38adc7b:
--- https://rpc10.n3.nspcc.ru:10331
+++ http://seed2.neo.org:10332
@@ -1,2 +1,2 @@
-(*result.ApplicationLog)(0xc0004ca4c0)({
+(*result.ApplicationLog)(0xc00038a440)({
  Container: (util.Uint256) (len=32 cap=32) 7bdc8ab3694bd484506487f403a17bf87dea8bb4ba0f4f535035d1b1d54912cd,
@@ -15,3 +15,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc00014ca20)(Array)
+     Item: (*stackitem.Array)(0xc00014d7d0)(Array)
     },
@@ -20,3 +20,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc00014cc30)(Array)
+     Item: (*stackitem.Array)(0xc00014d9e0)(Array)
     },
@@ -25,3 +25,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc00014ce40)(Array)
+     Item: (*stackitem.Array)(0xc00014dbf0)(Array)
     },
@@ -30,3 +30,3 @@
      Name: (string) (len=6) "Synced",
-     Item: (*stackitem.Array)(0xc00014cfc0)(Array)
+     Item: (*stackitem.Array)(0xc00014dd70)(Array)
     },
@@ -35,3 +35,3 @@
      Name: (string) (len=7) "Swapped",
-     Item: (*stackitem.Array)(0xc00014d2c0)(Array)
+     Item: (*stackitem.Array)(0xc000024300)(Array)
     }

transaction d0a94e4048fd2563637be21bb646459854eb17253800412ac8a96d9b434bd68c:
--- https://rpc10.n3.nspcc.ru:10331
+++ http://seed2.neo.org:10332
@@ -1,2 +1,2 @@
-(*result.ApplicationLog)(0xc00038a700)({
+(*result.ApplicationLog)(0xc000210440)({
  Container: (util.Uint256) (len=32 cap=32) 8cd64b439b6da9c82a4100382517eb54984546b61be27b636325fd48404ea9d0,
@@ -7,3 +7,3 @@
    VMState: (vmstate.State) HALT,
-   GasConsumed: (int64) 41639596,
+   GasConsumed: (int64) 43233295,
    Stack: ([]stackitem.Item) (len=1 cap=1) {
@@ -11,3 +11,3 @@
    },
-   Events: ([]state.NotificationEvent) (len=11 cap=13) {
+   Events: ([]state.NotificationEvent) (len=7 cap=9) {
     (state.NotificationEvent) {
@@ -15,3 +15,3 @@
      Name: (string) (len=5) "event",
-     Item: (*stackitem.Array)(0xc000204240)(Array)
+     Item: (*stackitem.Array)(0xc000205bc0)(Array)
     },
@@ -20,3 +20,3 @@
      Name: (string) (len=5) "event",
-     Item: (*stackitem.Array)(0xc0002043c0)(Array)
+     Item: (*stackitem.Array)(0xc000205ce0)(Array)
     },
@@ -25,3 +25,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc000204630)(Array)
+     Item: (*stackitem.Array)(0xc000205ef0)(Array)
     },
@@ -30,23 +30,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc000204870)(Array)
-    },
-    (state.NotificationEvent) {
-     ScriptHash: (util.Uint160) (len=20 cap=20) ccdba6514039dec29588221856b756520fbbdea2,
-     Name: (string) (len=10) "PTokenSwap",
-     Item: (*stackitem.Array)(0xc000204a80)(Array)
-    },
-    (state.NotificationEvent) {
-     ScriptHash: (util.Uint160) (len=20 cap=20) d5ff61d0518ad47d725c34c59433d03f63a71447,
-     Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc000204c90)(Array)
-    },
-    (state.NotificationEvent) {
-     ScriptHash: (util.Uint160) (len=20 cap=20) 20f0bea450ada7b903b89749d7c9bbc160b148cd,
-     Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc000204ea0)(Array)
-    },
-    (state.NotificationEvent) {
-     ScriptHash: (util.Uint160) (len=20 cap=20) 9c8467c6d2599f99fe4d7fbe9866b5597d178f47,
-     Name: (string) (len=9) "TokenSwap",
-     Item: (*stackitem.Array)(0xc000205230)(Array)
+     Item: (*stackitem.Array)(0xc000276120)(Array)
     },
@@ -55,3 +35,3 @@
      Name: (string) (len=11) "UnlockEvent",
-     Item: (*stackitem.Array)(0xc0002054d0)(Array)
+     Item: (*stackitem.Array)(0xc000276330)(Array)
     },
@@ -60,3 +40,3 @@
      Name: (string) (len=5) "event",
-     Item: (*stackitem.Array)(0xc0002055f0)(Array)
+     Item: (*stackitem.Array)(0xc000276450)(Array)
     },
@@ -65,3 +45,3 @@
      Name: (string) (len=21) "CrossChainUnlockEvent",
-     Item: (*stackitem.Array)(0xc000205800)(Array)
+     Item: (*stackitem.Array)(0xc000276720)(Array)
     }
```

### PR DESCRIPTION
**Pull request by roman-khimov**
Our wrapping optimization relied on the caller context having a TRY block, but each context (including internal calls!) has an exception handling stack of its own, which means that for an invocation stack of

    entry
    A.someMethodFromEntry()   # this one has a TRY
    A.internalMethodViaCALL() # this one doesn't
    B.someMethod()

we get `HasTryBlock() == false` for `A.internalMethodViaCALL()` context, which leads to missing wrapper and missing rollbacks if B is to THROW. What this patch does instead is it checks for any context within contract boundaries.

Fixes #3045.

### CODE REVIEW

File: pkg/vm/vm.go [hunk 1]
```diff
@@ -1804,6 +1804,28 @@ func throwUnhandledException(item stackitem.Item) {
...
+// ContractHasTryBlock checks if the currently executing contract has a TRY
+// block in one of its contexts.
+func (v *VM) ContractHasTryBlock() bool {
+	var topctx *Context // Currently executing context.
+	for i := 0; i < len(v.istack); i++ {
+		ictx := v.istack[len(v.istack)-1-i] // It's a stack, going backwards like handleException().
+		if topctx == nil {
+			topctx = ictx
+		}
+		if ictx.sc != topctx.sc {
```
Comment (cthulhu-rider) [inline pkg/vm/vm.go:1816]: micro: this always false if condition above is true

**Review by cthulhu-rider — APPROVED** [review]

File: pkg/vm/vm.go [hunk 2]
```diff
@@ -1804,6 +1804,28 @@ func throwUnhandledException(item stackitem.Item) {
 	panic(msg)
 }
 
+// ContractHasTryBlock checks if the currently executing contract has a TRY
+// block in one of its contexts.
+func (v *VM) ContractHasTryBlock() bool {
+	var topctx *Context // Currently executing context.
+	for i := 0; i < len(v.istack); i++ {
+		ictx := v.istack[len(v.istack)-1-i] // It's a stack, going backwards like handleException().
```
Comment (cthulhu-rider) [inline pkg/vm/vm.go:1812]: maybe it'd be easier to invert `i` then

File: pkg/vm/vm.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/vm/vm.go:1816]: Yeah, but it's a feature. We always check the top context.

File: pkg/vm/vm.go (hunk 2 above)
Comment (roman-khimov) [reply pkg/vm/vm.go:1812]: Copy-pasting from `handleException` is more reliable!

**Review by notimetoname — APPROVED** [review]

**Review by AnnaShaleva — COMMENTED** [review]
Late comment, but it's a really good catch, ACK.
