### PR TITLE
cli: support Uint160 hashes with 0x prefix

### LINKED ISSUE #1753: CLI invokefunction/testinvokefunction rejects contract hashes with 0x prefix
`./bin/neo-go contract testinvokefunction -r ... 0xa501d7d7d10983673b61b7a2d3a813b36f9f0e43 deploy ...`:
`incorrect script hash: expected string size of 40 got 42`

It's use quite frequently with 0x, so it should be supported. We might as well support addresses here, it can be useful in some cases.

### PR DESCRIPTION
**Pull request by fyrchik**
Close #1753 .

### CODE REVIEW

**Comment by roman-khimov** [comment]
Same thing happens with `importNEP17Token` and `importDeployed`. Similar code is used in `calcHash`. So maybe we should provide some common utility function to convert parameter into uint160 using plain hash, prefixed hash and address and then use it everywhere (allowing addresses everywhere hashes are allowed (and updating documentation if needed))?

**Review by AnnaShaleva — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]

File: cli/smartcontract/smart_contract.go [hunk 1]
```diff
@@ -524,7 +518,7 @@ func invokeInternal(ctx *cli.Context, signAndPush bool) error {
 	if !args.Present() {
 		return cli.NewExitError(errNoScriptHash, 1)
 	}
-	script, err := util.Uint160DecodeStringLE(args[0])
+	script, err := flags.ParseAddress(args[0])
```
Comment (AnnaShaleva) [inline cli/smartcontract/smart_contract.go:521]: Let's then use it as an address flag in `cli.Command`'s description instead of using a simple string flag.

I.g. like we have for `wallet register` command:
```
Flags: append([]cli.Flag{
				walletPathFlag,
				gasFlag,
				flags.AddressFlag{
					Name:  "address, a",
					Usage: "Address to register",
				},
			}
```

Then we can just do
```
addrFlag := ctx.Generic("address").(*flags.Address)
addr := addrFlag.Uint160()
```

without errors handling.

**Review by AnnaShaleva — CHANGES_REQUESTED** [review]

File: cli/smartcontract/smart_contract.go (hunk 1 above)
Comment (fyrchik) [reply cli/smartcontract/smart_contract.go:521]: I think with `invoke*` positional argument is more convenient.

**Review by AnnaShaleva — APPROVED** [review]
