### PR TITLE
rpcsrv: fix `TestFilteredSubscriptions`

### LINKED ISSUE #3693: Notification subscription filter unit test checks nothing
https://github.com/nspcc-dev/neo-go/blob/57eec71101bad9d6d01bbaeecba0a2105f9dbd6b/pkg/services/rpcsrv/subscription_test.go#L244-L263

## Current Behavior
Subscription filters (execution notification) are called, none of the events are ever sent back, check funcs are also never called, test does nothing.

## Expected Behavior

Use some real notifications that are triggered and that can be tested. E.e. from the Rubl contract or from some native contract. 

## Possible Solution

Drop `my_pretty_notification`, this name is from nowhere. I don't know if it ever worked before but now it does not for sure. Use some real notifications from dumped blocks.

## Steps to Reproduce

Add some `print` in `check` func, see that it is never called
or
do `my_pretty_notification` search, see that it is never called, does not exist in any example contract, and is not passed in any predefined-blocks code, this event cannot happen from nowhere.

## Context
I tried to understand how to extend notification filter tests and could not understand why it works but it just does not work.

## Regression
Not sure, seems like not, the commit that adds it, does not change any example contract code.

## Your Environment
v0.106.3

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3693

### CODE REVIEW

File: pkg/services/rpcsrv/subscription_test.go [hunk 1]
```diff
@@ -244,23 +244,23 @@ func TestFilteredSubscriptions(t *testing.T) {
...
 		"notification matching name": {
-			params: `["notification_from_execution", {"name":"my_pretty_notification"}]`,
+			params: `["notification_from_execution", {"name":"Transfer"}]`,
 			check: func(t *testing.T, resp *neorpc.Notification) {
 				rmap := resp.Payload[0].(map[string]any)
 				require.Equal(t, neorpc.NotificationEventID, resp.Event)
-				n := rmap["name"].(string)
-				require.Equal(t, "my_pretty_notification", n)
+				n := rmap["eventname"].(string)
+				require.Equal(t, "Transfer", n)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:252]: The test is constructed improperly. We won't even notice if #3693 is repeated with some other notification. Refactor the test so that if `check` is not called when it's needed then the test should fail. It may be done by adding `shouldCheck bool` to the `cases` value struct.

File: pkg/services/rpcsrv/subscription_test.go [hunk 2]
```diff
@@ -376,7 +395,16 @@ func TestFilteredSubscriptions(t *testing.T) {
 					}
 					continue
 				}
-				this.check(t, resp)
+				if this.shouldCheck {
+					checkCalled = true
+					this.check(t, resp)
+				} else {
+					t.Fatal("unexpected notification match for case: " + name)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:402]: Case name is already provided by `t.Run`, no need to duplicate this information.

File: pkg/services/rpcsrv/subscription_test.go [hunk 3]
```diff
@@ -360,7 +376,10 @@ func TestFilteredSubscriptions(t *testing.T) {
 			blockSubID := callSubscribe(t, c, respMsgs, `["block_added"]`)
 			subID := callSubscribe(t, c, respMsgs, this.params)
 
-			var lastBlock uint32
+			var (
+				lastBlock   uint32
+				checkCalled = false
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:381]: s/checkCalled/checked ?

File: pkg/services/rpcsrv/subscription_test.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/subscription_test.go:402]: Instead, serialized notification can be passed as an argument. It's just easier to debug in this case.

File: pkg/services/rpcsrv/subscription_test.go [hunk 4]
```diff
@@ -376,7 +395,16 @@ func TestFilteredSubscriptions(t *testing.T) {
...
+				if this.shouldCheck {
+					checkCalled = true
+					this.check(t, resp)
+				} else {
+					t.Fatal("unexpected notification match for case: " + name)
+				}
+			}
+
+			if this.shouldCheck && !checkCalled {
+				t.Fatalf("expected check to be called for case: %s, but it wasn't", name)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:407]: Ditto.

File: pkg/services/rpcsrv/subscription_test.go (hunk 2 above)
Comment (AliceInHunterland) [reply pkg/services/rpcsrv/subscription_test.go]: Is event ID enough?

File: pkg/services/rpcsrv/subscription_test.go [hunk 5]
```diff
@@ -376,7 +395,16 @@ func TestFilteredSubscriptions(t *testing.T) {
...
+				if this.shouldCheck {
+					checked = true
+					this.check(t, resp)
+				} else {
+					t.Fatal("unexpected notification: " + resp.EventID().String())
+				}
+			}
+
+			if this.shouldCheck && !checked {
+				t.Fatalf("expected check is not performed")
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:407]: `t.Fatalf` is used when you need a formatted error message. You have only a single string here.

File: pkg/services/rpcsrv/subscription_test.go [hunk 6]
```diff
@@ -376,7 +395,16 @@ func TestFilteredSubscriptions(t *testing.T) {
 					}
 					continue
 				}
-				this.check(t, resp)
+				if this.shouldCheck {
+					checked = true
+					this.check(t, resp)
+				} else {
+					t.Fatal("unexpected notification: " + resp.EventID().String())
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:402]: And here `t.Fatalf("msg: %s", resp.EventID)` is more appropriate.

File: pkg/services/rpcsrv/subscription_test.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/subscription_test.go]: Let it be.

File: pkg/services/rpcsrv/subscription_test.go [hunk 7]
```diff
@@ -376,7 +395,16 @@ func TestFilteredSubscriptions(t *testing.T) {
 					}
 					continue
 				}
-				this.check(t, resp)
+				if this.shouldCheck {
+					checked = true
+					this.check(t, resp)
+				} else {
+					t.Fatalf("msg: %s", resp.EventID())
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:402]: @AliceInHunterland, oh-oh, by `msg` from https://github.com/nspcc-dev/neo-go/pull/3715#discussion_r1879594528 I meant your error message, I just was too lazy to copy the whole message to the comment. Get the old message back.

**Review by AnnaShaleva — APPROVED** [review]
Nice!
