### PR TITLE
vm CLI: replace ishell with urfave/cli

### LINKED ISSUE #1743: VM CLI is not UTF-8 compatible
```
NEO-GO-VM > loadgo фыва/test.go
Error: Unknown rune: 1092
NEO-GO-VM > loadnef фыва/test.nef фыва/test.json
Error: Unknown rune: 1092
```

### LINKED ISSUE #2268: VM CLI: make it work on Windows
Currently VM CLI doesn't pass tests on Windows with errors like:
```
2021-11-17T15:51:18.0009119Z === RUN   TestErrorOnStepInto
2021-11-17T15:51:18.0009542Z EOF
2021-11-17T15:51:18.0009888Z     cli_test.go:102: 
2021-11-17T15:51:18.0010323Z         	Error Trace:	cli_test.go:102
2021-11-17T15:51:18.0010765Z         	            				cli_test.go:495
2021-11-17T15:51:18.0011184Z         	Error:      	Expect "
2021-11-17T15:51:18.0011513Z 
2021-11-17T15:51:18.0011799Z 
2021-11-17T15:51:18.0012069Z 
2021-11-17T15:51:18.0012351Z 
2021-11-17T15:51:18.0012710Z 
2021-11-17T15:51:18.0012993Z 
2021-11-17T15:51:18.0013274Z 
2021-11-17T15:51:18.0013537Z 
2021-11-17T15:51:18.0013987Z 
2021-11-17T15:51:18.0014299Z 
2021-11-17T15:51:18.0014583Z 
2021-11-17T15:51:18.0014901Z [JNEO-GO-VM > 
2021-11-17T15:51:18.0015237Z 
2021-11-17T15:51:18.0015502Z 
2021-11-17T15:51:18.0015780Z 
2021-11-17T15:51:18.0016043Z 
2021-11-17T15:51:18.0016324Z 
2021-11-17T15:51:18.0016606Z 
2021-11-17T15:51:18.0016868Z 
2021-11-17T15:51:18.0017146Z 
2021-11-17T15:51:18.0017407Z 
2021-11-17T15:51:18.0017686Z 
2021-11-17T15:51:18.0017948Z 
2021-11-17T15:51:18.0018278Z [JNEO-GO-VM > 
...
2021-11-17T15:51:18.0077972Z [JNEO-GO-VM > stepover
2021-11-17T15:51:18.0078737Z         	            	" to match "Error:.*no program loaded"
2021-11-17T15:51:18.0079361Z         	Test:       	TestErrorOnStepInto
2021-11-17T15:51:18.0080021Z --- FAIL: TestErrorOnStepInto (0.01s)
```
The problem is in interactive console library we're using (https://github.com/abiosoft/ishell). See also example of failing `Windows, Go 1.17` test job: https://github.com/nspcc-dev/neo-go/runs/4252308539.
Running VM CLI manually on Windows results in the following:
```
PS C:\Users\Anna\Documents\GitProjects\nspcc-dev\neo-go> .\bin\neo-go.exe vm

    _   ____________        __________      _    ____  ___
   / | / / ____/ __ \      / ____/ __ \    | |  / /  |/  /
  /  |/ / __/ / / / /_____/ / __/ / / /____| | / / /|_/ /
 / /|  / /___/ /_/ /_____/ /_/ / /_/ /_____/ |/ / /  / /
/_/ |_/_____/\____/      \____/\____/      |___/_/  /_/


NEO-GO-VM > ←[J←[2K
```
So there are problems with input.

There's also https://github.com/nspcc-dev/neo-go/issues/1743, so maybe it's time to replace this CLI library.

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #1743, close #2268.

https://github.com/urfave/cli/issues/44 tells that `urfave/cli` can be used as an interactive console, although the way is not very efficient. However, to be able to correctly handle escape sequences, manage commands history and perform autocompletion it needs some additional library. Use https://github.com/chzyer/readline to provide these capabilities.

TODO:

- [x] Use named parameters instead of positional arguments where possible.
- [ ] Override `^C` to match the previous behaviour.
- [x] Enable commands autocompetion.
- [x] Split code into commits properly.
- [x] Fix linter errors and review the code.
- [x] Ensure tests pass on Windows.

### CODE REVIEW

File: pkg/vm/cli/cli.go [hunk 1]
```diff
@@ -210,209 +242,310 @@ var (
...
+	ctl.Writer = l.Stdout()
+	ctl.ErrWriter = l.Stderr()
+	ctl.Version = config.Version
+	ctl.Usage = "Official VM CLI for Neo-Go"
+
+	// TODO: maybe it's better to replace `afterF` with infinite cycle with new App
+	// creation at each iteration, see how it is done in
+	// https://github.com/codegangsta/hip/blob/master/hip.go#L64-L78
+	afterF := func(context *cli.Context) error {
+		line, err := l.Readline()
```
Comment (AnnaShaleva) [inline pkg/vm/cli/cli.go:312]: Subject for discussion.

File: pkg/vm/cli/cli.go [hunk 2]
```diff
@@ -210,209 +242,310 @@ var (
...
+		// TODO: we need more complicated solution to split line into a bash-like set of arguments.
+		// The problem is in proper quotes/escaping symbols handling, so we can't just use
+		// `strings.Fields(...)` or `strings.Split(...)` here.
+		// Possible libraries that can be used for that:
+		// 1. https://github.com/kballard/go-shellquote
+		// 2. https://github.com/cosiner/argv
+		// 3. https://github.com/anmitsu/go-shlex (used by ishell)
+		//
+		// See how this is done by ishell: https://github.com/abiosoft/ishell/blob/master/ishell.go#L291-L333
+		args, err := shlex.Split(line)
```
Comment (AnnaShaleva) [inline pkg/vm/cli/cli.go:329]: Subject for discussion.

**Comment by AnnaShaleva** [comment]
@roman-khimov, currently we have three unresolved questions:

1. https://github.com/nspcc-dev/neo-go/pull/2365#discussion_r809055715
2. https://github.com/nspcc-dev/neo-go/pull/2365#discussion_r809055945
3. Currently `^C` interrupts prompt immediately and I'm not sure I am able to correctly override this behaviour. Can we leave it as is?

The rest of the code is as close to the old version as possible, so it can be reviewed.

File: pkg/vm/cli/cli.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/vm/cli/cli.go]: Fixed with external infinite loop.

File: pkg/vm/cli/cli.go [hunk 3]
```diff
@@ -47,63 +47,67 @@ const (
...
-		Usage:     "Place a breakpoint",
-		UsageText: `break <ip>`,
-		Description: `break <ip>
-<ip> is mandatory parameter, example:
-> break 12`,
+		Name:  "break",
+		Usage: "Place a breakpoint at the specified instruction",
+		Flags: []cli.Flag{
+			cli.IntFlag{
+				Name:     "ip, i",
```
Comment (roman-khimov) [inline pkg/vm/cli/cli.go:64]: So we need to type `break --ip 12` instead of `break 12`? That's a regression, it shouldn't be like that.

File: pkg/vm/cli/cli.go [hunk 4]
```diff
@@ -47,63 +47,67 @@ const (
...
-		Usage:     "Load a NEF-consistent script into the VM",
-		UsageText: `loadnef <file> <manifest>`,
-		Description: `loadnef <file> <manifest>
-both parameters are mandatory, example:
-> loadnef /path/to/script.nef /path/to/manifest.json`,
+		Name:  "loadnef",
+		Usage: "Load a NEF-consistent script into the VM",
+		Flags: []cli.Flag{
+			cli.StringFlag{
+				Name:     "manifest, m",
```
Comment (roman-khimov) [inline pkg/vm/cli/cli.go:101]: It's a task-specific CLI, positional arguments are fine here.

File: pkg/vm/cli/cli.go (hunk 3 above)
Comment (AnnaShaleva) [reply pkg/vm/cli/cli.go]: OK, reverted.

File: pkg/vm/cli/cli.go [hunk 5]
```diff
@@ -819,7 +819,7 @@ const logo = `
 `
 
 func printLogo(w io.Writer) {
-	fmt.Fprintln(w, logo)
+	fmt.Fprintf(w, "%s\n", logo)
```
Comment (roman-khimov) [inline pkg/vm/cli/cli.go:822]: `fmt.Fprint`? `Fprintf` is always slower (not that it matters much here, but).

**Review by roman-khimov — APPROVED** [review]
