### PR TITLE
vm,dao: return storage iterator from DAO in Storage.Find interop

### LINKED ISSUE #988: Storage mismatch @mainnet's block 4634551
file BlockStorage_4700000/dump-block-4635000.json: block 4634551, changes number mismatch: 7 vs 5

We have more changes than C#, likely some transaction succeeds for us, but fails in C# similar to #977. Nothing in the log for this block.

### PR DESCRIPTION
**Pull request by fyrchik**
Fix #988 .

Reproduce behavior of the reference realization:
- if item was Put in cache after it was encountered during
  Storage.Find, it must appear twice
- checking if item is in cache must be performed in real-time
  during `Iterator.Next()`

Need too retest #822 .

### CODE REVIEW

**Comment by fyrchik** [comment]
Linter is unhappy, because we return unexported type. But it is intended to be opaque. Maybe we should just return an interop item.

**Comment by roman-khimov** [comment]
Or maybe we can move `storageWrapper` out of `vm`? I don't think it should be a part of `vm`.

File: pkg/core/dao/cacheddao.go [hunk 1]
```diff
@@ -315,6 +316,51 @@ func (cd *Cached) DeleteStorageItem(scripthash util.Uint160, key []byte) error {
 	return nil
 }
 
+// GetStorageItemsIterator returns iterator over all storage items.
+// Function returned can be called until first error.
+func (cd *Cached) GetStorageItemsIterator(hash util.Uint160, prefix []byte) (vm.StorageIteratorFunc, error) {
+	items, err := cd.DAO.GetStorageItems(hash)
```
Comment (roman-khimov) [inline pkg/core/dao/cacheddao.go:322]: It'd be nice to limit these by `prefix`.

File: pkg/core/dao/cacheddao.go [hunk 2]
```diff
@@ -315,6 +316,51 @@ func (cd *Cached) DeleteStorageItem(scripthash util.Uint160, key []byte) error {
...
+			return nil, nil, errors.New("no more items")
+		}
+		k := cd.storage.keys[hash][keyIndex]
+		v := cache[k]
+		if v.State != delOp && bytes.HasPrefix([]byte(k), prefix) {
+			val := make([]byte, len(v.StorageItem.Value))
+			copy(val, v.StorageItem.Value)
+			return []byte(k), val, nil
+		}
+		return getItemFromCache()
```
Comment (roman-khimov) [inline pkg/core/dao/cacheddao.go:345]: Mixing iterative and recursive styles this way is not a good idea, IMO. This is complex enough already.

Comment (fyrchik) [reply pkg/core/dao/cacheddao.go]: Fixed.

File: pkg/core/dao/cacheddao.go (hunk 1 above)
Comment (fyrchik) [reply pkg/core/dao/cacheddao.go]: Fixed.

**Comment by roman-khimov** [comment]
Confirming that is actually fixes #977 too:
```
2020-05-27T11:30:15.241+0300    WARN    contract invocation failed      {"tx": "61366ab9fe37e100854446ab30005d7afbb093096670592ed8d499e3b6a6f753", "block": 2400907, "error": "error encountered at instruction 79 (THROWIFNOT): THROWIFNOT"}
```
Quick application log dump:
```
&{53f7a6b6e399d4d82e5970660993b0fb7a5d0030ab46448500e137feb96a3661 Application FAULT 5.645 [] []}
```
