### PR TITLE
compiler: support handling SwitchStmt.Init

### LINKED ISSUE #3991: `SwitchStmt.Init` field is ignored by the compiler
```go
func handleSwitchInit() int {
	var n int
	switch n = 1; {
	}
	return n
}
```
## Current Behavior
The `SwitchStmt.Init` field is ignored by the compiler.

## Possible Solution
To the `codegen.Visit` method add handling the `SwitchStmt.Init` field.

## Steps to Reproduce
See what result the function above returns. (It should return 1).

## Your Environment
v0.111.0

### PR DESCRIPTION
**Pull request by Turalchik**
Close #3991.

### CODE REVIEW

File: pkg/compiler/switch_test.go [hunk 1]
```diff
@@ -259,6 +259,104 @@ var switchTestCases = []testCase{
 		`,
 		big.NewInt(6),
 	},
+	{
+		"switch with init assignment",
```
Comment (AnnaShaleva) [inline pkg/compiler/switch_test.go]: No need to specify `switch` here, it's a batch of `switch` tests.

File: pkg/compiler/switch_test.go [hunk 2]
```diff
@@ -259,6 +259,104 @@ var switchTestCases = []testCase{
...
+			var n int
+			switch n = 1; {
+			}
+			return n
+		}
+		`,
+		big.NewInt(1),
+	},
+	{
+		"switch init short decl shadow",
```
Comment (AnnaShaleva) [inline pkg/compiler/switch_test.go]: Punctuation?

File: pkg/compiler/switch_test.go [hunk 3]
```diff
@@ -259,6 +259,104 @@ var switchTestCases = []testCase{
...
+			return n
+		}
+		`,
+		big.NewInt(10),
+	},
+	{
+		"switch init with multiple assignment",
+		`func F%d() int {
+			var a, b int
+			switch a, b = 2, 3; {
```
Comment (AnnaShaleva) [inline pkg/compiler/switch_test.go:292]: Check also `:=` with multiple assignment, without shadowing.

File: pkg/compiler/switch_test.go [hunk 4]
```diff
@@ -259,6 +259,104 @@ var switchTestCases = []testCase{
...
+				return -1
+			}
+		}
+		`,
+		big.NewInt(7),
+	},
+	{
+		"switch init evaluation order",
+		`var order []int
+		func mark(v int) int { order = append(order, v); return v }
```
Comment (AnnaShaleva) [inline pkg/compiler/switch_test.go]: s/mark/add

**Review by AnnaShaleva — APPROVED** [review]
Good job, nice testcases.
