### PR TITLE
vm: convert big.Int to []byte properly

### LINKED ISSUE #501: Fix failing TXes from mainnet
Attached set fails with our node:
```
time="2019-11-14T18:25:25+03:00" level=warning msg="contract invocation failed" block=1572863 err="error encountered at instruction 163 (THROWIFNOT): THROWIFNOT" tx=f8d2009b72ae27ea77a8e4b3bb787af0a9dd447fc97263f5e08a9f6428ad06d2
time="2019-11-14T18:25:30+03:00" level=warning msg="contract invocation failed" block=1574127 err="error encountered at instruction 79 (THROWIFNOT): THROWIFNOT" tx=10a2c1c8b28cbb30420cc9e41d954ebb2e909f8495fc3ea5fb978f222eabd452
time="2019-11-14T18:25:30+03:00" level=warning msg="contract invocation failed" block=1574134 err="error encountered at instruction 79 (THROWIFNOT): THROWIFNOT" tx=a927babda72a709308a06151806d1b971187ff455c31c3ddf68116e1719ad9d9
time="2019-11-14T18:25:30+03:00" level=warning msg="contract invocation failed" block=1574147 err="error encountered at instruction 79 (THROWIFNOT): THROWIFNOT" tx=d23951999319a1fa5e8b01cbd4fb8aa892554ea8408439ea605c508ecff4cb05
time="2019-11-14T18:25:30+03:00" level=warning msg="contract invocation failed" block=1574148 err="error encountered at instruction 79 (THROWIFNOT): THROWIFNOT" tx=9d3179aadab28c2cf47d232820c95b017e049c153bb6e139f96da2daf9ffe579
time="2019-11-14T18:25:30+03:00" level=warning msg="contract invocation failed" block=1574155 err="error encountered at instruction 79 (THROWIFNOT): THROWIFNOT" tx=fab5d311c14491bcbfdbd9fd83ce34001438750192375f4399784e996725fad7
time="2019-11-14T18:25:30+03:00" level=warning msg="contract invocation failed" block=1574159 err="error encountered at instruction 79 (THROWIFNOT): THROWIFNOT" tx=c2b1cbd1170f0f5ef1c10a6d3d47ba74d42bcce3dc53cc32f7c17cb59659bde8
time="2019-11-14T18:25:30+03:00" level=warning msg="contract invocation failed" block=1574166 err="error encountered at instruction 79 (THROWIFNOT): THROWIFNOT" tx=0a5786202b4846d7fdb220f1e06b7503a7a5ee6681d55ad0573a9e4d515b2a9e
time="2019-11-14T18:25:33+03:00" level=warning msg="contract invocation failed" block=1575138 err="error encountered at instruction 81 (THROWIFNOT): THROWIFNOT" tx=beeaeb3409821d646bd0c2982cfb24ffc250540ad5987285e9464aa304715893
time="2019-11-14T18:25:38+03:00" level=warning msg="contract invocation failed" block=1575759 err="error encountered at instruction 163 (THROWIFNOT): THROWIFNOT" tx=58bcb10029f5a132cca9af8bead9faa38f61a7ca8ba15e7e3fb20f350146c6e7
time="2019-11-14T18:25:51+03:00" level=warning msg="contract invocation failed" block=1579486 err="error encountered at instruction 161 (THROWIFNOT): THROWIFNOT" tx=67013e6093d55cbddd6dddc88c35a2db09d30a5d1e10989cd2dfa427f8722e89
time="2019-11-14T18:25:51+03:00" level=warning msg="contract invocation failed" block=1579492 err="error encountered at instruction 161 (THROWIFNOT): THROWIFNOT" tx=47b63789bcd056f1bc5c054a32f221f965742e7f60556f903e99db8553c816ab
time="2019-11-14T18:25:51+03:00" level=warning msg="contract invocation failed" block=1579495 err="error encountered at instruction 161 (THROWIFNOT): THROWIFNOT" tx=27149890ce9777fcd4b773740b3819e0ba9613e0b35626cda725d68e06422269
time="2019-11-14T18:25:51+03:00" level=warning msg="contract invocation failed" block=1579501 err="error encountered at instruction 161 (THROWIFNOT): THROWIFNOT" tx=ab08040b6bb86f646f50f94330d59291ea749656123d304c959bc2619594538e
time="2019-11-14T18:25:52+03:00" level=warning msg="contract invocation failed" block=1579571 err="error encountered at instruction 79 (THROWIFNOT): THROWIFNOT" tx=41a4ee8859fb29100e01c082b08c3738865a2b1278a9dda44d48e4ccc3fad7e6
time="2019-11-14T18:25:52+03:00" level=warning msg="contract invocation failed" block=1579582 err="error encountered at instruction 77 (THROWIFNOT): THROWIFNOT" tx=86bee85323b58000c561907289602b61be606353b26ffb3c9b1ca7c76b07f1a5
time="2019-11-14T18:25:52+03:00" level=warning msg="contract invocation failed" block=1579582 err="error encountered at instruction 77 (THROWIFNOT): THROWIFNOT" tx=22d6732cce472213aa9bf9c4f70ddd50656b89f9175d0b1307b4af3c2c5d84c6
time="2019-11-14T18:25:52+03:00" level=warning msg="contract invocation failed" block=1579582 err="error encountered at instruction 77 (THROWIFNOT): THROWIFNOT" tx=44a2c2dda73a75e929c2a703c6b6205b2e77076a7d6a40b4fa3609c4230ad361
time="2019-11-14T18:25:55+03:00" level=warning msg="contract invocation failed" block=1579966 err="error encountered at instruction 162 (THROWIFNOT): THROWIFNOT" tx=17b20bd813d7cf14995f71e1de1976d96359a0ae12cd785f51bdfe8ef1070ad8
time="2019-11-14T18:25:56+03:00" level=warning msg="contract invocation failed" block=1580064 err="error encountered at instruction 323 (THROWIFNOT): THROWIFNOT" tx=0ce6c08e8c5415a953639fb55cc30a018e038e70287b225ddf8c0577ecd07dd6
time="2019-11-14T18:25:56+03:00" level=warning msg="contract invocation failed" block=1580066 err="error encountered at instruction 323 (THROWIFNOT): THROWIFNOT" tx=142ad37c6be442fc0b12c30863af3601b3274846f2513a7055c57e41f64a62ca
time="2019-11-14T18:25:56+03:00" level=warning msg="contract invocation failed" block=1580069 err="error encountered at instruction 323 (THROWIFNOT): THROWIFNOT" tx=bdb8c7f1e2a3c1804395e6e07601b584c7d17a0857eaef3575798a244ad98ed4
time="2019-11-14T18:31:21+03:00" level=warning msg="contract invocation failed" block=1699830 err="error encountered at instruction 81 (THROWIFNOT): THROWIFNOT" tx=9150383d7a35ec27c3fee21426e09402bbb723af85f909ecdd4ee403eb6b837c
time="2019-11-14T18:31:33+03:00" level=warning msg="contract invocation failed" block=1703749 err="error encountered at instruction 81 (THROWIFNOT): THROWIFNOT" tx=09950f40413487c251fcbf8984ff9c997c5ab081da715f47fa5e9bb57a3a3110
time="2019-11-14T18:31:34+03:00" level=warning msg="contract invocation failed" block=1704005 err="error encountered at instruction 81 (THROWIFNOT): THROWIFNOT" tx=a6f2b224a0bed7683f6daf543e8d1dff94808b9c6b3c15598d46ef4c7649a7cf
time="2019-11-14T18:32:40+03:00" level=warning msg="contract invocation failed" block=1717968 err="error encountered at instruction 81 (THROWIFNOT): THROWIFNOT" tx=367ea8a40f34e7f4a00df6db48fd1d809c4b5ee63389c0245e66b746619c4342
time="2019-11-14T18:33:49+03:00" level=warning msg="contract invocation failed" block=1734778 err="error encountered at instruction 81 (THROWIFNOT): THROWIFNOT" tx=74e45a49cd3b9efd2d5b4ee357371b6633758099acbefa85f54254202cf44627
time="2019-11-14T18:34:48+03:00" level=warning msg="contract invocation failed" block=1751310 err="error encountered at instruction 81 (THROWIFNOT): THROWIFNOT" tx=49ab4f454ea1d7a5be74c82ef8fb64fda26bb40b13715b65f646970661559ac6
```
But it works for C# node:
```
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xf8d2009b72ae27ea77a8e4b3bb787af0a9dd447fc97263f5e08a9f6428ad06d2","executions":[{"trigger":"Application","contract":"0xd7cad909cead03b5df421bb845d133c14eb79471","vmstate":"HALT","gas_consumed":"5.653","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"a984fdfe5d98dce26432ba2fcd6ff45d04a82f2d"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"001082e3d103"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"45ca6736836d52d4c0d9f2c0ed1d384c65d39a81"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00d0c3a2ac03"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"90cd1bf0d8e27ecc59cf2d7e189655dc83c25ae8"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00c02cc89901"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x10a2c1c8b28cbb30420cc9e41d954ebb2e909f8495fc3ea5fb978f222eabd452","executions":[{"trigger":"Application","contract":"0x300cc3c2193becf9f86b3d6b3a0b237d0e36b6c1","vmstate":"HALT","gas_consumed":"1.885","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"138bb1207f869b6c08a6fbd911251fcbf8194aa9"},{"type":"ByteArray","value":"8e568bcbf3bab3d524f556a78148d462c0be7383"},{"type":"ByteArray","value":"80c3c901"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xa927babda72a709308a06151806d1b971187ff455c31c3ddf68116e1719ad9d9","executions":[{"trigger":"Application","contract":"0xe3f70b3647cc04ea2cef5140144a5c2e7dfecded","vmstate":"HALT","gas_consumed":"2.793","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"8e568bcbf3bab3d524f556a78148d462c0be7383"},{"type":"ByteArray","value":"138bb1207f869b6c08a6fbd911251fcbf8194aa9"},{"type":"ByteArray","value":"804a5d05"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xd23951999319a1fa5e8b01cbd4fb8aa892554ea8408439ea605c508ecff4cb05","executions":[{"trigger":"Application","contract":"0xc322ab538fe91f279cef0eb707cc5a5b3da2e8da","vmstate":"HALT","gas_consumed":"2.793","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"138bb1207f869b6c08a6fbd911251fcbf8194aa9"},{"type":"ByteArray","value":"8e568bcbf3bab3d524f556a78148d462c0be7383"},{"type":"ByteArray","value":"80f0fa02"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x9d3179aadab28c2cf47d232820c95b017e049c153bb6e139f96da2daf9ffe579","executions":[{"trigger":"Application","contract":"0x826fc7d75484a02a9e5820360d337880a5119e12","vmstate":"HALT","gas_consumed":"1.885","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"138bb1207f869b6c08a6fbd911251fcbf8194aa9"},{"type":"ByteArray","value":"8e568bcbf3bab3d524f556a78148d462c0be7383"},{"type":"ByteArray","value":"005a6202"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xfab5d311c14491bcbfdbd9fd83ce34001438750192375f4399784e996725fad7","executions":[{"trigger":"Application","contract":"0xde967fd33363bd911fca3dd78a10a8846f02f7c5","vmstate":"HALT","gas_consumed":"1.885","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"8e568bcbf3bab3d524f556a78148d462c0be7383"},{"type":"ByteArray","value":"138bb1207f869b6c08a6fbd911251fcbf8194aa9"},{"type":"ByteArray","value":"005a6202"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xc2b1cbd1170f0f5ef1c10a6d3d47ba74d42bcce3dc53cc32f7c17cb59659bde8","executions":[{"trigger":"Application","contract":"0x5c96cef496541b15091ea840930bf53880caff2d","vmstate":"HALT","gas_consumed":"1.885","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"138bb1207f869b6c08a6fbd911251fcbf8194aa9"},{"type":"ByteArray","value":"8e568bcbf3bab3d524f556a78148d462c0be7383"},{"type":"ByteArray","value":"00879303"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x0a5786202b4846d7fdb220f1e06b7503a7a5ee6681d55ad0573a9e4d515b2a9e","executions":[{"trigger":"Application","contract":"0x1e69ceebb933cd4b1f571abd6bfe2ccede5a4059","vmstate":"HALT","gas_consumed":"1.885","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"8e568bcbf3bab3d524f556a78148d462c0be7383"},{"type":"ByteArray","value":"138bb1207f869b6c08a6fbd911251fcbf8194aa9"},{"type":"ByteArray","value":"00879303"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xbeeaeb3409821d646bd0c2982cfb24ffc250540ad5987285e9464aa304715893","executions":[{"trigger":"Application","contract":"0xb574eddb8c301f6d59b2187ccfdf069508623c25","vmstate":"HALT","gas_consumed":"4.677","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"4de8339da3cf90cf2639028150e83643b8935896"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"008c85763105"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"f81488dce63111459f0422f133860d7d4cfb59bf"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"0014edd7e603"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x58bcb10029f5a132cca9af8bead9faa38f61a7ca8ba15e7e3fb20f350146c6e7","executions":[{"trigger":"Application","contract":"0x64f919014c6659049460bc44787b271e5dc09a33","vmstate":"HALT","gas_consumed":"6.561","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"6777310bc18404b27f162e3ddac32656e9077849"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00d0bca54104"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"525a6a913202ce97f3a4a219e76856c82157a068"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00043a092804"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"230663f4668973ce2c040ecc288535f81701f3bf"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00cc7b9fae00"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x67013e6093d55cbddd6dddc88c35a2db09d30a5d1e10989cd2dfa427f8722e89","executions":[{"trigger":"Application","contract":"0x2bf4197e613662c2e66dcc8e08eb26e4ec3baaab","vmstate":"HALT","gas_consumed":"4.677","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"120571912bf0bc241a038a3b72d7740ff5b3b47d"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"006641ce0c"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"e3a4446ece4facd8f971c3d36b77f85405ce922a"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"0082357a0a"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x47b63789bcd056f1bc5c054a32f221f965742e7f60556f903e99db8553c816ab","executions":[{"trigger":"Application","contract":"0x393f81b35c3cb89f4ecfbc6b1f4660f24a637d01","vmstate":"HALT","gas_consumed":"4.677","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"4660fd1cc8afebf4c4961cdf45d5fad65069dbff"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"005847f80d"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"5f5bb4f12477bf1d5d530f057bd2a5519a2a83eb"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00902f5009"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x27149890ce9777fcd4b773740b3819e0ba9613e0b35626cda725d68e06422269","executions":[{"trigger":"Application","contract":"0x317feb6414791e8799d6e73d9da3642bf61d94b6","vmstate":"HALT","gas_consumed":"4.677","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"fa040fb0962dd449e09f536980e2ae0f8cfac512"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"005847f80d"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"dfa94370a4b127830561cdc68dfa2da3894d4b14"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00902f5009"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xab08040b6bb86f646f50f94330d59291ea749656123d304c959bc2619594538e","executions":[{"trigger":"Application","contract":"0x9e2f0590b7bda28cb2c53982332e3392a36bbea0","vmstate":"HALT","gas_consumed":"4.677","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"993ea2ff45f1dce3bf2a79aae6e619764e49734f"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"005847f80d"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"890e1cc21efe9ba795fc8a201a5b16f5282e9e2a"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00902f5009"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x41a4ee8859fb29100e01c082b08c3738865a2b1278a9dda44d48e4ccc3fad7e6","executions":[{"trigger":"Application","contract":"0x634669802d3e350552c0de64bdf3b05bd3c3bccc","vmstate":"HALT","gas_consumed":"1.885","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"2eeee960be8629bdc52db81012331890a1450f20"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00e1f505"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x86bee85323b58000c561907289602b61be606353b26ffb3c9b1ca7c76b07f1a5","executions":[{"trigger":"Application","contract":"0xc799526c09013348d86cb554225b944e1f8a0f92","vmstate":"HALT","gas_consumed":"2.793","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"63725bf5ad9785954d4a39f548f634eabd6ff6e0"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"1027"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x22d6732cce472213aa9bf9c4f70ddd50656b89f9175d0b1307b4af3c2c5d84c6","executions":[{"trigger":"Application","contract":"0x62c056f57b01cfffd8a8bc40086a9c1d2e142dac","vmstate":"HALT","gas_consumed":"2.793","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"63725bf5ad9785954d4a39f548f634eabd6ff6e0"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"1027"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x44a2c2dda73a75e929c2a703c6b6205b2e77076a7d6a40b4fa3609c4230ad361","executions":[{"trigger":"Application","contract":"0x4ff94455cbc0c90e4f38d1dfee63b32c03506239","vmstate":"HALT","gas_consumed":"1.885","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"63725bf5ad9785954d4a39f548f634eabd6ff6e0"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"1027"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x17b20bd813d7cf14995f71e1de1976d96359a0ae12cd785f51bdfe8ef1070ad8","executions":[{"trigger":"Application","contract":"0x23969a5bcb806ab5b17bab921847f26091a96b7a","vmstate":"HALT","gas_consumed":"4.677","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"1e8ed6e6c6d34fa48c1af6ee55fcb972b4c77d15"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00fc8d0e8000"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"fc5eda77325091cd4c90be8c8f331de9e94fc0b8"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"001417c668"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x0ce6c08e8c5415a953639fb55cc30a018e038e70287b225ddf8c0577ecd07dd6","executions":[{"trigger":"Application","contract":"0x75c76e114c65d0f1f20debb1a16ef2a000c36aca","vmstate":"HALT","gas_consumed":"8.445","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"f79ec98f48efea41f4f494b8b1e4626dc96ed8aa"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00b1e3962e"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"7ea2ded9f42d6fccda355e29991e04501412864c"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00b864d945"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"1d3ed967ec1b43274a151326bbbc7d2199afe9e0"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00b864d945"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"9a0ae745f6221f8bb0c0327d07b1f139e4ac61bc"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00eff78a2e"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x142ad37c6be442fc0b12c30863af3601b3274846f2513a7055c57e41f64a62ca","executions":[{"trigger":"Application","contract":"0xb399634a1a5147b4817805eb77649e2ba249fa7b","vmstate":"HALT","gas_consumed":"8.445","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"e1c24f258016534b683e7223c856c867d4b93e43"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00d0ed902e"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"b88cdbff983843b02cedffd9e7906b36cfc1557b"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00b864d945"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"67db4d21c1747c0cae39fdfce69b904ab9858490"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00b864d945"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"2a1429356d3f49a216a85f7f5f2c48f1b0ea9167"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00d0ed902e"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xbdb8c7f1e2a3c1804395e6e07601b584c7d17a0857eaef3575798a244ad98ed4","executions":[{"trigger":"Application","contract":"0x4251637d9547ad4b77ff7aa8cf22eff808292da3","vmstate":"HALT","gas_consumed":"8.445","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"296aeae3a8909d051475434a42c0af19e622b231"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00d0ed902e"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"8ce27af51991ad57d4f69f72b511c8c3fbb9aa72"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00b864d945"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"7731f52f879dcf8e64ed66622a0793f6707051c0"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00b864d945"}]}},{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"a338a456cc2cd83c078794b201b3226df9446727"},{"type":"ByteArray","value":"6063795d3b9b3cd55aef026eae992b91063db0db"},{"type":"ByteArray","value":"00d0ed902e"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x9150383d7a35ec27c3fee21426e09402bbb723af85f909ecdd4ee403eb6b837c","executions":[{"trigger":"Application","contract":"0x81866f351a9fcfe31f4eb6070317c03d6acd7449","vmstate":"HALT","gas_consumed":"2.822","stack":[],"notifications":[{"contract":"0xa0777c3ce2b169d4a23bcba4565e3225a0122d95","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"4c21b65ff0d42fc053db9463c03ab05c9023c4aa"},{"type":"ByteArray","value":"843ea8e688aeaecd92695a34eff18f4dfd0d7942"},{"type":"ByteArray","value":"00407a10f35a"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x09950f40413487c251fcbf8984ff9c997c5ab081da715f47fa5e9bb57a3a3110","executions":[{"trigger":"Application","contract":"0xed1e965ebafea188d58e81ffd3f2056d21878887","vmstate":"HALT","gas_consumed":"2.822","stack":[],"notifications":[{"contract":"0xa0777c3ce2b169d4a23bcba4565e3225a0122d95","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"4c21b65ff0d42fc053db9463c03ab05c9023c4aa"},{"type":"ByteArray","value":"34ed6c161b12bc489715e0446c3db3d9c6f53eb5"},{"type":"ByteArray","value":"00c6de803509"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0xa6f2b224a0bed7683f6daf543e8d1dff94808b9c6b3c15598d46ef4c7649a7cf","executions":[{"trigger":"Application","contract":"0x55cc216904eadfb2af6bfcbaba7a44cef4af6a85","vmstate":"HALT","gas_consumed":"2.822","stack":[],"notifications":[{"contract":"0xa0777c3ce2b169d4a23bcba4565e3225a0122d95","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"4c21b65ff0d42fc053db9463c03ab05c9023c4aa"},{"type":"ByteArray","value":"3b3d3aad2889b7ca7a87f1258a1660907d4be1b9"},{"type":"ByteArray","value":"00359e753a4f"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x367ea8a40f34e7f4a00df6db48fd1d809c4b5ee63389c0245e66b746619c4342","executions":[{"trigger":"Application","contract":"0x762fde4042cd456e8af9609c5a833a597e597fbd","vmstate":"HALT","gas_consumed":"5.644","stack":[],"notifications":[{"contract":"0xa0777c3ce2b169d4a23bcba4565e3225a0122d95","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"4c21b65ff0d42fc053db9463c03ab05c9023c4aa"},{"type":"ByteArray","value":"ff086c3a83fdfdabe387eec9236be5a9c91187ee"},{"type":"ByteArray","value":"0020dd0d7a07"}]}},{"contract":"0xa0777c3ce2b169d4a23bcba4565e3225a0122d95","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"4c21b65ff0d42fc053db9463c03ab05c9023c4aa"},{"type":"ByteArray","value":"4901ec6a5ab4110cebd8b27bacfb4c1404bb5483"},{"type":"ByteArray","value":"006d07e46e0b"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x74e45a49cd3b9efd2d5b4ee357371b6633758099acbefa85f54254202cf44627","executions":[{"trigger":"Application","contract":"0x91072aeebca5e8e7824c4b9da86a7c1001f70d3a","vmstate":"HALT","gas_consumed":"1.884","stack":[],"notifications":[{"contract":"0xecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"3b044b9a4675065138459af5e751b4404aea4f0d"},{"type":"ByteArray","value":"43ea17118069fd50e56436eb371aaf01a03425a1"},{"type":"ByteArray","value":"00fc8d0e8000"}]}}]}]}}
{"jsonrpc":"2.0","id":1,"result":{"txid":"0x49ab4f454ea1d7a5be74c82ef8fb64fda26bb40b13715b65f646970661559ac6","executions":[{"trigger":"Application","contract":"0xc94f028173189984b047b3ce18f61a68035417a5","vmstate":"HALT","gas_consumed":"2.857","stack":[],"notifications":[{"contract":"0x0d821bd7b6d53f5c2b40e217c6defc8bbe896cf5","state":{"type":"Array","value":[{"type":"ByteArray","value":"7472616e73666572"},{"type":"ByteArray","value":"95fad563c2ee4adb6dc5c4c4e3f6d2e05ba60c92"},{"type":"ByteArray","value":"fde61e22ddbfa4c26cd1ea90c177b47b61eeac3b"},{"type":"ByteArray","value":"00e092651701"}]}}]}]}}
```
[haltedTxes.txt](https://github.com/nspcc-dev/neo-go/files/3852092/haltedTxes.txt)

### PR DESCRIPTION
**Pull request by fyrchik**
Closes #501 .

Big.Int Bytes()/SetBytes() methods are not symmetric.
Moreover we need to mimic C# node behavior:
- if a positive number has MSB set, 0x00 byte should be appended
  to distinguish positive number from negatives
- negative numbers should serialize as two's-complement

### CODE REVIEW

File: pkg/vm/bigint_test.go [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+	{-255, []byte{1, 255}},
+	{256, []byte{0, 1}},
+	{-256, []byte{0, 255}},
+	{123456789, []byte{21, 205, 91, 7}},
+	{-123456789, []byte{235, 50, 164, 248}},
+	{-6777216, []byte{128, 150, 152}}, // tx c8ba2ce29e07447639b9b658db3930c4cce617652d325e78b768ee9d4dbd72b8
+	{6777216, []byte{128, 105, 103}},
+
+	{127, []byte{127}},
+	{-128, []byte{128}},
```
Comment (roman-khimov) [inline pkg/vm/bigint_test.go]: These two are duplicated above.

File: pkg/vm/bigint_test.go [hunk 2]
```diff
@@ -0,0 +1,108 @@
+package vm
+
+import (
+	"math/big"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+
```
Comment (roman-khimov) [inline pkg/vm/bigint_test.go]: Empty line.

File: pkg/vm/bigint.go [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+	"math/big"
+	"math/bits"
+)
+
+// wordSizeBytes is a size of a big.Word (uint) in bytes.`
+const wordSizeBytes = bits.UintSize / 8
+
+// bytesToInt converts data in little-endian format to
+// an integer.
+func bytesToInt(n *big.Int, data []byte) *big.Int {
```
Comment (roman-khimov) [inline pkg/vm/bigint.go]: Why `n` parameter? All users of it allocate a new `big.Int` and that could easily be done inside `bytesToInt`. It also makes these functions more symmetric.

Comment (fyrchik) [reply pkg/vm/bigint.go]: Yeah, I was thinking about scenarios where it is preallocated, but anyway right now I allocate new big.Int on every usage.

File: pkg/vm/bigint.go [hunk 4]
```diff
@@ -0,0 +1,137 @@
+package vm
+
+import (
+	"encoding/binary"
+	"math/big"
+	"math/bits"
+)
+
+// wordSizeBytes is a size of a big.Word (uint) in bytes.`
```
Comment (volekerb) [inline pkg/vm/bigint.go]: .` in the end of the line. Is that expected?
