### PR TITLE
rpc/request: allow to provide bool parameters

### LINKED ISSUE #1919: RPC server does not parse boolean smart contract type correctly
neo-go version 0.91.1

Consider smart contract method with boolean argument:
```go
package testcontract
import "github.com/nspcc-dev/neo-go/pkg/interop/runtime"
func Foo(x bool) {
	if x {
		runtime.Log("True")
	} else {
		runtime.Log("False")
	}
}
```

Invocations of this method fail with this error:
```
$ neo-go contract testinvokefunction -r http://127.0.0.1:30333 cdd9805cb66358af557185e34c002f80f3338967 foo bool:true
Invalid Params (-32602) - Problem parsing request parameters - %!s(<nil>)
```

It seems that [unmarshal](https://github.com/nspcc-dev/neo-go/blob/933743ce870915ed8b15073f5bae0c4bdc710157/pkg/rpc/request/param.go#L263) function of `request.Param` structure can't parse bool field of such request:
```json
["cdd9805cb66358af557185e34c002f80f3338967","foo",[{"type":"Boolean","value":true}],[{"account":"0x8aebbe8c9ebe48a946057d5fa7fbceb439b4f768","scopes":"Global"}]]
```
In the end it returns `return errors.New("unknown type")` error.

Invocations with `int:0` and `int:1` arguments execute correctly.

### PR DESCRIPTION
**Pull request by fyrchik**
Fix #1919.

### CODE REVIEW

File: pkg/rpc/request/param.go [hunk 1]
```diff
@@ -263,10 +266,12 @@ func (p Param) GetSignersWithWitnesses() ([]transaction.Signer, []transaction.Wi
 func (p *Param) UnmarshalJSON(data []byte) error {
 	var s string
 	var num float64
+	var b bool
 	// To unmarshal correctly we need to pass pointers into the decoder.
 	var attempts = [...]Param{
 		{NumberT, &num},
 		{StringT, &s},
+		{BooleanT, &b},
```
Comment (roman-khimov) [inline pkg/rpc/request/param.go:274]: Swap with `StringT`?

**Review by AnnaShaleva — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]
