### PR TITLE
Network reconnections and fixes

### LINKED ISSUE #390: No peer reconnection attempts after disconnect
Running neo-go for testnet:
```
$ ./bin/neo-go node -testnet
```
It connects to ten specified nodes:
```
INFO[0000] node started                                  blockHeight=0 headerHeight=0
INFO[0002] new peer connected                            addr="47.254.28.42:20333"
INFO[0002] new peer connected                            addr="47.89.253.82:20333"
INFO[0002] new peer connected                            addr="47.52.168.73:20333"
INFO[0002] new peer connected                            addr="47.91.248.98:20333"
INFO[0002] new peer connected                            addr="47.97.73.20:20333"
INFO[0002] new peer connected                            addr="47.254.44.88:20333"
INFO[0002] new peer connected                            addr="47.254.83.14:20333"
INFO[0002] new peer connected                            addr="47.254.43.76:20333"
INFO[0002] new peer connected                            addr="47.91.225.117:20333"
INFO[0002] new peer connected                            addr="47.52.159.228:20333"
INFO[0002] started protocol                              addr="47.254.43.76:20333" id=2034639675 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.254.44.88:20333" id=268155065 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.254.83.14:20333" id=1894107231 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.89.253.82:20333" id=467902258 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.254.28.42:20333" id=404946088 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.97.73.20:20333" id=294459045 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.91.248.98:20333" id=1893056092 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.52.159.228:20333" id=1817730681 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.91.225.117:20333" id=1994689351 startHeight=3104817 userAgent="/Neo:2.10.3/"
INFO[0002] started protocol                              addr="47.52.168.73:20333" id=2142382291 startHeight=3104817 userAgent="/Neo:2.10.3/"
```
Syncs some blocks:
```
INFO[0028] blockchain persist completed                  blockHeight=200 headerHeight=2000 persisted=200 took=8.259051ms
INFO[0040] blockchain persist completed                  blockHeight=600 headerHeight=8000 persisted=200 took=12.520599ms
```
And then peers start to disconnect with `read: connection reset by peer`:
```
WARN[0042] peer disconnected                             addr="47.97.73.20:20333" peerCount=9 reason="read tcp 10.8.103.64:39904->47.97.73.20:20333: read: connection reset by peer"
WARN[0047] peer disconnected                             addr="47.254.28.42:20333" peerCount=8 reason="read tcp 10.8.103.64:34390->47.254.28.42:20333: read: connection reset by peer"
```
After a while all of them disconnect:
```
INFO[1318] blockchain persist completed                  blockHeight=15437 headerHeight=150000 persisted=131 took=11.868324ms
INFO[1326] blockchain persist completed                  blockHeight=15637 headerHeight=152000 persisted=200 took=8.035574ms
INFO[1350] blockchain persist completed                  blockHeight=15688 headerHeight=154000 persisted=51 took=3.130332ms
WARN[1350] peer disconnected                             addr="47.254.43.76:20333" peerCount=0 reason="read tcp 10.8.103.64:56134->47.254.43.76:20333: read: connection reset by peer"
```
And no reconnection attempts are made which is wrong, the node just sits waiting for something. It shouldn't require restarting a node to continue synchronizing.

### PR DESCRIPTION
**Pull request by roman-khimov**
This one fixes #390 and some connected problems. After this patchset the node reconnects to some other nodes if anything goes wrong and it better senses when something goes wrong. It also fixes some block handling problems based on the testnet connection experience.

### CODE REVIEW

File: pkg/network/server.go [hunk 1]
```diff
@@ -15,13 +16,15 @@ import (
...
 const (
-	minPeers      = 5
-	maxBlockBatch = 200
-	minPoolCount  = 30
+	// peer numbers are arbitrary at the moment
+	minPeers       = 5
+	maxPeers       = 20
+	maxBlockBatch  = 200
+	maxAddrsToSend = 200
+	minPoolCount   = 30
```
Comment (golangcibot) [inline pkg/network/server.go]: `minPoolCount` is unused (from `deadcode`)

Comment (roman-khimov) [reply pkg/network/server.go]: Yeah, thanks @golangcibot.

**Comment by roman-khimov** [comment]
I have one more little change in the queue, now based on mainnet connection experience. Mainnet is a completely different beast in its connection dynamics, which allowed to see some minor issues with current code (nonetheless I'm running the node for more than 10 hours at the moment, so it was able to reconnect to different other nodes many many times).

File: pkg/core/blockchain.go [hunk 2]
```diff
@@ -429,6 +429,15 @@ func (bc *Blockchain) persist(ctx context.Context) (err error) {
 			"blockHeight":  bc.BlockHeight(),
 			"took":         time.Since(start),
 		}).Info("blockchain persist completed")
+	} else {
+		// So we have some blocks in cache but can't persist them?
+		// Either there are some stale blocks there or the other way
+		// around (which was seen in practice) --- there are some fresh
+		// blocks that we can't persist yet. Some of the latter can be useful
+		// or can be bogus (higher than the header height we expect at
```
Comment (volekerb) [inline pkg/core/blockchain.go]: nit: looks like closing bracket missing

File: pkg/network/discovery.go [hunk 3]
```diff
@@ -6,6 +6,7 @@ import (
 
 const (
 	maxPoolSize = 200
+	connRetries = 3
```
Comment (volekerb) [inline pkg/network/discovery.go]: nit: probably it will make sense to move it to config. But not now maybe.

File: pkg/network/payload/payload.go [hunk 4]
```diff
@@ -7,3 +7,22 @@ type Payload interface {
 	EncodeBinary(io.Writer) error
 	DecodeBinary(io.Reader) error
 }
+
+// NullPayload is a dummy payload with no fields
```
Comment (volekerb) [inline pkg/network/payload/payload.go]: nit: dot in the end

File: pkg/network/server.go [hunk 5]
```diff
@@ -253,6 +266,14 @@ func (s *Server) handleInvCmd(p Peer, inv *payload.Inventory) error {
 	return p.WriteMsg(NewMessage(s.Net, CMDGetData, payload))
 }
 
+// handleAddrCmd will process received addresses.
+func (s *Server) handleAddrCmd(p Peer, addrs *payload.AddressList) error {
```
Comment (volekerb) [inline pkg/network/server.go]: is that an implementation of some interface and that's why it returns error?
since right now it always returns nil for some reason

File: pkg/network/server.go [hunk 6]
```diff
@@ -312,29 +315,37 @@ func (s *Server) handleMessage(peer Peer, msg *Message) error {
...
-		if peer.Version() == nil {
-			return errInvalidHandshake
+	if peer.Handshaked() {
+		switch msg.CommandType() {
+		case CMDAddr:
+			addrs := msg.Payload.(*payload.AddressList)
+			return s.handleAddrCmd(peer, addrs)
+		case CMDHeaders:
+			headers := msg.Payload.(*payload.Headers)
+			go s.handleHeadersCmd(peer, headers)
```
Comment (volekerb) [inline pkg/network/server.go]: curios: 
why do u handle headers in separate routine but handle blocks not?

File: pkg/network/tcp_peer.go [hunk 7]
```diff
@@ -45,6 +72,55 @@ func (p *TCPPeer) WriteMsg(msg *Message) error {
 	}
 }
 
+// Handshaked returns status of the handshake, whether it's completed or not
```
Comment (volekerb) [inline pkg/network/tcp_peer.go]: nit: dots in the end of comments

File: pkg/network/discovery.go [hunk 8]
```diff
@@ -105,6 +114,28 @@ func (d *DefaultDiscovery) BadPeers() []string {
 	return addrs
 }
 
+// GoodPeers returns all addresses of known good peers (that at least once
+// succeded handshaking with us.
+func (d *DefaultDiscovery) GoodPeers() []string {
```
Comment (volekerb) [inline pkg/network/discovery.go]: GoodPeers == ConnectedPeers? or not?

Comment (volekerb) [reply pkg/network/discovery.go]: not yet got it. Just only handshaked

File: pkg/network/payload/payload.go (hunk 4 above)
Comment (volekerb) [reply pkg/network/payload/payload.go]: https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

File: pkg/network/tcp_peer.go (hunk 7 above)
Comment (volekerb) [reply pkg/network/tcp_peer.go]: https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

File: pkg/network/discovery.go (hunk 8 above)
Comment (roman-khimov) [reply pkg/network/discovery.go]: Not exactly, semantically it's `ConnectedOnce`, they can be disconnected now, but we were able to do a complete handshake with them once upon a time, so they're probably good.

File: pkg/network/discovery.go (hunk 3 above)
Comment (roman-khimov) [reply pkg/network/discovery.go]: Maybe, but that's not a priority for now, certainly.

File: pkg/network/payload/payload.go (hunk 4 above)
Comment (roman-khimov) [reply pkg/network/payload/payload.go]: I will start putting dots in the end of sentences.

File: pkg/network/tcp_peer.go (hunk 7 above)
Comment (roman-khimov) [reply pkg/network/tcp_peer.go]: I will start putting dots in the end of sentences.

File: pkg/network/server.go (hunk 5 above)
Comment (roman-khimov) [reply pkg/network/server.go]: I made it return error just to unify handlers even though they don't have any standardized interfaces.

File: pkg/network/server.go (hunk 6 above)
Comment (roman-khimov) [reply pkg/network/server.go]: Well, it was done this way originally and I'm not yet sure why. Maybe it's worth some digging into, but I think not in this PR.

Comment (volekerb) [reply pkg/network/server.go]: I see
