### PR TITLE
rpc, core: add FaultException to AppExecResult and Invoke* results

### LINKED ISSUE #1440: Add error message to execution results
See neo-project/neo#1885. Related to neo-project/neo-modules#334. I think we can implement the last one right away, it may be an extension if it won't be implemented in C# module, but we really need it for neo-go client invocations to show more meaningful errors.

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Closes #1440

### CODE REVIEW

File: pkg/core/state/notification_event.go [hunk 1]
```diff
@@ -62,6 +64,11 @@ func (aer *AppExecResult) EncodeBinary(w *io.BinWriter) {
 	w.WriteU64LE(uint64(aer.GasConsumed))
 	stackitem.EncodeBinaryStackItem(stackitem.NewArray(aer.Stack), w)
 	w.WriteArray(aer.Events)
+	var e string
+	if aer.FaultException != nil {
+		e = aer.FaultException.Error()
+	}
+	w.WriteString(hex.EncodeToString([]byte(e)))
```
Comment (fyrchik) [inline pkg/core/state/notification_event.go:71]: Why do we need to encode this in hex?

File: pkg/core/state/notification_event.go [hunk 2]
```diff
@@ -23,12 +24,13 @@ type NotificationEvent struct {
...
-	GasConsumed int64
-	Stack       []stackitem.Item
-	Events      []NotificationEvent
+	TxHash         util.Uint256
+	Trigger        trigger.Type
+	VMState        vm.State
+	GasConsumed    int64
+	Stack          []stackitem.Item
+	Events         []NotificationEvent
+	FaultException error
```
Comment (fyrchik) [inline pkg/core/state/notification_event.go:33]: I think, string is ok here, because we use it as string anyway and `encode/decode` conversion is lossy.

File: pkg/core/state/notification_event_test.go [hunk 3]
```diff
@@ -11,6 +11,7 @@ import (
 	"github.com/nspcc-dev/neo-go/pkg/vm"
 	"github.com/nspcc-dev/neo-go/pkg/vm/stackitem"
 	"github.com/stretchr/testify/require"
+	"github.com/syndtr/goleveldb/leveldb/errors"
```
Comment (fyrchik) [inline pkg/core/state/notification_event_test.go:14]: Wrong import.

File: pkg/core/state/notification_event.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/core/state/notification_event.go]: Fixed, just bytes now.

File: pkg/rpc/client/policy.go [hunk 4]
```diff
@@ -33,8 +33,12 @@ func (c *Client) invokeNativePolicyMethod(operation string) (int64, error) {
...
 	if err != nil {
 		return 0, err
-	} else if result.State != "HALT" || len(result.Stack) == 0 {
-		return 0, errors.New("invalid VM state")
+	}
+	if result.State != "HALT" {
+		return 0, fmt.Errorf("invalid VM state: %s", result.FaultException)
+	}
+	if len(result.Stack) == 0 {
+		return 0, errors.New("result stack is sempty")
```
Comment (roman-khimov) [inline pkg/rpc/client/policy.go:41]: Maybe we need some
```
err := getInvocationError(*result.Invoke)
if err != nil {
    return err
}
```
To avoid this massive duplication?

**Review by roman-khimov — CHANGES_REQUESTED** [review]

File: pkg/rpc/client/rpc.go [hunk 5]
```diff
@@ -540,12 +540,17 @@ func (c *Client) AddNetworkFee(tx *transaction.Transaction, extraFee int64, accs
...
-					return core.ErrVerificationFailed
-				}
-			} else {
+			if res.State != "HALT" {
+				return fmt.Errorf("invalid VM state %s due to an error: %s", res.State, res.FaultException)
+			}
+			if l := len(res.Stack); l != 1 {
+				return fmt.Errorf("result stack length should be equal to 1, got %d", l)
+			}
+			if err != nil {
```
Comment (roman-khimov) [inline pkg/rpc/client/rpc.go:549]: This should be the first check then, it it's not `nil`, `res` might be `nil` easily and this code would fail earlier than expected.

**Review by roman-khimov — CHANGES_REQUESTED** [review]

**Review by roman-khimov — APPROVED** [review]
