### PR TITLE
rpcsrv: fix TestFailedPreconditionShutdown shutdown

### LINKED ISSUE #3217: Log in goroutine after `TestFailedPreconditionShutdown` has completed
Ubuntu, Go 1.21, v0.103.1 with a set of comments on top of it:
```
panic: Log in goroutine after TestFailedPreconditionShutdown has completed: 2023-11-22T14:00:08.975+0300	INFO	persisted to disk	{"blocks": 0, "keys": 127, "headerHeight": 0, "blockHeight": 0, "took": "47.595µs"}

goroutine 11944 [running]:
testing.(*common).logDepth(0xc017eec1a0, {0xc01ae48000, 0x88}, 0x3)
	/usr/local/go/src/testing/testing.go:1022 +0x4c5
testing.(*common).log(...)
	/usr/local/go/src/testing/testing.go:1004
testing.(*common).Logf(0xc017eec1a0, {0x109fc96?, 0x410505?}, {0xc01b8753f0?, 0xedecc0?, 0xc003c48301?})
	/usr/local/go/src/testing/testing.go:1055 +0x54
go.uber.org/zap/zaptest.testingWriter.Write({{0x7f0f8d4db120?, 0xc017eec1a0?}, 0x80?}, {0xc01aa5ac00?, 0x89, 0xc01b8753e0?})
	/home/anna/go/pkg/mod/go.uber.org/zap@v1.24.0/zaptest/logger.go:130 +0xdc
go.uber.org/zap/zapcore.(*ioCore).Write(0xc004422060, {0x0, {0xc14f95ae3a25ad68, 0xd6a11c4f2, 0x1b31620}, {0x0, 0x0}, {0x10ae318, 0x11}, {0x0, ...}, ...}, ...)
	/home/anna/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/core.go:99 +0xb5
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc010b5c270, {0xc00741c000, 0x5, 0x5})
	/home/anna/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:255 +0x1dc
go.uber.org/zap.(*Logger).Info(0x9e00dd4e257b9dc4?, {0x10ae318?, 0x1b31620?}, {0xc00741c000, 0x5, 0x5})
	/home/anna/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:220 +0x4e
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).persist(0xc0017f4580, 0x0)
	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/core/blockchain.go:2119 +0x4be
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).Run(0xc0017f4580)
	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/core/blockchain.go:1075 +0x1a8
created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.getUnitTestChainWithCustomConfig in goroutine 11942
	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/services/rpcsrv/server_helper_test.go:85 +0x5e7
FAIL	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv	57.638s

```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3217

### CODE REVIEW

**Comment by AliceInHunterland** [comment]
hm
```
2024-03-04T17:14:48.8779100Z === RUN   TestFilteredNotaryRequestSubscriptions
2024-03-04T17:14:48.8780280Z     logger.go:130: 2024-03-04T17:04:02.459Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-03-04T17:14:48.8781300Z     logger.go:130: 2024-03-04T17:04:02.459Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-03-04T17:14:48.8782570Z     logger.go:130: 2024-03-04T17:04:02.460Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-03-04T17:14:48.8783970Z     logger.go:130: 2024-03-04T17:04:02.460Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-03-04T17:14:48.8785270Z     logger.go:130: 2024-03-04T17:04:02.460Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2024-03-04T17:14:48.8786000Z     logger.go:130: 2024-03-04T17:04:02.474Z	INFO	no storage version found! creating genesis block
2024-03-04T17:14:48.8787100Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2024-03-04T17:14:48.8788150Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	SessionPoolSize is not set or wrong, setting default value	{"SessionPoolSize": 20}
2024-03-04T17:14:48.8789340Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2024-03-04T17:14:48.8790590Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-03-04T17:14:48.8791620Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2024-03-04T17:14:48.8792780Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
2024-03-04T17:14:48.8793980Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
2024-03-04T17:14:48.8795130Z     logger.go:130: 2024-03-04T17:04:02.482Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2024-03-04T17:14:48.8795840Z     logger.go:130: 2024-03-04T17:04:02.482Z	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
2024-03-04T17:14:48.8796600Z     logger.go:130: 2024-03-04T17:04:02.674Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2024-03-04T17:14:48.8797330Z     logger.go:130: 2024-03-04T17:04:02.674Z	INFO	node reached synchronized state, starting services
2024-03-04T17:14:48.8798370Z     logger.go:130: 2024-03-04T17:04:02.862Z	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "70.418493ms"}
2024-03-04T17:14:48.8799410Z     logger.go:130: 2024-03-04T17:04:02.965Z	DEBUG	done processing headers	{"headerIndex": 2, "blockHeight": 1, "took": "865.422µs"}
2024-03-04T17:14:48.8800440Z     logger.go:130: 2024-03-04T17:04:02.969Z	DEBUG	done processing headers	{"headerIndex": 3, "blockHeight": 2, "took": "943.987µs"}
2024-03-04T17:14:48.8801580Z     logger.go:130: 2024-03-04T17:04:02.972Z	DEBUG	done processing headers	{"headerIndex": 4, "blockHeight": 3, "took": "710.744µs"}
2024-03-04T17:14:48.8802630Z     logger.go:130: 2024-03-04T17:04:02.995Z	DEBUG	done processing headers	{"headerIndex": 5, "blockHeight": 4, "took": "703.643µs"}
2024-03-04T17:14:48.8804850Z     logger.go:130: 2024-03-04T17:04:02.997Z	INFO	bad notification	{"contract": "565cff9508ebc75aadd7fe59f38dac610ab6093c", "event": "Transfer", "error": "notification Transfer is invalid: parameter 0 type mismatch: Hash160 (manifest) vs ByteString (notification)"}
2024-03-04T17:14:48.8805880Z     logger.go:130: 2024-03-04T17:04:03.000Z	DEBUG	done processing headers	{"headerIndex": 6, "blockHeight": 5, "took": "1.162408ms"}
2024-03-04T17:14:48.8807020Z     logger.go:130: 2024-03-04T17:04:03.005Z	DEBUG	done processing headers	{"headerIndex": 7, "blockHeight": 6, "took": "1.648468ms"}
2024-03-04T17:14:48.8808060Z     logger.go:130: 2024-03-04T17:04:03.008Z	DEBUG	done processing headers	{"headerIndex": 8, "blockHeight": 7, "took": "714.789µs"}
2024-03-04T17:14:48.8809100Z     logger.go:130: 2024-03-04T17:04:03.010Z	DEBUG	done processing headers	{"headerIndex": 9, "blockHeight": 8, "took": "730.162µs"}
2024-03-04T17:14:48.8810130Z     logger.go:130: 2024-03-04T17:04:03.081Z	DEBUG	done processing headers	{"headerIndex": 10, "blockHeight": 9, "took": "942.499µs"}
2024-03-04T17:14:48.8811320Z     logger.go:130: 2024-03-04T17:04:03.086Z	DEBUG	done processing headers	{"headerIndex": 11, "blockHeight": 10, "took": "1.089595ms"}
2024-03-04T17:14:48.8812360Z     logger.go:130: 2024-03-04T17:04:03.358Z	DEBUG	done processing headers	{"headerIndex": 12, "blockHeight": 11, "took": "13.29073ms"}
2024-03-04T17:14:48.8813550Z     logger.go:130: 2024-03-04T17:04:03.530Z	INFO	persisted to disk	{"blocks": 11, "keys": 438, "headerHeight": 12, "blockHeight": 11, "took": "21.816995ms"}
2024-03-04T17:14:48.8814590Z     logger.go:130: 2024-03-04T17:04:03.556Z	DEBUG	done processing headers	{"headerIndex": 13, "blockHeight": 12, "took": "24.71533ms"}
2024-03-04T17:14:48.8815650Z     logger.go:130: 2024-03-04T17:04:03.650Z	DEBUG	done processing headers	{"headerIndex": 14, "blockHeight": 13, "took": "22.205158ms"}
2024-03-04T17:14:48.8816690Z     logger.go:130: 2024-03-04T17:04:03.780Z	DEBUG	done processing headers	{"headerIndex": 15, "blockHeight": 14, "took": "754.942µs"}
2024-03-04T17:14:48.8818400Z     logger.go:130: 2024-03-04T17:04:03.790Z	DEBUG	done processing headers	{"headerIndex": 16, "blockHeight": 15, "took": "1.087414ms"}
2024-03-04T17:14:48.8819890Z     logger.go:130: 2024-03-04T17:04:03.795Z	DEBUG	done processing headers	{"headerIndex": 17, "blockHeight": 16, "took": "645.864µs"}
2024-03-04T17:14:48.8821830Z     logger.go:130: 2024-03-04T17:04:03.801Z	DEBUG	done processing headers	{"headerIndex": 18, "blockHeight": 17, "took": "1.250881ms"}
2024-03-04T17:14:48.8822060Z     subscription_test.go:36: 
2024-03-04T17:14:48.8822910Z         	Error Trace:	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:36
2024-03-04T17:14:48.8823740Z         	            				/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/asm_amd64.s:1650
2024-03-04T17:14:48.8824030Z         	Error:      	Received unexpected error:
2024-03-04T17:14:48.8824650Z         	            	read tcp 127.0.0.1:51059->127.0.0.1:51058: i/o timeout
2024-03-04T17:14:48.8825020Z         	Test:       	TestFilteredNotaryRequestSubscriptions
2024-03-04T17:14:48.8826110Z     logger.go:130: 2024-03-04T17:04:03.920Z	DEBUG	done processing headers	{"headerIndex": 19, "blockHeight": 18, "took": "725.706µs"}
2024-03-04T17:14:48.8827150Z     logger.go:130: 2024-03-04T17:04:03.923Z	DEBUG	done processing headers	{"headerIndex": 20, "blockHeight": 19, "took": "755.266µs"}
2024-03-04T17:14:48.8828280Z     logger.go:130: 2024-03-04T17:04:03.926Z	DEBUG	done processing headers	{"headerIndex": 21, "blockHeight": 20, "took": "672.855µs"}
2024-03-04T17:14:48.8829440Z     logger.go:130: 2024-03-04T17:04:03.929Z	DEBUG	done processing headers	{"headerIndex": 22, "blockHeight": 21, "took": "686.697µs"}
2024-03-04T17:14:48.8830860Z     logger.go:130: 2024-03-04T17:04:03.967Z	DEBUG	done processing headers	{"headerIndex": 23, "blockHeight": 22, "took": "22.948823ms"}
2024-03-04T17:14:48.8832630Z     logger.go:130: 2024-03-04T17:04:03.968Z	WARN	contract invocation failed	{"tx": "82279bfe9bada282ca0f8cb8e0bb124b921af36f00c69a518320322c6f4fef60", "block": 23, "error": "at instruction 0 (ABORT): ABORT"}
2024-03-04T17:14:48.8833000Z === RUN   TestFilteredNotaryRequestSubscriptions/matching_signer
2024-03-04T17:14:48.8833260Z === NAME  TestFilteredNotaryRequestSubscriptions
2024-03-04T17:14:48.8834310Z     logger.go:130: 2024-03-04T17:04:03.994Z	DEBUG	processing rpc request	{"method": "subscribe", "params": "[notary_request_event ]"}
2024-03-04T17:14:48.8835670Z     logger.go:130: 2024-03-04T17:04:04.586Z	INFO	persisted to disk	{"blocks": 12, "keys": 867, "headerHeight": 23, "blockHeight": 23, "took": "847.439µs"}
2024-03-04T17:14:48.8835860Z panic: test timed out after 10m0s
2024-03-04T17:14:48.8836010Z running tests:
2024-03-04T17:14:48.8836290Z 	TestFilteredNotaryRequestSubscriptions (8m40s)
2024-03-04T17:14:48.8836670Z 	TestFilteredNotaryRequestSubscriptions/matching_signer (8m39s)
2024-03-04T17:14:48.8836690Z 
2024-03-04T17:14:48.8837010Z goroutine 13212 [running]:
2024-03-04T17:14:48.8837170Z testing.(*M).startAlarm.func1()
2024-03-04T17:14:48.8837680Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2259 +0x259
2024-03-04T17:14:48.8837830Z created by time.goFunc
2024-03-04T17:14:48.8838270Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/time/sleep.go:176 +0x45
2024-03-04T17:14:48.8838280Z 
2024-03-04T17:14:48.8838460Z goroutine 1 [chan receive, 8 minutes]:
2024-03-04T17:14:48.8838740Z testing.(*T).Run(0xc00020c680, {0x240fa27, 0x26}, 0x252b8d8)
2024-03-04T17:14:48.8839240Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1649 +0x871
2024-03-04T17:14:48.8839410Z testing.runTests.func1(0x0?)
2024-03-04T17:14:48.8839890Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2054 +0x85
2024-03-04T17:14:48.8840080Z testing.tRunner(0xc00020c680, 0xc0002adaf8)
2024-03-04T17:14:48.8840570Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1595 +0x262
2024-03-04T17:14:48.8841180Z testing.runTests(0xc00022c140?, {0x2fb0600, 0x31, 0x31}, {0x1c?, 0x1e?, 0x2fbc6c0?})
2024-03-04T17:14:48.8841660Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2052 +0x8ae
2024-03-04T17:14:48.8841820Z testing.(*M).Run(0xc00022c140)
2024-03-04T17:14:48.8842310Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1925 +0xcd8
2024-03-04T17:14:48.8842450Z main.main()
2024-03-04T17:14:48.8842610Z 	_testmain.go:145 +0x2be
2024-03-04T17:14:48.8842620Z 
2024-03-04T17:14:48.8842800Z goroutine 8092 [select, 9 minutes]:
2024-03-04T17:14:48.8843450Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleSubEvents(0xc016b5f680)
2024-03-04T17:14:48.8843980Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:2921 +0x86d
2024-03-04T17:14:48.8844660Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start in goroutine 8089
2024-03-04T17:14:48.8845160Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:391 +0xf4
2024-03-04T17:14:48.8845170Z 
2024-03-04T17:14:48.8845350Z goroutine 697 [IO wait, 9 minutes]:
2024-03-04T17:14:48.8845580Z internal/poll.runtime_pollWait(0x4d3ff880, 0x72)
2024-03-04T17:14:48.8846070Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/netpoll.go:343 +0x85
2024-03-04T17:14:48.8846390Z internal/poll.(*pollDesc).wait(0xc0018487a0, 0xc000ef5000?, 0x0)
2024-03-04T17:14:48.8846990Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-04T17:14:48.8847180Z internal/poll.(*pollDesc).waitRead(...)
2024-03-04T17:14:48.8847720Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:89
2024-03-04T17:14:48.8848090Z internal/poll.(*FD).Read(0xc001848780, {0xc000ef5000, 0x1000, 0x1000})
2024-03-04T17:14:48.8848760Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_unix.go:164 +0x405
2024-03-04T17:14:48.8849080Z net.(*netFD).Read(0xc001848780, {0xc000ef5000, 0x1000, 0x1000})
2024-03-04T17:14:48.8849530Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/fd_posix.go:55 +0x4b
2024-03-04T17:14:48.8849890Z net.(*conn).Read(0xc00014ca68, {0xc000ef5000, 0x1000, 0x1000})
2024-03-04T17:14:48.8850370Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/net.go:179 +0xad
2024-03-04T17:14:48.8850750Z net/http.(*connReader).Read(0xc001850120, {0xc000ef5000, 0x1000, 0x1000})
2024-03-04T17:14:48.8851240Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:791 +0x2b2
2024-03-04T17:14:48.8851400Z bufio.(*Reader).fill(0xc001852300)
2024-03-04T17:14:48.8852020Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/bufio/bufio.go:113 +0x29a
2024-03-04T17:14:48.8852210Z bufio.(*Reader).Peek(0xc001852300, 0x4)
2024-03-04T17:14:48.8852670Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/bufio/bufio.go:151 +0xc7
2024-03-04T17:14:48.8852980Z net/http.(*conn).serve(0xc00047eea0, {0x27096f0, 0xc000eb53e0})
2024-03-04T17:14:48.8853470Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:2044 +0xe7c
2024-03-04T17:14:48.8853860Z created by net/http.(*Server).Serve in goroutine 613
2024-03-04T17:14:48.8854350Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:3086 +0x86d
2024-03-04T17:14:48.8854350Z 
2024-03-04T17:14:48.8854540Z goroutine 393 [IO wait, 9 minutes]:
2024-03-04T17:14:48.8854770Z internal/poll.runtime_pollWait(0x4d3ffe50, 0x72)
2024-03-04T17:14:48.8855250Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/netpoll.go:343 +0x85
2024-03-04T17:14:48.8855580Z internal/poll.(*pollDesc).wait(0xc000f1d8a0, 0xc0016f2000?, 0x0)
2024-03-04T17:14:48.8856170Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-04T17:14:48.8856360Z internal/poll.(*pollDesc).waitRead(...)
2024-03-04T17:14:48.8856890Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:89
2024-03-04T17:14:48.8857250Z internal/poll.(*FD).Read(0xc000f1d880, {0xc0016f2000, 0x1000, 0x1000})
2024-03-04T17:14:48.8857780Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_unix.go:164 +0x405
2024-03-04T17:14:48.8858180Z net.(*netFD).Read(0xc000f1d880, {0xc0016f2000, 0x1000, 0x1000})
2024-03-04T17:14:48.8858620Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/fd_posix.go:55 +0x4b
2024-03-04T17:14:48.8858910Z net.(*conn).Read(0xc00014c2a0, {0xc0016f2000, 0x1000, 0x1000})
2024-03-04T17:14:48.8859310Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/net.go:179 +0xad
2024-03-04T17:14:48.8859690Z net/http.(*connReader).Read(0xc0016e4a20, {0xc0016f2000, 0x1000, 0x1000})
2024-03-04T17:14:48.8860170Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:791 +0x2b2
2024-03-04T17:14:48.8860330Z bufio.(*Reader).fill(0xc00169dda0)
2024-03-04T17:14:48.8860780Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/bufio/bufio.go:113 +0x29a
2024-03-04T17:14:48.8860960Z bufio.(*Reader).Peek(0xc00169dda0, 0x4)
2024-03-04T17:14:48.8861390Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/bufio/bufio.go:151 +0xc7
2024-03-04T17:14:48.8861700Z net/http.(*conn).serve(0xc000d38e10, {0x27096f0, 0xc0003840c0})
2024-03-04T17:14:48.8862180Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:2044 +0xe7c
2024-03-04T17:14:48.8862450Z created by net/http.(*Server).Serve in goroutine 274
2024-03-04T17:14:48.8862930Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:3086 +0x86d
2024-03-04T17:14:48.8862940Z 
2024-03-04T17:14:48.8863110Z goroutine 613 [IO wait, 9 minutes]:
2024-03-04T17:14:48.8863340Z internal/poll.runtime_pollWait(0x4d3ffa70, 0x72)
2024-03-04T17:14:48.8863820Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/netpoll.go:343 +0x85
2024-03-04T17:14:48.8864130Z internal/poll.(*pollDesc).wait(0xc000e809a0, 0x10c9d01?, 0x0)
2024-03-04T17:14:48.8864820Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-04T17:14:48.8865020Z internal/poll.(*pollDesc).waitRead(...)
2024-03-04T17:14:48.8865560Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:89
2024-03-04T17:14:48.8865750Z internal/poll.(*FD).Accept(0xc000e80980)
2024-03-04T17:14:48.8866280Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_unix.go:611 +0x425
2024-03-04T17:14:48.8866440Z net.(*netFD).accept(0xc000e80980)
2024-03-04T17:14:48.8866870Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/fd_unix.go:172 +0x3e
2024-03-04T17:14:48.8867050Z net.(*TCPListener).accept(0xc001fce9c0)
2024-03-04T17:14:48.8867540Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/tcpsock_posix.go:152 +0x3e
2024-03-04T17:14:48.8867810Z net.(*TCPListener).Accept(0xc001fce9c0)
2024-03-04T17:14:48.8868260Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/tcpsock.go:315 +0x65
2024-03-04T17:14:48.8868580Z net/http.(*Server).Serve(0xc000dcc1e0, {0x27072b0, 0xc001fce9c0})
2024-03-04T17:14:48.8869070Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:3056 +0x5e8
2024-03-04T17:14:48.8869280Z net/http/httptest.(*Server).goServe.func1()
2024-03-04T17:14:48.8869820Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/httptest/server.go:310 +0xd0
2024-03-04T17:14:48.8870280Z created by net/http/httptest.(*Server).goServe in goroutine 592
2024-03-04T17:14:48.8870820Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/httptest/server.go:308 +0xa6
2024-03-04T17:14:48.8870830Z 
2024-03-04T17:14:48.8871010Z goroutine 133 [IO wait, 9 minutes]:
2024-03-04T17:14:48.8871230Z internal/poll.runtime_pollWait(0x4d400328, 0x72)
2024-03-04T17:14:48.8871710Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/netpoll.go:343 +0x85
2024-03-04T17:14:48.8872050Z internal/poll.(*pollDesc).wait(0xc0001a4420, 0xc000081a01?, 0x0)
2024-03-04T17:14:48.8872630Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-04T17:14:48.8872830Z internal/poll.(*pollDesc).waitRead(...)
2024-03-04T17:14:48.8873360Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:89
2024-03-04T17:14:48.8873560Z internal/poll.(*FD).Accept(0xc0001a4400)
2024-03-04T17:14:48.8874180Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_unix.go:611 +0x425
2024-03-04T17:14:48.8874350Z net.(*netFD).accept(0xc0001a4400)
2024-03-04T17:14:48.8874780Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/fd_unix.go:172 +0x3e
2024-03-04T17:14:48.8874960Z net.(*TCPListener).accept(0xc00018f480)
2024-03-04T17:14:48.8875450Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/tcpsock_posix.go:152 +0x3e
2024-03-04T17:14:48.8875630Z net.(*TCPListener).Accept(0xc00018f480)
2024-03-04T17:14:48.8876070Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/tcpsock.go:315 +0x65
2024-03-04T17:14:48.8876390Z net/http.(*Server).Serve(0xc0000ac0f0, {0x27072b0, 0xc00018f480})
2024-03-04T17:14:48.8876880Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:3056 +0x5e8
2024-03-04T17:14:48.8877090Z net/http/httptest.(*Server).goServe.func1()
2024-03-04T17:14:48.8877640Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/httptest/server.go:310 +0xd0
2024-03-04T17:14:48.8878000Z created by net/http/httptest.(*Server).goServe in goroutine 101
2024-03-04T17:14:48.8878540Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/httptest/server.go:308 +0xa6
2024-03-04T17:14:48.8878550Z 
2024-03-04T17:14:48.8878730Z goroutine 11213 [select, 8 minutes]:
2024-03-04T17:14:48.8879450Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleSubEvents(0xc004991180)
2024-03-04T17:14:48.8879980Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:2921 +0x86d
2024-03-04T17:14:48.8880670Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start in goroutine 11210
2024-03-04T17:14:48.8881180Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:391 +0xf4
2024-03-04T17:14:48.8881190Z hm
2024-03-04T17:14:48.8779100Z === RUN   TestFilteredNotaryRequestSubscriptions
2024-03-04T17:14:48.8780280Z     logger.go:130: 2024-03-04T17:04:02.459Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-03-04T17:14:48.8781300Z     logger.go:130: 2024-03-04T17:04:02.459Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-03-04T17:14:48.8782570Z     logger.go:130: 2024-03-04T17:04:02.460Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-03-04T17:14:48.8783970Z     logger.go:130: 2024-03-04T17:04:02.460Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-03-04T17:14:48.8785270Z     logger.go:130: 2024-03-04T17:04:02.460Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2024-03-04T17:14:48.8786000Z     logger.go:130: 2024-03-04T17:04:02.474Z	INFO	no storage version found! creating genesis block
2024-03-04T17:14:48.8787100Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2024-03-04T17:14:48.8788150Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	SessionPoolSize is not set or wrong, setting default value	{"SessionPoolSize": 20}
2024-03-04T17:14:48.8789340Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2024-03-04T17:14:48.8790590Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-03-04T17:14:48.8791620Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2024-03-04T17:14:48.8792780Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
2024-03-04T17:14:48.8793980Z     logger.go:130: 2024-03-04T17:04:02.481Z	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
2024-03-04T17:14:48.8795130Z     logger.go:130: 2024-03-04T17:04:02.482Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2024-03-04T17:14:48.8795840Z     logger.go:130: 2024-03-04T17:04:02.482Z	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
2024-03-04T17:14:48.8796600Z     logger.go:130: 2024-03-04T17:04:02.674Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2024-03-04T17:14:48.8797330Z     logger.go:130: 2024-03-04T17:04:02.674Z	INFO	node reached synchronized state, starting services
2024-03-04T17:14:48.8798370Z     logger.go:130: 2024-03-04T17:04:02.862Z	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "70.418493ms"}
2024-03-04T17:14:48.8799410Z     logger.go:130: 2024-03-04T17:04:02.965Z	DEBUG	done processing headers	{"headerIndex": 2, "blockHeight": 1, "took": "865.422µs"}
2024-03-04T17:14:48.8800440Z     logger.go:130: 2024-03-04T17:04:02.969Z	DEBUG	done processing headers	{"headerIndex": 3, "blockHeight": 2, "took": "943.987µs"}
2024-03-04T17:14:48.8801580Z     logger.go:130: 2024-03-04T17:04:02.972Z	DEBUG	done processing headers	{"headerIndex": 4, "blockHeight": 3, "took": "710.744µs"}
2024-03-04T17:14:48.8802630Z     logger.go:130: 2024-03-04T17:04:02.995Z	DEBUG	done processing headers	{"headerIndex": 5, "blockHeight": 4, "took": "703.643µs"}
2024-03-04T17:14:48.8804850Z     logger.go:130: 2024-03-04T17:04:02.997Z	INFO	bad notification	{"contract": "565cff9508ebc75aadd7fe59f38dac610ab6093c", "event": "Transfer", "error": "notification Transfer is invalid: parameter 0 type mismatch: Hash160 (manifest) vs ByteString (notification)"}
2024-03-04T17:14:48.8805880Z     logger.go:130: 2024-03-04T17:04:03.000Z	DEBUG	done processing headers	{"headerIndex": 6, "blockHeight": 5, "took": "1.162408ms"}
2024-03-04T17:14:48.8807020Z     logger.go:130: 2024-03-04T17:04:03.005Z	DEBUG	done processing headers	{"headerIndex": 7, "blockHeight": 6, "took": "1.648468ms"}
2024-03-04T17:14:48.8808060Z     logger.go:130: 2024-03-04T17:04:03.008Z	DEBUG	done processing headers	{"headerIndex": 8, "blockHeight": 7, "took": "714.789µs"}
2024-03-04T17:14:48.8809100Z     logger.go:130: 2024-03-04T17:04:03.010Z	DEBUG	done processing headers	{"headerIndex": 9, "blockHeight": 8, "took": "730.162µs"}
2024-03-04T17:14:48.8810130Z     logger.go:130: 2024-03-04T17:04:03.081Z	DEBUG	done processing headers	{"headerIndex": 10, "blockHeight": 9, "took": "942.499µs"}
2024-03-04T17:14:48.8811320Z     logger.go:130: 2024-03-04T17:04:03.086Z	DEBUG	done processing headers	{"headerIndex": 11, "blockHeight": 10, "took": "1.089595ms"}
2024-03-04T17:14:48.8812360Z     logger.go:130: 2024-03-04T17:04:03.358Z	DEBUG	done processing headers	{"headerIndex": 12, "blockHeight": 11, "took": "13.29073ms"}
2024-03-04T17:14:48.8813550Z     logger.go:130: 2024-03-04T17:04:03.530Z	INFO	persisted to disk	{"blocks": 11, "keys": 438, "headerHeight": 12, "blockHeight": 11, "took": "21.816995ms"}
2024-03-04T17:14:48.8814590Z     logger.go:130: 2024-03-04T17:04:03.556Z	DEBUG	done processing headers	{"headerIndex": 13, "blockHeight": 12, "took": "24.71533ms"}
2024-03-04T17:14:48.8815650Z     logger.go:130: 2024-03-04T17:04:03.650Z	DEBUG	done processing headers	{"headerIndex": 14, "blockHeight": 13, "took": "22.205158ms"}
2024-03-04T17:14:48.8816690Z     logger.go:130: 2024-03-04T17:04:03.780Z	DEBUG	done processing headers	{"headerIndex": 15, "blockHeight": 14, "took": "754.942µs"}
2024-03-04T17:14:48.8818400Z     logger.go:130: 2024-03-04T17:04:03.790Z	DEBUG	done processing headers	{"headerIndex": 16, "blockHeight": 15, "took": "1.087414ms"}
2024-03-04T17:14:48.8819890Z     logger.go:130: 2024-03-04T17:04:03.795Z	DEBUG	done processing headers	{"headerIndex": 17, "blockHeight": 16, "took": "645.864µs"}
2024-03-04T17:14:48.8821830Z     logger.go:130: 2024-03-04T17:04:03.801Z	DEBUG	done processing headers	{"headerIndex": 18, "blockHeight": 17, "took": "1.250881ms"}
2024-03-04T17:14:48.8822060Z     subscription_test.go:36: 
2024-03-04T17:14:48.8822910Z         	Error Trace:	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:36
2024-03-04T17:14:48.8823740Z         	            				/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/asm_amd64.s:1650
2024-03-04T17:14:48.8824030Z         	Error:      	Received unexpected error:
2024-03-04T17:14:48.8824650Z         	            	read tcp 127.0.0.1:51059->127.0.0.1:51058: i/o timeout
2024-03-04T17:14:48.8825020Z         	Test:       	TestFilteredNotaryRequestSubscriptions
2024-03-04T17:14:48.8826110Z     logger.go:130: 2024-03-04T17:04:03.920Z	DEBUG	done processing headers	{"headerIndex": 19, "blockHeight": 18, "took": "725.706µs"}
2024-03-04T17:14:48.8827150Z     logger.go:130: 2024-03-04T17:04:03.923Z	DEBUG	done processing headers	{"headerIndex": 20, "blockHeight": 19, "took": "755.266µs"}
2024-03-04T17:14:48.8828280Z     logger.go:130: 2024-03-04T17:04:03.926Z	DEBUG	done processing headers	{"headerIndex": 21, "blockHeight": 20, "took": "672.855µs"}
2024-03-04T17:14:48.8829440Z     logger.go:130: 2024-03-04T17:04:03.929Z	DEBUG	done processing headers	{"headerIndex": 22, "blockHeight": 21, "took": "686.697µs"}
2024-03-04T17:14:48.8830860Z     logger.go:130: 2024-03-04T17:04:03.967Z	DEBUG	done processing headers	{"headerIndex": 23, "blockHeight": 22, "took": "22.948823ms"}
2024-03-04T17:14:48.8832630Z     logger.go:130: 2024-03-04T17:04:03.968Z	WARN	contract invocation failed	{"tx": "82279bfe9bada282ca0f8cb8e0bb124b921af36f00c69a518320322c6f4fef60", "block": 23, "error": "at instruction 0 (ABORT): ABORT"}
2024-03-04T17:14:48.8833000Z === RUN   TestFilteredNotaryRequestSubscriptions/matching_signer
2024-03-04T17:14:48.8833260Z === NAME  TestFilteredNotaryRequestSubscriptions
2024-03-04T17:14:48.8834310Z     logger.go:130: 2024-03-04T17:04:03.994Z	DEBUG	processing rpc request	{"method": "subscribe", "params": "[notary_request_event ]"}
2024-03-04T17:14:48.8835670Z     logger.go:130: 2024-03-04T17:04:04.586Z	INFO	persisted to disk	{"blocks": 12, "keys": 867, "headerHeight": 23, "blockHeight": 23, "took": "847.439µs"}
2024-03-04T17:14:48.8835860Z panic: test timed out after 10m0s
2024-03-04T17:14:48.8836010Z running tests:
2024-03-04T17:14:48.8836290Z 	TestFilteredNotaryRequestSubscriptions (8m40s)
2024-03-04T17:14:48.8836670Z 	TestFilteredNotaryRequestSubscriptions/matching_signer (8m39s)
2024-03-04T17:14:48.8836690Z 
2024-03-04T17:14:48.8837010Z goroutine 13212 [running]:
2024-03-04T17:14:48.8837170Z testing.(*M).startAlarm.func1()
2024-03-04T17:14:48.8837680Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2259 +0x259
2024-03-04T17:14:48.8837830Z created by time.goFunc
2024-03-04T17:14:48.8838270Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/time/sleep.go:176 +0x45
2024-03-04T17:14:48.8838280Z 
2024-03-04T17:14:48.8838460Z goroutine 1 [chan receive, 8 minutes]:
2024-03-04T17:14:48.8838740Z testing.(*T).Run(0xc00020c680, {0x240fa27, 0x26}, 0x252b8d8)
2024-03-04T17:14:48.8839240Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1649 +0x871
2024-03-04T17:14:48.8839410Z testing.runTests.func1(0x0?)
2024-03-04T17:14:48.8839890Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2054 +0x85
2024-03-04T17:14:48.8840080Z testing.tRunner(0xc00020c680, 0xc0002adaf8)
2024-03-04T17:14:48.8840570Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1595 +0x262
2024-03-04T17:14:48.8841180Z testing.runTests(0xc00022c140?, {0x2fb0600, 0x31, 0x31}, {0x1c?, 0x1e?, 0x2fbc6c0?})
2024-03-04T17:14:48.8841660Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2052 +0x8ae
2024-03-04T17:14:48.8841820Z testing.(*M).Run(0xc00022c140)
2024-03-04T17:14:48.8842310Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1925 +0xcd8
2024-03-04T17:14:48.8842450Z main.main()
2024-03-04T17:14:48.8842610Z 	_testmain.go:145 +0x2be
2024-03-04T17:14:48.8842620Z 
2024-03-04T17:14:48.8842800Z goroutine 8092 [select, 9 minutes]:
2024-03-04T17:14:48.8843450Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleSubEvents(0xc016b5f680)
2024-03-04T17:14:48.8843980Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:2921 +0x86d
2024-03-04T17:14:48.8844660Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start in goroutine 8089
2024-03-04T17:14:48.8845160Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:391 +0xf4
2024-03-04T17:14:48.8845170Z 
2024-03-04T17:14:48.8845350Z goroutine 697 [IO wait, 9 minutes]:
2024-03-04T17:14:48.8845580Z internal/poll.runtime_pollWait(0x4d3ff880, 0x72)
2024-03-04T17:14:48.8846070Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/netpoll.go:343 +0x85
2024-03-04T17:14:48.8846390Z internal/poll.(*pollDesc).wait(0xc0018487a0, 0xc000ef5000?, 0x0)
2024-03-04T17:14:48.8846990Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-04T17:14:48.8847180Z internal/poll.(*pollDesc).waitRead(...)
2024-03-04T17:14:48.8847720Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:89
2024-03-04T17:14:48.8848090Z internal/poll.(*FD).Read(0xc001848780, {0xc000ef5000, 0x1000, 0x1000})
2024-03-04T17:14:48.8848760Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_unix.go:164 +0x405
2024-03-04T17:14:48.8849080Z net.(*netFD).Read(0xc001848780, {0xc000ef5000, 0x1000, 0x1000})
2024-03-04T17:14:48.8849530Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/fd_posix.go:55 +0x4b
2024-03-04T17:14:48.8849890Z net.(*conn).Read(0xc00014ca68, {0xc000ef5000, 0x1000, 0x1000})
2024-03-04T17:14:48.8850370Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/net.go:179 +0xad
2024-03-04T17:14:48.8850750Z net/http.(*connReader).Read(0xc001850120, {0xc000ef5000, 0x1000, 0x1000})
2024-03-04T17:14:48.8851240Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:791 +0x2b2
2024-03-04T17:14:48.8851400Z bufio.(*Reader).fill(0xc001852300)
2024-03-04T17:14:48.8852020Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/bufio/bufio.go:113 +0x29a
2024-03-04T17:14:48.8852210Z bufio.(*Reader).Peek(0xc001852300, 0x4)
2024-03-04T17:14:48.8852670Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/bufio/bufio.go:151 +0xc7
2024-03-04T17:14:48.8852980Z net/http.(*conn).serve(0xc00047eea0, {0x27096f0, 0xc000eb53e0})
2024-03-04T17:14:48.8853470Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:2044 +0xe7c
2024-03-04T17:14:48.8853860Z created by net/http.(*Server).Serve in goroutine 613
2024-03-04T17:14:48.8854350Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:3086 +0x86d
2024-03-04T17:14:48.8854350Z 
2024-03-04T17:14:48.8854540Z goroutine 393 [IO wait, 9 minutes]:
2024-03-04T17:14:48.8854770Z internal/poll.runtime_pollWait(0x4d3ffe50, 0x72)
2024-03-04T17:14:48.8855250Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/netpoll.go:343 +0x85
2024-03-04T17:14:48.8855580Z internal/poll.(*pollDesc).wait(0xc000f1d8a0, 0xc0016f2000?, 0x0)
2024-03-04T17:14:48.8856170Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-04T17:14:48.8856360Z internal/poll.(*pollDesc).waitRead(...)
2024-03-04T17:14:48.8856890Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:89
2024-03-04T17:14:48.8857250Z internal/poll.(*FD).Read(0xc000f1d880, {0xc0016f2000, 0x1000, 0x1000})
2024-03-04T17:14:48.8857780Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_unix.go:164 +0x405
2024-03-04T17:14:48.8858180Z net.(*netFD).Read(0xc000f1d880, {0xc0016f2000, 0x1000, 0x1000})
2024-03-04T17:14:48.8858620Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/fd_posix.go:55 +0x4b
2024-03-04T17:14:48.8858910Z net.(*conn).Read(0xc00014c2a0, {0xc0016f2000, 0x1000, 0x1000})
2024-03-04T17:14:48.8859310Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/net.go:179 +0xad
2024-03-04T17:14:48.8859690Z net/http.(*connReader).Read(0xc0016e4a20, {0xc0016f2000, 0x1000, 0x1000})
2024-03-04T17:14:48.8860170Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:791 +0x2b2
2024-03-04T17:14:48.8860330Z bufio.(*Reader).fill(0xc00169dda0)
2024-03-04T17:14:48.8860780Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/bufio/bufio.go:113 +0x29a
2024-03-04T17:14:48.8860960Z bufio.(*Reader).Peek(0xc00169dda0, 0x4)
2024-03-04T17:14:48.8861390Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/bufio/bufio.go:151 +0xc7
2024-03-04T17:14:48.8861700Z net/http.(*conn).serve(0xc000d38e10, {0x27096f0, 0xc0003840c0})
2024-03-04T17:14:48.8862180Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:2044 +0xe7c
2024-03-04T17:14:48.8862450Z created by net/http.(*Server).Serve in goroutine 274
2024-03-04T17:14:48.8862930Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:3086 +0x86d
2024-03-04T17:14:48.8862940Z 
2024-03-04T17:14:48.8863110Z goroutine 613 [IO wait, 9 minutes]:
2024-03-04T17:14:48.8863340Z internal/poll.runtime_pollWait(0x4d3ffa70, 0x72)
2024-03-04T17:14:48.8863820Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/netpoll.go:343 +0x85
2024-03-04T17:14:48.8864130Z internal/poll.(*pollDesc).wait(0xc000e809a0, 0x10c9d01?, 0x0)
2024-03-04T17:14:48.8864820Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-04T17:14:48.8865020Z internal/poll.(*pollDesc).waitRead(...)
2024-03-04T17:14:48.8865560Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:89
2024-03-04T17:14:48.8865750Z internal/poll.(*FD).Accept(0xc000e80980)
2024-03-04T17:14:48.8866280Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_unix.go:611 +0x425
2024-03-04T17:14:48.8866440Z net.(*netFD).accept(0xc000e80980)
2024-03-04T17:14:48.8866870Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/fd_unix.go:172 +0x3e
2024-03-04T17:14:48.8867050Z net.(*TCPListener).accept(0xc001fce9c0)
2024-03-04T17:14:48.8867540Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/tcpsock_posix.go:152 +0x3e
2024-03-04T17:14:48.8867810Z net.(*TCPListener).Accept(0xc001fce9c0)
2024-03-04T17:14:48.8868260Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/tcpsock.go:315 +0x65
2024-03-04T17:14:48.8868580Z net/http.(*Server).Serve(0xc000dcc1e0, {0x27072b0, 0xc001fce9c0})
2024-03-04T17:14:48.8869070Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:3056 +0x5e8
2024-03-04T17:14:48.8869280Z net/http/httptest.(*Server).goServe.func1()
2024-03-04T17:14:48.8869820Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/httptest/server.go:310 +0xd0
2024-03-04T17:14:48.8870280Z created by net/http/httptest.(*Server).goServe in goroutine 592
2024-03-04T17:14:48.8870820Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/httptest/server.go:308 +0xa6
2024-03-04T17:14:48.8870830Z 
2024-03-04T17:14:48.8871010Z goroutine 133 [IO wait, 9 minutes]:
2024-03-04T17:14:48.8871230Z internal/poll.runtime_pollWait(0x4d400328, 0x72)
2024-03-04T17:14:48.8871710Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/runtime/netpoll.go:343 +0x85
2024-03-04T17:14:48.8872050Z internal/poll.(*pollDesc).wait(0xc0001a4420, 0xc000081a01?, 0x0)
2024-03-04T17:14:48.8872630Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-04T17:14:48.8872830Z internal/poll.(*pollDesc).waitRead(...)
2024-03-04T17:14:48.8873360Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_poll_runtime.go:89
2024-03-04T17:14:48.8873560Z internal/poll.(*FD).Accept(0xc0001a4400)
2024-03-04T17:14:48.8874180Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/internal/poll/fd_unix.go:611 +0x425
2024-03-04T17:14:48.8874350Z net.(*netFD).accept(0xc0001a4400)
2024-03-04T17:14:48.8874780Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/fd_unix.go:172 +0x3e
2024-03-04T17:14:48.8874960Z net.(*TCPListener).accept(0xc00018f480)
2024-03-04T17:14:48.8875450Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/tcpsock_posix.go:152 +0x3e
2024-03-04T17:14:48.8875630Z net.(*TCPListener).Accept(0xc00018f480)
2024-03-04T17:14:48.8876070Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/tcpsock.go:315 +0x65
2024-03-04T17:14:48.8876390Z net/http.(*Server).Serve(0xc0000ac0f0, {0x27072b0, 0xc00018f480})
2024-03-04T17:14:48.8876880Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/server.go:3056 +0x5e8
2024-03-04T17:14:48.8877090Z net/http/httptest.(*Server).goServe.func1()
2024-03-04T17:14:48.8877640Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/httptest/server.go:310 +0xd0
2024-03-04T17:14:48.8878000Z created by net/http/httptest.(*Server).goServe in goroutine 101
2024-03-04T17:14:48.8878540Z 	/Users/runner/hostedtoolcache/go/1.21.7/x64/src/net/http/httptest/server.go:308 +0xa6
2024-03-04T17:14:48.8878550Z 
2024-03-04T17:14:48.8878730Z goroutine 11213 [select, 8 minutes]:
2024-03-04T17:14:48.8879450Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleSubEvents(0xc004991180)
2024-03-04T17:14:48.8879980Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:2921 +0x86d
2024-03-04T17:14:48.8880670Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start in goroutine 11210
2024-03-04T17:14:48.8881180Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:391 +0xf4
2024-03-04T17:14:48.8881190Z 
```

File: pkg/core/blockchain.go [hunk 1]
```diff
@@ -2113,6 +2115,8 @@ func (bc *Blockchain) persist(isSync bool) (time.Duration, error) {
 		persisted int
 		err       error
 	)
+	bc.wgPersist.Add(1)
+	defer bc.wgPersist.Done()
```
Comment (AnnaShaleva) [inline pkg/core/blockchain.go:2119]: As we see from the panic message, it's `persist` who is responsible for logging after test shutdown:
```
go.uber.org/zap.(*Logger).Info(0x9e00dd4e257b9dc4?, {0x10ae318?, 0x1b31620?}, {0xc00741c000, 0x5, 0x5})
	/home/anna/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:220 +0x4e
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).persist(0xc0017f4580, 0x0)
	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/core/blockchain.go:2119 +0x4be
```
Checking out to the appropriate commit allows us to detect the "faulty" lines:
```
		bc.log.Info("persisted to disk",
			zap.Uint32("blocks", diff),
			zap.Int("keys", persisted),
			zap.Uint32("headerHeight", storedHeaderHeight),
			zap.Uint32("blockHeight", bHeight),
			zap.Duration("took", duration))
```

Navigate to the persist caller, it's `(bc *Blockchain) Run()`. As we've discussed, the first thing we need to check is whether `(bc *Blockchain) Close()` waits for `Run()` to exit properly. Turns out that it waits with the help of `runToExitCh`:
```
		bc.isRunning.Store(false)
		close(bc.runToExitCh)
```
And thus, you don't need this syncing code.

After that, you have to check whether blockchain is properly closed in `TestFailedPreconditionShutdown`. Turns out that it's not:
https://github.com/nspcc-dev/neo-go/blob/8d67f17943553740fe4caa31c3e9efcf7921aba2/pkg/services/rpcsrv/server_test.go#L4138-L4141

Blockchain variable is not even named. So what you really need in this test is to properly close blockchain in the end of the test, that's all.

**Review by AnnaShaleva — CHANGES_REQUESTED** [review]

File: pkg/services/rpcsrv/server_test.go [hunk 2]
```diff
@@ -4135,10 +4139,10 @@ func BenchmarkHandleIn(b *testing.B) {
 }
 
 func TestFailedPreconditionShutdown(t *testing.T) {
-	_, srv, _ := initClearServerWithCustomConfig(t, func(c *config.Config) {
+	chain, srv, _ := initClearServerWithCustomConfig(t, func(c *config.Config) {
 		c.ApplicationConfiguration.RPC.Addresses = []string{"not an address"}
 	})
-
+	defer chain.Close()
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_test.go:4145]: Good, this should solve the problem. But while we're here I see that the common pattern of `initClearServerWithCustomConfig` usage is to always shutdown both chain and server. And thus, we need to do the following:
1. Move chain and RPC server shutdown to a `t.Cleanup` functions. Move these cleanups to the place where chain and RPC server are started respectively.
2. Remove all deferred chain/RPC server shutdown from the callers of `initClearServerWithCustomConfig` and related methods.
3. In a separate commit always close http server as far (if it was started). This should be done in a separate `t.Cleanup`. And BTW, this is likely the source of problems with leaking fds in tests and network-related tests timeouts like https://github.com/nspcc-dev/neo-go/issues/3300.
4. Review all failing tests from our list that may be closed by 3. Link them with commit from 3.

File: pkg/services/rpcsrv/server_helper_test.go [hunk 3]
```diff
@@ -83,6 +83,11 @@ func getUnitTestChainWithCustomConfig(t testing.TB, enableOracle bool, enableNot
 	}
 
 	go chain.Run()
+	t.Cleanup(
+		func() {
+			chain.Close()
+			logger.Sync()
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_helper_test.go:89]: Don't need it here, `chain.Close()` already contains it.

File: pkg/services/rpcsrv/server_helper_test.go [hunk 4]
```diff
@@ -125,6 +130,11 @@ func wrapUnitTestChain(t testing.TB, chain *core.Blockchain, orc OracleHandler,
 	errCh := make(chan error, 2)
 	rpcServer := New(chain, cfg.ApplicationConfiguration.RPC, server, orc, logger, errCh)
 	rpcServer.Start()
+	t.Cleanup(func() {
+		rpcServer.Shutdown()
+		server.Shutdown()
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_helper_test.go:135]: Move `server.Shutdown()` to a separate commit, it fixes a separate issue.

Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server_helper_test.go:135]: Link related issue to this commit.

**Review by AnnaShaleva — COMMENTED** [review]
Tests are failing, need to remove the following code from TestErrorResponseContentType:
```
	defer chain.Close()
	defer rpcSrv.Shutdown()
```

File: pkg/services/rpcsrv/server_helper_test.go (hunk 4 above)
Comment (AliceInHunterland) [reply pkg/services/rpcsrv/server_helper_test.go:135]: Shouldnt we add shutdown of the srv:= httptest.NewServer(handler), to a separate commit? but not  server, err := network.NewServer(serverConfig, chain, chain.GetStateSyncModule(), logger), because the function doesn't return?

Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server_helper_test.go:134]: Sure, my bad. It should be http server those shutdown should be in a separate commit.

File: pkg/services/rpcsrv/server_test.go (hunk 2 above)
Comment (AliceInHunterland) [reply pkg/services/rpcsrv/server_test.go]: about 3 - waiting for tests, but locally it doesn't help

File: pkg/services/rpcsrv/server_helper_test.go [hunk 5]
```diff
@@ -136,6 +136,9 @@ func wrapUnitTestChain(t testing.TB, chain *core.Blockchain, orc OracleHandler,
 
 	handler := http.HandlerFunc(rpcServer.handleHTTPRequest)
 	srv := httptest.NewServer(handler)
+	t.Cleanup(func() {
+		srv.Close()
+	})
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_helper_test.go:141]: Just `t.Cleunup(srv.Close)`.

File: pkg/services/rpcsrv/server_helper_test.go [hunk 6]
```diff
@@ -83,6 +83,10 @@ func getUnitTestChainWithCustomConfig(t testing.TB, enableOracle bool, enableNot
 	}
 
 	go chain.Run()
+	t.Cleanup(
+		func() {
+			chain.Close()
+		})
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_helper_test.go:89]: Just `t.Cleanup(chain.Close)`.

File: pkg/services/rpcsrv/server_test.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server_test.go]: If it doesn't then remove the linked issue and adjust the comment. But we need this commit.

File: pkg/services/rpcsrv/server_helper_test.go [hunk 7]
```diff
@@ -136,6 +136,9 @@ func wrapUnitTestChain(t testing.TB, chain *core.Blockchain, orc OracleHandler,
 
 	handler := http.HandlerFunc(rpcServer.handleHTTPRequest)
 	srv := httptest.NewServer(handler)
+	t.Cleanup(func() {
+		srv.Close()
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_helper_test.go:140]: It's not the only place where we should properly close this server. And it's suspicious that we have exactly those tests failing where `src.Close` isn't called. Search through the failing test issues and check whether it solves some of them.

**Comment by AliceInHunterland** [comment]
still problms with tcp traverse and traverseiterator on windows and mac

**Comment by AnnaShaleva** [comment]
> still problms with tcp traverse and traverseiterator on windows and mac

Don't reference those issues that are not solved and not related to this PR then. These two are separate problems.

File: pkg/rpcclient/wsclient_test.go [hunk 8]
```diff
@@ -276,6 +276,7 @@ func TestWSClientEvents(t *testing.T) {
 	require.False(t, ok)
 	_, ok = <-ntfCh
 	require.False(t, ok)
+	t.Cleanup(srv.Close)
```
Comment (AnnaShaleva) [inline pkg/rpcclient/wsclient_test.go:279]: > to prevent fd leak.

Have you checked that it's fd leak? Because I'm not sure about it. If you're not sure, then either don't write it or check for sure.

Comment (AnnaShaleva) [inline pkg/rpcclient/wsclient_test.go:279]: > Refs https://github.com/nspcc-dev/neo-go/issues/3300
Ref https://github.com/nspcc-dev/neo-go/issues/2958

No way. Separate problem.

Comment (AnnaShaleva) [reply pkg/rpcclient/wsclient_test.go:279]: It's just written in test HTTP server constructor that it should be properly closed in the end of the test.

Comment (AnnaShaleva) [inline pkg/rpcclient/wsclient_test.go:279]: Should be placed right after `srv` construction because if test breaks in the middle of execution, the server won't be properly closed.

**Review by AnnaShaleva — COMMENTED** [review]
> Close https://github.com/nspcc-dev/neo-go/issues/3312
Close https://github.com/nspcc-dev/neo-go/issues/2956
Close https://github.com/nspcc-dev/neo-go/issues/3005

Why?

**Review by AnnaShaleva — APPROVED** [review]

**Comment by AnnaShaleva** [comment]
@roman-khimov, ready for review, you'll like this PR.

**Review by roman-khimov — APPROVED** [review]
