### PR TITLE
Drop redundant dev code part 4

### LINKED ISSUE #173: InvocationTX:  DecodeBinary bug (Master branch)
The implementaion of the `DecodeBinary` method is not correct:
https://github.com/CityOfZion/neo-go/blob/master/pkg/core/transaction/invocation.go#L36
```go
// DecodeBinary implements the Payload interface.
func (tx *InvocationTX) DecodeBinary(r io.Reader) error {
	lenScript := util.ReadVarUint(r)
	tx.Script = make([]byte, lenScript)
	if err := binary.Read(r, binary.LittleEndian, tx.Script); err != nil {
		return err
	}
	return binary.Read(r, binary.LittleEndian, &tx.Gas)
}
```

the equivalent C# looks as follow:
https://github.com/neo-project/neo/blob/master/neo/Network/P2P/Payloads/InvocationTransaction.cs#L24
```C#
protected override void DeserializeExclusiveData(BinaryReader reader)
        {
            if (Version > 1) throw new FormatException();
            Script = reader.ReadVarBytes(65536);
            if (Script.Length == 0) throw new FormatException();
            if (Version >= 1)
            {
                Gas = reader.ReadSerializable<Fixed8>();
                if (Gas < Fixed8.Zero) throw new FormatException();
            }
            else
            {
                Gas = Fixed8.Zero;
            }
        }
```

as we can see the golang implementation fails to include the `Version` logic.

For this raw transaction
```go
raw_tx:= "d1001b00046e616d6567d3d8602814a429a91afdbaa3914884a1c90c733101201cc9c05cefffe6cdd7b182816a9152ec218d2ec000000141403387ef7940a5764259621e655b3c621a6aafd869a611ad64adcc364d8dd1edf84e00a7f8b11b630a377eaef02791d1c289d711c08b7ad04ff0d6c9caca22cfe6232103cbb45da6072c14761c9da545749d9cfd863f860c351066d16df480602a2024c6ac"
byteTx, err := hex.DecodeString(param); err != nil {
			err = errors.Wrapf(err, "unable to decode %s to []byte", param.StringVal)
			resultsErr = NewInvalidParamsError(err.Error(), err)
		} else {
			r := bytes.NewReader(byteTx)
			tx := &transaction.Transaction{}
			err = tx.DecodeBinary(r)
}
```
we expect tx to be:
```go
{'txid': '0x1672df78b7dd21f3516fb0759518dfab29cbe106715504a59a3e12a359850397', 'size': 157, 'type': 'InvocationTransaction', 'version': 0, 'attributes': [{'usage': 32, 'data': '1cc9c05cefffe6cdd7b182816a9152ec218d2ec0'}], 'vout': [], 'vin': [], 'sys_fee': '0', 'net_fee': '0', 'scripts': [{'invocation': '403387ef7940a5764259621e655b3c621a6aafd869a611ad64adcc364d8dd1edf84e00a7f8b11b630a377eaef02791d1c289d711c08b7ad04ff0d6c9caca22cfe6', 'verification': '2103cbb45da6072c14761c9da545749d9cfd863f860c351066d16df480602a2024c6ac'}], 'script': '00046e616d6567d3d8602814a429a91afdbaa3914884a1c90c7331', 'gas': 0}
```

in particular `gas = 0`

### PR DESCRIPTION
**Pull request by roman-khimov**
The next one in series of #315, #318 and #322. Continuing with #307. Fixes #173 along the way.

### CODE REVIEW

File: pkg/core/block_test.go [hunk 1]
```diff
@@ -101,3 +101,159 @@ func TestBlockVerify(t *testing.T) {
...
+	rawBlockBytes, _ := hex.DecodeString(rawBlock)
+
+	b := Block{}
+
+	r := bytes.NewReader(rawBlockBytes)
+	b.DecodeBinary(r)
```
Comment (golangcibot) [inline pkg/core/block_test.go]: Error return value of `b.DecodeBinary` is not checked (from `errcheck`)

File: pkg/core/block_test.go [hunk 2]
```diff
@@ -101,3 +101,159 @@ func TestBlockVerify(t *testing.T) {
...
+	assert.Equal(t, "552102486fd15702c4490a26703112a5cc1d0923fd697a33406bd5a1c00e0013b09a7021024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d2102aaec38470f6aad0042c6e877cfd8087d2676b0f516fddd362801b9bd3936399e2103b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c2103b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a2102ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba5542102df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e89509357ae", hex.EncodeToString(b.Script.VerificationScript))
+	assert.Equal(t, "0006d3ff96e269f599eb1b5c5a527c218439e498dcc65b63794591bbcdc0516b", b.Hash().ReverseString())
+
+
+	buf := new(bytes.Buffer)
+
+	b.EncodeBinary(buf)
```
Comment (golangcibot) [inline pkg/core/block_test.go]: Error return value of `b.EncodeBinary` is not checked (from `errcheck`)

File: pkg/network/payload/inventory_test.go [hunk 3]
```diff
@@ -17,16 +17,20 @@ func TestInventoryEncodeDecode(t *testing.T) {
...
+}
 
-	if !reflect.DeepEqual(inv, invDecode) {
-		t.Fatalf("expected both inventories to be equal %v and %v", inv, invDecode)
-	}
+func TestEmptyInv(t *testing.T) {
+	msgInv := NewInventory(TXType, []Uint256{})
+
+	buf := new(bytes.Buffer)
+	msgInv.EncodeBinary(buf)
```
Comment (golangcibot) [inline pkg/network/payload/inventory_test.go]: Error return value of `msgInv.EncodeBinary` is not checked (from `errcheck`)

File: pkg/network/payload/headers_test.go [hunk 4]
```diff
@@ -41,18 +42,41 @@ func TestHeadersEncodeDecode(t *testing.T) {
...
+
+	var headerMsg Headers
+
+	rawBlockBytes, _ := hex.DecodeString(rawBlockHeaders)
+
+	r := bytes.NewReader(rawBlockBytes)
+
+	err := headerMsg.DecodeBinary(r)
```
Comment (golangcibot) [inline pkg/network/payload/headers_test.go]: ineffectual assignment to `err` (from `ineffassign`)

File: pkg/core/transaction/invocation.go [hunk 5]
```diff
@@ -35,14 +36,28 @@ func NewInvocationTX(script []byte) *Transaction {
...
-	bw.WriteLE(tx.Gas)
+	if (tx.Version >= 1) {
+		bw.WriteLE(tx.Gas)
+	}
 	return bw.Err
 }
+
+func (tx *InvocationTX) Size() int {
+	sz := util.GetVarSize(tx.Script)
+	if (tx.Version >= 1) {
```
Comment (volekerb) [inline pkg/core/transaction/invocation.go]: Just a thought:
Looks like Version 1+ introduced at some point some incompatible changes to the structures of transactions.
I believe that is could be much better to separate implementations in different packages with have v0 and v1 and having check for version somewhere in one place. Yes in that case we will have dupe code but it will make live easier and cone cleaner. WDYT?
It's just and idea. It we would agree on that -> will create an issue and some day we can do it.

File: pkg/network/payload/headers_test.go [hunk 6]
```diff
@@ -41,18 +42,41 @@ func TestHeadersEncodeDecode(t *testing.T) {
...
+	assert.Nil(t, err)
+	assert.Equal(t, 1, len(headerMsg.Hdrs))
+
+	header := headerMsg.Hdrs[0]
+	hash := header.Hash()
+
+	assert.Equal(t, "f3c4ec44c07eccbda974f1ee34bc6654ab6d3f22cd89c2e5c593a16d6cc7e6e8", hash.ReverseString())
```
Comment (volekerb) [inline pkg/network/payload/headers_test.go]: What do you think about moving "f3c4ec44c07eccbda974f1ee34bc6654ab6d3f22cd89c2e5c593a16d6cc7e6e8" to a constant with some name?

Comment (roman-khimov) [reply pkg/network/payload/headers_test.go]: It's only used once here, I don't think it makes much difference making it a named constant.

File: pkg/core/transaction/invocation.go (hunk 5 above)
Comment (roman-khimov) [reply pkg/core/transaction/invocation.go]: That depends on level of similarities (or differences) between versions. Here we have 99% similar code for different versions, so adding new packages will just create a lot of duplication and boilerplate with no real gains, IMO. NEO3 is going to be different, but then I'm not sure if there is a need to keep compatibility with current version when we are to move to NEO3.

File: pkg/network/payload/headers_test.go (hunk 6 above)
Comment (volekerb) [reply pkg/network/payload/headers_test.go]: header.Hash() could be inlined as well then?=)
Good to have constant in order to comfortably review the code. So without looking through the code you know what it is.
