### PR TITLE
smartcontract: fix go version mismatch in TestContractInitAndCompile

### LINKED ISSUE #3152: Failing TestContractInitAndCompile due to unexpected go version
Go 1.18, Ubuntu, firstly discovered in https://github.com/nspcc-dev/neo-go/pull/3110 tests (https://github.com/nspcc-dev/neo-go/actions/runs/6467920919/job/17558942258?pr=3110).
```
2023-10-10T10:20:09.4189302Z === RUN   TestContractInitAndCompile/excessive_parameters#01
2023-10-10T10:20:09.4189485Z additional arguments given while this command expects none
2023-10-10T10:20:09.4233893Z ##[error]error while trying to compile smart contract file: /tmp/TestContractInitAndCompile2057603306/001/testcontract/main.go:13:27: undeclared name: any (requires version go1.18 or later)
2023-10-10T10:20:09.4241749Z === CONT  TestContractInitAndCompile
2023-10-10T10:20:09.4241926Z     executor.go:277: 
2023-10-10T10:20:09.4242586Z         	Error Trace:	/home/runner/work/neo-go/neo-go/internal/testcli/executor.go:277
2023-10-10T10:20:09.4243525Z         	            				/home/runner/work/neo-go/neo-go/cli/smartcontract/contract_test.go:281
2023-10-10T10:20:09.4243784Z         	Error:      	Received unexpected error:
2023-10-10T10:20:09.4244646Z ##[error]        	            	error while trying to compile smart contract file: /tmp/TestContractInitAndCompile2057603306/001/testcontract/main.go:13:27: undeclared name: any (requires version go1.18 or later)
2023-10-10T10:20:09.4245274Z         	Test:       	TestContractInitAndCompile
2023-10-10T10:20:09.4245525Z --- FAIL: TestContractInitAndCompile (0.06s)
2023-10-10T10:20:09.4245894Z     --- PASS: TestContractInitAndCompile/no_path_is_provided (0.00s)
2023-10-10T10:20:09.4246231Z     --- PASS: TestContractInitAndCompile/invalid_path (0.00s)
2023-10-10T10:20:09.4246605Z     --- PASS: TestContractInitAndCompile/excessive_parameters (0.00s)
2023-10-10T10:20:09.4247018Z     --- PASS: TestContractInitAndCompile/don't_rewrite_existing_directory (0.00s)
2023-10-10T10:20:09.4247358Z     --- PASS: TestContractInitAndCompile/missing_source (0.00s)
2023-10-10T10:20:09.4247774Z     --- PASS: TestContractInitAndCompile/missing_config,_but_require_manifest (0.00s)
2023-10-10T10:20:09.4248152Z     --- PASS: TestContractInitAndCompile/provided_non-existent_config (0.00s)
2023-10-10T10:20:09.4248540Z     --- PASS: TestContractInitAndCompile/provided_corrupted_config (0.00s)
2023-10-10T10:20:09.4248907Z     --- PASS: TestContractInitAndCompile/excessive_parameters#01 (0.00s)
```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
It is necessary to update dependencies in the test for go1.18 and above to match with the interop module.

Close #3152

### CODE REVIEW

File: cli/smartcontract/contract_test.go [hunk 1]
```diff
@@ -280,6 +281,11 @@ func TestContractInitAndCompile(t *testing.T) {
 	t.Run("excessive parameters", func(t *testing.T) {
 		e.RunWithError(t, append(cmd, "something")...)
 	})
+	cmdGoModTidy := exec.Command("go", "mod", "tidy")
+	cmdGoModTidy.Dir = ctrPath
+
+	err = cmdGoModTidy.Run()
+	require.NoError(t, err, "Running go mod tidy failed")
```
Comment (AnnaShaleva) [inline cli/smartcontract/contract_test.go:288]: Why do you need this? What is the exact reason of the test failure? Have you managed to reproduce the test failure on the current master locally or in the testing jobs? 

The only dependency this example SC has is `interop` package. This dependency is being replaced by the local package. So the question is whether this issue still relevant, because now minimum required go version is 1.19 for both neo-go and interop.

Comment (AnnaShaleva) [reply cli/smartcontract/contract_test.go:288]: In fact, when you run `go tidy`, it also adds minimum required go version to the `go.mod` file (this is the currently installed go version). So I'd suggest to fix contract go.mod template and add minimum required go version by ourselves:
https://github.com/nspcc-dev/neo-go/blob/71fb759c0d009218437d0048f7ba085a2a74c66f/cli/smartcontract/smart_contract.go#L376-L379

Also may fix the indent while we're here.

**Review by AnnaShaleva — CHANGES_REQUESTED** [review]

File: cli/smartcontract/contract_test.go (hunk 1 above)
Comment (AliceInHunterland) [reply cli/smartcontract/contract_test.go:288]: I managed to reproduce it only with go1.18 locally on Ubuntu with the revision of the master with go1.18 (however interop also required go1.18 at that point, I'm still not sure why we had this problem), so it's not relevant now.  With the current master, it's not reproducible (and with go1.18, it's not runnable).

Comment (AliceInHunterland) [reply cli/smartcontract/contract_test.go]: also without go mod tidy i got `error while trying to compile smart contract file: err: exit status 1: stderr: go: updates to go.mod needed; to update it:
	go mod tidy` 
	(go1.18 ubuntu)

File: cli/smartcontract/smart_contract.go [hunk 2]
```diff
@@ -374,9 +374,10 @@ func initSmartContract(ctx *cli.Context) error {
 	}
 
 	gm := []byte("module " + contractName + `
-require (
+	go 1.18
```
Comment (AnnaShaleva) [inline cli/smartcontract/smart_contract.go:377]: Fix the indent, please.

Comment (AnnaShaleva) [inline cli/smartcontract/smart_contract.go:377]: We need go 1.19 for now.

Comment (AnnaShaleva) [reply cli/smartcontract/smart_contract.go:377]: Here and below. Run `neo-go smartcontract init` and see the generated file, it should have the correct indent.

File: cli/smartcontract/contract_test.go (hunk 1 above)
Comment (AnnaShaleva) [reply cli/smartcontract/contract_test.go]: I think this problem is not relevant anymore with go 1.19 and updated interop deps.

File: cli/smartcontract/smart_contract.go [hunk 3]
```diff
@@ -374,9 +374,12 @@ func initSmartContract(ctx *cli.Context) error {
 	}
 
 	gm := []byte("module " + contractName + `
+
 require (
 	github.com/nspcc-dev/neo-go/pkg/interop ` + ver + `
-)`)
+)
+
+go 1.19`)
```
[the remark this answers is not in the document]
Comment (roman-khimov) [reply cli/smartcontract/smart_contract.go:382]: It's OK to have it (all regular `go.mod` files have some `go` definition).

But why after `require`?

[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply cli/smartcontract/smart_contract.go:382]: I thought it's kind of standard to have it in the end of go.mod:
https://github.com/nspcc-dev/neo-go/blob/71fb759c0d009218437d0048f7ba085a2a74c66f/go.mod#L80

But according to https://go.dev/doc/modules/gomod-ref, it should be put before `require`, thus @AliceInHunterland, let's update the current PR and NeoGo gomod file (in a separate commit).

**Review by roman-khimov — APPROVED** [review]
