### PR TITLE
keys: support returning legacy verification script

### LINKED ISSUE #1110: Can't convert neo2 wallet to neo3 wallet
I've created new wallet with `neo-go v0.75.0`

```
$ neo-go --version                                                       
neo-go version 0.75.0                          
$ neo-go wallet init -a -p ./old-wallet.json
Enter the name of the account >                                      
Enter passphrase >                                                 
Confirm passphrase >                     
wallet successfully created, file location is ./old-wallet.json
```

Then I switched to a latest commit in master branch and tried to convert this wallet. Unfortunately this didn't go well.

```
$ neo-go --version
neo-go version 0.90.0-pre-537-g3d6ff355
$ neo-go wallet convert -p ./old-wallet.json -o new-wallet.json
Enter passphrase for account AKiEjj7ZWp1hQnkiC5mjgL7LunsAaxU1xe (label '') > 
invalid passphrase
```

It failed both with empty and non-empty passphrase.

### PR DESCRIPTION
**Pull request by fyrchik**
Closes #1110 .
When one works with legacy (NEO2) wallets, it is useful to have access
to old verification script formats.

### CODE REVIEW

File: pkg/crypto/keys/publickey.go [hunk 1]
```diff
@@ -242,6 +242,12 @@ func (p *PublicKey) EncodeBinary(w *io.BinWriter) {
 func (p *PublicKey) GetVerificationScript() []byte {
 	b := p.Bytes()
 	buf := io.NewBufBinWriter()
+	if address.Prefix == address.NEO2Prefix {
```
Comment (roman-khimov) [inline pkg/crypto/keys/publickey.go:245]: Depending on `address` here is a bad idea.

Comment (fyrchik) [reply pkg/crypto/keys/publickey.go:245]: What do you suggest?

Comment (fyrchik) [reply pkg/crypto/keys/publickey.go:245]: I think we should just have all legacy decoding inside the cli package.

**Comment by roman-khimov** [comment]
OK, I'll accept it as a temporary preview2 fix and will fix it later.
