### PR TITLE
rpcclient: fix TestWSClientNonBlockingEvents

### LINKED ISSUE #3005: Failing `TestWSClientNonBlockingEvents`
Ubuntu, go 1.19. Firstly discovered at https://github.com/nspcc-dev/neo-go/actions/runs/4883739029/jobs/8715507458?pr=3004.
```
2023-05-04T14:10:52.3767949Z === RUN   TestWSClientNonBlockingEvents
2023-05-04T14:10:52.3768321Z     wsclient_test.go:349: 
2023-05-04T14:10:52.3769041Z         	Error Trace:	/home/runner/work/neo-go/neo-go/pkg/rpcclient/wsclient_test.go:349
2023-05-04T14:10:52.3769525Z         	Error:      	Condition never satisfied
2023-05-04T14:10:52.3769973Z         	Test:       	TestWSClientNonBlockingEvents
2023-05-04T14:10:52.3770414Z --- FAIL: TestWSClientNonBlockingEvents (2.10s)
```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Add waiting for startSending to ensure that the client is ready before the server starts sending messages.

Close #3005
Close https://github.com/nspcc-dev/neo-go/issues/3312

### CODE REVIEW

**Comment by AliceInHunterland** [comment]
maybe we can add such "checks" to all httptest.NewServer cases in the wsclient tests?

**Review by AnnaShaleva — APPROVED** [review]
Good, should fix the problem.

**Comment by AnnaShaleva** [comment]
> maybe we can add such "checks" to all httptest.NewServer cases in the wsclient tests?

Yes, let's review all related tests because for example `TestWSClientEvents` has the same problem.

File: pkg/rpcclient/rpc_test.go [hunk 1]
```diff
@@ -2022,6 +2030,7 @@ func TestUninitedClient(t *testing.T) {
 
 	c, err := New(context.TODO(), endpoint, opts)
 	require.NoError(t, err)
+	close(startSending)
```
Comment (AnnaShaleva) [inline pkg/rpcclient/rpc_test.go:2033]: Also, I don't think we need this fix for non-WS client, because standard RPC client doesn't open connection on client creation. @roman-khimov, agree?

File: pkg/rpcclient/wsclient_test.go [hunk 2]
```diff
@@ -781,11 +823,13 @@ func TestWSConcurrentAccess(t *testing.T) {
 	}
 	ids.m = make(map[int]struct{})
 
+	startSending := make(chan struct{})
 	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
 		if req.URL.Path == "/ws" && req.Method == "GET" {
 			var upgrader = websocket.Upgrader{}
 			ws, err := upgrader.Upgrade(w, req, nil)
 			require.NoError(t, err)
+			<-startSending
```
Comment (AnnaShaleva) [inline pkg/rpcclient/wsclient_test.go:832]: Also likely not needed since it's infinite `for` loop handler.

File: pkg/services/rpcsrv/client_test.go [hunk 3]
```diff
@@ -67,8 +67,9 @@ import (
 func TestClient_NEP17(t *testing.T) {
 	_, _, httpSrv := initServerWithInMemoryChain(t)
 
-	c, err := rpcclient.New(context.Background(), httpSrv.URL, rpcclient.Options{})
+	c, err := rpcclient.New(context.Background(), httpSrv.URL(), rpcclient.Options{})
 	require.NoError(t, err)
+	httpSrv.StartSend()
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/client_test.go:72]: Why do you need this change?

File: pkg/services/rpcsrv/client_test.go [hunk 4]
```diff
@@ -1699,16 +1721,25 @@ func TestClient_Iterator_SessionConfigVariations(t *testing.T) {
...
+		handler := http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
+			// Wait for the start signal.
+			<-startSending
+			rpcSrv.handleHTTPRequest(w, req)
+		})
+
 		httpSrv := httptest.NewServer(handler)
 		t.Cleanup(httpSrv.Close)
 		defer rpcSrv.Shutdown()
+
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/client_test.go:1734]: Useless change.

File: pkg/services/rpcsrv/server_helper_test.go [hunk 5]
```diff
@@ -29,6 +30,34 @@ const (
 	notaryPass = "one"
 )
 
+// ServerWrapper wraps httptest.Server with startSending channel.
+type ServerWrapper struct {
+	Server       *httptest.Server
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_helper_test.go:35]: Just `*httptest.Server`, it allows to remove `func (sw *ServerWrapper) URL()`.

File: pkg/services/rpcsrv/server_helper_test.go [hunk 6]
```diff
@@ -29,6 +30,34 @@ const (
...
+
+// Close closes the underlying server and the startSending channel if it's not already closed.
+func (sw *ServerWrapper) Close() {
+	if !sw.Closed.Load() {
+		if sw.StartSending != nil {
+			close(*sw.StartSending)
+		}
+		sw.Closed.Store(true)
+	}
+	sw.Server.Close()
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_helper_test.go:48]: It's racy, use `CAS`.

File: pkg/services/rpcsrv/server_helper_test.go [hunk 7]
```diff
@@ -128,22 +158,32 @@ func wrapUnitTestChain(t testing.TB, chain *core.Blockchain, orc OracleHandler,
...
 	t.Cleanup(rpcServer.Shutdown)
 
-	handler := http.HandlerFunc(rpcServer.handleHTTPRequest)
-	srv := httptest.NewServer(handler)
+	// Create a new test server with modified handler
+	handler := http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
+		// Wait for the signal to start sending messages
+		<-startSending
+
+		rpcServer.handleHTTPRequest(w, req)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_helper_test.go:166]: Why do you need this wrapper for RPC server tests?

**Review by AnnaShaleva — CHANGES_REQUESTED** [review]

File: pkg/rpcclient/rpc_test.go [hunk 8]
```diff
@@ -1881,15 +1877,18 @@ func testRPCClient(t *testing.T, newClient func(context.Context, string, Options
...
 
 					endpoint := srv.URL
 					opts := Options{}
 					c, err := newClient(context.TODO(), endpoint, opts)
 					if err != nil {
 						t.Fatal(err)
 					}
+					close(startSending)
 					c.getNextRequestID = getTestRequestID
+					require.NoError(t, c.Init())
```
[the remark this answers is not in the document]
Comment (roman-khimov) [reply pkg/rpcclient/rpc_test.go:1892]: My thought was "this PR does too much now". In most cases it's OK to have a server that answers directly to new requests, single request --- single reply (and this change is not needed). But notification tests are not exactly about requests, they expect different data. Some other tests that do multiple requests can have additional requirements as well.

File: pkg/rpcclient/rpc_test.go [hunk 9]
```diff
@@ -1909,17 +1908,20 @@ func testRPCClient(t *testing.T, newClient func(context.Context, string, Options
...
-
-		endpoint := srv.URL
-		opts := Options{}
 		for _, testCase := range testBatch {
 			t.Run(testCase.name, func(t *testing.T) {
+				startSending := make(chan struct{})
+				srv := initTestServer(t, serverResponse, startSending)
+
+				endpoint := srv.URL
+				opts := Options{}
```
[the remark this answers is not in the document]
Comment (roman-khimov) [reply pkg/rpcclient/rpc_test.go:1917]: It's very expensive, true.

File: pkg/rpcclient/rpc_test.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/rpcclient/rpc_test.go:2033]: Yes.

File: pkg/rpcclient/wsclient_test.go [hunk 10]
```diff
@@ -391,11 +397,12 @@ func TestWSExecutionNotificationNameCheck(t *testing.T) {
 func TestWSFilteredSubscriptions(t *testing.T) {
 	var cases = []struct {
 		name       string
-		clientCode func(*testing.T, *WSClient)
+		clientCode func(*testing.T, *WSClient, chan struct{})
```
Comment (AnnaShaleva) [inline pkg/rpcclient/wsclient_test.go:400]: Not needed in this test.

**Review by AnnaShaleva — COMMENTED** [review]
OK, I've checked other tests, so the result is only two are affected: TestWSClientEvents and TestWSClientNonBlockingEvents. TestWSFilteredSubscriptions seems to be OK without this fix (need to revert fix for this test).

Otherwise LGTM.

**Review by AnnaShaleva — APPROVED** [review]
