### PR TITLE
Handshake and peers fix

### LINKED ISSUE #458: Server can't properly handshake clients
Our production nodes have a lot of cases like this in their logs:
```
time="2019-10-25T23:06:52Z" level=info msg="new peer connected" addr="X.X.X.X:55234"
time="2019-10-25T23:06:52Z" level=warning msg="peer disconnected" addr="X.X.X.X:55234" peerCount=26 reason="invalid handshake: received Version in nothingDone state"
```
The problem is that the server doesn't expect `Version` packet to come from the client. Usually our node is a client and it sends its `Version` first, but on the server side this conversation is mirrored and should be processed the other way around.

### PR DESCRIPTION
**Pull request by roman-khimov**
Fixes #458, MaxPeers handling and some other related things.

### CODE REVIEW

File: pkg/network/tcp_peer.go [hunk 1]
```diff
@@ -12,13 +12,13 @@ import (
...
-	versionSent     handShakeStage = 1
-	versionReceived handShakeStage = 2
-	verAckSent      handShakeStage = 3
-	verAckReceived  handShakeStage = 4
+	versionSent handShakeStage = 1 << iota
+	versionReceived
+	verAckSent
+	verAckReceived
+
+	nothingDone handShakeStage = 0
```
Comment (golangcibot) [inline pkg/network/tcp_peer.go]: `nothingDone` is unused (from `varcheck`)

**Comment by roman-khimov** [comment]
@codecov is sooooo dumb...

**Comment by volekerb** [comment]
> @codecov is sooooo dumb...

welcome to the club!
