### PR TITLE
storage: fix Get for BoltDB, fix #1482

### LINKED ISSUE #1482: Single node fails on first commit
neo-go version 0.91.1-pre-331-gc72ecd1b

I started single node consensus with latest neo-go from master and it throws panic on when first block is ready.
```
2020-10-13T14:56:51.878+0300    INFO    approving block {"height": 2, "hash": "d304f876fd956e0a3b9f29e9c8007c2b7341a6a9dc66182b4dcad30638315078", "tx_count": 0, "merkle": "b789811f5b043046f3a325f589fdaec54c539f23adc5ac0f98386a7d0c5e73a9", "prev": "d4a5885cda667e9787ad6ac8eb
2a5371b75f1d7ac7033783fd2bce1aeb57d277"}                                                                                          
unexpected fault address 0x7f3b267f148f                             
fatal error: fault                                                                                                                 
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f3b267f148f pc=0xa58fe2]
                                                                                                                      
goroutine 81 [running]:                                                
runtime.throw(0xe041d2, 0x5)                                                     
        runtime/panic.go:1116 +0x72 fp=0xc001495d60 sp=0xc001495d30 pc=0x437632
runtime.sigpanic()                                                      
        runtime/signal_unix.go:727 +0x405 fp=0xc001495d90 sp=0xc001495d60 pc=0x44ddc5
github.com/nspcc-dev/neo-go/pkg/core/state.(*NEP5TransferLog).Append(0xc0002802c0, 0xc00020fa80, 0x178256213f674eb3, 0xeb88a496)
        github.com/nspcc-dev/neo-go/pkg/core/state/nep5.go:98 +0x1a2 fp=0xc001495ea0 sp=0xc001495d90 pc=0xa58fe2
github.com/nspcc-dev/neo-go/pkg/core/dao.(*Cached).AppendNEP5Transfer(0xc00040baa0, 0x2e44f9d85cf8aaa, 0x178256213f674eb3, 0xeb88a496, 0xc00020fa80, 0x0, 0x0, 0x0)
        github.com/nspcc-dev/neo-go/pkg/core/dao/cacheddao.go:95 +0x8a fp=0xc001495f28 sp=0xc001495ea0 pc=0xa6b82a
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).processNEP5Transfer(0xc0002a89c0, 0xc00040baa0, 0xa6e95fd76f804d3, 0x2b7c00c8e9299f3b, 0x2b1866dca9a64173, 0x7850313806d3ca4d, 0xc0000d7600, 0xadd4c784d641afbc, 0x9d7b70a99dd9e06e, 0xc0668e0c1f, ...)
        github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:810 +0x4c5 fp=0xc0014960e8 sp=0xc001495f28 pc=0xaa7545
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).handleNotification(0xc0002a89c0, 0xc0002a4f30, 0xc00040baa0, 0xc0000d7600, 0xa6e95fd76f804d3, 0x2b7c00c8e9299f3b, 0x2b1866dca9a64173, 0x7850313806d3ca4d)
        github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:746 +0x247 fp=0xc0014961d0 sp=0xc0014960e8 pc=0xaa6e27
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).runPersist(0xc0002a89c0, 0xc0002e0280, 0x56, 0x94, 0xc0000d7600, 0xc00040baa0, 0xc0001dcee0, 0x0, 0x0)
        github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:700 +0x22b fp=0xc001496370 sp=0xc0014961d0 pc=0xaa67cb                  
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).storeBlock(0xc0002a89c0, 0xc0000d7600, 0xc000292e10, 0x1586f30, 0xa9735e0c7d6a3898)
        github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:620 +0x1298 fp=0xc001496878 sp=0xc001496370 pc=0xaa5898
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).AddBlock(0xc0002a89c0, 0xc0000d7600, 0x0, 0x0)
        github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:448 +0x1f8 fp=0xc001496af0 sp=0xc001496878 pc=0xaa27b8
github.com/nspcc-dev/neo-go/pkg/consensus.(*service).processBlock(0xc0002d60b0, 0x1055000, 0xc0000d7600)
        github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:458 +0xbf fp=0xc001496cb8 sp=0xc001496af0 pc=0xb07aff
github.com/nspcc-dev/neo-go/pkg/consensus.(*service).processBlock-fm(0x1055000, 0xc0000d7600)
        github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:454 +0x3e fp=0xc001496ce0 sp=0xc001496cb8 pc=0xb114de
github.com/nspcc-dev/dbft.(*DBFT).checkCommit(0xc0001d6000)         
        github.com/nspcc-dev/dbft@v0.0.0-20200925163137-8f3b9ab3b720/check.go:73 +0x974 fp=0xc0014970c8 sp=0xc001496ce0 pc=0xaf3a94
github.com/nspcc-dev/dbft.(*DBFT).checkPrepare(0xc0001d6000)                      
        github.com/nspcc-dev/dbft@v0.0.0-20200925163137-8f3b9ab3b720/check.go:36 +0x45c fp=0xc001497300 sp=0xc0014970c8 pc=0xaf2e5c
github.com/nspcc-dev/dbft.(*DBFT).sendPrepareRequest(0xc0001d6000)   
        github.com/nspcc-dev/dbft@v0.0.0-20200925163137-8f3b9ab3b720/send.go:42 +0x2fd fp=0xc001497420 sp=0xc001497300 pc=0xafecbd
github.com/nspcc-dev/dbft.(*DBFT).OnTimeout(0xc0001d6000, 0x2)      
        github.com/nspcc-dev/dbft@v0.0.0-20200925163137-8f3b9ab3b720/dbft.go:183 +0x64c fp=0xc0014975f0 sp=0xc001497420 pc=0xaf788c
github.com/nspcc-dev/neo-go/pkg/consensus.(*service).eventLoop(0xc0002d60b0)
        github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:230 +0x10bd fp=0xc001497fd8 sp=0xc0014975f0 pc=0xb052bd
runtime.goexit()
        runtime/asm_amd64.s:1374 +0x1 fp=0xc001497fe0 sp=0xc001497fd8 pc=0x46f941
created by github.com/nspcc-dev/neo-go/pkg/consensus.(*service).Start
        github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:208 +0x9b
```

### PR DESCRIPTION
**Pull request by roman-khimov**

### CODE REVIEW

File: pkg/core/storage/boltdb_store.go [hunk 1]
```diff
@@ -61,6 +61,12 @@ func (s *BoltDBStore) Get(key []byte) (val []byte, err error) {
 	err = s.db.View(func(tx *bbolt.Tx) error {
 		b := tx.Bucket(Bucket)
 		val = b.Get(key)
+		// Value from Get is only valid for the lifetime of transcation, #1482
```
Comment (fyrchik) [inline pkg/core/storage/boltdb_store.go:64]: s/transcation/transaction/

**Review by fyrchik — APPROVED** [review]

File: pkg/core/storage/boltdb_store.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/core/storage/boltdb_store.go]: Fixed

**Review by AnnaShaleva — APPROVED** [review]
