### PR TITLE
services: fix defer function in `retry` of NeoFSBlockFetcher

### LINKED ISSUE #3734: NeoFS BlockFetcher is hanging on startup
## Current Behavior
0.107.1 node (`{unit="neogo-morph-rpc.service", instance="tenes4"}`) is hanging after NeoFS BlockFetcher service start. Its height is up-to-date, so no blocks should be fetched from NeoFS.

```
2024-12-06 14:36:13.869	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}	
2024-12-06 14:36:13.869	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}	
2024-12-06 14:36:13.869	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}	
2024-12-06 14:36:13.869	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}	
2024-12-06 14:36:13.869	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}	
2024-12-06 14:36:13.871	INFO	restoring blockchain	{"version": "0.2.12"}	
2024-12-06 14:36:14.231	INFO	starting service	{"service": "Prometheus", "endpoint": "localhost:2132"}	
2024-12-06 14:36:14.232	INFO	starting service	{"service": "Pprof", "endpoint": "localhost:2133"}
2024-12-06 14:36:14.232	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}	
2024-12-06 14:36:14.232	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}	
2024-12-06 14:36:14.232	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}	
2024-12-06 14:36:14.232	INFO	MaxFindStorageResultItems is not set or wrong, setting default value	{"MaxFindStorageResultItems": 50}	
2024-12-06 14:36:14.232	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-12-06 14:36:14.232	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}	
2024-12-06 14:36:14.232	INFO	starting NeoFS BlockFetcher service
2024-12-06 14:36:14.232	INFO	node started	{"blockHeight": 4690951, "headerHeight": 4690951}
2024-12-06 14:36:14.232	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2024-12-06 14:36:14.232	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
```

It's the full node logs, there are no more peer connections/any other logs.

## Expected Behavior
Node's height is up-to-date, so no blocks should be fetched from NeoFS (and NeoFS doesn't store the recent blocks anyway). The node is expected to shut the service down and move to P2P sync.

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3734

### CODE REVIEW

File: pkg/services/blockfetcher/blockfetcher.go [hunk 1]
```diff
@@ -518,7 +518,10 @@ func (bfs *Service) retry(action func() error) error {
 	)
 	defer func() {
 		if !timer.Stop() {
-			<-timer.C
+			select {
+			case <-timer.C:
+			default:
```
Comment (AnnaShaleva) [inline pkg/services/blockfetcher/blockfetcher.go:523]: 🎉

**Review by AnnaShaleva — APPROVED** [review]
