### PR TITLE
services: update Notary transaction size after completion

### LINKED ISSUE #1766: Block with notary tx fails size check in `UnmarshalJSON`
neo-go version 0.94.0-pre-41-g61e04f04

I made a transaction via notary contract that contains three cosigners:
- proxy contract,
- multiaddress wallet,
- notary contract.

This transaction was successfully created by notary contract and then included in the block. 

I have an application that subscribed to a new blocks via `WSClient`. When block with notary transaction appears, `WSClient` closes notification channel. I found out, that such blocks fail at `err = json.Unmarshal(slice[0], val)` [here](https://github.com/nspcc-dev/neo-go/blob/61e04f04de0ad03e792f68b558fd3eefb25e94cc/pkg/rpc/client/wsclient.go#L156). It throws `'size' doesn't match transaction size` error.

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #1766

### CODE REVIEW

File: pkg/services/notary/notary.go [hunk 1]
```diff
@@ -316,7 +317,28 @@ func (n *Notary) finalize(tx *transaction.Transaction) error {
...
+
+// updateTxSize returns transaction with re-calculated size and an error.
+func updateTxSize(tx *transaction.Transaction) (*transaction.Transaction, error) {
+	bw := io.NewBufBinWriter()
+	tx.EncodeBinary(bw.BinWriter)
+	if bw.Err != nil {
+		return nil, fmt.Errorf("encode binary: %w", bw.Err)
+	}
+	newTx := &transaction.Transaction{Network: tx.Network}
+	br := io.NewBinReaderFromBuf(bw.Bytes())
```
Comment (roman-khimov) [inline pkg/services/notary/notary.go:336]: `return transaction.NewTransactionFromBytes(tx.Network, bw.Bytes())`?

File: pkg/services/notary/notary.go [hunk 2]
```diff
@@ -316,7 +317,28 @@ func (n *Notary) finalize(tx *transaction.Transaction) error {
...
+		return fmt.Errorf("failed to update completed transaction's size: %w", err)
+	}
+
+	return n.onTransaction(newTx)
+}
+
+// updateTxSize returns transaction with re-calculated size and an error.
+func updateTxSize(tx *transaction.Transaction) (*transaction.Transaction, error) {
+	bw := io.NewBufBinWriter()
+	tx.EncodeBinary(bw.BinWriter)
```
Comment (roman-khimov) [inline pkg/services/notary/notary.go:331]: `tx.Bytes()`?

File: pkg/services/notary/notary.go [hunk 3]
```diff
@@ -316,7 +317,28 @@ func (n *Notary) finalize(tx *transaction.Transaction) error {
...
+	if bw.Err != nil {
+		return nil, fmt.Errorf("encode binary: %w", bw.Err)
+	}
+	newTx := &transaction.Transaction{Network: tx.Network}
+	br := io.NewBinReaderFromBuf(bw.Bytes())
+	newTx.DecodeBinary(br)
```
Comment (fyrchik) [inline pkg/services/notary/notary.go:337]: Is encoding + decoding really necessary? Why don't have helper function or method inside `transaction` package?

Comment (roman-khimov) [reply pkg/services/notary/notary.go:337]: My fear is that exposing these internals (providing `(*Transaction) RecalcSize()` may open a can of worms worse than this encoding/decoding. And to properly calculate size we need to serialize the transaction anyway.

File: pkg/services/notary/notary.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/services/notary/notary.go:331]: But what about encoding error if it occurs?

File: pkg/services/notary/notary.go (hunk 3 above)
Comment (AnnaShaleva) [reply pkg/services/notary/notary.go]: We may create `(*transaction).UpdateSize()`  method, but the notary module is the only place where it can be applied.

**Review by fyrchik — APPROVED** [review]

File: pkg/services/notary/notary.go (hunk 2 above)
Comment (roman-khimov) [reply pkg/services/notary/notary.go]: You can still check for `nil` and return error, although it won't be specific, so current code is somewhat better here.

**Review by roman-khimov — APPROVED** [review]

File: pkg/services/notary/notary.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/services/notary/notary.go]: Although it's not possible. Fixed.

File: pkg/services/notary/notary.go [hunk 4]
```diff
@@ -8,6 +8,8 @@ import (
 	"fmt"
 	"sync"
 
+	"go.uber.org/zap"
+
```
Comment (roman-khimov) [inline pkg/services/notary/notary.go:12]: Wat?

File: pkg/services/notary/notary.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/services/notary/notary.go:331]: Reverted.

**Review by roman-khimov — APPROVED** [review]
