### PR TITLE
rpcsrv: fix TestWSClientsLimit

### LINKED ISSUE #3379: TestWSClientsLimit fails macos
[Run tests (macos-14, 1.22)](https://github.com/nspcc-dev/neo-go/actions/runs/8472779511/job/23217827420#logs)
[6_Run tests (windows-2022, 1.22).txt](https://github.com/nspcc-dev/neo-go/files/14800506/6_Run.tests.windows-2022.1.22.txt)

```
2024-03-28T20:02:13.6376650Z === RUN   TestWSClientsLimit
2024-03-28T20:02:13.6376780Z === RUN   TestWSClientsLimit/default
2024-03-28T20:02:13.6377380Z     logger.go:146: 2024-03-28T19:59:33.367Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-03-28T20:02:13.6378100Z     logger.go:146: 2024-03-28T19:59:33.367Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-03-28T20:02:13.6378610Z     logger.go:146: 2024-03-28T19:59:33.367Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-03-28T20:02:13.6379180Z     logger.go:146: 2024-03-28T19:59:33.368Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-03-28T20:02:13.6379790Z     logger.go:146: 2024-03-28T19:59:33.368Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-03-28T20:02:13.6380420Z     logger.go:146: 2024-03-28T19:59:33.368Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2024-03-28T20:02:13.6380830Z     logger.go:146: 2024-03-28T19:59:33.369Z	INFO	no storage version found! creating genesis block
2024-03-28T20:02:13.6381380Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2024-03-28T20:02:13.6381900Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	SessionPoolSize is not set or wrong, setting default value	{"SessionPoolSize": 20}
2024-03-28T20:02:13.6382490Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2024-03-28T20:02:13.6383040Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-03-28T20:02:13.6383560Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2024-03-28T20:02:13.6384150Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
2024-03-28T20:02:13.6384730Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
2024-03-28T20:02:13.6385300Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2024-03-28T20:02:13.6385670Z     logger.go:146: 2024-03-28T19:59:33.372Z	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
2024-03-28T20:02:13.6386120Z     logger.go:146: 2024-03-28T19:59:33.923Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6386710Z     logger.go:146: 2024-03-28T19:59:34.465Z	INFO	persisted to disk	{"blocks": 0, "keys": 127, "headerHeight": 0, "blockHeight": 0, "took": "209.959µs"}
2024-03-28T20:02:13.6387150Z     logger.go:146: 2024-03-28T19:59:35.144Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6387590Z     logger.go:146: 2024-03-28T19:59:35.792Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6388020Z     logger.go:146: 2024-03-28T19:59:36.763Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6388470Z     logger.go:146: 2024-03-28T19:59:37.379Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6388910Z     logger.go:146: 2024-03-28T19:59:38.132Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6389350Z     logger.go:146: 2024-03-28T19:59:39.158Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6389780Z     logger.go:146: 2024-03-28T19:59:40.103Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6390310Z     logger.go:146: 2024-03-28T19:59:41.164Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6390840Z     logger.go:146: 2024-03-28T19:59:42.245Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6391270Z     logger.go:146: 2024-03-28T19:59:43.296Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6391700Z     logger.go:146: 2024-03-28T19:59:43.874Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6392150Z     logger.go:146: 2024-03-28T19:59:44.953Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6392590Z     logger.go:146: 2024-03-28T19:59:45.826Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6393020Z     logger.go:146: 2024-03-28T19:59:46.845Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6393460Z     logger.go:146: 2024-03-28T19:59:48.230Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6393900Z     logger.go:146: 2024-03-28T19:59:49.314Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6394340Z     logger.go:146: 2024-03-28T19:59:50.440Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6394780Z     logger.go:146: 2024-03-28T19:59:51.624Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6395210Z     logger.go:146: 2024-03-28T19:59:52.578Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6395630Z     logger.go:146: 2024-03-28T19:59:53.462Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6396050Z     logger.go:146: 2024-03-28T19:59:54.309Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6396470Z     logger.go:146: 2024-03-28T19:59:55.485Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6396890Z     logger.go:146: 2024-03-28T19:59:56.219Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6397310Z     logger.go:146: 2024-03-28T19:59:57.324Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6397730Z     logger.go:146: 2024-03-28T19:59:58.361Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6398150Z     logger.go:146: 2024-03-28T19:59:59.177Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6398560Z     logger.go:146: 2024-03-28T20:00:00.688Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6398980Z     logger.go:146: 2024-03-28T20:00:01.639Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6399400Z     logger.go:146: 2024-03-28T20:00:02.891Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6399830Z     logger.go:146: 2024-03-28T20:00:03.665Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6400250Z     logger.go:146: 2024-03-28T20:00:04.664Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6400660Z     logger.go:146: 2024-03-28T20:00:05.279Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6401080Z     logger.go:146: 2024-03-28T20:00:06.320Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6401500Z     logger.go:146: 2024-03-28T20:00:07.234Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6401920Z     logger.go:146: 2024-03-28T20:00:08.047Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6402390Z     logger.go:146: 2024-03-28T20:00:09.158Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6402890Z     logger.go:146: 2024-03-28T20:00:10.225Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6403360Z     logger.go:146: 2024-03-28T20:00:11.298Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6403780Z     logger.go:146: 2024-03-28T20:00:12.333Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6404200Z     logger.go:146: 2024-03-28T20:00:13.362Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6404620Z     logger.go:146: 2024-03-28T20:00:14.013Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6405030Z     logger.go:146: 2024-03-28T20:00:15.032Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6405450Z     logger.go:146: 2024-03-28T20:00:16.010Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6405870Z     logger.go:146: 2024-03-28T20:00:17.075Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6406290Z     logger.go:146: 2024-03-28T20:00:17.700Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6406710Z     logger.go:146: 2024-03-28T20:00:18.617Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6407130Z     logger.go:146: 2024-03-28T20:00:19.846Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6407550Z     logger.go:146: 2024-03-28T20:00:20.579Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6407960Z     logger.go:146: 2024-03-28T20:00:21.524Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6408380Z     logger.go:146: 2024-03-28T20:00:22.598Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6408880Z     logger.go:146: 2024-03-28T20:00:23.154Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6409310Z     logger.go:146: 2024-03-28T20:00:23.927Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6409720Z     logger.go:146: 2024-03-28T20:00:24.550Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6410140Z     logger.go:146: 2024-03-28T20:00:25.862Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6410550Z     logger.go:146: 2024-03-28T20:00:27.188Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6410970Z     logger.go:146: 2024-03-28T20:00:28.418Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6411390Z     logger.go:146: 2024-03-28T20:00:29.459Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6411810Z     logger.go:146: 2024-03-28T20:00:30.213Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6412230Z     logger.go:146: 2024-03-28T20:00:31.365Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6412700Z     logger.go:146: 2024-03-28T20:00:32.104Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6413120Z     logger.go:146: 2024-03-28T20:00:33.057Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6413540Z     logger.go:146: 2024-03-28T20:00:33.755Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6413960Z     logger.go:146: 2024-03-28T20:00:34.906Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6414060Z     subscription_test.go:605: 
2024-03-28T20:02:13.6414530Z         	Error Trace:	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:605
2024-03-28T20:02:13.6414780Z         	Error:      	An error is expected but got nil.
2024-03-28T20:02:13.6415010Z         	Test:       	TestWSClientsLimit/default
2024-03-28T20:02:13.6415440Z     logger.go:146: 2024-03-28T20:00:35.802Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:50911"}
2024-03-28T20:02:13.6415530Z === RUN   TestWSClientsLimit/8
2024-03-28T20:02:13.6416080Z     logger.go:146: 2024-03-28T20:00:36.071Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-03-28T20:02:13.6416760Z     logger.go:146: 2024-03-28T20:00:36.071Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-03-28T20:02:13.6417260Z     logger.go:146: 2024-03-28T20:00:36.071Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-03-28T20:02:13.6417830Z     logger.go:146: 2024-03-28T20:00:36.071Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-03-28T20:02:13.6418420Z     logger.go:146: 2024-03-28T20:00:36.071Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-03-28T20:02:13.6419040Z     logger.go:146: 2024-03-28T20:00:36.071Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2024-03-28T20:02:13.6419410Z     logger.go:146: 2024-03-28T20:00:36.072Z	INFO	no storage version found! creating genesis block
2024-03-28T20:02:13.6419940Z     logger.go:146: 2024-03-28T20:00:36.075Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2024-03-28T20:02:13.6420450Z     logger.go:146: 2024-03-28T20:00:36.076Z	INFO	SessionPoolSize is not set or wrong, setting default value	{"SessionPoolSize": 20}
2024-03-28T20:02:13.6421030Z     logger.go:146: 2024-03-28T20:00:36.076Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2024-03-28T20:02:13.6421570Z     logger.go:146: 2024-03-28T20:00:36.076Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-03-28T20:02:13.6422070Z     logger.go:146: 2024-03-28T20:00:36.076Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2024-03-28T20:02:13.6422630Z     logger.go:146: 2024-03-28T20:00:36.076Z	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
2024-03-28T20:02:13.6423210Z     logger.go:146: 2024-03-28T20:00:36.076Z	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
2024-03-28T20:02:13.6423570Z     logger.go:146: 2024-03-28T20:00:36.076Z	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
2024-03-28T20:02:13.6424000Z     logger.go:146: 2024-03-28T20:00:37.191Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6424560Z     logger.go:146: 2024-03-28T20:00:37.191Z	INFO	persisted to disk	{"blocks": 0, "keys": 127, "headerHeight": 0, "blockHeight": 0, "took": "111.875µs"}
2024-03-28T20:02:13.6424990Z     logger.go:146: 2024-03-28T20:00:38.295Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6425420Z     logger.go:146: 2024-03-28T20:00:39.385Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6425840Z     logger.go:146: 2024-03-28T20:00:40.522Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6426270Z     logger.go:146: 2024-03-28T20:00:41.525Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6426690Z     logger.go:146: 2024-03-28T20:00:42.501Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6427110Z     logger.go:146: 2024-03-28T20:00:43.491Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6427580Z     logger.go:146: 2024-03-28T20:00:44.385Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6428320Z     logger.go:146: 2024-03-28T20:00:44.823Z	ERROR	Error encountered with rpc request	{"code": -32603, "cause": "websocket users limit reached", "method": "", "params": "[]"}
2024-03-28T20:02:13.6428770Z     logger.go:146: 2024-03-28T20:00:45.188Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6429190Z     logger.go:146: 2024-03-28T20:00:45.603Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6429610Z     logger.go:146: 2024-03-28T20:00:45.959Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6430030Z     logger.go:146: 2024-03-28T20:00:46.343Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6430450Z     logger.go:146: 2024-03-28T20:00:46.834Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6430870Z     logger.go:146: 2024-03-28T20:00:47.265Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6431290Z     logger.go:146: 2024-03-28T20:00:47.647Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6431710Z     logger.go:146: 2024-03-28T20:00:48.261Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-03-28T20:02:13.6432100Z     logger.go:146: 2024-03-28T20:00:48.463Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:50978"}
2024-03-28T20:02:13.6432190Z === RUN   TestWSClientsLimit/disabled
2024-03-28T20:02:13.6432750Z     logger.go:146: 2024-03-28T20:00:48.465Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-03-28T20:02:13.6433430Z     logger.go:146: 2024-03-28T20:00:48.465Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-03-28T20:02:13.6433930Z     logger.go:146: 2024-03-28T20:00:48.465Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-03-28T20:02:13.6434500Z     logger.go:146: 2024-03-28T20:00:48.465Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-03-28T20:02:13.6435080Z     logger.go:146: 2024-03-28T20:00:48.465Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-03-28T20:02:13.6435700Z     logger.go:146: 2024-03-28T20:00:48.465Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2024-03-28T20:02:13.6436070Z     logger.go:146: 2024-03-28T20:00:48.467Z	INFO	no storage version found! creating genesis block
2024-03-28T20:02:13.6436600Z     logger.go:146: 2024-03-28T20:00:48.721Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2024-03-28T20:02:13.6437110Z     logger.go:146: 2024-03-28T20:00:48.721Z	INFO	SessionPoolSize is not set or wrong, setting default value	{"SessionPoolSize": 20}
2024-03-28T20:02:13.6437680Z     logger.go:146: 2024-03-28T20:00:48.721Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2024-03-28T20:02:13.6438220Z     logger.go:146: 2024-03-28T20:00:48.721Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-03-28T20:02:13.6438720Z     logger.go:146: 2024-03-28T20:00:48.721Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2024-03-28T20:02:13.6439280Z     logger.go:146: 2024-03-28T20:00:48.721Z	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
2024-03-28T20:02:13.6439850Z     logger.go:146: 2024-03-28T20:00:48.721Z	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
2024-03-28T20:02:13.6440270Z     logger.go:146: 2024-03-28T20:00:48.721Z	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
2024-03-28T20:02:13.6441020Z     logger.go:146: 2024-03-28T20:00:49.113Z	ERROR	Error encountered with rpc request	{"code": -32603, "cause": "websocket users limit reached", "method": "", "params": "[]"}
2024-03-28T20:02:13.6441430Z     logger.go:146: 2024-03-28T20:00:49.455Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:50989"}
2024-03-28T20:02:13.6442010Z     logger.go:146: 2024-03-28T20:00:49.455Z	INFO	persisted to disk	{"blocks": 0, "keys": 127, "headerHeight": 0, "blockHeight": 0, "took": "110.125µs"}
2024-03-28T20:02:13.6442120Z --- FAIL: TestWSClientsLimit (76.09s)
2024-03-28T20:02:13.6442290Z     --- FAIL: TestWSClientsLimit/default (62.70s)
2024-03-28T20:02:13.6442440Z     --- PASS: TestWSClientsLimit/8 (12.39s)
2024-03-28T20:02:13.6442610Z     --- PASS: TestWSClientsLimit/disabled (0.99s)
```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3379

### CODE REVIEW

File: pkg/services/rpcsrv/subscription_test.go [hunk 1]
```diff
@@ -575,39 +576,53 @@ func doSomeWSRequest(t *testing.T, ws *websocket.Conn) {
...
-		} else if limit < 0 {
-			effectiveClients = 0
-		}
 		t.Run(tname, func(t *testing.T) {
+			effectiveClients := limit
+			if limit == 0 {
+				effectiveClients = defaultMaxWebSocketClients
+			} else if limit < 0 {
+				effectiveClients = 0
+			}
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:585]: Useless change.

File: pkg/services/rpcsrv/subscription_test.go [hunk 2]
```diff
@@ -575,39 +576,53 @@ func doSomeWSRequest(t *testing.T, ws *websocket.Conn) {
...
 			url := "ws" + strings.TrimPrefix(httpSrv.URL, "http") + "/ws"
-			wss := make([]*websocket.Conn, effectiveClients)
-
-			for i := 0; i < len(wss)+1; i++ {
-				ws, r, err := dialer.Dial(url, nil)
-				if r != nil && r.Body != nil {
-					defer r.Body.Close()
-				}
-				if i < effectiveClients {
+			wss := make([]*websocket.Conn, 0, effectiveClients)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:592]: Useless change.

File: pkg/services/rpcsrv/subscription_test.go [hunk 3]
```diff
@@ -575,39 +576,53 @@ func doSomeWSRequest(t *testing.T, ws *websocket.Conn) {
...
+			var mu sync.Mutex // To safely append to wss slice
+			var wg sync.WaitGroup
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:594]: Mutex not needed, you have indexes, use them instead of `append`.

File: pkg/services/rpcsrv/subscription_test.go [hunk 4]
```diff
@@ -575,39 +576,53 @@ func doSomeWSRequest(t *testing.T, ws *websocket.Conn) {
...
+					if r != nil {
+						defer r.Body.Close()
+					}
 					require.NoError(t, err)
-					wss[i] = ws
-					// Check that it's completely ready.
-					doSomeWSRequest(t, ws)
-				} else {
-					require.Error(t, err)
-				}
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:605]: Make request for these connections.

File: pkg/services/rpcsrv/subscription_test.go [hunk 5]
```diff
@@ -575,39 +576,53 @@ func doSomeWSRequest(t *testing.T, ws *websocket.Conn) {
...
+					mu.Lock()
+					wss = append(wss, ws)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:607]: Use index-based assignment instead of append.

File: pkg/services/rpcsrv/subscription_test.go [hunk 6]
```diff
@@ -575,39 +576,53 @@ func doSomeWSRequest(t *testing.T, ws *websocket.Conn) {
...
 			}
+
+			wg.Wait() // Wait for all successful connections
+
+			// Attempt one more connection, which should fail
+			_, r, err := dialer.Dial(url, nil)
+			require.Error(t, err, "The connection beyond the limit should fail")
+			if r != nil {
+				r.Body.Close()
+			}
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:619]: It's always nil for failing connection, isn't it? Check it.

**Review by AnnaShaleva — COMMENTED** [review]
Description of failure reason should to be added to the commit. Only "default" test case is failing, because default number of connections is 64 (quite large for slow runners). The failure reason is:
    * given ~1 second for [dealing + request] per connection (time is taken from the test log)
    * by the moment 65-th connection is reached, some connections from the start of the test have died due to inactivity (this process literally takes 1 minute)

File: pkg/services/rpcsrv/subscription_test.go (hunk 6 above)
Comment (AliceInHunterland) [reply pkg/services/rpcsrv/subscription_test.go:619]: no, response is:
`&http.Response{Status:"500 Internal Server Error", StatusCode:500, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Length":[]string{"118"}, "Content-Type":[]string{"application/json; charset=utf-8"}, "Date":[]string{"Tue, 02 Apr 2024 12:04:43 GMT"}}, Body:io.nopCloserWriterTo{Reader:(*bytes.Reader)(0x140002bfa70)}, ContentLength:118, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0x140007a0200), TLS:(*tls.ConnectionState)(nil)}`

Comment (AnnaShaleva) [reply pkg/services/rpcsrv/subscription_test.go:619]: OK.

File: pkg/services/rpcsrv/subscription_test.go [hunk 7]
```diff
@@ -582,25 +583,38 @@ func TestWSClientsLimit(t *testing.T) {
...
+						defer r.Body.Close()
+					}
 					require.NoError(t, err)
 					wss[i] = ws
-					// Check that it's completely ready.
 					doSomeWSRequest(t, ws)
-				} else {
-					require.Error(t, err)
-				}
+				}(i)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:601]: Oh-oh. https://go.dev/blog/loopvar-preview

**Review by AnnaShaleva — COMMENTED** [review]
Otherwise LGTM.

File: pkg/services/rpcsrv/subscription_test.go [hunk 8]
```diff
@@ -582,25 +583,38 @@ func TestWSClientsLimit(t *testing.T) {
...
-				if r != nil && r.Body != nil {
-					defer r.Body.Close()
-				}
-				if i < effectiveClients {
+			var wg sync.WaitGroup
+
+			// Dial effectiveClients connections in parallel
+			for i := 0; i < effectiveClients; i++ {
+				wg.Add(1)
+				i := i
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:591]: Let's just make `j := i` here...

File: pkg/services/rpcsrv/subscription_test.go [hunk 9]
```diff
@@ -582,25 +583,38 @@ func TestWSClientsLimit(t *testing.T) {
...
+				go func(i int) {
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:592]: ... remove argument here...

File: pkg/services/rpcsrv/subscription_test.go [hunk 10]
```diff
@@ -582,25 +583,38 @@ func TestWSClientsLimit(t *testing.T) {
...
+					defer wg.Done()
+					ws, r, err := dialer.Dial(url, nil)
+					if r != nil {
+						defer r.Body.Close()
+					}
 					require.NoError(t, err)
 					wss[i] = ws
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:599]: ... and use `wss[j] = ws` here directly.

File: pkg/services/rpcsrv/subscription_test.go [hunk 11]
```diff
@@ -582,25 +583,38 @@ func TestWSClientsLimit(t *testing.T) {
...
-					// Check that it's completely ready.
 					doSomeWSRequest(t, ws)
-				} else {
-					require.Error(t, err)
-				}
+				}(i)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:601]: Argument can also be removed.

File: pkg/services/rpcsrv/subscription_test.go (hunk 7 above)
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/subscription_test.go:601]: I've tried it locally, and actually it will work properly when you pass `i` as an argument. But for direct loopvar usage in function - it won't.

**Review by AnnaShaleva — APPROVED** [review]
Waiting for the tests to finish.

**Comment by AnnaShaleva** [comment]
Still not fast enough for connections to be alive for the default case of 64+1 connections. Some of them are start to die after 5 seconds of test:
```
2024-04-03T14:06:22.5504034Z === RUN   TestWSClientsLimit
2024-04-03T14:06:22.5504142Z === RUN   TestWSClientsLimit/default
2024-04-03T14:06:22.5504868Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-04-03T14:06:22.5505730Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-04-03T14:06:22.5506373Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-04-03T14:06:22.5507094Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-04-03T14:06:22.5507843Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-04-03T14:06:22.5508644Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2024-04-03T14:06:22.5509114Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	no storage version found! creating genesis block
2024-04-03T14:06:22.5509788Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2024-04-03T14:06:22.5510476Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	SessionPoolSize is not set or wrong, setting default value	{"SessionPoolSize": 20}
2024-04-03T14:06:22.5511258Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2024-04-03T14:06:22.5511951Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-04-03T14:06:22.5512598Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2024-04-03T14:06:22.5513316Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
2024-04-03T14:06:22.5514060Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
2024-04-03T14:06:22.5514755Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2024-04-03T14:06:22.5515215Z     logger.go:146: 2024-04-03T14:04:30.637Z	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
2024-04-03T14:06:22.5515874Z     logger.go:146: 2024-04-03T14:04:31.200Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5516442Z     logger.go:146: 2024-04-03T14:04:31.200Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5516973Z     logger.go:146: 2024-04-03T14:04:31.226Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5517502Z     logger.go:146: 2024-04-03T14:04:31.388Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5518027Z     logger.go:146: 2024-04-03T14:04:31.398Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5518551Z     logger.go:146: 2024-04-03T14:04:31.420Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5519082Z     logger.go:146: 2024-04-03T14:04:31.577Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5519606Z     logger.go:146: 2024-04-03T14:04:31.587Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5520133Z     logger.go:146: 2024-04-03T14:04:31.624Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5520850Z     logger.go:146: 2024-04-03T14:04:31.780Z	INFO	persisted to disk	{"blocks": 0, "keys": 127, "headerHeight": 0, "blockHeight": 0, "took": "121.8µs"}
2024-04-03T14:06:22.5521398Z     logger.go:146: 2024-04-03T14:04:31.780Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5521925Z     logger.go:146: 2024-04-03T14:04:31.812Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5522452Z     logger.go:146: 2024-04-03T14:04:31.969Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5522975Z     logger.go:146: 2024-04-03T14:04:32.016Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5523507Z     logger.go:146: 2024-04-03T14:04:32.172Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5524033Z     logger.go:146: 2024-04-03T14:04:32.219Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5524555Z     logger.go:146: 2024-04-03T14:04:32.273Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5525081Z     logger.go:146: 2024-04-03T14:04:32.376Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5525604Z     logger.go:146: 2024-04-03T14:04:32.423Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5526131Z     logger.go:146: 2024-04-03T14:04:32.563Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5526691Z     logger.go:146: 2024-04-03T14:04:32.627Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5527254Z     logger.go:146: 2024-04-03T14:04:32.767Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5527777Z     logger.go:146: 2024-04-03T14:04:32.830Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5528304Z     logger.go:146: 2024-04-03T14:04:32.955Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5528824Z     logger.go:146: 2024-04-03T14:04:33.033Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5529352Z     logger.go:146: 2024-04-03T14:04:33.158Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5529871Z     logger.go:146: 2024-04-03T14:04:33.237Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5530395Z     logger.go:146: 2024-04-03T14:04:33.322Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5530921Z     logger.go:146: 2024-04-03T14:04:33.348Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5531472Z     logger.go:146: 2024-04-03T14:04:33.444Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5532031Z     logger.go:146: 2024-04-03T14:04:33.535Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5532555Z     logger.go:146: 2024-04-03T14:04:33.645Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5533084Z     logger.go:146: 2024-04-03T14:04:33.724Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5533604Z     logger.go:146: 2024-04-03T14:04:33.848Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5534132Z     logger.go:146: 2024-04-03T14:04:33.926Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5534662Z     logger.go:146: 2024-04-03T14:04:34.036Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5535190Z     logger.go:146: 2024-04-03T14:04:34.130Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5535712Z     logger.go:146: 2024-04-03T14:04:34.224Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5536231Z     logger.go:146: 2024-04-03T14:04:34.318Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5536758Z     logger.go:146: 2024-04-03T14:04:34.413Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5537277Z     logger.go:146: 2024-04-03T14:04:34.423Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5537805Z     logger.go:146: 2024-04-03T14:04:34.423Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5538329Z     logger.go:146: 2024-04-03T14:04:34.523Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5538855Z     logger.go:146: 2024-04-03T14:04:34.602Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5539382Z     logger.go:146: 2024-04-03T14:04:34.612Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5539908Z     logger.go:146: 2024-04-03T14:04:34.712Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5540431Z     logger.go:146: 2024-04-03T14:04:34.805Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5540956Z     logger.go:146: 2024-04-03T14:04:34.915Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5541515Z     logger.go:146: 2024-04-03T14:04:34.993Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5542070Z     logger.go:146: 2024-04-03T14:04:35.118Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5542599Z     logger.go:146: 2024-04-03T14:04:35.181Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5543125Z     logger.go:146: 2024-04-03T14:04:35.307Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5543650Z     logger.go:146: 2024-04-03T14:04:35.385Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5544169Z     logger.go:146: 2024-04-03T14:04:35.426Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5544695Z     logger.go:146: 2024-04-03T14:04:35.510Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5545262Z     logger.go:146: 2024-04-03T14:04:35.589Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5545839Z     logger.go:146: 2024-04-03T14:04:35.698Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5546421Z     logger.go:146: 2024-04-03T14:04:35.777Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5547045Z     logger.go:146: 2024-04-03T14:04:35.902Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5547593Z     logger.go:146: 2024-04-03T14:04:35.980Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-04-03T14:06:22.5551421Z     subscription_test.go:620: 
2024-04-03T14:06:22.5551977Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:620
2024-04-03T14:06:22.5552611Z         	            				C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/asm_amd64.s:1695
2024-04-03T14:06:22.5552821Z         	Error:      	Received unexpected error:
2024-04-03T14:06:22.5553328Z         	            	read tcp 127.0.0.1:51969->127.0.0.1:51909: i/o timeout
2024-04-03T14:06:22.5553535Z         	Test:       	TestWSClientsLimit/default
2024-04-03T14:06:22.5553676Z     subscription_test.go:620: 
2024-04-03T14:06:22.5554223Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:620
2024-04-03T14:06:22.5554831Z         	            				C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/asm_amd64.s:1695
2024-04-03T14:06:22.5555036Z         	Error:      	Received unexpected error:
2024-04-03T14:06:22.5555521Z         	            	read tcp 127.0.0.1:51970->127.0.0.1:51909: i/o timeout
2024-04-03T14:06:22.5555723Z         	Test:       	TestWSClientsLimit/default
2024-04-03T14:06:22.5555860Z     subscription_test.go:620: 
2024-04-03T14:06:22.5556336Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:620
2024-04-03T14:06:22.5556953Z         	            				C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/asm_amd64.s:1695
2024-04-03T14:06:22.5557160Z         	Error:      	Received unexpected error:
2024-04-03T14:06:22.5557636Z         	            	read tcp 127.0.0.1:51973->127.0.0.1:51909: i/o timeout
2024-04-03T14:06:22.5557831Z         	Test:       	TestWSClientsLimit/default
2024-04-03T14:06:22.5557967Z     subscription_test.go:620: 
2024-04-03T14:06:22.5558437Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:620
2024-04-03T14:06:22.5559028Z         	            				C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/asm_amd64.s:1695
2024-04-03T14:06:22.5559229Z         	Error:      	Received unexpected error:
2024-04-03T14:06:22.5559696Z         	            	read tcp 127.0.0.1:51971->127.0.0.1:51909: i/o timeout
2024-04-03T14:06:22.5559891Z         	Test:       	TestWSClientsLimit/default
2024-04-03T14:06:22.5560024Z     subscription_test.go:620: 
2024-04-03T14:06:22.5560490Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:620
2024-04-03T14:06:22.5561142Z         	            				C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/asm_amd64.s:1695
2024-04-03T14:06:22.5561371Z         	Error:      	Received unexpected error:
2024-04-03T14:06:22.5561849Z         	            	read tcp 127.0.0.1:51972->127.0.0.1:51909: i/o timeout
2024-04-03T14:06:22.5562043Z         	Test:       	TestWSClientsLimit/default
2024-04-03T14:06:22.5562179Z     subscription_test.go:630: 
2024-04-03T14:06:22.5562638Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:630
2024-04-03T14:06:22.5562879Z         	Error:      	An error is expected but got nil.
2024-04-03T14:06:22.5563073Z         	Test:       	TestWSClientsLimit/default
2024-04-03T14:06:22.5563361Z         	Messages:   	The connection beyond the limit should fail
2024-04-03T14:06:22.5563886Z     logger.go:146: 2024-04-03T14:04:36.481Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:51908"}
```

File: pkg/services/rpcsrv/subscription_test.go [hunk 12]
```diff
@@ -601,28 +602,40 @@ func TestWSClientsLimit(t *testing.T) {
 				cfg.ApplicationConfiguration.RPC.MaxWebSocketClients = limit
 			})
 
-			dialer := websocket.Dialer{HandshakeTimeout: 5 * time.Second}
+			dialer := websocket.Dialer{HandshakeTimeout: 10 * time.Second}
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/subscription_test.go:605]: Move it to a separate commit, attach the latest failing log. We need a reason for every change.

Comment (AnnaShaleva) [reply pkg/services/rpcsrv/subscription_test.go:605]: Let's firstly see if it solves the problem.

Comment (AliceInHunterland) [reply pkg/services/rpcsrv/subscription_test.go:605]: waiting for tests, in case 10s isn't enough.

**Comment by AliceInHunterland** [comment]
@AnnaShaleva got the same problem here https://github.com/nspcc-dev/neo-go/pull/3392#issuecomment-2031590403

**Review by AnnaShaleva — APPROVED** [review]
