### PR TITLE
cli: increase NeoFS pool deadlines for upload-bin command

### LINKED ISSUE #3620: BlockUploader fails due to timeouts
## Current Behavior
```
Oct 17 10:57:34 kaede systemd[1]: Stopped neogo-block-fetcher-testnet.service - NeoGo Block Fetcher testnet.
Oct 17 10:57:34 kaede systemd[1]: Started neogo-block-fetcher-testnet.service - NeoGo Block Fetcher testnet.
Oct 17 10:57:35 kaede neogo-block-fetcher[2991350]: Chain block height: 4816438
Oct 17 10:58:11 kaede neogo-block-fetcher[2991350]: failed to fetch the latest missing block index from container: search of index files failed for batch with indexes from 4820000 to 4830000: error during object IDs iteration: context deadline exceeded
Oct 17 10:58:11 kaede systemd[1]: neogo-block-fetcher-testnet.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 10:58:11 kaede systemd[1]: neogo-block-fetcher-testnet.service: Failed with result 'exit-code'.
```

And also https://github.com/nspcc-dev/neo-go/pull/3582#discussion_r1782183181 and https://github.com/nspcc-dev/neo-go/pull/3582#discussion_r1792899198

## Expected Behavior

Timeouts themselves are quite native, but they break the application and seamless script work is impossible due to timeouts. They must be customizable and we should now where exactly they happen to be able to increase them.

## Possible Solution

Find the reason. Increase timeout or move it to the command setting.

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3620

### CODE REVIEW

File: cli/util/uploader.go [hunk 1]
```diff
@@ -51,6 +51,12 @@ const (
 	maxBackoff = 10 * time.Second
 )
 
+// Constants related to NeoFS pool request timeouts.
+const (
+	defaultDialTimeout   = 10 * time.Minute
+	defaultStreamTimeout = 10 * time.Minute
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:57]: It would be nice to have a comment in the code why do we need such large timeouts.

File: cli/util/uploader.go [hunk 2]
```diff
@@ -82,7 +88,11 @@ func uploadBin(ctx *cli.Context) error {
 	fmt.Fprintln(ctx.App.Writer, "Chain block height:", currentBlockHeight)
 
 	signer := user.NewAutoIDSignerRFC6979(acc.PrivateKey().PrivateKey)
-	p, err := pool.New(pool.NewFlatNodeParams(rpcNeoFS), signer, pool.DefaultOptions())
+
+	params := pool.DefaultOptions()
+	params.SetNodeDialTimeout(defaultDialTimeout)
+	params.SetNodeStreamTimeout(defaultStreamTimeout)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:94]: I still think that the one who must be blamed is the stream timeout because search operation holds underlying stream open for a long time. Let's change dial timeout to 1 minute and also set `NodeRequestTimeout` to 1 minute. I'm OK with NodeStreamTimeout of 10 minutes. Let's see if these new values are OK.

**Comment by AnnaShaleva** [comment]
Have you tried to upload with the updated timeouts? Was uploading operation interrupted by timeout?

**Comment by AliceInHunterland** [comment]
Currently, the NeoFS mainnet is responding slowly or not responding at all. The pool is failing with timeouts. On the testnet, the default values have been sufficient and are still working fine. Even though testnet hardware is quite limited and should be much slower than the mainnet, it is hard to adjust the parameters accurately at this point. I tried changing both The Stream and Dual timeout settings. Only with larger values for both was the uploader able to upload a few batches, but it took a couple of hours, which is unacceptable. Now, the uploader can't even get a response from the search request. Our side is functioning as expected, but something has gone wrong on the NeoFS side.

**Comment by AliceInHunterland** [comment]
just in case -s 60s should be provided for increasing neo-go timeout too

` ./bin/neo-go util upload-bin --cid HmP48JvCcmiEbJemG7jFNEg2qkdCTx4thD3EwWUi288Q --wallet-config ./wallet-config.yml --block-attribute block --index-attribute index --rpc-endpoint https://rpc.t5.n3.nspcc.ru:20331 -fsr st1.storage.fs.neo.org:8080 -fsr st2.storage.fs.neo.org:8080 -fsr st3.storage.fs.neo.org:8080 -fsr st4.storage.fs.neo.org:8080 -s 60s`

**Comment by AnnaShaleva** [comment]
> for increasing neo-go timeout too

RPC client timeout doesn't affect ordinary RPC requests, AFAIK.

**Review by AnnaShaleva — APPROVED** [review]

**Comment by AnnaShaleva** [comment]
> RPC client timeout doesn't affect ordinary RPC requests, AFAIK.

My bad, of course it does, I just missed that line in code.
