### PR TITLE
Reword some error messages

### LINKED ISSUE #2197: Make notary balance error more descriptive
`Block or transaction validation failed. (-504) - invalid transaction due to conflicts with the memory pool - %!s(<nil>)` error message appears [when](https://github.com/nspcc-dev/neo-go/blob/v0.97.3-pre/pkg/core/mempool/mem_pool.go#L25) "Sender doesn't have enough GAS to pay for all transactions in the pool". But it is not clear that the problem is related to balances when reading such error text. Also `%!s(<nil>)` wrapping is confusing.

### PR DESCRIPTION
**Pull request by fyrchik**
Fix #2197.

### CODE REVIEW

File: pkg/core/mempool/mem_pool.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ var (
 	// ErrConflict is returned when transaction being added is incompatible
 	// with the contents of the memory pool (Sender doesn't have enough GAS
 	// to pay for all transactions in the pool).
-	ErrConflict = errors.New("conflicts with the memory pool")
+	ErrConflict = errors.New("conflicts with memory pool: sender has insufficient funds to pay fee for all pool transactions")
```
Comment (roman-khimov) [inline pkg/core/mempool/mem_pool.go:25]: Seem to be too long. "conflict: insufficient funds for all pooled tx"?

**Review by roman-khimov — APPROVED** [review]
