### PR TITLE
Fix golint 213

### LINKED ISSUE #213: CI/CD: Golint fix
Golint currently asks for all exported methods to be commented or it will fail. However, this is kind of silly for methods like `New()` as the comment will always be in region of "New creates a X object" which doesn't give any new information about the struct, that could not be implied from the name

### PR DESCRIPTION
**Pull request by roman-khimov**
Make our build green again! Fixes #213.

### CODE REVIEW

File: pkg/rpc/rpc.go [hunk 1]
```diff
@@ -10,9 +10,9 @@ import (
 	"github.com/pkg/errors"
 )
 
-// GetBlock returns a block by its hash or index/height. If verbose is true
+// getBlock returns a block by its hash or index/height. If verbose is true
 // the response will contain a pretty Block object instead of the raw hex string.
-func (c *Client) GetBlock(indexOrHash interface{}, verbose bool) (*response, error) {
+func (c *Client) getBlock(indexOrHash interface{}, verbose bool) (*response, error) {
```
Comment (golangcibot) [inline pkg/rpc/rpc.go]: U1000: func `(*Client).getBlock` is unused (from `unused`)

File: pkg/rpc/rpc.go [hunk 2]
```diff
@@ -78,8 +78,8 @@ func (c *Client) Invoke(script string, params []smartcontract.Parameter) (*Invok
 	return resp, nil
 }
 
-// GetRawTransaction queries a transaction by hash.
-func (c *Client) GetRawTransaction(hash string, verbose bool) (*response, error) {
+// getRawTransaction queries a transaction by hash.
+func (c *Client) getRawTransaction(hash string, verbose bool) (*response, error) {
```
Comment (golangcibot) [inline pkg/rpc/rpc.go]: U1000: func `(*Client).getRawTransaction` is unused (from `unused`)

**Comment by roman-khimov** [comment]
Codecov is showing something really strange here with its 2.63% as there are no real code changes here.

**Comment by volekerb** [comment]
nice nice! =)
