### PR TITLE
compiler: properly process `defer` in conditional statements

### LINKED ISSUE #2293: Conditional defers don't work
This test case:
```
package foo

var a int

func Main() int {
	return h() + a
}
func h() int {
	if false {
		defer func() {
			if r := recover(); r != nil {
				a = 3
			} else {
				a = 4
			}
		}()
	}
	a = 1
	return a
}
```
Will fail
```
                Error:          Received unexpected error:
                                at instruction 30 (ENDTRY): runtime error: index out of range [-1]
```
And it can't be solved without `defer` code generation restructuring, `ENDTRY` is emitted irrespective of whether we entered `TRY` context or not.

### PR DESCRIPTION
**Pull request by fyrchik**
Close #2293 .

Signed-off-by: Evgeniy Stratonikov <evgeniy@nspcc.ru>

### CODE REVIEW

File: pkg/vm/vm.go [hunk 1]
```diff
@@ -1594,6 +1594,9 @@ func (v *VM) call(ctx *Context, offset int) {
 	newCtx.retCount = -1
 	newCtx.local = nil
 	newCtx.arguments = nil
+	// If memory for `elems` is reused, we can end up
+	// with incorrect exception context state in the caller.
+	newCtx.tryStack.elems = nil
```
Comment (roman-khimov) [inline pkg/vm/vm.go:1599]: Deserves commit of its own.

**Comment by AnnaShaleva** [comment]
@fyrchik, could you, please, fetch the current master and rebase this PR on it? I'd like to see whether our coverage job works properly.

**Review by roman-khimov — APPROVED** [review]

**Review by AnnaShaleva — APPROVED** [review]
