### PR TITLE
Various verification fixes 2

### LINKED ISSUE #295: Proper instruction handling in CompileAndInspect()
`CompileAndInspect()` has some special treatment for `PUSHBYTES*` and `JMP*/CALL` (after #292) instructions, but it actually still is wrong when dealing with `PUSHDATA*`, `SYSCALL`, `APPCALL`, `TAILCALL` and `CALL_*` instructions as all of these have some additional data (of fixed or variable length).

While at it it would also be nice to improve output for these cases, not outputting new strings for parameters, but displaying them in the description field of the respective instruction.

### PR DESCRIPTION
**Pull request by roman-khimov**
This focuses on VM improvements necessary to make tx verification work. It's mostly related to interop functionality, but doesn't add interops at the moment (I want to add more of them before the first push). Fixes #295 along the way.

### CODE REVIEW

File: pkg/core/blockchain.go [hunk 1]
```diff
@@ -1045,14 +1045,17 @@ func (bc *Blockchain) VerifyWitnesses(t *transaction.Transaction) error {
 		if vm.HasFailed() {
 			return errors.Errorf("vm failed to execute the script")
 		}
-		res := vm.PopResult()
-		switch res.(type) {
-		case bool:
-			if !(res.(bool)) {
+		resel := vm.Estack().Pop()
```
Comment (volekerb) [inline pkg/core/blockchain.go]: nit: resel -- is result element?

Comment (roman-khimov) [reply pkg/core/blockchain.go]: Ugh. `resEl`, yeah.

File: pkg/vm/stack_item.go [hunk 2]
```diff
@@ -248,3 +248,30 @@ func toMapKey(key StackItem) interface{} {
 		panic("wrong key type")
 	}
 }
+
+// InteropItem represents interop data on the stack.
+type InteropItem struct {
+	value interface{}
+}
+
+// NewInteropItem returns an new InteropItem object.
```
Comment (volekerb) [inline pkg/vm/stack_item.go]: nit: a new

Comment (volekerb) [reply pkg/vm/stack_item.go]: or just 'new'

File: pkg/vm/stack_item.go [hunk 3]
```diff
@@ -248,3 +248,30 @@ func toMapKey(key StackItem) interface{} {
...
+}
+
+// Value implements StackItem interface.
+func (i *InteropItem) Value() interface{} {
+	return i.value
+}
+
+// String implements stringer interface.
+func (i *InteropItem) String() string {
+	return "InteropItem"
```
Comment (volekerb) [inline pkg/vm/stack_item.go]: don't we want to add value itself for string representation?

File: pkg/vm/vm.go [hunk 4]
```diff
@@ -80,6 +80,15 @@ func (v *VM) RegisterInteropFunc(name string, f InteropFunc, price int) {
 	v.interop[name] = InteropFuncPrice{f, price}
 }
 
+// RegisterInteropFuncs will register all interop functions passed in a map in
+// the VM. Effectively it's a batched version of RegisterInteropFunc.
+func (v *VM) RegisterInteropFuncs(interops map[string]InteropFuncPrice) {
+	// We allow reregistration here.
+	for name, funprice := range interops {
```
Comment (volekerb) [inline pkg/vm/vm.go]: nit:btw it's not a big problem for me =)
funprice -> funPrice ?

File: pkg/core/blockchain.go [hunk 5]
```diff
@@ -643,6 +647,33 @@ func getAssetStateFromStore(s storage.Store, assetID util.Uint256) *AssetState {
...
+		cs = getContractStateFromStore(bc.Store, hash)
+	}
+	return cs
+}
+
+// getContractStateFromStore returns contract state as recorded in the given
+// store by the given script hash.
+func getContractStateFromStore(s storage.Store, hash util.Uint160) *ContractState {
+	key := storage.AppendPrefix(storage.STContract, hash.Bytes())
+	contractbytes, err := s.Get(key)
```
Comment (volekerb) [inline pkg/core/blockchain.go]: nit: contractBytes

File: pkg/core/contract_state.go [hunk 6]
```diff
@@ -21,3 +27,69 @@ type ContractState struct {
...
+		b.Put(key, buf.Bytes())
+		buf.Reset()
+	}
+	return nil
+}
+
+// DecodeBinary implements Serializable interface.
+func (a *ContractState) DecodeBinary(br *io.BinReader) {
+	a.Script = br.ReadBytes()
+	parambytes := br.ReadBytes()
```
Comment (volekerb) [inline pkg/core/contract_state.go]: nit: paramBytes

File: pkg/core/contract_state.go [hunk 7]
```diff
@@ -21,3 +27,69 @@ type ContractState struct {
...
+	a.ParamList = make([]smartcontract.ParamType, len(parambytes))
```
Comment (volekerb) [inline pkg/core/contract_state.go]: nit: smartContract or just sc?

File: pkg/core/contract_state_test.go [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+	"github.com/CityOfZion/neo-go/pkg/smartcontract"
+	"github.com/stretchr/testify/assert"
+)
+
+func TestEncodeDecodeContractState(t *testing.T) {
+	script := []byte("testscript")
+
+	contract := &ContractState{
+		Script:           script,
+		ParamList:        []smartcontract.ParamType{smartcontract.StringType, smartcontract.IntegerType, smartcontract.Hash160Type},
```
Comment (volekerb) [inline pkg/core/contract_state_test.go]: nit: same with smartcontract

File: pkg/vm/vm.go [hunk 9]
```diff
@@ -850,17 +855,17 @@ func (v *VM) execute(ctx *Context, op Instruction) {
 		}
 
 	case APPCALL, TAILCALL:
-		if len(v.scripts) == 0 {
-			panic("script table is empty")
+		if v.getScript == nil {
+			panic("no getScript callback is set up")
```
Comment (volekerb) [inline pkg/vm/vm.go]: dunno if it's planned that we have 2 diff messages:
`panic("no getScript callback is set up")`
and on line 864 869 
`panic("could not find script")`
for the same reason

File: pkg/core/contract_state_test.go (hunk 8 above)
Comment (roman-khimov) [reply pkg/core/contract_state_test.go]: And here too.

File: pkg/vm/vm.go (hunk 9 above)
Comment (roman-khimov) [reply pkg/vm/vm.go]: These are different! In the second case you do have the callback, but it can't find the script to call.

File: pkg/core/contract_state.go (hunk 7 above)
Comment (volekerb) [reply pkg/core/contract_state.go]: true true

File: pkg/vm/vm.go (hunk 9 above)
Comment (volekerb) [reply pkg/vm/vm.go]: got it!
