### PR TITLE
core: add validUntilBlock field to transaction

### LINKED ISSUE #841: Add validUntilBlock to Transaction
With the same semantics as in C# in that transactions should fail verification if current blockchain height is more than validUntilBlock.

### PR DESCRIPTION
**Pull request by AnnaShaleva**
closes #841

### CODE REVIEW

File: pkg/core/blockchain.go [hunk 1]
```diff
@@ -1340,6 +1340,10 @@ func (bc *Blockchain) verifyHeader(currHeader, prevHeader *block.Header) error {
 
 // verifyTx verifies whether a transaction is bonafide or not.
 func (bc *Blockchain) verifyTx(t *transaction.Transaction, block *block.Block) error {
+	height := bc.BlockHeight()
+	if t.ValidUntilBlock <= height || t.ValidUntilBlock > height+transaction.MaxValidUntilBlockIncrement {
+		return errors.Errorf("transaction has been expired. ValidUntilBlock = %d should be more than current blockchain height = %d and not exceed it more than %d", t.ValidUntilBlock, height, transaction.MaxValidUntilBlockIncrement)
```
Comment (roman-khimov) [inline pkg/core/blockchain.go:1345]: `has expired` and I think its enough to tell `ValidUntilBlock: %d, current height: %d`.

File: pkg/core/util.go [hunk 2]
```diff
@@ -59,10 +59,12 @@ func createGenesisBlock(cfg config.ProtocolConfiguration) (*block.Block, error)
 	scriptOut := hash.Hash160(rawScript)
 
 	minerTx := transaction.NewMinerTXWithNonce(2083236893)
+	minerTx.ValidUntilBlock = 1
```
Comment (roman-khimov) [inline pkg/core/util.go:62]: I don't think it's a valid value for these transactions. NEO 3 genesis block transactions don't set it in any way and given our regular transaction flow they're kinda verified at height -1, because they appear in block 0, so it's OK for them to have `ValidUntilBlock == 0`.

File: pkg/rpc/client/rpc.go [hunk 3]
```diff
@@ -545,3 +558,17 @@ func (c *Client) ValidateAddress(address string) error {
...
 }
+
+// CalculateValidUntilBlock calculates ValidUntilBlock field for tx.
+func (c *Client) CalculateValidUntilBlock() (uint32, error) {
+	var result uint32
+	blockCount, err := c.GetBlockCount()
+	if err != nil {
+		return result, errors.Wrapf(err, "cannot get block count")
+	}
+	validators, err := c.GetValidators()
```
Comment (roman-khimov) [inline pkg/rpc/client/rpc.go:569]: I fear this is quite an expensive call, doing it often may be a bit problematic, so it either should be cached (for some block number) or substituted with `len(standbyvalidators)`.

Comment (AnnaShaleva) [reply pkg/rpc/client/rpc.go:569]: However, we don't have `standbyvalidators` here as there's no such RPC-call

Comment (roman-khimov) [reply pkg/rpc/client/rpc.go:569]: I'd thought about config file, but I guess for RPC client even that might be unavailable, so let's cache this call (its results don't change very often) for some 100 blocks (a little less than half an hour given the default block time setting).

Comment (AnnaShaleva) [reply pkg/rpc/client/rpc.go:577]: Implemented cache like field in Client struct (see: https://github.com/nspcc-dev/neo-go/pull/856/commits/e36cd5a4d7af8fca01d23252c6072f57778a9250), but not sure that it's a good solution as every time we create new client and call GetValidators, we'll still re-send "getvalidators" request. 

I also thought about [httputil.DumpResponce(...)](https://golang.org/pkg/net/http/httputil/#DumpResponse) method, but here we have to save the dump somewhere (on disk?)

Comment (roman-khimov) [reply pkg/rpc/client/rpc.go:577]: > every time we create new client and call GetValidators, we'll still re-send "getvalidators" request.

It should be OK, think about some long-term service that operates using our client (like gorshok!), it will generate one transaction after another using the same client instance and it will benefit from this caching.

At the same time, caching whole `GetValidators` response is not something we want, it has a direct mapping to the RPC call, so when I call `GetValidators` I expect to see actual server response every time. But it's OK to define whatever semantics we want for auxiliary higher-level methods like `CalculateValidUntilBlock` (as long as this semantics is correctly explained to the user of this method). So caching should be done in this function and only for validators count (we don't care about validators list itself here).

We may change it in the future when we're to have event subscription.

Comment (AnnaShaleva) [reply pkg/rpc/client/rpc.go]: Fixed this and added annotation for caching structures in Client.

File: pkg/rpc/client/client.go [hunk 4]
```diff
@@ -40,6 +42,7 @@ type Client struct {
 	wif        *keys.WIF
 	balancerMu *sync.Mutex
 	balancer   request.BalanceGetter
+	cache      *cache
```
Comment (roman-khimov) [inline pkg/rpc/client/client.go:45]: Why a pointer? Is it initialized anywhere?

File: pkg/rpc/client/rpc.go [hunk 5]
```diff
@@ -545,3 +558,30 @@ func (c *Client) ValidateAddress(address string) error {
 	}
 	return nil
 }
+
+// CalculateValidUntilBlock calculates ValidUntilBlock field for tx using cache.
+func (c *Client) CalculateValidUntilBlock() (uint32, error) {
```
Comment (roman-khimov) [inline pkg/rpc/client/rpc.go:563]: Does it have any test?

File: pkg/rpc/client/rpc.go [hunk 6]
```diff
@@ -545,3 +558,30 @@ func (c *Client) ValidateAddress(address string) error {
 	}
 	return nil
 }
+
+// CalculateValidUntilBlock calculates ValidUntilBlock field for tx using cache.
```
Comment (roman-khimov) [inline pkg/rpc/client/rpc.go:562]: I think we should explain how it calculates this value and what's being cached.

File: pkg/rpc/client/client.go (hunk 4 above)
Comment (AnnaShaleva) [reply pkg/rpc/client/client.go]: Removed pointer, it's not necessary here.

File: pkg/rpc/client/rpc.go (hunk 5 above)
Comment (AnnaShaleva) [reply pkg/rpc/client/rpc.go:566]: Added test, but it's a bit more complicated than others.
