### PR TITLE
compiler: fix array's items swap

### LINKED ISSUE #3611: Array's items swap compiles but does not work as expected
Another hour of debug.

## Current Behavior
```go
    arr := []byte{1, 0}
    arr[0], arr[1] = arr[1], arr[0]
```
compiles ok. I want to get `{0, 1}`

## Expected Behavior
...  but i get `{0, 0}`

## Possible Solution
1. Do not allow such code
2. Make swap with the third var as it is done in many languages (e.g. go)

## Steps to Reproduce
Code from `Current Behavior`

## Context
https://github.com/nspcc-dev/neofs-contract/pull/438

## Regression
Not sure

## Your Environment
github.com/nspcc-dev/neo-go v0.106.3

### PR DESCRIPTION
**Pull request by Turalchik**
Close #3611.

### CODE REVIEW

File: pkg/compiler/codegen.go [hunk 1]
```diff
@@ -680,7 +680,16 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
 			ast.Walk(c, n.Rhs[0])
 			c.emitToken(n.Tok, c.typeOf(n.Rhs[0]))
 		}
-		for i := range n.Lhs {
+		if !isAssignOp {
+			for i := range n.Rhs {
+				ast.Walk(c, n.Rhs[i])
```
Comment (AnnaShaleva) [inline pkg/compiler/codegen.go:696]: This code will walk through `f` twice on `v, ok := f().(int)`.

File: pkg/compiler/slice_test.go [hunk 2]
```diff
@@ -338,6 +338,63 @@ var sliceTestCases = []testCase{
...
+			`,
+		[]stackitem.Item{stackitem.Make(2), stackitem.Make(10), stackitem.Make(10)},
+	},
+	{
+		"swap with side effects",
+		`func F%d() []int {
+				i = 0
+				s := []int{3, 5, 2}
+				s[2], s[0], s[1] = mdfySlice(s)[1], mdfySlice(s)[2], mdfySlice(s)[0]
+				return s
```
Comment (AnnaShaleva) [inline pkg/compiler/slice_test.go]: ?

File: pkg/compiler/struct_test.go [hunk 3]
```diff
@@ -431,6 +431,35 @@ var structTestCases = []testCase{
...
+			return t
+		}
+		func F%() *T {
+			t := &T{1, 2}
+			t.A, t.B = mdfyStruct(t).B, mdfyStruct(t).A
+			return t
+		}
+		`,
+		[]stackitem.Item{stackitem.Make(7), stackitem.Make(3)},
+	},*/
```
Comment (AnnaShaleva) [inline pkg/compiler/struct_test.go]: ?

File: pkg/compiler/codegen.go (hunk 1 above)
Comment (Turalchik) [reply pkg/compiler/codegen.go:696]: 1. Why? In this line of code https://github.com/nspcc-dev/neo-go/blob/ea1d3c76c3dd35a426aa264a3cc56c2544e92b1b/pkg/compiler/codegen.go#L667 we are not generating a script.
2. I tried to write a test like this
```golang
func TestBla(t *testing.T) {
	src := `package foo
	var i int
	func f() any {
		i++
		return i
	}
	func Main() int {
		v, ok := f().(int)
		if !ok {
			panic("unexpected panic")
        }
        return v
    }`
    eval(t, src, big.NewInt(1))
}
```
but it throws the following error: `type assertion with two return values is not supported`

File: pkg/compiler/codegen.go [hunk 4]
```diff
@@ -691,7 +691,16 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
 		if isMapKeyCheck {
 			c.emitGetMapValueWithOKFlag(n.Rhs[0])
 		}
-		for i := range n.Lhs {
+		if !isAssignOp && !isMapKeyCheck {
```
Comment (AnnaShaleva) [inline pkg/compiler/codegen.go:694]: From what we've discussed, the logic related to `isMapKeyCheck` is a separate bugfix, we need to move it to a separate commit and add a proper description of the bug and link to the original PR.

Comment (AnnaShaleva) [reply pkg/compiler/codegen.go:694]: Also, the important thing is that we need a test-case that will cover this bug.

Comment (Turalchik) [reply pkg/compiler/codegen.go:694]: I don't quite understand what bug we're talking about, the logic related to `isMapKeyCheck` puts a boolean value on a result stack first, and a value from map or zero-value on top, a multiRet logic is exactly the same, a first argument should be on top of a stack.
