### PR TITLE
core: take care of block-targeted Conflicts attributes processing

### LINKED ISSUE #3426: missing applicationlog
# Current Behavior
Can't retrieve applicationlog for 0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "error": {
        "code": -105,
        "message": "Unknown script container",
        "data": "failed to locate application log: EOF"
    }
}
```
## Expected Behavior
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockhash": "0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15",
        "executions": [
            {
                "trigger": "OnPersist",
                "vmstate": "HALT",
                "gasconsumed": "0",
                "stack": [],
                "notifications": [
                    {
                        "contract": "0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "axI92L7HGGSIUrvHhZXjU2oFj58="
                                },
                                {
                                    "type": "Integer",
                                    "value": "100000000"
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "axI92L7HGGSIUrvHhZXjU2oFj58="
                                },
                                {
                                    "type": "Integer",
                                    "value": "5200000000000000"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "trigger": "PostPersist",
                "vmstate": "HALT",
                "gasconsumed": "0",
                "stack": [],
                "notifications": [
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "lpSe1ILnxgqu7GkVUPGz1ZkUYZQ="
                                },
                                {
                                    "type": "Integer",
                                    "value": "50000000"
                                }
                            ]
                        }
                    }
                ]
            }
        ]
    }
}
```

## Possible Solution
don't know

## Steps to Reproduce
not working go-nodes
```shell
curl --location 'https://rpc10.n3.nspcc.ru:10331' \
--header 'Content-Type: text/plain' \
--data '{
  "jsonrpc": "2.0",
  "method": "getapplicationlog",
  "params": ["0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15"],
  "id": 1
}'
```

working neo-cli nodes
```shell
curl --location 'https://mainnet1.neo.coz.io:443' \
--header 'Content-Type: text/plain' \
--data '{
  "jsonrpc": "2.0",
  "method": "getapplicationlog",
  "params": ["0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15"],
  "id": 1
}'
```

### LINKED ISSUE #3427: can't request block 0 over RPC
I'm trying to request block 0 over RPC and neo-go can't provide it whereas neo-cli can.

## Current Behavior
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "error": {
        "code": -101,
        "message": "Unknown block",
        "data": "key not found"
    }
}
```

## Expected Behavior
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACI6hnvVQEAAB2sK3wAAAAAAAAAAABrEj3YvscYZIhSu8eFleNTagWPnwEAAREA"
}
```

## Steps to Reproduce
not working go node
```shell
curl --location 'https://rpc10.n3.nspcc.ru:10331' \
--header 'Content-Type: text/plain' \
--data '{
  "jsonrpc": "2.0",
  "method": "getblock",
  "params": [0],
  "id": 1
}'
```

working neo-cli node
```
curl --location 'https://mainnet1.neo.coz.io:443' \
--header 'Content-Type: text/plain' \
--data '{
  "jsonrpc": "2.0",
  "method": "getblock",
  "params": [0],
  "id": 1
}'
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #3426, close #3427.

A possible solution (the best from my POW) is implemented. The part with verification of such conflicting transactions may be discussed since I'm not quite sure it's a good solution to allow to pass verification for these transactions. We may forbid them since we have `VerifyTransactions` set to `false` in mainnet anyway.

@roman-khimov, the only question I have right now is: why our CN has successfully accepted PrepareRequest, verified the block and responded with PrepareReqponse. The node shouldn't ever accept this transaction to the mempool since `verifyTxAttributes` call should fail without e6ceee0f230a21c87006a9297636be29c0d8ea47 implemented.

### CODE REVIEW

File: pkg/core/blockchain.go [hunk 1]
```diff
@@ -1515,8 +1515,11 @@ func (bc *Blockchain) AddBlock(block *block.Block) error {
 			} else {
 				err = bc.verifyAndPoolTx(tx, mp, bc)
 			}
-			if err != nil && bc.config.VerifyTransactions {
-				return fmt.Errorf("transaction %s failed to verify: %w", tx.Hash().StringLE(), err)
+			if err != nil {
+				bc.log.Warn(fmt.Sprintf("transaction %s failed to verify, but transaction verification report is disabled: %s", tx.Hash().StringLE(), err))
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/core/blockchain.go]: Fixed.

File: pkg/core/blockchain.go [hunk 2]
```diff
@@ -1518,6 +1518,7 @@ func (bc *Blockchain) AddBlock(block *block.Block) error {
 			if err != nil && bc.config.VerifyTransactions {
 				return fmt.Errorf("transaction %s failed to verify: %w", tx.Hash().StringLE(), err)
 			}
+			bc.log.Warn(fmt.Sprintf("transaction %s failed to verify: %s", tx.Hash().StringLE(), err))
```
Comment (roman-khimov) [inline pkg/core/blockchain.go:1521]: `transaction xxx failed to verify: nil` for every transaction?

Comment (AnnaShaleva) [reply pkg/core/blockchain.go:1521]: Oh, my bad, got distracted.

Comment (AnnaShaleva) [reply pkg/core/blockchain.go]: Fixed.

**Review by roman-khimov — APPROVED** [review]
