### PR TITLE
Fix race caused by design of native Neo validators/committee cache

### LINKED ISSUE #2989: Race detected during `TestWalletClaimGas` test execution
macOS, go 1.20, firstly noticed after https://github.com/nspcc-dev/neo-go/actions/runs/4789234667/jobs/8516850530?pr=2988 run.
```
2023-04-24T17:36:40.6068980Z === RUN   TestWalletClaimGas
2023-04-24T17:36:40.6069700Z     logger.go:130: 2023-04-24T17:35:50.606Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2023-04-24T17:36:40.6070540Z     logger.go:130: 2023-04-24T17:35:50.606Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2023-04-24T17:36:40.6071180Z     logger.go:130: 2023-04-24T17:35:50.606Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2023-04-24T17:36:40.6071890Z     logger.go:130: 2023-04-24T17:35:50.607Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2023-04-24T17:36:40.6072620Z     logger.go:130: 2023-04-24T17:35:50.607Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2023-04-24T17:36:40.6073370Z     logger.go:130: 2023-04-24T17:35:50.607Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 864000}
2023-04-24T17:36:40.6074260Z     logger.go:130: 2023-04-24T17:35:50.609Z	INFO	no storage version found! creating genesis block
2023-04-24T17:36:40.6075050Z     logger.go:130: 2023-04-24T17:35:50.616Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2023-04-24T17:36:40.6075590Z     logger.go:130: 2023-04-24T17:35:50.616Z	INFO	starting rpc-server	{"endpoint": "localhost:0"}
2023-04-24T17:36:40.6076180Z === RUN   TestWalletClaimGas/missing_wallet_path
2023-04-24T17:36:40.6076700Z wallet path is mandatory and should be passed using (--wallet, -w) flags or via wallet config using --wallet-config flag
2023-04-24T17:36:40.6076870Z === RUN   TestWalletClaimGas/missing_address
2023-04-24T17:36:40.6076990Z address was not provided
2023-04-24T17:36:40.6077150Z === RUN   TestWalletClaimGas/invalid_address
2023-04-24T17:36:40.6077520Z can't find account for the address: NKuyBkoGdZZSLyPbJEetheRhMjeznFZszf
2023-04-24T17:36:40.6077690Z === RUN   TestWalletClaimGas/missing_endpoint
2023-04-24T17:36:40.6078030Z no RPC endpoint specified, use option '--rpc-endpoint' or '-r'
2023-04-24T17:36:40.6078200Z === RUN   TestWalletClaimGas/insufficient_funds
2023-04-24T17:36:40.6078330Z === NAME  TestWalletClaimGas
2023-04-24T17:36:40.6078940Z     logger.go:130: 2023-04-24T17:35:50.626Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-24T17:36:40.6079580Z     logger.go:130: 2023-04-24T17:35:50.627Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2023-04-24T17:36:40.6080150Z     logger.go:130: 2023-04-24T17:35:50.644Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-24T17:36:40.6081380Z     logger.go:130: 2023-04-24T17:35:50.645Z	DEBUG	processing rpc request	{"method": "invokescript", "params": "[CxAMFNwk6EPkEi4hj1BzCuuZPYVDDVeBDBTcJOhD5BIuIY9QcwrrmT2FQw1XgRTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I5 ]"}
2023-04-24T17:36:40.6081980Z     logger.go:130: 2023-04-24T17:35:50.648Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2023-04-24T17:36:40.6084620Z     logger.go:130: 2023-04-24T17:35:50.649Z	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[AE6iJGu0P5gAAAAAAAAAAAAAAAAAAwAAAAHcJOhD5BIuIY9QcwrrmT2FQw1XgQEAVwsQDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU3CToQ+QSLiGPUHMK65k9hUMNV4EUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQEAKAwhApd1MhCKuk+UUSF0us+LTXWT080Ozb18sexcCtOXfVMmQVbnsyc=]"}
2023-04-24T17:36:40.6084720Z EOF
2023-04-24T17:36:40.6085290Z     logger.go:130: 2023-04-24T17:35:50.653Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-24T17:36:40.6085910Z     logger.go:130: 2023-04-24T17:35:50.655Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2023-04-24T17:36:40.6086660Z     logger.go:130: 2023-04-24T17:35:50.671Z	DEBUG	processing rpc request	{"method": "getnep17balances", "params": "[56c989e76f9a2ca05bb5caa6c96f524d905accd8]"}
2023-04-24T17:36:40.6087420Z     logger.go:130: 2023-04-24T17:35:50.673Z	DEBUG	processing rpc request	{"method": "getnep17balances", "params": "[56c989e76f9a2ca05bb5caa6c96f524d905accd8]"}
2023-04-24T17:36:40.6088000Z     logger.go:130: 2023-04-24T17:35:50.675Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-24T17:36:40.6090320Z     logger.go:130: 2023-04-24T17:35:50.676Z	DEBUG	processing rpc request	{"method": "invokescript", "params": "[CwHoAwwU3CToQ+QSLiGPUHMK65k9hUMNV4EMFNjMWpBNUm/Jpsq1W6Asmm/niclWFMAfDAh0cmFuc2ZlcgwU9WPqQLwoPU0OBcSOowWz8qBzQO9BYn1bUjkLAwDodkgXAAAADBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBTPduKL0AYsSkeO41VhARMZ88+k0kFifVtSOQ== ]"}
2023-04-24T17:36:40.6090450Z ==================
2023-04-24T17:36:40.6090560Z WARNING: DATA RACE
2023-04-24T17:36:40.6090710Z Read at 0x00c0003041f0 by goroutine 2043:
2023-04-24T17:36:40.6091100Z   github.com/nspcc-dev/neo-go/pkg/core/native.copyNeoCache()
2023-04-24T17:36:40.6091640Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/native_neo.go:130 +0x184
2023-04-24T17:36:40.6092360Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*NeoCache).Copy()
2023-04-24T17:36:40.6092990Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/native_neo.go:121 +0x9d
2023-04-24T17:36:40.6093350Z   github.com/nspcc-dev/neo-go/pkg/core/dao.(*Simple).getCache()
2023-04-24T17:36:40.6093830Z       /Users/runner/work/neo-go/neo-go/pkg/core/dao/dao.go:931 +0xf6
2023-04-24T17:36:40.6094660Z   github.com/nspcc-dev/neo-go/pkg/core/dao.(*Simple).GetRWCache()
2023-04-24T17:36:40.6095140Z       /Users/runner/work/neo-go/neo-go/pkg/core/dao/dao.go:913 +0xae
2023-04-24T17:36:40.6095550Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).ModifyAccountVotes()
2023-04-24T17:36:40.6096070Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/native_neo.go:887 +0x84
2023-04-24T17:36:40.6096450Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).increaseBalance()
2023-04-24T17:36:40.6096960Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/native_neo.go:479 +0x6dc
2023-04-24T17:36:40.6097350Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).increaseBalance-fm()
2023-04-24T17:36:40.6097540Z       <autogenerated>:1 +0x93
2023-04-24T17:36:40.6097990Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*nep17TokenNative).updateAccBalance()
2023-04-24T17:36:40.6098520Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/native_nep17.go:190 +0x3a8
2023-04-24T17:36:40.6098960Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*nep17TokenNative).TransferInternal()
2023-04-24T17:36:40.6099500Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/native_nep17.go:230 +0x6e4
2023-04-24T17:36:40.6099900Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*nep17TokenNative).Transfer()
2023-04-24T17:36:40.6100420Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/native_nep17.go:118 +0x233
2023-04-24T17:36:40.6100830Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*nep17TokenNative).Transfer-fm()
2023-04-24T17:36:40.6101010Z       <autogenerated>:1 +0x6d
2023-04-24T17:36:40.6101330Z   github.com/nspcc-dev/neo-go/pkg/core/native.Call()
2023-04-24T17:36:40.6101850Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/interop.go:63 +0x15e4
2023-04-24T17:36:40.6102250Z   github.com/nspcc-dev/neo-go/pkg/core/interop.(*Context).SyscallHandler()
2023-04-24T17:36:40.6102770Z       /Users/runner/work/neo-go/neo-go/pkg/core/interop/context.go:323 +0x2ef
2023-04-24T17:36:40.6103170Z   github.com/nspcc-dev/neo-go/pkg/core/interop.(*Context).SyscallHandler-fm()
2023-04-24T17:36:40.6103350Z       <autogenerated>:1 +0x4b
2023-04-24T17:36:40.6103660Z   github.com/nspcc-dev/neo-go/pkg/vm.(*VM).execute()
2023-04-24T17:36:40.6104120Z       /Users/runner/work/neo-go/neo-go/pkg/vm/vm.go:1473 +0x1370
2023-04-24T17:36:40.6104420Z   github.com/nspcc-dev/neo-go/pkg/vm.(*VM).step()
2023-04-24T17:36:40.6104870Z       /Users/runner/work/neo-go/neo-go/pkg/vm/vm.go:472 +0x16f
2023-04-24T17:36:40.6105170Z   github.com/nspcc-dev/neo-go/pkg/vm.(*VM).Run()
2023-04-24T17:36:40.6105610Z       /Users/runner/work/neo-go/neo-go/pkg/vm/vm.go:444 +0x28f
2023-04-24T17:36:40.6106020Z   github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).runScriptInVM()
2023-04-24T17:36:40.6106550Z       /Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:2205 +0x105
2023-04-24T17:36:40.6106950Z   github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).invokescript()
2023-04-24T17:36:40.6107470Z       /Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:2017 +0xee
2023-04-24T17:36:40.6107860Z   github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleIn()
2023-04-24T17:36:40.6108370Z       /Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:602 +0x927
2023-04-24T17:36:40.6108760Z   github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleRequest()
2023-04-24T17:36:40.6109280Z       /Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:528 +0x18b
2023-04-24T17:36:40.6109690Z   github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest()
2023-04-24T17:36:40.6110210Z       /Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:508 +0x12b5
2023-04-24T17:36:40.6111000Z   github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest-fm()
2023-04-24T17:36:40.6111240Z       <autogenerated>:1 +0x57
2023-04-24T17:36:40.6111420Z   net/http.HandlerFunc.ServeHTTP()
2023-04-24T17:36:40.6111820Z       /Users/runner/hostedtoolcache/go/1.20.3/x64/src/net/http/server.go:2122 +0x4d
2023-04-24T17:36:40.6112390Z   net/http.serverHandler.ServeHTTP()
2023-04-24T17:36:40.6112800Z       /Users/runner/hostedtoolcache/go/1.20.3/x64/src/net/http/server.go:2936 +0x682
2023-04-24T17:36:40.6112930Z   net/http.(*conn).serve()
2023-04-24T17:36:40.6113320Z       /Users/runner/hostedtoolcache/go/1.20.3/x64/src/net/http/server.go:1995 +0xbd4
2023-04-24T17:36:40.6114500Z   net/http.(*Server).Serve.func3()
2023-04-24T17:36:40.6115470Z       /Users/runner/hostedtoolcache/go/1.20.3/x64/src/net/http/server.go:3089 +0x58
2023-04-24T17:36:40.6115510Z 
2023-04-24T17:36:40.6115710Z Previous write at 0x00c0003041f0 by goroutine 2019:
2023-04-24T17:36:40.6116270Z   github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).ComputeNextBlockValidators()
2023-04-24T17:36:40.6116850Z       /Users/runner/work/neo-go/neo-go/pkg/core/native/native_neo.go:1060 +0x2c4
2023-04-24T17:36:40.6117240Z   github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).GetValidators()
2023-04-24T17:36:40.6117750Z       /Users/runner/work/neo-go/neo-go/pkg/core/blockchain.go:2705 +0x94
2023-04-24T17:36:40.6118150Z   github.com/nspcc-dev/neo-go/pkg/consensus.(*service).getValidators()
2023-04-24T17:36:40.6118660Z       /Users/runner/work/neo-go/neo-go/pkg/consensus/consensus.go:682 +0x89
2023-04-24T17:36:40.6119060Z   github.com/nspcc-dev/neo-go/pkg/consensus.(*service).getValidators-fm()
2023-04-24T17:36:40.6119240Z       <autogenerated>:1 +0x64
2023-04-24T17:36:40.6119540Z   github.com/nspcc-dev/dbft.(*Context).Fill()
2023-04-24T17:36:40.6120450Z       /Users/runner/go/pkg/mod/github.com/nspcc-dev/dbft@v0.0.0-20230404091436-0108387748cd/context.go:268 +0x525
2023-04-24T17:36:40.6120850Z   github.com/nspcc-dev/dbft.(*Context).makePrepareRequest()
2023-04-24T17:36:40.6121710Z       /Users/runner/go/pkg/mod/github.com/nspcc-dev/dbft@v0.0.0-20230404091436-0108387748cd/send.go:19 +0x30
2023-04-24T17:36:40.6122090Z   github.com/nspcc-dev/dbft.(*DBFT).sendPrepareRequest()
2023-04-24T17:36:40.6122720Z       /Users/runner/go/pkg/mod/github.com/nspcc-dev/dbft@v0.0.0-20230404091436-0108387748cd/send.go:31 +0x4c
2023-04-24T17:36:40.6123030Z   github.com/nspcc-dev/dbft.(*DBFT).start()
2023-04-24T17:36:40.6123660Z       /Users/runner/go/pkg/mod/github.com/nspcc-dev/dbft@v0.0.0-20230404091436-0108387748cd/dbft.go:291 +0x18b
2023-04-24T17:36:40.6123950Z   github.com/nspcc-dev/dbft.(*DBFT).Start()
2023-04-24T17:36:40.6124570Z       /Users/runner/go/pkg/mod/github.com/nspcc-dev/dbft@v0.0.0-20230404091436-0108387748cd/dbft.go:83 +0x9a
2023-04-24T17:36:40.6125120Z   github.com/nspcc-dev/neo-go/pkg/consensus.(*service).Start()
2023-04-24T17:36:40.6125700Z       /Users/runner/work/neo-go/neo-go/pkg/consensus/consensus.go:283 +0x1ee
2023-04-24T17:36:40.6126110Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).tryStartServices()
2023-04-24T17:36:40.6126610Z       /Users/runner/work/neo-go/neo-go/pkg/network/server.go:551 +0x221
2023-04-24T17:36:40.6126940Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start()
2023-04-24T17:36:40.6127430Z       /Users/runner/work/neo-go/neo-go/pkg/network/server.go:273 +0x298
2023-04-24T17:36:40.6127830Z   github.com/nspcc-dev/neo-go/internal/testcli.NewTestChain.func2()
2023-04-24T17:36:40.6128350Z       /Users/runner/work/neo-go/neo-go/internal/testcli/executor.go:167 +0x39
2023-04-24T17:36:40.6128360Z 
2023-04-24T17:36:40.6128500Z Goroutine 2043 (running) created at:
2023-04-24T17:36:40.6128650Z   net/http.(*Server).Serve()
2023-04-24T17:36:40.6129140Z       /Users/runner/hostedtoolcache/go/1.20.3/x64/src/net/http/server.go:3089 +0x817
2023-04-24T17:36:40.6129590Z   github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start.func1()
2023-04-24T17:36:40.6130570Z       /Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:363 +0x78
2023-04-24T17:36:40.6131070Z   github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start.func4()
2023-04-24T17:36:40.6131600Z       /Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:368 +0x47
2023-04-24T17:36:40.6131620Z 
2023-04-24T17:36:40.6131750Z Goroutine 2019 (running) created at:
2023-04-24T17:36:40.6132580Z   github.com/nspcc-dev/neo-go/internal/testcli.NewTestChain()
2023-04-24T17:36:40.6133320Z       /Users/runner/work/neo-go/neo-go/internal/testcli/executor.go:167 +0x1151
2023-04-24T17:36:40.6133790Z   github.com/nspcc-dev/neo-go/internal/testcli.NewExecutorWithConfig()
2023-04-24T17:36:40.6134320Z       /Users/runner/work/neo-go/neo-go/internal/testcli/executor.go:193 +0x4e4
2023-04-24T17:36:40.6134670Z   github.com/nspcc-dev/neo-go/internal/testcli.NewExecutor()
2023-04-24T17:36:40.6135180Z       /Users/runner/work/neo-go/neo-go/internal/testcli/executor.go:176 +0x54
2023-04-24T17:36:40.6135560Z   github.com/nspcc-dev/neo-go/cli/wallet_test.TestWalletClaimGas()
2023-04-24T17:36:40.6136620Z       /Users/runner/work/neo-go/neo-go/cli/wallet/wallet_test.go:537 +0x3e
2023-04-24T17:36:40.6136810Z   testing.tRunner()
2023-04-24T17:36:40.6137240Z       /Users/runner/hostedtoolcache/go/1.20.3/x64/src/testing/testing.go:1576 +0x216
2023-04-24T17:36:40.6137390Z   testing.(*T).Run.func1()
2023-04-24T17:36:40.6137800Z       /Users/runner/hostedtoolcache/go/1.20.3/x64/src/testing/testing.go:1629 +0x47
2023-04-24T17:36:40.6137900Z ==================
2023-04-24T17:36:40.6138600Z     logger.go:130: 2023-04-24T17:35:50.682Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2023-04-24T17:36:40.6141500Z     logger.go:130: 2023-04-24T17:35:50.683Z	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[AEz0555ofzABAAAAAAAAAAAAAAAAAwAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAuAsB6AMMFNwk6EPkEi4hj1BzCuuZPYVDDVeBDBTYzFqQTVJvyabKtVugLJpv54nJVhTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I5CwMA6HZIFwAAAAwU3CToQ+QSLiGPUHMK65k9hUMNV4EMFNjMWpBNUm/Jpsq1W6Asmm/niclWFMAfDAh0cmFuc2ZlcgwUz3bii9AGLEpHjuNVYQETGfPPpNJBYn1bUjkBACoRDCECs2Ir9AF73+MXxYrtX0x1PyBrfbiWBG+n13S7xL9/jcIRQZ7Q3Do=]"}
2023-04-24T17:36:40.6145230Z     logger.go:130: 2023-04-24T17:35:50.685Z	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[AEz0555ofzABAAAAANxBFAAAAAAAAwAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAuAsB6AMMFNwk6EPkEi4hj1BzCuuZPYVDDVeBDBTYzFqQTVJvyabKtVugLJpv54nJVhTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I5CwMA6HZIFwAAAAwU3CToQ+QSLiGPUHMK65k9hUMNV4EMFNjMWpBNUm/Jpsq1W6Asmm/niclWFMAfDAh0cmFuc2ZlcgwUz3bii9AGLEpHjuNVYQETGfPPpNJBYn1bUjkBQgxAy+wc0LnG4s4f3QqJmt2Gke7EH7Y2KAPJKuq/q+0IGfHQwKlvIIbIxDoAEsU0Mk9PoUI7H/aWhAgN4b+PHkFINyoRDCECs2Ir9AF73+MXxYrtX0x1PyBrfbiWBG+n13S7xL9/jcIRQZ7Q3Do=]"}
2023-04-24T17:36:40.6146080Z     logger.go:130: 2023-04-24T17:35:50.690Z	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "524.22µs"}
2023-04-24T17:36:40.6146760Z     logger.go:130: 2023-04-24T17:35:50.793Z	DEBUG	done processing headers	{"headerIndex": 2, "blockHeight": 1, "took": "296.701µs"}
2023-04-24T17:36:40.6147420Z     logger.go:130: 2023-04-24T17:35:50.894Z	DEBUG	done processing headers	{"headerIndex": 3, "blockHeight": 2, "took": "324.058µs"}
2023-04-24T17:36:40.6148020Z     logger.go:130: 2023-04-24T17:35:50.895Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-24T17:36:40.6148670Z     logger.go:130: 2023-04-24T17:35:50.896Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2023-04-24T17:36:40.6149250Z     logger.go:130: 2023-04-24T17:35:50.909Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-24T17:36:40.6150490Z     logger.go:130: 2023-04-24T17:35:50.910Z	DEBUG	processing rpc request	{"method": "invokescript", "params": "[CxAMFNwk6EPkEi4hj1BzCuuZPYVDDVeBDBTcJOhD5BIuIY9QcwrrmT2FQw1XgRTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I5 ]"}
2023-04-24T17:36:40.6151630Z     logger.go:130: 2023-04-24T17:35:50.912Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2023-04-24T17:36:40.6154390Z     logger.go:130: 2023-04-24T17:35:50.913Z	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[AK1BcPu0P5gAAAAAAAAAAAAAAAAABgAAAAHcJOhD5BIuIY9QcwrrmT2FQw1XgQEAVwsQDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU3CToQ+QSLiGPUHMK65k9hUMNV4EUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQEAKAwhApd1MhCKuk+UUSF0us+LTXWT080Ozb18sexcCtOXfVMmQVbnsyc=]"}
2023-04-24T17:36:40.6157840Z     logger.go:130: 2023-04-24T17:35:50.914Z	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[AK1BcPu0P5gAAAAAAOi+EgAAAAAABgAAAAHcJOhD5BIuIY9QcwrrmT2FQw1XgQEAVwsQDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU3CToQ+QSLiGPUHMK65k9hUMNV4EUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQFCDEBe7T1AU4Vac0jjrd78deU06Rk24kUwlrVrwZxHDqG0j21TK/DLBTQ3VJhiVXbN+7xVx83lB9zZdTJzQkapth3VKAwhApd1MhCKuk+UUSF0us+LTXWT080Ozb18sexcCtOXfVMmQVbnsyc=]"}
2023-04-24T17:36:40.6158520Z     logger.go:130: 2023-04-24T17:35:50.997Z	DEBUG	done processing headers	{"headerIndex": 4, "blockHeight": 3, "took": "291.203µs"}
2023-04-24T17:36:40.6159810Z     logger.go:130: 2023-04-24T17:35:51.018Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:51017"}
2023-04-24T17:36:40.6160560Z     logger.go:130: 2023-04-24T17:35:51.019Z	INFO	persisted to disk	{"blocks": 4, "keys": 183, "headerHeight": 4, "blockHeight": 4, "took": "232.134µs"}
2023-04-24T17:36:40.6161330Z     testing.go:1446: race detected during execution of test
2023-04-24T17:36:40.6161670Z --- FAIL: TestWalletClaimGas (0.42s)
2023-04-24T17:36:40.6162200Z     --- PASS: TestWalletClaimGas/missing_wallet_path (0.00s)
2023-04-24T17:36:40.6162600Z     --- PASS: TestWalletClaimGas/missing_address (0.00s)
2023-04-24T17:36:40.6162970Z     --- PASS: TestWalletClaimGas/invalid_address (0.00s)
2023-04-24T17:36:40.6163340Z     --- PASS: TestWalletClaimGas/missing_endpoint (0.00s)
2023-04-24T17:36:40.6163720Z     --- PASS: TestWalletClaimGas/insufficient_funds (0.03s)
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Fix validators/committee cache of native Neo contract. See the bug description in the commit messages.

Close #2989 along the way.

### CODE REVIEW

**Comment by AnnaShaleva** [comment]
And I'd add this PR into 0.102.0 milestone because of the last commit. We don't want this bug to be present in our next release.

File: pkg/core/native/native_neo.go [hunk 1]
```diff
@@ -40,6 +41,15 @@ type NEO struct {
...
 	standbyKeys keys.PublicKeys
+
+	// validatorsCache represents NEO's next block validators cache and is a
+	// special cache that is allowed to be updated at any time by the outside
+	// callers bypassing the standard hierarchical DAO persist procedure. It may
+	// be invalidated by the subsequent block persist if votes ratio has been
+	// changed. After invalidation the first call to ComputeNextBlockValidators will
+	// recalculate validatorsCache.
+	validatorsCacheLock sync.RWMutex
+	validatorsCache     keys.PublicKeys
```
Comment (roman-khimov) [inline pkg/core/native/native_neo.go:52]: Very complicated and fragile. Doesn't fit into the overall layering structure.

File: pkg/core/native/native_neo.go [hunk 2]
```diff
@@ -1045,20 +1077,26 @@ func (n *NEO) getAccountState(ic *interop.Context, args []stackitem.Item) stacki
 // ComputeNextBlockValidators returns an actual list of current validators.
 func (n *NEO) ComputeNextBlockValidators(blockHeight uint32, d *dao.Simple) (keys.PublicKeys, error) {
 	numOfCNs := n.cfg.GetNumOfCNs(blockHeight + 1)
-	// Most of the time it should be OK with RO cache, thus try to retrieve
-	// validators without RW cache creation to avoid cached values copying.
-	cache := d.GetROCache(n.ID).(*NeoCache)
```
Comment (roman-khimov) [inline pkg/core/native/native_neo.go:1050]: Option 2: _always_ take the value from cache and _never_ compute here. Update the list in PostPersist if needed (if it's `nil` effectively), it'll be pushed into the lower DAO in a standard way then. This adds a bit of additional load to non-CN nodes, but at the same time doesn't change much for CN ones.

**Review by roman-khimov — CHANGES_REQUESTED** [review]

File: pkg/core/native/native_neo.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/core/native/native_neo.go:1050]: I like this approach, it's similar to the standard way of working with simple contract values, implemented.

**Comment by AnnaShaleva** [comment]
OK, now we have race problem with proper version *between concurrent test runs*, so the first fix doesn't work:
```
2023-08-30T11:14:47.3084055Z === RUN   TestNEP11_ND_OwnerOf_BalanceOf_Transfer
2023-08-30T11:14:47.3084315Z ==================
2023-08-30T11:14:47.3084541Z WARNING: DATA RACE
2023-08-30T11:14:47.3084827Z Write at 0x0000026ba670 by goroutine 347:
2023-08-30T11:14:47.3085338Z   github.com/nspcc-dev/neo-go/internal/testcli.NewExecutorWithConfig()
2023-08-30T11:14:47.3086038Z       /home/runner/work/neo-go/neo-go/internal/testcli/executor.go:198 +0x4bd
2023-08-30T11:14:47.3086557Z   github.com/nspcc-dev/neo-go/internal/testcli.NewExecutor()
2023-08-30T11:14:47.3087195Z       /home/runner/work/neo-go/neo-go/internal/testcli/executor.go:176 +0x54
2023-08-30T11:14:47.3087796Z   github.com/nspcc-dev/neo-go/cli/nep_test_test.TestNEP11_ND_OwnerOf_BalanceOf_Transfer()
2023-08-30T11:14:47.3088465Z       /home/runner/work/neo-go/neo-go/cli/nep_test/nep11_test.go:113 +0x3e
2023-08-30T11:14:47.3088801Z   testing.tRunner()
2023-08-30T11:14:47.3089276Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1446 +0x216
2023-08-30T11:14:47.3089609Z   testing.(*T).Run.func1()
2023-08-30T11:14:47.3090085Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1493 +0x47
2023-08-30T11:14:47.3090305Z 
2023-08-30T11:14:47.3090458Z Previous read at 0x0000026ba670 by goroutine 104:
2023-08-30T11:14:47.3090928Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start()
2023-08-30T11:14:47.3091538Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:288 +0x670
2023-08-30T11:14:47.3092074Z   github.com/nspcc-dev/neo-go/internal/testcli.NewTestChain.func2()
2023-08-30T11:14:47.3092887Z       /home/runner/work/neo-go/neo-go/internal/testcli/executor.go:167 +0x39
2023-08-30T11:14:47.3093113Z 
2023-08-30T11:14:47.3093247Z Goroutine 347 (running) created at:
2023-08-30T11:14:47.3093526Z   testing.(*T).Run()
2023-08-30T11:14:47.3093995Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1493 +0x75d
2023-08-30T11:14:47.3094631Z   testing.runTests.func1()
2023-08-30T11:14:47.3095129Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1846 +0x99
2023-08-30T11:14:47.3095442Z   testing.tRunner()
2023-08-30T11:14:47.3096051Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1446 +0x216
2023-08-30T11:14:47.3096382Z   testing.runTests()
2023-08-30T11:14:47.3096857Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1844 +0x7ec
2023-08-30T11:14:47.3097162Z   testing.(*M).Run()
2023-08-30T11:14:47.3097636Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1726 +0xa84
2023-08-30T11:14:47.3097952Z   main.main()
2023-08-30T11:14:47.3098250Z       _testmain.go:59 +0x2e9
2023-08-30T11:14:47.3098409Z 
2023-08-30T11:14:47.3098541Z Goroutine 104 (finished) created at:
2023-08-30T11:14:47.3099030Z   github.com/nspcc-dev/neo-go/internal/testcli.NewTestChain()
2023-08-30T11:14:47.3099683Z       /home/runner/work/neo-go/neo-go/internal/testcli/executor.go:167 +0x1071
2023-08-30T11:14:47.3100247Z   github.com/nspcc-dev/neo-go/internal/testcli.NewExecutorWithConfig()
2023-08-30T11:14:47.3100919Z       /home/runner/work/neo-go/neo-go/internal/testcli/executor.go:201 +0x524
2023-08-30T11:14:47.3101427Z   github.com/nspcc-dev/neo-go/internal/testcli.NewExecutor()
2023-08-30T11:14:47.3102061Z       /home/runner/work/neo-go/neo-go/internal/testcli/executor.go:176 +0x54
2023-08-30T11:14:47.3102588Z   github.com/nspcc-dev/neo-go/cli/nep_test_test.TestNEP11Import()
2023-08-30T11:14:47.3103218Z       /home/runner/work/neo-go/neo-go/cli/nep_test/nep11_test.go:35 +0x3e
2023-08-30T11:14:47.3103524Z   testing.tRunner()
2023-08-30T11:14:47.3104005Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1446 +0x216
2023-08-30T11:14:47.3104338Z   testing.(*T).Run.func1()
2023-08-30T11:14:47.3104849Z       /opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1493 +0x47
2023-08-30T11:14:47.3105148Z ==================
```

File: internal/testcli/executor.go [hunk 3]
```diff
@@ -189,6 +189,7 @@ func NewExecutorWithConfig(t *testing.T, needChain, runChain bool, f func(*confi
 	}
 	e.CLI.Writer = e.Out
 	e.CLI.ErrWriter = e.Err
+
```
Comment (roman-khimov) [inline internal/testcli/executor.go:192]: Ouch.

File: pkg/core/native/native_neo.go [hunk 4]
```diff
@@ -269,6 +274,7 @@ func (n *NEO) Initialize(ic *interop.Context) error {
 	cache := &NeoCache{
 		gasPerVoteCache: make(map[string]big.Int),
 		votesChanged:    true,
+		validators:      nil, // will be updated in genezis PostPersist.
```
Comment (roman-khimov) [inline pkg/core/native/native_neo.go:277]: genesis

File: pkg/core/native/native_neo.go [hunk 5]
```diff
@@ -1042,24 +1083,17 @@ func (n *NEO) getAccountState(ic *interop.Context, args []stackitem.Item) stacki
...
 }
 
-// ComputeNextBlockValidators returns an actual list of current validators.
-func (n *NEO) ComputeNextBlockValidators(blockHeight uint32, d *dao.Simple) (keys.PublicKeys, error) {
-	numOfCNs := n.cfg.GetNumOfCNs(blockHeight + 1)
-	// Most of the time it should be OK with RO cache, thus try to retrieve
-	// validators without RW cache creation to avoid cached values copying.
+// ComputeNextBlockValidators returns an actual list of current validators that is
+// relevant for the latest persisted block.
+func (n *NEO) ComputeNextBlockValidators(d *dao.Simple) (keys.PublicKeys, error) {
```
Comment (roman-khimov) [inline pkg/core/native/native_neo.go:1088]: `func (n *NEO) NextBlockValidators(d *dao.Simple) keys.PublicKeys`?

File: pkg/core/native/native_neo.go [hunk 6]
```diff
@@ -437,6 +463,21 @@ func (n *NEO) PostPersist(ic *interop.Context) error {
 			}
 		}
 	}
+	// Update next block validators cache for external users.
+	var (
+		h        = ic.Block.Index // consider persisting block as stored to get _next_ block validators
+		numOfCNs = n.cfg.GetNumOfCNs(h + 1)
+	)
+	if cache.validators == nil || numOfCNs != len(cache.validators) {
```
Comment (roman-khimov) [inline pkg/core/native/native_neo.go:471]: Can be reduced to `numOfCNs != len(cache.validators)`, but it's a little hackish...

Comment (AnnaShaleva) [reply pkg/core/native/native_neo.go:471]: It can, but could we keep it as is to avoid misunderstanding in future if one day we'll extend/refactor this code? To be honest, I'm afraid of touching NEO cache.

Comment (AnnaShaleva) [reply pkg/core/native/native_neo.go:471]: I'm sure that `numOfCNs != len(cache.validators)` won't change the things, but current version may help to understand what's going on in other contract parts.

File: pkg/core/native/native_neo.go (hunk 4 above)
Comment (AnnaShaleva) [reply pkg/core/native/native_neo.go]: Fixed.

File: internal/testcli/executor.go (hunk 3 above)
Comment (AnnaShaleva) [reply internal/testcli/executor.go]: Fixed.

File: internal/versionutil/init.go [hunk 7]
```diff
@@ -0,0 +1,13 @@
...
+
+import "github.com/nspcc-dev/neo-go/pkg/config"
+
+// TestVersion is a NeoGo version that should be used to keep all
+// compiled NEFs the same from run to run for tests.
+const TestVersion = "0.90.0-test"
+
+// Init sets config.Version to a dummy TestVersion value to keep contract NEFs
+// consistent between test runs. For test use only!
+func Init() {
```
Comment (roman-khimov) [inline internal/versionutil/init.go:11]: Can be `init()`?

File: pkg/compiler/compiler_test.go [hunk 8]
```diff
@@ -23,14 +23,17 @@ const examplePath = "../../examples"
 const exampleCompilePath = "testdata/compile"
 const exampleSavePath = exampleCompilePath + "/save"
```
Comment (roman-khimov) [inline pkg/compiler/compiler_test.go:25]: Would require some `_ = versionutil.TestVersion` here probably, but it's a little easier than a full `init()` here.

File: pkg/consensus/consensus.go [hunk 9]
```diff
@@ -679,7 +679,7 @@ func (s *service) getValidators(txes ...block.Transaction) []crypto.PublicKey {
 	if txes == nil {
```
Comment (roman-khimov) [inline pkg/consensus/consensus.go:679]: BTW, this likely doesn't make much sense now. IIRC it was an optimization. Needs to be checked wrt C# though.

File: pkg/consensus/consensus.go [hunk 10]
```diff
@@ -725,7 +725,7 @@ func (s *service) newBlockFromContext(ctx *dbft.Context) block.Block {
 	var err error
 	cfg := s.Chain.GetConfig().ProtocolConfiguration
 	if cfg.ShouldUpdateCommitteeAt(ctx.BlockIndex) {
```
Comment (roman-khimov) [inline pkg/consensus/consensus.go:727]: And this one as well.

File: pkg/consensus/consensus.go (hunk 9 above)
Comment (roman-khimov) [reply pkg/consensus/consensus.go:679]: Not exactly. 7eef8950612b37f83da2f3639d32fd61800a6670

Comment (AnnaShaleva) [reply pkg/consensus/consensus.go:679]: IMHO, it's definitely not the optimisation. See the 7eef8950, and I've checked the C# node: we use Blockchain's `GetNextBlockValidators` API to retrieve the list of validators that is constant and is updated once per N blocks (N - committee size). And we use `getValidators()` without parameters to initialize the set of validators who will sign the subsequent dBFT block. This part matches the C#.

And we use `getValidators(txs...)` to retrieve the `NextConsensus` field for the subsequent dBFT block. And according to our code, NextConsensus address can be changed at every block, because it fetches the most fresh candidates/votes data and calculates committee based on it. See the updated methods comments. And now I'm doubting that this part matches the C#, let's discuss it on the meeting tomorrow.

File: pkg/consensus/consensus.go (hunk 10 above)
Comment (AnnaShaleva) [reply pkg/consensus/consensus.go:727]: And this one is definitely not the optimisation as far.

File: internal/versionutil/init.go (hunk 7 above)
Comment (AnnaShaleva) [reply internal/versionutil/init.go]: Fixed.

File: pkg/compiler/compiler_test.go (hunk 8 above)
Comment (AnnaShaleva) [reply pkg/compiler/compiler_test.go:25]: Fixed.

File: pkg/core/native/native_neo.go [hunk 11]
```diff
@@ -1042,24 +1083,21 @@ func (n *NEO) getAccountState(ic *interop.Context, args []stackitem.Item) stacki
...
-	numOfCNs := n.cfg.GetNumOfCNs(blockHeight + 1)
-	// Most of the time it should be OK with RO cache, thus try to retrieve
-	// validators without RW cache creation to avoid cached values copying.
+// ComputeNextBlockValidators computes an actual list of current validators that is
+// relevant for the latest persisted block and based on the latest changes made by
+// register/unregister/vote calls.
+// Note: this method isn't actually "computes" new committee list and calculates
+// new validators list from it. Instead, it uses cache, but the cache itself is
+// updated every block.
+func (n *NEO) ComputeNextBlockValidators(d *dao.Simple) keys.PublicKeys {
```
Comment (AnnaShaleva) [inline pkg/core/native/native_neo.go:1092]: I've reverted the `ComputeNextBlockValidators` -> `NextBlockValidators` renaming, because the name of this exported method must match its meaning. And what this method performs is literally computing validators from based on the most fresh vote/candidates ratio got from the latest contract storage. The users of this exported method don't care *how* it is done, they just have to now that these data are fresh. And it's just NAO contract who stores this value in cache and updates it every PostPersist.

File: pkg/consensus/consensus.go (hunk 9 above)
Comment (AnnaShaleva) [reply pkg/consensus/consensus.go:679]:
```
During the consensus phase, a speaker will send PrepareRequest message with NextConsensus , which determines the next block consensus nodes. The Speaker gets the next round of consensus nodes by combining the transactions in the proposal block with the previous votes in blockchain, and assign the script hash of 2/3 multi-signature contract to NextConsensus .
```

Comment (roman-khimov) [reply pkg/consensus/consensus.go:679]: The doc is just not correct. This is the way it was on Legacy:
https://github.com/nspcc-dev/neo-go/blob/fae1d562e7852e57c9f2077c6fc913c3e955204b/pkg/consensus/consensus.go#L625-L633
Where votes were really processed for the new set of transactions:
https://github.com/nspcc-dev/neo-go/blob/fae1d562e7852e57c9f2077c6fc913c3e955204b/pkg/core/blockchain.go#L2159-L2164
On N3 that would correspond to executing the whole set of transactions right in the consensus process, but we don't do it, at block N we build N+1 using validators from the state N-1 (to sign N+1) and including validators from the current state N into the `NextConsensus`. The set of transactions of N+1 will influence the `NextConsensus` at N+2 and will be used for N+3.

But if we have (cached, committee-based) `GetNextBlockValidators()` _always_ used to determine the _current_ set of validators (while picking the NextConsensus ones from dynamic voting), we might have a problem changing the set if there are more than F nodes changed. This needs to be checked against C#.

**Comment by AnnaShaleva** [comment]
OK, @roman-khimov, something is wrong with the last commit that optimizes cache usage. The rest of commits work fine, although I haven't tested them in hybrid network scenario. Could you take a look, please?

File: pkg/core/native/native_neo.go (hunk 11 above)
Comment (roman-khimov) [reply pkg/core/native/native_neo.go:1115]: Call it `GetNextNextBlockValidators()`. Make `validators` always have the list (maybe call them `nextNextValidators, never set it to `nil`.

File: pkg/core/native/native_neo.go (hunk 6 above)
Comment (roman-khimov) [inline pkg/core/native/native_neo.go]: `validators` can't be `nil`, so `votesChanged` can be checked.

File: pkg/consensus/consensus.go [hunk 12]
```diff
@@ -677,9 +677,22 @@ func (s *service) getValidators(txes ...block.Transaction) []crypto.PublicKey {
...
+		// getValidators with empty args is used by dbft to fill the list of
+		// block's validators, thus should return validators from the current
+		// epoch without recalculation.
 		pKeys, err = s.Chain.GetNextBlockValidators()
 	} else {
-		pKeys = s.Chain.ComputeNextBlockValidators()
+		// getValidators with non-empty args is used by dbft to fill block's
+		// NextConsensus field, thus should return proper value for NextConsensus.
+		cfg := s.Chain.GetConfig().ProtocolConfiguration
+		if cfg.ShouldUpdateCommitteeAt(s.dbft.Context.BlockIndex) {
```
Comment (roman-khimov) [inline pkg/consensus/consensus.go:688]: Then here you won't need to think about indexes, just request `NextNext` list.

File: pkg/consensus/consensus.go (hunk 10 above)
Comment (roman-khimov) [reply pkg/consensus/consensus.go:740]: And here as well.

File: pkg/core/native/native_neo.go (hunk 6 above)
Comment (AnnaShaleva) [reply pkg/core/native/native_neo.go]: We have a single case with `unregister` where `votesChanged` isn't set to `true`. Fixed.

File: pkg/consensus/consensus.go (hunk 12 above)
Comment (AnnaShaleva) [reply pkg/consensus/consensus.go]: Fixed. Although it's just an improvement, and there's still a bug somewhere in the code, I'm investigating it.

**Comment by AnnaShaleva** [comment]
OK, at least it works in the NeoGo nodes privenet:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ docker logs neo_go_node_one 
=> Try to restore blocks before running node
2023-09-01T15:22:18.767Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2023-09-01T15:22:18.767Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2023-09-01T15:22:18.767Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2023-09-01T15:22:18.767Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2023-09-01T15:22:18.767Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2023-09-01T15:22:18.767Z	INFO	Hardforks are not set, using default value
2023-09-01T15:22:18.768Z	INFO	no storage version found! creating genesis block
2023-09-01T15:22:18.769Z	INFO	starting service	{"service": "Prometheus", "endpoint": ":20001"}
2023-09-01T15:22:18.770Z	INFO	service hasn't started since it's disabled	{"service": "Pprof"}
2023-09-01T15:22:18.770Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-09-01T15:22:19.209Z	INFO	SessionExpirationTime is not set or wrong, setting default value	{"SessionExpirationTime": 15}
2023-09-01T15:22:19.209Z	INFO	SessionPoolSize is not set or wrong, setting default value	{"SessionPoolSize": 20}
2023-09-01T15:22:19.209Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2023-09-01T15:22:19.209Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2023-09-01T15:22:19.209Z	INFO	MaxFindStorageResultItems is not set or wrong, setting default value	{"MaxFindStorageResultItems": 50}
2023-09-01T15:22:19.209Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2023-09-01T15:22:19.209Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2023-09-01T15:22:19.209Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2023-09-01T15:22:19.209Z	INFO	starting rpc-server	{"endpoint": ":30333"}

    _   ____________        __________
   / | / / ____/ __ \      / ____/ __ \
  /  |/ / __/ / / / /_____/ / __/ / / /
 / /|  / /___/ /_/ /_____/ /_/ / /_/ /
/_/ |_/_____/\____/      \____/\____/

/NEO-GO:0.101.5-pre-275-g4d8f72e2/

2023-09-01T15:22:19.308Z	INFO	new peer connected	{"addr": "172.200.0.2:20336", "peerCount": 1}
2023-09-01T15:22:19.308Z	INFO	started protocol	{"addr": "172.200.0.2:20336", "userAgent": "/NEO-GO:0.101.5-pre-275-g4d8f72e2/", "startHeight": 0, "id": 128453548}
2023-09-01T15:22:19.329Z	INFO	new peer connected	{"addr": "172.200.0.3:50380", "peerCount": 2}
2023-09-01T15:22:19.329Z	INFO	started protocol	{"addr": "172.200.0.3:50380", "userAgent": "/NEO-GO:0.101.5-pre-275-g4d8f72e2/", "startHeight": 0, "id": 1384127839}
2023-09-01T15:22:19.329Z	INFO	node reached synchronized state, starting services
2023-09-01T15:22:19.329Z	INFO	starting state validation service
2023-09-01T15:22:19.329Z	INFO	starting consensus service
2023-09-01T15:22:19.329Z	INFO	initializing dbft	{"height": 1, "view": 0, "index": 2, "role": "Backup"}
2023-09-01T15:22:19.329Z	INFO	RPC server already started
2023-09-01T15:22:19.329Z	INFO	skip change view	{"nc": 0, "nf": 3}
2023-09-01T15:22:19.331Z	INFO	received PrepareRequest	{"validator": 1, "tx": 0}
2023-09-01T15:22:19.331Z	INFO	sending PrepareResponse	{"height": 1, "view": 0}
2023-09-01T15:22:19.332Z	INFO	received PrepareResponse	{"validator": 0}
2023-09-01T15:22:19.332Z	INFO	sending Commit	{"height": 1, "view": 0}
2023-09-01T15:22:19.334Z	INFO	received Commit	{"validator": 1}
2023-09-01T15:22:19.334Z	INFO	received Commit	{"validator": 0}
2023-09-01T15:22:19.335Z	INFO	approving block	{"height": 1, "hash": "81b5f19b4e03ab26afd75fe3d1bb27109c4670f0adec64f0affe57ddaf3bbc84", "tx_count": 0, "merkle": "0000000000000000000000000000000000000000000000000000000000000000", "prev": "c49d7b254edd009e9094db4380fb60410616fda75cf77a09f3b92a7de1b48f0f"}
2023-09-01T15:22:19.335Z	INFO	initializing dbft	{"height": 2, "view": 0, "index": 2, "role": "Primary"}
2023-09-01T15:22:19.390Z	INFO	new peer connected	{"addr": "172.200.0.3:20334", "peerCount": 3}
2023-09-01T15:22:19.390Z	WARN	peer disconnected	{"addr": "172.200.0.3:20334", "error": "already connected", "peerCount": 2}
2023-09-01T15:22:19.475Z	INFO	new peer connected	{"addr": "172.200.0.4:20333", "peerCount": 3}
2023-09-01T15:22:19.476Z	INFO	new peer connected	{"addr": "172.200.0.4:42436", "peerCount": 4}
2023-09-01T15:22:19.476Z	WARN	peer disconnected	{"addr": "172.200.0.4:20333", "error": "identical node id", "peerCount": 3}
2023-09-01T15:22:19.476Z	WARN	peer disconnected	{"addr": "172.200.0.4:42436", "error": "identical node id", "peerCount": 2}
2023-09-01T15:22:19.505Z	INFO	new peer connected	{"addr": "172.200.0.3:20334", "peerCount": 3}
2023-09-01T15:22:19.505Z	WARN	peer disconnected	{"addr": "172.200.0.3:20334", "error": "unexpected empty payload: CMDVersion", "peerCount": 2}
2023-09-01T15:22:19.606Z	INFO	new peer connected	{"addr": "172.200.0.2:37306", "peerCount": 3}
2023-09-01T15:22:19.606Z	WARN	peer disconnected	{"addr": "172.200.0.2:37306", "error": "already connected", "peerCount": 2}
2023-09-01T15:22:19.621Z	INFO	new peer connected	{"addr": "172.200.0.4:42452", "peerCount": 3}
2023-09-01T15:22:19.621Z	INFO	new peer connected	{"addr": "172.200.0.4:20333", "peerCount": 4}
2023-09-01T15:22:19.621Z	WARN	peer disconnected	{"addr": "172.200.0.4:20333", "error": "identical node id", "peerCount": 3}
2023-09-01T15:22:19.621Z	WARN	peer disconnected	{"addr": "172.200.0.4:42452", "error": "unexpected empty payload: CMDVersion", "peerCount": 2}
2023-09-01T15:22:19.772Z	INFO	persisted to disk	{"blocks": 1, "keys": 130, "headerHeight": 1, "blockHeight": 1, "took": "2.32973ms"}
2023-09-01T15:22:20.309Z	INFO	new peer connected	{"addr": "172.200.0.1:43636", "peerCount": 3}
2023-09-01T15:22:20.309Z	INFO	started protocol	{"addr": "172.200.0.1:43636", "userAgent": "/NEO-GO:0.101.5-pre-275-g4d8f72e2/", "startHeight": 1, "id": 3281164708}
2023-09-01T15:22:20.478Z	INFO	new peer connected	{"addr": "172.200.0.1:43648", "peerCount": 4}
2023-09-01T15:22:20.478Z	WARN	peer disconnected	{"addr": "172.200.0.1:43648", "error": "already connected", "peerCount": 3}
2023-09-01T15:22:23.008Z	INFO	new peer connected	{"addr": "172.200.0.3:20334", "peerCount": 4}
2023-09-01T15:22:23.008Z	WARN	peer disconnected	{"addr": "172.200.0.3:20334", "error": "already connected", "peerCount": 3}
2023-09-01T15:22:34.336Z	INFO	sending PrepareRequest	{"height": 2, "view": 0}
2023-09-01T15:22:34.337Z	INFO	received PrepareResponse	{"validator": 1}
2023-09-01T15:22:34.337Z	INFO	received PrepareResponse	{"validator": 0}
2023-09-01T15:22:34.337Z	INFO	sending Commit	{"height": 2, "view": 0}
2023-09-01T15:22:34.338Z	INFO	received PrepareResponse	{"validator": 3}
2023-09-01T15:22:34.338Z	INFO	received Commit	{"validator": 0}
2023-09-01T15:22:34.339Z	INFO	received Commit	{"validator": 1}
2023-09-01T15:22:34.339Z	INFO	approving block	{"height": 2, "hash": "7be42087f593cb2b40e32da87a8fd35a72f52af7e26a088c47815fe1032b0689", "tx_count": 0, "merkle": "0000000000000000000000000000000000000000000000000000000000000000", "prev": "81b5f19b4e03ab26afd75fe3d1bb27109c4670f0adec64f0affe57ddaf3bbc84"}
2023-09-01T15:22:34.340Z	INFO	initializing dbft	{"height": 3, "view": 0, "index": 2, "role": "Backup"}
2023-09-01T15:22:34.779Z	INFO	persisted to disk	{"blocks": 1, "keys": 19, "headerHeight": 2, "blockHeight": 2, "took": "1.925627ms"}
2023-09-01T15:22:49.340Z	INFO	received PrepareRequest	{"validator": 3, "tx": 0}
2023-09-01T15:22:49.340Z	INFO	sending PrepareResponse	{"height": 3, "view": 0}
2023-09-01T15:22:49.342Z	INFO	received PrepareResponse	{"validator": 0}
2023-09-01T15:22:49.342Z	INFO	sending Commit	{"height": 3, "view": 0}
2023-09-01T15:22:49.342Z	INFO	received PrepareResponse	{"validator": 1}
2023-09-01T15:22:49.343Z	INFO	received Commit	{"validator": 1}
2023-09-01T15:22:49.344Z	INFO	received Commit	{"validator": 0}
2023-09-01T15:22:49.345Z	INFO	approving block	{"height": 3, "hash": "62c2e7876f65bb427a119d8143d6f251dd66da0525b2f1c424ad18d0fbed4339", "tx_count": 0, "merkle": "0000000000000000000000000000000000000000000000000000000000000000", "prev": "7be42087f593cb2b40e32da87a8fd35a72f52af7e26a088c47815fe1032b0689"}
2023-09-01T15:22:49.346Z	INFO	initializing dbft	{"height": 4, "view": 0, "index": 2, "role": "Backup"}
2023-09-01T15:22:49.788Z	INFO	persisted to disk	{"blocks": 1, "keys": 19, "headerHeight": 3, "blockHeight": 3, "took": "2.18139ms"}
2023-09-01T15:23:04.345Z	INFO	received PrepareRequest	{"validator": 0, "tx": 0}
2023-09-01T15:23:04.345Z	INFO	sending PrepareResponse	{"height": 4, "view": 0}
2023-09-01T15:23:04.347Z	INFO	received PrepareResponse	{"validator": 1}
2023-09-01T15:23:04.347Z	INFO	sending Commit	{"height": 4, "view": 0}
2023-09-01T15:23:04.348Z	INFO	received PrepareResponse	{"validator": 3}
2023-09-01T15:23:04.349Z	INFO	received Commit	{"validator": 0}
2023-09-01T15:23:04.349Z	INFO	received Commit	{"validator": 3}
2023-09-01T15:23:04.350Z	INFO	approving block	{"height": 4, "hash": "bed55fee6082f899771d06f0b3c553bcff8e3ca0ae796d68de315133429f8c06", "tx_count": 0, "merkle": "0000000000000000000000000000000000000000000000000000000000000000", "prev": "62c2e7876f65bb427a119d8143d6f251dd66da0525b2f1c424ad18d0fbed4339"}
2023-09-01T15:23:04.351Z	INFO	initializing dbft	{"height": 5, "view": 0, "index": 2, "role": "Backup"}
2023-09-01T15:23:04.796Z	INFO	persisted to disk	{"blocks": 1, "keys": 20, "headerHeight": 4, "blockHeight": 4, "took": "2.003925ms"}

```

**Comment by AnnaShaleva** [comment]
I actually had one more outdated RPC node in the private network running on my machine that was making the things bad and spamming some irrelevant blocks. I've discovered it and killed this extra node, after that this patch starts blocks accepting without unexpected `2023-09-01T15:14:06.010Z	WARN	blockQueue: failed adding block into the blockchain	{"error": "previous header was not found: key not found", "blockHeight": 1, "nextIndex": 2}` logs.

**Comment by AnnaShaleva** [comment]
@roman-khimov, the overall solution that is shown in the `Files changed` section is valid and solves the problem. However, some of PR's commits are not valid if taken them along separately from the others. Is it better to squash these commits?

**Comment by roman-khimov** [comment]
e3fadde6bb2cf21e7ee2d357b4374fa07d573146 has some commented out code that is removed afterwards. But otherwise it seems to be OK.

**Comment by AnnaShaleva** [comment]
OK, I've rechecked this code and the logic seems to be correct to me. Hope, that there's no bugs in the updated logic.

**Comment by AnnaShaleva** [comment]
Tests are checked, `TestWalletClaimGas` isn't failing any more (at least, at the several subsequent runs). Ready for review and merge.

**Review by roman-khimov — APPROVED** [review]
