### PR TITLE
services: fix race in TestNotary

### LINKED ISSUE #3366: TestNotary ubuntu fails
[Run tests (ubuntu-22.04, 1.21)](https://github.com/nspcc-dev/neo-go/actions/runs/8349223035/job/22852919548#logs)
```
2024-03-19T19:54:07.3877958Z === RUN   TestNotary
2024-03-19T19:54:07.3878726Z     logger.go:146: 2024-03-19T19:50:24.600Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-03-19T19:54:07.3879388Z     logger.go:146: 2024-03-19T19:50:24.600Z	INFO	mempool size is not set or wrong, setting default value	{"MemPoolSize": 50000}
2024-03-19T19:54:07.3880290Z     logger.go:146: 2024-03-19T19:50:24.600Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-03-19T19:54:07.3880953Z     logger.go:146: 2024-03-19T19:50:24.600Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-03-19T19:54:07.3881703Z     logger.go:146: 2024-03-19T19:50:24.600Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-03-19T19:54:07.3882545Z     logger.go:146: 2024-03-19T19:50:24.600Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-03-19T19:54:07.3883372Z     logger.go:146: 2024-03-19T19:50:24.600Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 86400}
2024-03-19T19:54:07.3883823Z     logger.go:146: 2024-03-19T19:50:24.601Z	INFO	Hardforks are not set, using default value
2024-03-19T19:54:07.3884308Z     logger.go:146: 2024-03-19T19:50:24.608Z	INFO	no storage version found! creating genesis block
2024-03-19T19:54:07.3884668Z     logger.go:146: 2024-03-19T19:50:24.615Z	INFO	starting notary service
2024-03-19T19:54:07.3885366Z     logger.go:146: 2024-03-19T19:50:24.619Z	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "789.359µs"}
2024-03-19T19:54:07.3886124Z     logger.go:146: 2024-03-19T19:50:25.613Z	INFO	persisted to disk	{"blocks": 1, "keys": 148, "headerHeight": 1, "blockHeight": 1, "took": "190.366µs"}
2024-03-19T19:54:07.3887018Z     logger.go:146: 2024-03-19T19:50:26.924Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3887693Z     logger.go:146: 2024-03-19T19:50:26.926Z	DEBUG	done processing headers	{"headerIndex": 2, "blockHeight": 1, "took": "575.64µs"}
2024-03-19T19:54:07.3888618Z     logger.go:146: 2024-03-19T19:50:26.931Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3889313Z     logger.go:146: 2024-03-19T19:50:26.933Z	DEBUG	done processing headers	{"headerIndex": 3, "blockHeight": 2, "took": "1.39604ms"}
2024-03-19T19:54:07.3889961Z     logger.go:146: 2024-03-19T19:50:26.935Z	DEBUG	done processing headers	{"headerIndex": 4, "blockHeight": 3, "took": "515.424µs"}
2024-03-19T19:54:07.3890779Z     logger.go:146: 2024-03-19T19:50:26.992Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3891448Z     logger.go:146: 2024-03-19T19:50:26.994Z	DEBUG	done processing headers	{"headerIndex": 5, "blockHeight": 4, "took": "599.671µs"}
2024-03-19T19:54:07.3892262Z     logger.go:146: 2024-03-19T19:50:26.994Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3892923Z     logger.go:146: 2024-03-19T19:50:26.995Z	DEBUG	done processing headers	{"headerIndex": 6, "blockHeight": 5, "took": "522.971µs"}
2024-03-19T19:54:07.3893898Z     logger.go:146: 2024-03-19T19:50:27.052Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3894564Z     logger.go:146: 2024-03-19T19:50:27.053Z	DEBUG	done processing headers	{"headerIndex": 7, "blockHeight": 6, "took": "538.317µs"}
2024-03-19T19:54:07.3895368Z     logger.go:146: 2024-03-19T19:50:27.055Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3896185Z     logger.go:146: 2024-03-19T19:50:27.056Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3896842Z     logger.go:146: 2024-03-19T19:50:27.056Z	DEBUG	done processing headers	{"headerIndex": 8, "blockHeight": 7, "took": "898.864µs"}
2024-03-19T19:54:07.3897652Z     logger.go:146: 2024-03-19T19:50:27.057Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3898463Z     logger.go:146: 2024-03-19T19:50:27.057Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3899120Z     logger.go:146: 2024-03-19T19:50:27.058Z	DEBUG	done processing headers	{"headerIndex": 9, "blockHeight": 8, "took": "573.205µs"}
2024-03-19T19:54:07.3899998Z     logger.go:146: 2024-03-19T19:50:27.058Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3900804Z     logger.go:146: 2024-03-19T19:50:27.059Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3901463Z     logger.go:146: 2024-03-19T19:50:27.059Z	DEBUG	done processing headers	{"headerIndex": 10, "blockHeight": 9, "took": "487.1µs"}
2024-03-19T19:54:07.3902270Z     logger.go:146: 2024-03-19T19:50:27.060Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3903069Z     logger.go:146: 2024-03-19T19:50:27.060Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3903747Z     logger.go:146: 2024-03-19T19:50:27.061Z	DEBUG	done processing headers	{"headerIndex": 11, "blockHeight": 10, "took": "495.757µs"}
2024-03-19T19:54:07.3904622Z     logger.go:146: 2024-03-19T19:50:27.062Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3905427Z     logger.go:146: 2024-03-19T19:50:27.062Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3906097Z     logger.go:146: 2024-03-19T19:50:27.063Z	DEBUG	done processing headers	{"headerIndex": 12, "blockHeight": 11, "took": "503.408µs"}
2024-03-19T19:54:07.3906900Z     logger.go:146: 2024-03-19T19:50:27.064Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3907698Z     logger.go:146: 2024-03-19T19:50:27.065Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3908357Z     logger.go:146: 2024-03-19T19:50:27.065Z	DEBUG	done processing headers	{"headerIndex": 13, "blockHeight": 12, "took": "827.868µs"}
2024-03-19T19:54:07.3909168Z     logger.go:146: 2024-03-19T19:50:27.066Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3909962Z     logger.go:146: 2024-03-19T19:50:27.066Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3910626Z     logger.go:146: 2024-03-19T19:50:27.066Z	DEBUG	done processing headers	{"headerIndex": 14, "blockHeight": 13, "took": "505.943µs"}
2024-03-19T19:54:07.3911551Z     logger.go:146: 2024-03-19T19:50:27.068Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3912354Z     logger.go:146: 2024-03-19T19:50:27.068Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3913060Z     logger.go:146: 2024-03-19T19:50:27.069Z	DEBUG	done processing headers	{"headerIndex": 15, "blockHeight": 14, "took": "939.79µs"}
2024-03-19T19:54:07.3913864Z     logger.go:146: 2024-03-19T19:50:27.069Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3914656Z     logger.go:146: 2024-03-19T19:50:27.070Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3915320Z     logger.go:146: 2024-03-19T19:50:27.070Z	DEBUG	done processing headers	{"headerIndex": 16, "blockHeight": 15, "took": "485.097µs"}
2024-03-19T19:54:07.3916118Z     logger.go:146: 2024-03-19T19:50:27.072Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3916913Z     logger.go:146: 2024-03-19T19:50:27.072Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3917652Z     logger.go:146: 2024-03-19T19:50:27.072Z	DEBUG	done processing headers	{"headerIndex": 17, "blockHeight": 16, "took": "844.983µs"}
2024-03-19T19:54:07.3918450Z     logger.go:146: 2024-03-19T19:50:27.074Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3919123Z     logger.go:146: 2024-03-19T19:50:27.074Z	DEBUG	done processing headers	{"headerIndex": 18, "blockHeight": 17, "took": "856.842µs"}
2024-03-19T19:54:07.3919926Z     logger.go:146: 2024-03-19T19:50:27.074Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3920722Z     logger.go:146: 2024-03-19T19:50:27.075Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3921519Z     logger.go:146: 2024-03-19T19:50:27.075Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3922259Z     logger.go:146: 2024-03-19T19:50:27.076Z	DEBUG	done processing headers	{"headerIndex": 19, "blockHeight": 18, "took": "684.049µs"}
2024-03-19T19:54:07.3923055Z     logger.go:146: 2024-03-19T19:50:27.077Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3923852Z     logger.go:146: 2024-03-19T19:50:27.077Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3924515Z     logger.go:146: 2024-03-19T19:50:27.078Z	DEBUG	done processing headers	{"headerIndex": 20, "blockHeight": 19, "took": "508.043µs"}
2024-03-19T19:54:07.3925309Z     logger.go:146: 2024-03-19T19:50:27.079Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3926101Z     logger.go:146: 2024-03-19T19:50:27.079Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3926765Z     logger.go:146: 2024-03-19T19:50:27.080Z	DEBUG	done processing headers	{"headerIndex": 21, "blockHeight": 20, "took": "485.979µs"}
2024-03-19T19:54:07.3927555Z     logger.go:146: 2024-03-19T19:50:27.080Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3928419Z     logger.go:146: 2024-03-19T19:50:27.081Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3929297Z     logger.go:146: 2024-03-19T19:50:27.081Z	DEBUG	done processing headers	{"headerIndex": 22, "blockHeight": 21, "took": "483.494µs"}
2024-03-19T19:54:07.3930109Z     logger.go:146: 2024-03-19T19:50:27.084Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3930943Z     logger.go:146: 2024-03-19T19:50:27.084Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3931766Z     logger.go:146: 2024-03-19T19:50:27.084Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3932578Z     logger.go:146: 2024-03-19T19:50:27.085Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3933407Z     logger.go:146: 2024-03-19T19:50:27.085Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3934209Z     logger.go:146: 2024-03-19T19:50:27.085Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3934894Z     logger.go:146: 2024-03-19T19:50:27.084Z	DEBUG	done processing headers	{"headerIndex": 23, "blockHeight": 22, "took": "1.315973ms"}
2024-03-19T19:54:07.3935789Z     logger.go:146: 2024-03-19T19:50:27.085Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3936594Z     logger.go:146: 2024-03-19T19:50:27.085Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3937399Z     logger.go:146: 2024-03-19T19:50:27.086Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3938204Z     logger.go:146: 2024-03-19T19:50:27.086Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3939006Z     logger.go:146: 2024-03-19T19:50:27.086Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3939875Z     logger.go:146: 2024-03-19T19:50:27.086Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3940689Z     logger.go:146: 2024-03-19T19:50:27.087Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3941487Z     logger.go:146: 2024-03-19T19:50:27.087Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3942294Z     logger.go:146: 2024-03-19T19:50:27.087Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3942960Z     logger.go:146: 2024-03-19T19:50:27.087Z	DEBUG	done processing headers	{"headerIndex": 24, "blockHeight": 23, "took": "878.162µs"}
2024-03-19T19:54:07.3943755Z     logger.go:146: 2024-03-19T19:50:27.088Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3944556Z     logger.go:146: 2024-03-19T19:50:27.090Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3945353Z     logger.go:146: 2024-03-19T19:50:27.090Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3946227Z     logger.go:146: 2024-03-19T19:50:27.090Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3947101Z     logger.go:146: 2024-03-19T19:50:27.090Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3947897Z     logger.go:146: 2024-03-19T19:50:27.090Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3948702Z     logger.go:146: 2024-03-19T19:50:27.090Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3949493Z     logger.go:146: 2024-03-19T19:50:27.090Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3950285Z     logger.go:146: 2024-03-19T19:50:27.090Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3950960Z     logger.go:146: 2024-03-19T19:50:27.091Z	DEBUG	done processing headers	{"headerIndex": 25, "blockHeight": 24, "took": "649.574µs"}
2024-03-19T19:54:07.3951761Z     logger.go:146: 2024-03-19T19:50:27.093Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3952552Z     logger.go:146: 2024-03-19T19:50:27.093Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3953417Z     logger.go:146: 2024-03-19T19:50:27.093Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3954224Z     logger.go:146: 2024-03-19T19:50:27.093Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3955020Z     logger.go:146: 2024-03-19T19:50:27.093Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3955822Z     logger.go:146: 2024-03-19T19:50:27.093Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3956611Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3957476Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3958276Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3959074Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3959867Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3960667Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3961462Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3962262Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3963053Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3963912Z     logger.go:146: 2024-03-19T19:50:27.094Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3964635Z     logger.go:146: 2024-03-19T19:50:27.095Z	DEBUG	done processing headers	{"headerIndex": 26, "blockHeight": 25, "took": "778.004µs"}
2024-03-19T19:54:07.3965440Z     logger.go:146: 2024-03-19T19:50:27.098Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3966237Z     logger.go:146: 2024-03-19T19:50:27.098Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3966914Z     logger.go:146: 2024-03-19T19:50:27.099Z	DEBUG	done processing headers	{"headerIndex": 27, "blockHeight": 26, "took": "881.678µs"}
2024-03-19T19:54:07.3967713Z     logger.go:146: 2024-03-19T19:50:27.100Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3968629Z     logger.go:146: 2024-03-19T19:50:27.101Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.3969304Z     logger.go:146: 2024-03-19T19:50:27.102Z	DEBUG	done processing headers	{"headerIndex": 28, "blockHeight": 27, "took": "488.28µs"}
2024-03-19T19:54:07.3970110Z     logger.go:146: 2024-03-19T19:50:27.263Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3970876Z     logger.go:146: 2024-03-19T19:50:27.264Z	DEBUG	done processing headers	{"headerIndex": 29, "blockHeight": 28, "took": "834.31µs"}
2024-03-19T19:54:07.3971682Z     logger.go:146: 2024-03-19T19:50:27.266Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3972496Z     logger.go:146: 2024-03-19T19:50:27.266Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3973176Z     logger.go:146: 2024-03-19T19:50:27.266Z	DEBUG	done processing headers	{"headerIndex": 30, "blockHeight": 29, "took": "1.042159ms"}
2024-03-19T19:54:07.3973974Z     logger.go:146: 2024-03-19T19:50:27.268Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3975091Z     logger.go:146: 2024-03-19T19:50:27.268Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3975816Z     logger.go:146: 2024-03-19T19:50:27.269Z	DEBUG	done processing headers	{"headerIndex": 31, "blockHeight": 30, "took": "1.061555ms"}
2024-03-19T19:54:07.3976616Z     logger.go:146: 2024-03-19T19:50:27.270Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3977426Z     logger.go:146: 2024-03-19T19:50:27.270Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3978102Z     logger.go:146: 2024-03-19T19:50:27.271Z	DEBUG	done processing headers	{"headerIndex": 32, "blockHeight": 31, "took": "509.713µs"}
2024-03-19T19:54:07.3978910Z     logger.go:146: 2024-03-19T19:50:27.272Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3979716Z     logger.go:146: 2024-03-19T19:50:27.272Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3980399Z     logger.go:146: 2024-03-19T19:50:27.273Z	DEBUG	done processing headers	{"headerIndex": 33, "blockHeight": 32, "took": "892.87µs"}
2024-03-19T19:54:07.3981193Z     logger.go:146: 2024-03-19T19:50:27.279Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3982152Z     logger.go:146: 2024-03-19T19:50:27.279Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3982822Z     logger.go:146: 2024-03-19T19:50:27.280Z	DEBUG	done processing headers	{"headerIndex": 34, "blockHeight": 33, "took": "492.541µs"}
2024-03-19T19:54:07.3983617Z     logger.go:146: 2024-03-19T19:50:27.281Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3984430Z     logger.go:146: 2024-03-19T19:50:27.281Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3985091Z     logger.go:146: 2024-03-19T19:50:27.282Z	DEBUG	done processing headers	{"headerIndex": 35, "blockHeight": 34, "took": "551.04µs"}
2024-03-19T19:54:07.3985888Z     logger.go:146: 2024-03-19T19:50:27.282Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3986688Z     logger.go:146: 2024-03-19T19:50:27.283Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3987353Z     logger.go:146: 2024-03-19T19:50:27.283Z	DEBUG	done processing headers	{"headerIndex": 36, "blockHeight": 35, "took": "482.435µs"}
2024-03-19T19:54:07.3988235Z     logger.go:146: 2024-03-19T19:50:27.285Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3989042Z     logger.go:146: 2024-03-19T19:50:27.286Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3989716Z     logger.go:146: 2024-03-19T19:50:27.286Z	DEBUG	done processing headers	{"headerIndex": 37, "blockHeight": 36, "took": "1.225581ms"}
2024-03-19T19:54:07.3990515Z     logger.go:146: 2024-03-19T19:50:27.288Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3991310Z     logger.go:146: 2024-03-19T19:50:27.288Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3991988Z     logger.go:146: 2024-03-19T19:50:27.288Z	DEBUG	done processing headers	{"headerIndex": 38, "blockHeight": 37, "took": "1.257942ms"}
2024-03-19T19:54:07.3992844Z     logger.go:146: 2024-03-19T19:50:27.289Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3993648Z     logger.go:146: 2024-03-19T19:50:27.289Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3994306Z     logger.go:146: 2024-03-19T19:50:27.290Z	DEBUG	done processing headers	{"headerIndex": 39, "blockHeight": 38, "took": "514.251µs"}
2024-03-19T19:54:07.3995111Z     logger.go:146: 2024-03-19T19:50:27.291Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3995900Z     logger.go:146: 2024-03-19T19:50:27.291Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3996567Z     logger.go:146: 2024-03-19T19:50:27.292Z	DEBUG	done processing headers	{"headerIndex": 40, "blockHeight": 39, "took": "525.212µs"}
2024-03-19T19:54:07.3997368Z     logger.go:146: 2024-03-19T19:50:27.293Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3998162Z     logger.go:146: 2024-03-19T19:50:27.293Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.3998846Z     logger.go:146: 2024-03-19T19:50:27.299Z	DEBUG	done processing headers	{"headerIndex": 41, "blockHeight": 40, "took": "6.304978ms"}
2024-03-19T19:54:07.3999849Z     logger.go:146: 2024-03-19T19:50:27.300Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4000652Z     logger.go:146: 2024-03-19T19:50:27.301Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4001340Z     logger.go:146: 2024-03-19T19:50:27.301Z	DEBUG	done processing headers	{"headerIndex": 42, "blockHeight": 41, "took": "1.098033ms"}
2024-03-19T19:54:07.4002137Z     logger.go:146: 2024-03-19T19:50:27.303Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4003202Z     logger.go:146: 2024-03-19T19:50:27.304Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4003947Z     logger.go:146: 2024-03-19T19:50:27.304Z	DEBUG	done processing headers	{"headerIndex": 43, "blockHeight": 42, "took": "1.06948ms"}
2024-03-19T19:54:07.4004749Z     logger.go:146: 2024-03-19T19:50:27.305Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4005547Z     logger.go:146: 2024-03-19T19:50:27.305Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4006311Z     logger.go:146: 2024-03-19T19:50:27.305Z	DEBUG	done processing headers	{"headerIndex": 44, "blockHeight": 43, "took": "528.027µs"}
2024-03-19T19:54:07.4007108Z     logger.go:146: 2024-03-19T19:50:27.306Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4007899Z     logger.go:146: 2024-03-19T19:50:27.306Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4008695Z     logger.go:146: 2024-03-19T19:50:27.307Z	DEBUG	done processing headers	{"headerIndex": 45, "blockHeight": 44, "took": "523.389µs"}
2024-03-19T19:54:07.4009495Z     logger.go:146: 2024-03-19T19:50:27.308Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4010290Z     logger.go:146: 2024-03-19T19:50:27.308Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4011040Z     logger.go:146: 2024-03-19T19:50:27.309Z	DEBUG	done processing headers	{"headerIndex": 46, "blockHeight": 45, "took": "508.721µs"}
2024-03-19T19:54:07.4011837Z     logger.go:146: 2024-03-19T19:50:27.310Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4012663Z     logger.go:146: 2024-03-19T19:50:27.310Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4013327Z     logger.go:146: 2024-03-19T19:50:27.311Z	DEBUG	done processing headers	{"headerIndex": 47, "blockHeight": 46, "took": "540.514µs"}
2024-03-19T19:54:07.4014125Z     logger.go:146: 2024-03-19T19:50:27.312Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4014917Z     logger.go:146: 2024-03-19T19:50:27.312Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4015871Z     logger.go:146: 2024-03-19T19:50:27.312Z	DEBUG	done processing headers	{"headerIndex": 48, "blockHeight": 47, "took": "529.53µs"}
2024-03-19T19:54:07.4016868Z     logger.go:146: 2024-03-19T19:50:27.314Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4017808Z     logger.go:146: 2024-03-19T19:50:27.314Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4018699Z     logger.go:146: 2024-03-19T19:50:27.315Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4019522Z     logger.go:146: 2024-03-19T19:50:27.316Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4020199Z     logger.go:146: 2024-03-19T19:50:27.315Z	DEBUG	done processing headers	{"headerIndex": 49, "blockHeight": 48, "took": "755.079µs"}
2024-03-19T19:54:07.4021009Z     logger.go:146: 2024-03-19T19:50:27.316Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4021813Z     logger.go:146: 2024-03-19T19:50:27.316Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4022629Z     logger.go:146: 2024-03-19T19:50:27.316Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4023431Z     logger.go:146: 2024-03-19T19:50:27.316Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4024322Z     logger.go:146: 2024-03-19T19:50:27.316Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4025123Z     logger.go:146: 2024-03-19T19:50:27.316Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4025796Z     logger.go:146: 2024-03-19T19:50:27.319Z	DEBUG	done processing headers	{"headerIndex": 50, "blockHeight": 49, "took": "703.856µs"}
2024-03-19T19:54:07.4026599Z     logger.go:146: 2024-03-19T19:50:27.581Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4027276Z     logger.go:146: 2024-03-19T19:50:27.583Z	DEBUG	done processing headers	{"headerIndex": 51, "blockHeight": 50, "took": "1.076202ms"}
2024-03-19T19:54:07.4028072Z     logger.go:146: 2024-03-19T19:50:27.585Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4028806Z     logger.go:146: 2024-03-19T19:50:27.586Z	DEBUG	done processing headers	{"headerIndex": 52, "blockHeight": 51, "took": "930.52µs"}
2024-03-19T19:54:07.4029621Z     logger.go:146: 2024-03-19T19:50:27.586Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4030423Z     logger.go:146: 2024-03-19T19:50:27.588Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4031238Z     logger.go:146: 2024-03-19T19:50:27.588Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4031917Z     logger.go:146: 2024-03-19T19:50:27.589Z	DEBUG	done processing headers	{"headerIndex": 53, "blockHeight": 52, "took": "1.377154ms"}
2024-03-19T19:54:07.4032716Z     logger.go:146: 2024-03-19T19:50:27.590Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4033519Z     logger.go:146: 2024-03-19T19:50:27.590Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4034195Z     logger.go:146: 2024-03-19T19:50:27.592Z	DEBUG	done processing headers	{"headerIndex": 54, "blockHeight": 53, "took": "934.076µs"}
2024-03-19T19:54:07.4034993Z     logger.go:146: 2024-03-19T19:50:27.593Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4035927Z     logger.go:146: 2024-03-19T19:50:27.593Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4036607Z     logger.go:146: 2024-03-19T19:50:27.595Z	DEBUG	done processing headers	{"headerIndex": 55, "blockHeight": 54, "took": "900.704µs"}
2024-03-19T19:54:07.4037408Z     logger.go:146: 2024-03-19T19:50:27.596Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4038073Z     logger.go:146: 2024-03-19T19:50:27.597Z	DEBUG	done processing headers	{"headerIndex": 56, "blockHeight": 55, "took": "957.761µs"}
2024-03-19T19:54:07.4038872Z     logger.go:146: 2024-03-19T19:50:27.598Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4039670Z     logger.go:146: 2024-03-19T19:50:27.599Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4040466Z     logger.go:146: 2024-03-19T19:50:27.599Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4041139Z     logger.go:146: 2024-03-19T19:50:27.601Z	DEBUG	done processing headers	{"headerIndex": 57, "blockHeight": 56, "took": "852.565µs"}
2024-03-19T19:54:07.4042016Z     logger.go:146: 2024-03-19T19:50:27.602Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4042827Z     logger.go:146: 2024-03-19T19:50:27.603Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4043496Z     logger.go:146: 2024-03-19T19:50:27.603Z	DEBUG	done processing headers	{"headerIndex": 58, "blockHeight": 57, "took": "638.211µs"}
2024-03-19T19:54:07.4044309Z     logger.go:146: 2024-03-19T19:50:27.605Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4045116Z     logger.go:146: 2024-03-19T19:50:27.605Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4045796Z     logger.go:146: 2024-03-19T19:50:27.606Z	DEBUG	done processing headers	{"headerIndex": 59, "blockHeight": 58, "took": "1.066444ms"}
2024-03-19T19:54:07.4046660Z     logger.go:146: 2024-03-19T19:50:27.608Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4047472Z     logger.go:146: 2024-03-19T19:50:27.609Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4048148Z     logger.go:146: 2024-03-19T19:50:27.609Z	DEBUG	done processing headers	{"headerIndex": 60, "blockHeight": 59, "took": "1.424093ms"}
2024-03-19T19:54:07.4049094Z     logger.go:146: 2024-03-19T19:50:27.611Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4049760Z     logger.go:146: 2024-03-19T19:50:27.612Z	DEBUG	done processing headers	{"headerIndex": 61, "blockHeight": 60, "took": "1.193201ms"}
2024-03-19T19:54:07.4050559Z     logger.go:146: 2024-03-19T19:50:27.612Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4051366Z     logger.go:146: 2024-03-19T19:50:27.613Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4052173Z     logger.go:146: 2024-03-19T19:50:27.614Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4053022Z     logger.go:146: 2024-03-19T19:50:27.614Z	INFO	persisted to disk	{"blocks": 60, "keys": 704, "headerHeight": 61, "blockHeight": 61, "took": "907.236µs"}
2024-03-19T19:54:07.4053781Z     logger.go:146: 2024-03-19T19:50:27.615Z	DEBUG	done processing headers	{"headerIndex": 62, "blockHeight": 61, "took": "691.828µs"}
2024-03-19T19:54:07.4054588Z     logger.go:146: 2024-03-19T19:50:27.616Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4055391Z     logger.go:146: 2024-03-19T19:50:27.617Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4056070Z     logger.go:146: 2024-03-19T19:50:27.618Z	DEBUG	done processing headers	{"headerIndex": 63, "blockHeight": 62, "took": "1.2941ms"}
2024-03-19T19:54:07.4056870Z     logger.go:146: 2024-03-19T19:50:27.619Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4057675Z     logger.go:146: 2024-03-19T19:50:27.621Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4058344Z     logger.go:146: 2024-03-19T19:50:27.621Z	DEBUG	done processing headers	{"headerIndex": 64, "blockHeight": 63, "took": "1.325298ms"}
2024-03-19T19:54:07.4059138Z     logger.go:146: 2024-03-19T19:50:27.623Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4060183Z     logger.go:146: 2024-03-19T19:50:27.624Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4060863Z     logger.go:146: 2024-03-19T19:50:27.624Z	DEBUG	done processing headers	{"headerIndex": 65, "blockHeight": 64, "took": "1.031689ms"}
2024-03-19T19:54:07.4061657Z     logger.go:146: 2024-03-19T19:50:27.626Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4062335Z     logger.go:146: 2024-03-19T19:50:27.627Z	DEBUG	done processing headers	{"headerIndex": 66, "blockHeight": 65, "took": "1.00513ms"}
2024-03-19T19:54:07.4062990Z     logger.go:146: 2024-03-19T19:50:27.629Z	DEBUG	done processing headers	{"headerIndex": 67, "blockHeight": 66, "took": "978.419µs"}
2024-03-19T19:54:07.4063647Z     logger.go:146: 2024-03-19T19:50:27.632Z	DEBUG	done processing headers	{"headerIndex": 68, "blockHeight": 67, "took": "854.938µs"}
2024-03-19T19:54:07.4064382Z     logger.go:146: 2024-03-19T19:50:27.634Z	DEBUG	done processing headers	{"headerIndex": 69, "blockHeight": 68, "took": "870.157µs"}
2024-03-19T19:54:07.4065056Z     logger.go:146: 2024-03-19T19:50:27.637Z	DEBUG	done processing headers	{"headerIndex": 70, "blockHeight": 69, "took": "1.159999ms"}
2024-03-19T19:54:07.4065716Z     logger.go:146: 2024-03-19T19:50:27.641Z	DEBUG	done processing headers	{"headerIndex": 71, "blockHeight": 70, "took": "1.712632ms"}
2024-03-19T19:54:07.4066544Z     logger.go:146: 2024-03-19T19:50:27.644Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4067361Z     logger.go:146: 2024-03-19T19:50:27.644Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4068177Z     logger.go:146: 2024-03-19T19:50:27.645Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4069000Z     logger.go:146: 2024-03-19T19:50:27.645Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4069804Z     logger.go:146: 2024-03-19T19:50:27.645Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4070676Z     logger.go:146: 2024-03-19T19:50:27.645Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4071545Z     logger.go:146: 2024-03-19T19:50:27.645Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4072352Z     logger.go:146: 2024-03-19T19:50:27.645Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": false}
2024-03-19T19:54:07.4073020Z     logger.go:146: 2024-03-19T19:50:27.797Z	DEBUG	done processing headers	{"headerIndex": 72, "blockHeight": 71, "took": "845µs"}
2024-03-19T19:54:07.4073829Z     logger.go:146: 2024-03-19T19:50:28.061Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4074499Z     logger.go:146: 2024-03-19T19:50:28.063Z	DEBUG	done processing headers	{"headerIndex": 73, "blockHeight": 72, "took": "952.24µs"}
2024-03-19T19:54:07.4075311Z     logger.go:146: 2024-03-19T19:50:28.064Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4076116Z     logger.go:146: 2024-03-19T19:50:28.065Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4076798Z     logger.go:146: 2024-03-19T19:50:28.065Z	DEBUG	done processing headers	{"headerIndex": 74, "blockHeight": 73, "took": "1.326932ms"}
2024-03-19T19:54:07.4077541Z     logger.go:146: 2024-03-19T19:50:28.067Z	DEBUG	done processing headers	{"headerIndex": 75, "blockHeight": 74, "took": "790.688µs"}
2024-03-19T19:54:07.4078348Z     logger.go:146: 2024-03-19T19:50:28.067Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4079153Z     logger.go:146: 2024-03-19T19:50:28.069Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4079968Z     logger.go:146: 2024-03-19T19:50:28.069Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4080765Z     logger.go:146: 2024-03-19T19:50:28.069Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4081430Z     logger.go:146: 2024-03-19T19:50:28.070Z	DEBUG	done processing headers	{"headerIndex": 76, "blockHeight": 75, "took": "931.121µs"}
2024-03-19T19:54:07.4082294Z     logger.go:146: 2024-03-19T19:50:28.072Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4082967Z     logger.go:146: 2024-03-19T19:50:28.073Z	DEBUG	done processing headers	{"headerIndex": 77, "blockHeight": 76, "took": "1.094847ms"}
2024-03-19T19:54:07.4083767Z     logger.go:146: 2024-03-19T19:50:28.074Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4084566Z     logger.go:146: 2024-03-19T19:50:28.074Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4085365Z     logger.go:146: 2024-03-19T19:50:28.075Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4086046Z     logger.go:146: 2024-03-19T19:50:28.075Z	DEBUG	done processing headers	{"headerIndex": 78, "blockHeight": 77, "took": "1.351617ms"}
2024-03-19T19:54:07.4086843Z     logger.go:146: 2024-03-19T19:50:28.077Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4087641Z     logger.go:146: 2024-03-19T19:50:28.078Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4088555Z     logger.go:146: 2024-03-19T19:50:28.078Z	DEBUG	done processing headers	{"headerIndex": 79, "blockHeight": 78, "took": "1.269032ms"}
2024-03-19T19:54:07.4089386Z     logger.go:146: 2024-03-19T19:50:28.080Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4090196Z     logger.go:146: 2024-03-19T19:50:28.080Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4090874Z     logger.go:146: 2024-03-19T19:50:28.081Z	DEBUG	done processing headers	{"headerIndex": 80, "blockHeight": 79, "took": "1.397844ms"}
2024-03-19T19:54:07.4091677Z     logger.go:146: 2024-03-19T19:50:28.082Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4092476Z     logger.go:146: 2024-03-19T19:50:28.082Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4093162Z     logger.go:146: 2024-03-19T19:50:28.084Z	DEBUG	done processing headers	{"headerIndex": 81, "blockHeight": 80, "took": "896.315µs"}
2024-03-19T19:54:07.4093956Z     logger.go:146: 2024-03-19T19:50:28.085Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4094843Z     logger.go:146: 2024-03-19T19:50:28.085Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4095519Z     logger.go:146: 2024-03-19T19:50:28.086Z	DEBUG	done processing headers	{"headerIndex": 82, "blockHeight": 81, "took": "810.085µs"}
2024-03-19T19:54:07.4096188Z     logger.go:146: 2024-03-19T19:50:28.089Z	DEBUG	done processing headers	{"headerIndex": 83, "blockHeight": 82, "took": "967.88µs"}
2024-03-19T19:54:07.4096847Z     logger.go:146: 2024-03-19T19:50:28.091Z	DEBUG	done processing headers	{"headerIndex": 84, "blockHeight": 83, "took": "850.901µs"}
2024-03-19T19:54:07.4097506Z     logger.go:146: 2024-03-19T19:50:28.093Z	DEBUG	done processing headers	{"headerIndex": 85, "blockHeight": 84, "took": "891.898µs"}
2024-03-19T19:54:07.4098159Z     logger.go:146: 2024-03-19T19:50:28.096Z	DEBUG	done processing headers	{"headerIndex": 86, "blockHeight": 85, "took": "802.501µs"}
2024-03-19T19:54:07.4098954Z     logger.go:146: 2024-03-19T19:50:28.088Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4099847Z     logger.go:146: 2024-03-19T19:50:28.098Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4100652Z     logger.go:146: 2024-03-19T19:50:28.099Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4101456Z     logger.go:146: 2024-03-19T19:50:28.099Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4102257Z     logger.go:146: 2024-03-19T19:50:28.099Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4103059Z     logger.go:146: 2024-03-19T19:50:28.099Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4103855Z     logger.go:146: 2024-03-19T19:50:28.100Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4104651Z     logger.go:146: 2024-03-19T19:50:28.100Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4105440Z     logger.go:146: 2024-03-19T19:50:28.100Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4106385Z     logger.go:146: 2024-03-19T19:50:28.100Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4107065Z     logger.go:146: 2024-03-19T19:50:28.099Z	DEBUG	done processing headers	{"headerIndex": 87, "blockHeight": 86, "took": "1.473445ms"}
2024-03-19T19:54:07.4107863Z     logger.go:146: 2024-03-19T19:50:28.101Z	ERROR	new transaction callback finished with error	{"error": "error while finalizing transaction", "is main": true}
2024-03-19T19:54:07.4108531Z     logger.go:146: 2024-03-19T19:50:28.102Z	DEBUG	done processing headers	{"headerIndex": 88, "blockHeight": 87, "took": "1.28867ms"}
2024-03-19T19:54:07.4109191Z     logger.go:146: 2024-03-19T19:50:28.105Z	DEBUG	done processing headers	{"headerIndex": 89, "blockHeight": 88, "took": "1.045906ms"}
2024-03-19T19:54:07.4109865Z     logger.go:146: 2024-03-19T19:50:28.107Z	DEBUG	done processing headers	{"headerIndex": 90, "blockHeight": 89, "took": "793.804µs"}
2024-03-19T19:54:07.4110536Z     logger.go:146: 2024-03-19T19:50:28.109Z	DEBUG	done processing headers	{"headerIndex": 91, "blockHeight": 90, "took": "1.124964ms"}
2024-03-19T19:54:07.4111212Z     logger.go:146: 2024-03-19T19:50:28.112Z	DEBUG	done processing headers	{"headerIndex": 92, "blockHeight": 91, "took": "1.179045ms"}
2024-03-19T19:54:07.4111879Z     logger.go:146: 2024-03-19T19:50:28.114Z	DEBUG	done processing headers	{"headerIndex": 93, "blockHeight": 92, "took": "813.921µs"}
2024-03-19T19:54:07.4112646Z     logger.go:146: 2024-03-19T19:50:28.116Z	DEBUG	done processing headers	{"headerIndex": 94, "blockHeight": 93, "took": "810.074µs"}
2024-03-19T19:54:07.4112777Z     core_test.go:318: 
2024-03-19T19:54:07.4113332Z         	Error Trace:	/home/runner/work/neo-go/neo-go/pkg/services/notary/core_test.go:318
2024-03-19T19:54:07.4114088Z         	            				/home/runner/work/neo-go/neo-go/pkg/services/notary/core_test.go:608
2024-03-19T19:54:07.4145605Z         	Error:      	Expected nil, but got: &transaction.Transaction{Version:0x0, Nonce:0x60, SystemFee:100000000, NetworkFee:0, ValidUntilBlock:0x70, Script:[]uint8{0x40}, Attributes:[]transaction.Attribute{transaction.Attribute{Type:0x22, Value:(*transaction.NotaryAssisted)(0xc0001db97f)}}, Signers:[]transaction.Signer{transaction.Signer{Account:util.Uint160{0x43, 0x93, 0xc1, 0x2c, 0x9c, 0x65, 0x37, 0x81, 0xe6, 0x13, 0x8a, 0x23, 0x40, 0xbe, 0xe9, 0xc3, 0x1c, 0x83, 0x29, 0x9f}, Scopes:0x0, AllowedContracts:[]util.Uint160(nil), AllowedGroups:[]*keys.PublicKey(nil), Rules:[]transaction.WitnessRule(nil)}, transaction.Signer{Account:util.Uint160{0xe2, 0xed, 0x49, 0x62, 0x97, 0x7d, 0x24, 0xce, 0x1a, 0x1d, 0x7, 0x32, 0xa6, 0x9b, 0x3b, 0x4d, 0xb, 0x91, 0xe4, 0x47}, Scopes:0x0, AllowedContracts:[]util.Uint160(nil), AllowedGroups:[]*keys.PublicKey(nil), Rules:[]transaction.WitnessRule(nil)}, transaction.Signer{Account:util.Uint160{0x13, 0x82, 0x62, 0x41, 0x3c, 0x7b, 0xec, 0x92, 0x9f, 0x2a, 0xd5, 0x79, 0xf, 0x2d, 0xd4, 0x3b, 0xba, 0xed, 0x5, 0x85}, Scopes:0x0, AllowedContracts:[]util.Uint160(nil), AllowedGroups:[]*keys.PublicKey(nil), Rules:[]transaction.WitnessRule(nil)}, transaction.Signer{Account:util.Uint160{0x3e, 0x90, 0x75, 0x10, 0x9b, 0xbc, 0x84, 0x59, 0xac, 0x67, 0xae, 0xfa, 0x26, 0x91, 0x41, 0xf, 0x76, 0xe3, 0x53, 0xc2}, Scopes:0x0, AllowedContracts:[]util.Uint160(nil), AllowedGroups:[]*keys.PublicKey(nil), Rules:[]transaction.WitnessRule(nil)}, transaction.Signer{Account:util.Uint160{0xc0, 0xb1, 0x8, 0xa8, 0x51, 0xd2, 0xce, 0x9c, 0x26, 0xd5, 0xc6, 0xf0, 0x88, 0x6b, 0xc6, 0x6a, 0x56, 0x3, 0x5, 0x9c}, Scopes:0x0, AllowedContracts:[]util.Uint160(nil), AllowedGroups:[]*keys.PublicKey(nil), Rules:[]transaction.WitnessRule(nil)}, transaction.Signer{Account:util.Uint160{0x3b, 0xec, 0x35, 0x31, 0x11, 0x9b, 0xba, 0xd7, 0x6d, 0xd0, 0x44, 0x92, 0xb, 0xd, 0xe6, 0xc3, 0x19, 0x4f, 0xe1, 0xc1}, Scopes:0x0, AllowedContracts:[]util.Uint160(nil), AllowedGroups:[]*keys.PublicKey(nil), Rules:[]transaction.WitnessRule(nil)}}, Scripts:[]transaction.Witness{transaction.Witness{InvocationScript:[]uint8{0xc, 0x40, 0x11, 0x7a, 0xcb, 0xff, 0x46, 0x13, 0x4e, 0xf2, 0x1f, 0xb, 0xa2, 0xb6, 0x64, 0xca, 0x72, 0xa1, 0x55, 0xcb, 0x69, 0x24, 0x3b, 0xcd, 0x2c, 0x1f, 0xfa, 0x54, 0x89, 0x1e, 0x58, 0x4, 0x61, 0x4, 0x2e, 0x95, 0x18, 0xa0, 0x5, 0x47, 0x8a, 0x45, 0x6e, 0xb2, 0x8b, 0xfe, 0xf3, 0x9c, 0x32, 0x1d, 0xd1, 0x8d, 0x39, 0x7f, 0xd5, 0x95, 0xd0, 0xfe, 0xea, 0x5a, 0xb8, 0xec, 0x9, 0xe7, 0x25, 0x97}, VerificationScript:[]uint8{0xc, 0x21, 0x3, 0x13, 0x1f, 0xf, 0xbe, 0x49, 0x18, 0xe4, 0x9c, 0x4b, 0x13, 0x6e, 0x3b, 0xa0, 0xb, 0xa7, 0x9b, 0x39, 0x38, 0xed, 0xcc, 0x86, 0x80, 0x6b, 0xb2, 0x58, 0xf2, 0x63, 0xdd, 0xd8, 0x55, 0x1, 0x93, 0x41, 0x56, 0xe7, 0xb3, 0x27}}, transaction.Witness{InvocationScript:[]uint8{0xc, 0x40, 0x25, 0x61, 0x95, 0x2, 0xb4, 0xfc, 0x82, 0x71, 0xf0, 0x2, 0x57, 0x76, 0x30, 0xdc, 0x21, 0x6d, 0x79, 0xf3, 0x61, 0xb4, 0x43, 0x8b, 0xca, 0xf0, 0x6e, 0xbf, 0xce, 0x66, 0xf9, 0xd4, 0x59, 0x46, 0x62, 0xab, 0xf3, 0x1d, 0x39, 0xe7, 0xae, 0xd3, 0xbf, 0x13, 0x28, 0xed, 0x57, 0xd1, 0x89, 0x92, 0x2, 0x4a, 0xee, 0x13, 0xcd, 0x52, 0x3c, 0x1f, 0x77, 0xa6, 0xda, 0x5d, 0x60, 0x91, 0x6e, 0x99}, VerificationScript:[]uint8{0xc, 0x21, 0x2, 0x88, 0x72, 0x4, 0x66, 0x79, 0xec, 0x14, 0x59, 0x24, 0xc9, 0x8, 0xf4, 0x80, 0xf8, 0x61, 0x50, 0x3f, 0x15, 0xc0, 0x74, 0x99, 0x6b, 0xb8, 0x71, 0xb3, 0x44, 0xee, 0xdf, 0xa6, 0x2f, 0xa1, 0x4b, 0x41, 0x56, 0xe7, 0xb3, 0x27}}, transaction.Witness{InvocationScript:[]uint8{0xc, 0x40, 0xaa, 0x3c, 0xdc, 0xf6, 0x33, 0x1a, 0x12, 0xcf, 0x30, 0x71, 0x7d, 0x75, 0x23, 0x23, 0x5b, 0x68, 0x98, 0x23, 0x5b, 0x9d, 0x9e, 0x19, 0x86, 0x77, 0x59, 0x0, 0x61, 0x9e, 0x79, 0x87, 0x7b, 0x3e, 0x14, 0x1e, 0x2a, 0x1b, 0x40, 0x5b, 0xbb, 0xc6, 0x65, 0xa7, 0xf5, 0xea, 0x8f, 0x23, 0xcb, 0xb9, 0x5c, 0x4c, 0x31, 0x61, 0x2c, 0x82, 0x16, 0xc3, 0xba, 0x12, 0x50, 0x31, 0x6d, 0x4f, 0xb1, 0x6}, VerificationScript:[]uint8{0xc, 0x21, 0x2, 0xb4, 0x24, 0x5d, 0xe0, 0x6, 0x5a, 0x77, 0xc1, 0x15, 0xf8, 0xc3, 0x76, 0xf4, 0x9, 0x13, 0xb9, 0x3a, 0x9f, 0x91, 0x14, 0x21, 0x3f, 0xfc, 0xe8, 0x1b, 0x8c, 0x1c, 0x7f, 0x92, 0x16, 0x6, 0xb2, 0x41, 0x56, 0xe7, 0xb3, 0x27}}, transaction.Witness{InvocationScript:[]uint8{0xc, 0x40, 0x3, 0x9c, 0xa7, 0xf3, 0x2f, 0x31, 0xc5, 0x69, 0x4e, 0x4c, 0x4c, 0x64, 0x8d, 0x96, 0xbe, 0x76, 0x9b, 0xf4, 0xf7, 0xa7, 0x7f, 0x3, 0x4a, 0xbe, 0xc2, 0x27, 0x33, 0x1e, 0x20, 0xbd, 0xb5, 0x78, 0xba, 0xbb, 0x71, 0xc9, 0x51, 0x6a, 0x0, 0xc2, 0xe8, 0x8f, 0xc6, 0x38, 0x66, 0x30, 0x4e, 0xb5, 0x3b, 0xed, 0xeb, 0xc2, 0xf2, 0x9d, 0x22, 0x7f, 0x32, 0x7b, 0x6b, 0x9b, 0xc8, 0x56, 0xd5, 0x78}, VerificationScript:[]uint8{0xc, 0x21, 0x2, 0xc3, 0x34, 0x38, 0x6b, 0xb5, 0x5d, 0x2, 0xc0, 0x5a, 0x5b, 0xf5, 0x4c, 0x7e, 0x8c, 0x34, 0xc4, 0x33, 0x26, 0x0, 0xc7, 0x32, 0x15, 0x96, 0xc2, 0x9e, 0x4f, 0xf7, 0xe3, 0x9f, 0x77, 0x50, 0xf8, 0x41, 0x56, 0xe7, 0xb3, 0x27}}, transaction.Witness{InvocationScript:[]uint8{0xc, 0x40, 0x79, 0xa8, 0xd3, 0x42, 0x30, 0xbc, 0x20, 0x56, 0x3e, 0xb9, 0x3b, 0xfd, 0x7, 0x21, 0x9c, 0x75, 0x41, 0xf4, 0xf5, 0xc9, 0xa, 0x9d, 0x17, 0xb1, 0x74, 0xbb, 0x96, 0x3b, 0xa7, 0x1e, 0x22, 0xdf, 0x5d, 0x8b, 0x49, 0x79, 0x11, 0xab, 0x3e, 0x2c, 0x26, 0xe5, 0x5c, 0xb6, 0xb5, 0x8d, 0x4e, 0x47, 0x7c, 0x76, 0x23, 0x92, 0x33, 0xbc, 0x55, 0x58, 0xa2, 0x23, 0x83, 0x86, 0xfc, 0x4a, 0x75, 0x24}, VerificationScript:[]uint8{0xc, 0x21, 0x2, 0xd0, 0x8b, 0xc5, 0x34, 0xda, 0x13, 0xf0, 0xc3, 0xa9, 0x18, 0xb0, 0xd8, 0xa0, 0xfc, 0x39, 0xf5, 0x4c, 0xfb, 0xf4, 0x91, 0xed, 0x8, 0x37, 0xaf, 0x9f, 0xf4, 0x9e, 0x6f, 0xa7, 0x41, 0xae, 0x99, 0x41, 0x56, 0xe7, 0xb3, 0x27}}, transaction.Witness{InvocationScript:[]uint8{0xc, 0x40, 0xd5, 0x65, 0xa, 0xc1, 0xab, 0x80, 0x82, 0xd8, 0x1e, 0x8a, 0x4c, 0xbf, 0xaa, 0xcb, 0x8f, 0x22, 0xaf, 0xde, 0x50, 0xbc, 0xf5, 0x33, 0xd9, 0x33, 0x1d, 0x6, 0xec, 0xf0, 0x4, 0x93, 0x94, 0xa8, 0x80, 0x59, 0xdd, 0x24, 0x60, 0x51, 0x8f, 0x31, 0xae, 0xce, 0x91, 0x81, 0x9a, 0x18, 0x86, 0xd7, 0xfa, 0x5b, 0x84, 0x6, 0x40, 0x96, 0x2c, 0x5f, 0xc8, 0x7, 0xf0, 0x4e, 0x8b, 0x16, 0xf7, 0x12}, VerificationScript:[]uint8{}}}, size:766, hash:util.Uint256{0x9e, 0xb5, 0x3d, 0xce, 0xd2, 0x81, 0xc3, 0x67, 0x86, 0xdd, 0xee, 0x66, 0x2, 0xc0, 0x75, 0x65, 0xfe, 0x28, 0x25, 0xc8, 0xdf, 0x9a, 0xba, 0x53, 0x95, 0x37, 0x95, 0xbb, 0x90, 0x31, 0xea, 0xe}, hashed:true, Trimmed:false}
2024-03-19T19:54:07.4146012Z         	Test:       	TestNotary
2024-03-19T19:54:07.4146538Z         	Messages:   	main transaction shouldn't be completed: sent 5 out of 5 requests
2024-03-19T19:54:07.4146919Z     logger.go:146: 2024-03-19T19:50:28.169Z	INFO	stopping notary service
2024-03-19T19:54:07.4147699Z     logger.go:146: 2024-03-19T19:50:28.170Z	INFO	persisted to disk	{"blocks": 33, "keys": 397, "headerHeight": 94, "blockHeight": 94, "took": "353.761µs"}
2024-03-19T19:54:07.4147856Z --- FAIL: TestNotary (3.57s)
2024-03-19T19:54:07.4147974Z === RUN   TestNotary_GenesisRoles
2024-03-19T19:54:07.4148721Z     logger.go:146: 2024-03-19T19:50:28.170Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-03-19T19:54:07.4149385Z     logger.go:146: 2024-03-19T19:50:28.171Z	INFO	mempool size is not set or wrong, setting default value	{"MemPoolSize": 50000}
2024-03-19T19:54:07.4150285Z     logger.go:146: 2024-03-19T19:50:28.171Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-03-19T19:54:07.4150955Z     logger.go:146: 2024-03-19T19:50:28.171Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-03-19T19:54:07.4151778Z     logger.go:146: 2024-03-19T19:50:28.171Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-03-19T19:54:07.4152559Z     logger.go:146: 2024-03-19T19:50:28.171Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-03-19T19:54:07.4153384Z     logger.go:146: 2024-03-19T19:50:28.171Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 86400}
2024-03-19T19:54:07.4153846Z     logger.go:146: 2024-03-19T19:50:28.171Z	INFO	Hardforks are not set, using default value
2024-03-19T19:54:07.4154336Z     logger.go:146: 2024-03-19T19:50:28.188Z	INFO	no storage version found! creating genesis block
2024-03-19T19:54:07.4155101Z     logger.go:146: 2024-03-19T19:50:28.195Z	INFO	persisted to disk	{"blocks": 0, "keys": 130, "headerHeight": 0, "blockHeight": 0, "took": "85.91µs"}
2024-03-19T19:54:07.4155276Z --- PASS: TestNotary_GenesisRoles (0.03s)
2024-03-19T19:54:07.4155369Z FAIL
2024-03-19T19:54:07.4155631Z FAIL	github.com/nspcc-dev/neo-go/pkg/services/notary	3.646s
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #3366. Roll back the test structure to the one that it has before d2a7162217e2c429600ff583690caeebc07e28a2. Add one extra block to ensure that main transaction won't be finilized. Add NVB increment slippage to avoid race between the first fallback acceptance and block acceptance.

### CODE REVIEW

File: pkg/services/notary/core_test.go [hunk 1]
```diff
@@ -591,23 +591,35 @@ func TestNotary(t *testing.T) {
...
+	mtx.RLock()
+	start := len(completedTxes)
+	finalizeWithError = false
+	mtx.RUnlock()
+
+	for i := range requests {
+		e.AddNewBlock(t)
 		e.AddNewBlock(t)
+		e.AddNewBlock(t)
+		require.Eventually(t, func() bool {
```
Comment (roman-khimov) [inline pkg/services/notary/core_test.go:614]: And this can be avoided if you're to add one more block.

File: pkg/services/notary/core_test.go [hunk 2]
```diff
@@ -591,23 +591,35 @@ func TestNotary(t *testing.T) {
...
 	// check PostPersist for valid fallbacks without finalisation error
-	// Add block before allowing tx to finalize to exclude race condition when
-	// main transaction is finalized between `finalizeWithError` restore and adding new block.
+	// Add a block before allowing tx to be finalized without error to exclude race condition when
+	// main transaction is finalized between `finalizeWithError` disabling and new block addition.
 	e.AddNewBlock(t)
-	setFinalizeWithError(false)
-	for i := range requests[1:] {
+	mtx.RLock()
+	start := len(completedTxes)
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/services/notary/core_test.go]: I don't like this test.

File: pkg/services/notary/core_test.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/services/notary/core_test.go]: Fixed.

File: pkg/services/notary/core_test.go [hunk 3]
```diff
@@ -591,23 +591,30 @@ func TestNotary(t *testing.T) {
...
-	// Add block before allowing tx to finalize to exclude race condition when
-	// main transaction is finalized between `finalizeWithError` restore and adding new block.
+	// Add a block before allowing tx to be finalized without error to exclude race condition when
+	// main transaction is finalized between `finalizeWithError` disabling and new block addition.
 	e.AddNewBlock(t)
-	setFinalizeWithError(false)
-	for i := range requests[1:] {
+	mtx.RLock()
+	finalizeWithError = false
+	mtx.RUnlock()
```
Comment (roman-khimov) [inline pkg/services/notary/core_test.go:607]: This is `setFinalizeWithError(false)`, isn't it?

Comment (AnnaShaleva) [reply pkg/services/notary/core_test.go]: It is, fixed.

**Review by roman-khimov — APPROVED** [review]
