### PR TITLE
core: store magic in the DB version, fix #2847

### LINKED ISSUE #2847: Store network magic in the DB's Version
#### Problem

Currently the following sequence of steps is considered as valid:

1. Start network(e.g. our privnet) with a magic X
2. Wait until several blocks are accepted
3. Stop all the nodes
4. *Change the network magic from X to Y* in the config
5. Start the network again *with the old DB*
6. Wait until some more blocks will be accepted
7. Profit, you have a broken chain. One part of it is signed using X magic, and another one with Y.

It's *very unlikely* to happen on some public network, but on private installations this leads to misunderstanding and can break the chain with some important data.

#### Suggestion

It's clear that the chain wasn't configured properly, so it's not a software bug. But I suggest to include the magic into `Version` structure and forbid to run the node with changed `Version`'s magic. We already have this check, so extending it will save us (and our users) from such bugs:
https://github.com/nspcc-dev/neo-go/blob/3e714a348e704c994588d667a69b4356fab253d9/pkg/core/blockchain.go#L399-L417

Thanks to @carpawell for the case.

@roman-khimov, what do you think?

### PR DESCRIPTION
**Pull request by roman-khimov**

### CODE REVIEW

File: pkg/core/dao/dao.go [hunk 1]
```diff
@@ -474,6 +475,11 @@ func (v *Version) FromBytes(data []byte) error {
 	v.P2PSigExtensions = data[i+2]&p2pSigExtensionsBit != 0
 	v.P2PStateExchangeExtensions = data[i+2]&p2pStateExchangeExtensionsBit != 0
 	v.KeepOnlyLatestState = data[i+2]&keepOnlyLatestStateBit != 0
+
+	m := i + 3
+	if len(data) == m+4 {
```
Comment (AnnaShaleva) [inline pkg/core/dao/dao.go:480]: Otherwise it's an error, isn't it?

Comment (AnnaShaleva) [reply pkg/core/dao/dao.go:480]: Oh, my bad.

**Review by AnnaShaleva — APPROVED** [review]
