### PR TITLE
compiler: prohibit to compile type assertion with two return values

### LINKED ISSUE #2692: Fail compilation for type assertion statement with two return values
Given the test:
```
func TestTypeAssertionWithOK(t *testing.T) {
	src := `package foo
	func Main() bool {
		a := 1
		var u interface{}
		u = a
		_, ok := u.(int)
		return ok
	}`
	eval(t, src, true)
}
```
the following opcodes will be generated:
```
INDEX    OPCODE      PARAMETER
0        INITSLOT    3 local, 0 arg    <<
3        PUSH1       
4        STLOC0      
5        PUSHNULL    
6        STLOC1      
7        LDLOC0      
8        STLOC1      
9        LDLOC1      
10       DUP         
11       ISTYPE      Integer (21)
13       JMPIF       17 (4/04)
15       CONVERT     Integer (21)
17       DROP        
18       STLOC2      
19       LDLOC2      
20       RET
```
which results in a runtime panic:
```
        	Error:      	Received unexpected error:
        	            	at instruction 18 (STLOC2): runtime error: index out of range [-1]
        	Test:       	TestTypeAssertionWithOK
```

The reason is somewhere around `13       JMPIF       17 (4/04)` instruction, we're not leaving on stack boolean result after that, thus, STLOC2 fails to pick it from stack (actually, the stack is empty by that moment thanks to `17       DROP`).

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #2692.

### CODE REVIEW

File: pkg/compiler/codegen.go [hunk 1]
```diff
@@ -1346,6 +1365,17 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
 	return c
 }
 
+func checkTypeAssertWithOK(n ast.Node) error {
+	switch t := n.(type) {
+	case *ast.TypeAssertExpr:
```
Comment (roman-khimov) [inline pkg/compiler/codegen.go:1370]: Do you need a `switch` here?

Comment (AnnaShaleva) [reply pkg/compiler/codegen.go]: No, it's a remnant from the previously implemented version, fixed.

**Review by roman-khimov — APPROVED** [review]
