### PR TITLE
vm: allow to serialize interop items

### LINKED ISSUE #1627: Single node stuck with invalid tx
neo-go version 0.91.1-pre-640-g42be00b5

I pushed invalid tx that doesn't have enough GAS to finish contract execution. Then consensus stuck with this tx on the same height.

```
2020-12-17T11:22:29.157Z	INFO	sending Commit	{"height": 247, "view": 0}
2020-12-17T11:22:29.158Z	INFO	approving block	{"height": 247, "hash": "d3f6da6d478aebe3dad34c5a67a7ba6c37b9b195232d1421c88784e2cc166aee", "tx_count": 1, "merkle": "d939513f4faf8c59b2485d8d5d435e598b88f762d79e16f50c920a8fb251ef1e", "prev": "56918bf1a34e6dbc25595caa4b04666dc65579bee55efed95eb6d83a4f4931cd"}
2020-12-17T11:22:29.162Z	INFO	initializing dbft	{"height": 248, "view": 0, "index": 0, "role": "Primary"}
2020-12-17T11:22:29.507Z	INFO	blockchain persist completed	{"persistedBlocks": 1, "persistedKeys": 36, "headerHeight": 247, "blockHeight": 247, "took": "22.171991ms"}
2020-12-17T11:22:30.158Z	INFO	sending PrepareRequest	{"height": 248, "view": 0}
2020-12-17T11:22:30.158Z	INFO	sending Commit	{"height": 248, "view": 0}
2020-12-17T11:22:30.159Z	INFO	approving block	{"height": 248, "hash": "8fdd8c79beb9ba2f2588d9777fde6c491ceff5c6f10e3c6343222ae2f0bf6be5", "tx_count": 7, "merkle": "6117c77d12234bbd3ad8fc10232cc7e14a80e4bd1b57305f9579ac6e394563bf", "prev": "d3f6da6d478aebe3dad34c5a67a7ba6c37b9b195232d1421c88784e2cc166aee"}
2020-12-17T11:22:30.168Z	INFO	runtime log	{"script": "b55ea2f209fd3f13a82f4d80036f0eb3b96b9bbb", "logs": "\"put: processed invoke from inner ring\""}
...
2020-12-17T11:22:30.219Z	INFO	runtime log	{"script": "19db0364abb7e2c147c72668f8106c3707f3671a", "logs": "\"addKey: processed indirect invoke\""}
2020-12-17T11:22:30.219Z	WARN	contract invocation failed	{"tx": "09a2f3aa4161cae675951b5a51fbfdadf4c789b6cfb1962508dbc0ee4666b0ee", "block": 248, "error": "error encountered at instruction 1433 (SYSCALL): failed to invoke syscall: insufficient amount of gas"}
2020-12-17T11:22:30.219Z	INFO	initializing dbft	{"height": 248, "view": 0, "index": 0, "role": "Primary"}
2020-12-17T11:22:30.528Z	INFO	blockchain persist completed	{"persistedBlocks": 0, "persistedKeys": 2, "headerHeight": 248, "blockHeight": 247, "took": "20.512537ms"}
2020-12-17T11:22:31.220Z	INFO	sending PrepareRequest	{"height": 248, "view": 0}
2020-12-17T11:22:31.220Z	INFO	sending Commit	{"height": 248, "view": 0}
2020-12-17T11:22:31.220Z	INFO	approving block	{"height": 248, "hash": "2147f4c964e2348a56da45f6f437c1bada7bef93616fb36732bbdee4d1602a5e", "tx_count": 14, "merkle": "450afe679523f51372a01945ea63cc0c75fbbdff958cf1b583eed6e49480b4aa", "prev": "d3f6da6d478aebe3dad34c5a67a7ba6c37b9b195232d1421c88784e2cc166aee"}
2020-12-17T11:22:31.227Z	INFO	runtime log	{"script": "0a9effff64659885bcc386aa04790a02c68976c4", "logs": "\"newEpoch: process new epoch\""}
...
2020-12-17T11:22:31.277Z	INFO	runtime log	{"script": "19db0364abb7e2c147c72668f8106c3707f3671a", "logs": "\"addKey: processed indirect invoke\""}
2020-12-17T11:22:31.277Z	WARN	contract invocation failed	{"tx": "09a2f3aa4161cae675951b5a51fbfdadf4c789b6cfb1962508dbc0ee4666b0ee", "block": 248, "error": "error encountered at instruction 1433 (SYSCALL): failed to invoke syscall: insufficient amount of gas"}
2020-12-17T11:22:31.277Z	WARN	error on add block	{"error": "failed to store tx exec result: interop item can't be serialized"}
2020-12-17T11:22:31.277Z	INFO	initializing dbft	{"height": 248, "view": 0, "index": 0, "role": "Primary"}
2020-12-17T11:22:32.278Z	INFO	sending PrepareRequest	{"height": 248, "view": 0}
2020-12-17T11:22:32.278Z	INFO	sending Commit	{"height": 248, "view": 0}
2020-12-17T11:22:32.278Z	INFO	approving block	{"height": 248, "hash": "8e98bc6836c03beb5437be2db3cee0adbc6953535d036bcb6c74478292a83833", "tx_count": 14, "merkle": "debb223eb92e1ec82fa57d57655c4ac8163efcb4b74dc140d512c492645b3958", "prev": "d3f6da6d478aebe3dad34c5a67a7ba6c37b9b195232d1421c88784e2cc166aee"}
2020-12-17T11:22:32.284Z	INFO	runtime log	{"script": "0a9effff64659885bcc386aa04790a02c68976c4", "logs": "\"newEpoch: process new epoch\""}
...
2020-12-17T11:22:32.326Z	INFO	runtime log	{"script": "19db0364abb7e2c147c72668f8106c3707f3671a", "logs": "\"addKey: processed indirect invoke\""}
2020-12-17T11:22:32.326Z	WARN	contract invocation failed	{"tx": "09a2f3aa4161cae675951b5a51fbfdadf4c789b6cfb1962508dbc0ee4666b0ee", "block": 248, "error": "error encountered at instruction 1433 (SYSCALL): failed to invoke syscall: insufficient amount of gas"}
2020-12-17T11:22:32.326Z	WARN	error on add block	{"error": "failed to store tx exec result: interop item can't be serialized"}
2020-12-17T11:22:32.326Z	INFO	initializing dbft	{"height": 248, "view": 0, "index": 0, "role": "Primary"}
2020-12-17T11:22:33.327Z	INFO	sending PrepareRequest	{"height": 248, "view": 0}
2020-12-17T11:22:33.327Z	INFO	sending Commit	{"height": 248, "view": 0}
2020-12-17T11:22:33.327Z	INFO	approving block	{"height": 248, "hash": "1447e25d553e757909313c018b789f6a6dc94e99a707cfa74bc44b0ab5a1a29e", "tx_count": 14, "merkle": "5aab910b45a051fdc3b0c29746e46ba0d16e47a4cc67e208e81ce2f9c9730987", "prev": "d3f6da6d478aebe3dad34c5a67a7ba6c37b9b195232d1421c88784e2cc166aee"}
2020-12-17T11:22:33.333Z	INFO	runtime log	{"script": "0a9effff64659885bcc386aa04790a02c68976c4", "logs": "\"newEpoch: process new epoch\""}
...
2020-12-17T11:22:33.380Z	INFO	runtime log	{"script": "19db0364abb7e2c147c72668f8106c3707f3671a", "logs": "\"addKey: processed indirect invoke\""}
2020-12-17T11:22:33.380Z	WARN	contract invocation failed	{"tx": "09a2f3aa4161cae675951b5a51fbfdadf4c789b6cfb1962508dbc0ee4666b0ee", "block": 248, "error": "error encountered at instruction 1433 (SYSCALL): failed to invoke syscall: insufficient amount of gas"}
2020-12-17T11:22:33.380Z	WARN	error on add block	{"error": "failed to store tx exec result: interop item can't be serialized"}
2020-12-17T11:22:33.380Z	INFO	initializing dbft	{"height": 248, "view": 0, "index": 0, "role": "Primary"}
```

### PR DESCRIPTION
**Pull request by fyrchik**
It still lossy (it can't be otherwise), but now is done
similar to JSON serialization.### Problem

Close #1627 .

### CODE REVIEW

File: pkg/vm/stackitem/serialization.go [hunk 1]
```diff
@@ -23,14 +23,30 @@ func SerializeItem(item Item) ([]byte, error) {
...
 }
 
-func serializeItemTo(item Item, w *io.BinWriter, seen map[Item]bool) {
+// EncodeBinaryStackItemAppExec encodes given Item into the given BinWriter. It's
+// similar to EncodeBinaryStackItem but allows to encode interop (only type, value is lost).
+func EncodeBinaryStackItemAppExec(item Item, w *io.BinWriter) {
+	bw := io.NewBufBinWriter()
+	serializeItemTo(item, bw.BinWriter, true, make(map[Item]bool))
+	if bw.Err != nil {
+		w.WriteBytes([]byte{byte(InvalidT)})
```
Comment (AnnaShaleva) [inline pkg/vm/stackitem/serialization.go:35]: We may probably want to set bw.Err to nil after that.

**Review by AnnaShaleva — CHANGES_REQUESTED** [review]

File: pkg/vm/stackitem/serialization.go (hunk 1 above)
Comment (fyrchik) [reply pkg/vm/stackitem/serialization.go:35]: No need for this: it is local to this function and there is immediate return after.

**Review by roman-khimov — APPROVED** [review]
