### PR TITLE
services: avoid changes in mempooled main notary tx

### LINKED ISSUE #2423: WSClient disconnected after NotaryRequestEvent receiving
#### Problem

RPC WSClient is being disconnected from the RPC node (v0.98.2) after it receives the following notary request notification:
```
{
   "type" : "removed",
   "notaryrequest" : {
      "maintx" : {
         "script" : "ERHAHwwIbmV3RXBvY2gMFOgmsZoMcCQzpf9zPoErwx/wHbyJQWJ9W1I=",
         "attributes" : [
            {
               "type" : "NotaryAssisted",
               "nkeys" : 4
            }
         ],
         "signers" : [
            {
               "scopes" : "None",
               "account" : "0x551cc859db145e92ebcf866d21d8dad3628c89b0"
            },
            {
               "scopes" : "Global",
               "account" : "0xd640b0769de258738ed3f3bb218d0e0d702b800f"
            },
            {
               "scopes" : "None",
               "account" : "0xc1e14f19c3e60d0b9244d06dd7ba9b113135ec3b"
            }
         ],
         "sysfee" : "46768180",
         "sender" : "Nc1QtYhNVXJwEFFVeMKoFK8ctK1jYsx9uP",
         "hash" : "0x99b5a8ef5628656b6ffa65a6cc565b96cd796737ac08870af1f8797286e0a0a2",
         "version" : 0,
         "size" : 421,
         "nonce" : 1,
         "validuntilblock" : 100,
         "witnesses" : [
            {
               "verification" : "",
               "invocation" : ""
            },
            {
               "verification" : "EwwhAwOaDCR0KSgiuMTmJnX5BOJvsG8kR4Inbxk2hzTq7/IIDCEDKweodBVbMiCSh5eNK5pMnIeOlx1jOgdSyyPjbt/9mbcMIQKGVityMuWS8MLBS6ZG3DwqSuDuBJ7TKEoWof+K3VSTOAwhArZeTldgxXe6ygEIEZZNaJKQZe7N4To0fYsbDeQLuj+bFEGe0Nw6",
               "invocation" : "DEC75z+gfdCUlzu+cXJHs/DGgdfyFftWOVDjP4nolUlbqoHHFrtHwp4d6BLCLXh12S+ynEI0t8kuT9CcNbn/nDfDDECNVN3ZvDvIe4w3CaUdIVOpS5rzaTlH/m2Hkg1jC5QiUfBDbnkH9CJowA/I925P5ycNMzJn0oIIiIVutzdrIJiCDEAbZgfUf/xaB/Mw1n2UVTLP8Iit/zP12inWJUWtx6Su8kiwZmv7DHStPzxJ2ocZwbXrcJrn/hR/qd4HEm8HIl7S"
            },
            {
               "invocation" : "DEAbZgfUf/xaB/Mw1n2UVTLP8Iit/zP12inWJUWtx6Su8kiwZmv7DHStPzxJ2ocZwbXrcJrn/hR/qd4HEm8HIl7S",
               "verification" : ""
            }
         ],
         "netfee" : "60203190"
      },
      "fallbacktx" : {
         "script" : "QA==",
         "signers" : [
            {
               "account" : "0xc1e14f19c3e60d0b9244d06dd7ba9b113135ec3b",
               "scopes" : "None"
            },
            {
               "scopes" : "None",
               "account" : "0x4d7efa415df21e06787e6c316297f63062d96ba5"
            }
         ],
         "attributes" : [
            {
               "type" : "NotaryAssisted",
               "nkeys" : 0
            },
            {
               "height" : 61,
               "type" : "NotValidBefore"
            },
            {
               "type" : "Conflicts",
               "hash" : "0x99b5a8ef5628656b6ffa65a6cc565b96cd796737ac08870af1f8797286e0a0a2"
            }
         ],
         "sysfee" : "0",
         "sender" : "NRNp25VPHahL3umVxBcMLuEENGZR9cHxtc",
         "hash" : "0x5f64292356ec6ce8b1d448c133138835e4a0f835d29a2fefc3b0720e2eb6fbd6",
         "size" : 291,
         "version" : 0,
         "nonce" : 672245080,
         "validuntilblock" : 100,
         "netfee" : "12257830",
         "witnesses" : [
            {
               "verification" : "",
               "invocation" : "DEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            },
            {
               "invocation" : "DEC2RBi5vAyvolCKdUH3Thqq1aS1/cQTL8fI208jnRZLTXs5gdGhRHchzEXXNvy98jJOgvzy8Xs4QXW8kGKsh4Qa",
               "verification" : "DCECtl5OV2DFd7rKAQgRlk1okpBl7s3hOjR9ixsN5Au6P5tBVuezJw=="
            }
         ]
      },
      "Witness" : {
         "verification" : "DCECtl5OV2DFd7rKAQgRlk1okpBl7s3hOjR9ixsN5Au6P5tBVuezJw==",
         "invocation" : "DEB54ovOaBvd79lxT9H8Vc7+AQjo62k/r4tj2eauz/u/PAMq7ZZr7SOmloh7vljg8i4QX4xL7eMe0FHZqpu+wJYM"
      }
   }
}
```

It happens due to the notary request JSON unmarshalling error: the specified main transaction size (421 bytes) doesn't equal to the real one (553 bytes):
```
'size' doesn't match transaction size
```

#### Cause

The following pipeline causes this error:

1. WSClient subscribes for the Notary notifications via `(c *WSClient) SubscribeForNotaryRequests`.
2. New notary request is being submitted to RPC node and added to the notary request pool. Notary request decoding causes caching of the main and fallback transactions size.
3. Notary service receives pointer to the main transaction and adds missing witnesses to main transaction.
4. Once main transaction is completed, it is accepted to the chain. Notary request pool removes notary request since main transaction is completed. The pool sends notification to its subscribers.
6. WSClient gets the request removal notification (JSON-serialised) where main transaction has its size cached, but more witnesses where added.

So the unmarshalling error is happened on the WSClient side.

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Closes #2423.

### CODE REVIEW

File: pkg/services/notary/notary.go [hunk 1]
```diff
@@ -218,15 +218,30 @@ func (n *Notary) OnNewRequest(payload *payload.P2PNotaryRequest) {
...
+			NetworkFee:      payload.MainTransaction.NetworkFee,
+			ValidUntilBlock: payload.MainTransaction.ValidUntilBlock,
+			Script:          payload.MainTransaction.Script,
+			Attributes:      payload.MainTransaction.Attributes,
+			Signers:         payload.MainTransaction.Signers,
+			Scripts:         payload.MainTransaction.Scripts,
+		}
 		r = &request{
-			main:              payload.MainTransaction,
+			main:              cp,
```
Comment (fyrchik) [inline pkg/services/notary/notary.go:235]: Do we still need size update in `finalize` then?

**Review by fyrchik — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]
