### PR TITLE
Handle terminal escape codes correctly in CLI

### LINKED ISSUE #1688: neo-go cli incorrectly handles backspace for non-ascii characters
When creating a new wallet with `neo-go wallet init` command, neo go doesn't understand escape sequences and, even if it look correct on the screen, writes corrupted input in the resulting wallet file.

Steps to reproduce:
- Run `wallet init -a -w test.wallet`
- Enter account name with few non-ascii characters (проверка), delete them and continue with regular latin characters (of the label)
- See the `label` field of the resulting wallet file.

Example output:
```
...
 			"label": "провof the label",
...
```

### PR DESCRIPTION
**Pull request by fyrchik**
Close #1688 .

Maybe we should allow only letters and numbers for account names and exclude spaces + punctuation.

### CODE REVIEW

**Comment by roman-khimov** [comment]
Have you tried `golang.org/x/term` for this? `golang.org/x/crypto/ssh/terminal` is really good for secure password reads, but it's deprecated and replaced by `golang.org/x/term` which actually does have some `ReadLine()` built-in which might be sufficient for our purposes. And I didn't expect there to be a need for this much of new code.

**Comment by fyrchik** [comment]
`x/term` was my first candidate, however it's behaviour was strange on my terminal. I have tried to do it again now and everything worked, probably forgot to enable `raw mode`.

File: cli/input/input.go [hunk 1]
```diff
@@ -1,44 +1,48 @@
...
+	io.Reader
+	io.Writer
+}
+
+var errInvalidString = errors.New("only printable characters are allowed")
+
+func checkString(s string) error {
+	for _, r := range s {
+		if !unicode.IsLetter(r) && !unicode.IsDigit(r) &&
+			!unicode.IsPunct(r) && !unicode.IsSpace(r) {
```
Comment (roman-khimov) [inline cli/input/input.go:25]: This doesn't allow for `2983$%#@.mdvgksdjgдлыоваъжх\` which is a valid nice UTF-8 string.

File: cli/wallet/wallet.go [hunk 2]
```diff
@@ -563,12 +563,15 @@ func createWallet(ctx *cli.Context) error {
 }
 
 func readAccountInfo(w io.Writer) (string, string, error) {
-	rawName, _ := input.ReadLine(w, "Enter the name of the account > ")
-	phrase, err := input.ReadPassword(w, "Enter passphrase > ")
+	rawName, err := input.ReadLine("Enter the name of the account > ")
```
Comment (roman-khimov) [inline cli/wallet/wallet.go:566]: For some reason if I'm to enter `2983$%#@.mdvgksdjgдлыоваъжх\` it not just fails, it also leaves terminal in unusable state (so that I have to use `reset` to restore it).

**Review by roman-khimov — CHANGES_REQUESTED** [review]

File: cli/wallet/wallet.go (hunk 2 above)
Comment (fyrchik) [reply cli/wallet/wallet.go:566]: This can be reproduced with simple `Ctrl+C` instead of account name. This is related to `restore` being done in `defer` which is not executed on `os.Exit`. For some reason this (unusable terminal state) only happens in Bash and not in Zsh or Fish. Moved all terminal handling to `input` package.

File: cli/main.go [hunk 3]
```diff
@@ -14,7 +14,6 @@ import (
 
 func main() {
 	ctl := newApp()
-
```
Comment (roman-khimov) [inline cli/main.go:17]: Meh.

Comment (fyrchik) [reply cli/main.go]: Fixed.

**Review by roman-khimov — APPROVED** [review]
