### PR TITLE
Fix nep5 balances migration (2.x)

### LINKED ISSUE #1144: NEP5 balance tracking info should be updated when contract migrates
Upon contract migration NEP5 balance tracking info should also be migrated from old script hash to the new one.

### PR DESCRIPTION
**Pull request by roman-khimov**
Fixes #1144. It's quite simple approach, we just update balance info right
upon contract migration. It will slow down migration transactions, but it
takes about 1-2 seconds to Seek through balances at mainnet's 3.8M, so the
approach should still work good enough. The other idea was to make lazy
updates (maintaining contract migration map), but it's more complicated to
implement (and implies that a balance get might also do a write).

There also is a concern about memory usage, it can give a spike of some tens
of megabytes, but that also is considered to be acceptable.

I'm still running it against mainnet chain, at 2.2M+ it's compatible with the old version wrt storage changes. Still need to get to the current state to check if it fixes the bug really.

### CODE REVIEW

File: pkg/core/dao/cacheddao.go [hunk 1]
```diff
@@ -149,6 +152,66 @@ func (cd *Cached) AppendNEP5Transfer(acc util.Uint160, index uint32, tr *state.N
 	return lg.Size() >= nep5TransferBatchSize, cd.PutNEP5TransferLog(acc, index, lg)
 }
 
+// MigrateNEP5Balances migrates NEP5 balances from old contract to the new one.
+func (cd *Cached) MigrateNEP5Balances(from, to util.Uint160) error {
```
Comment (AnnaShaleva) [inline pkg/core/dao/cacheddao.go:156]: Shouldn't we use this method in `contractMigrate` or somewhere else?

File: pkg/core/dao/cacheddao.go [hunk 2]
```diff
@@ -149,6 +152,66 @@ func (cd *Cached) AppendNEP5Transfer(acc util.Uint160, index uint32, tr *state.N
...
+	// TODO: deal with caching.
```
Comment (AnnaShaleva) [inline pkg/core/dao/cacheddao.go:157]: You have `dropNEP5Cache` flag, so is it still relevant?

Comment (roman-khimov) [reply pkg/core/dao/cacheddao.go:157]: Good catch, I'll fix that.

**Comment by roman-khimov** [comment]
Finally at 5821143 on mainnet, this doesn't fix the problem, some changes are going to be needed.

**Comment by roman-khimov** [comment]
Ugh, one line was missing... Importing the chain again to check.

**Comment by roman-khimov** [comment]
Updated, now it's confirmed to fix the problem. Though some testing for regressions is still needed (one more full import).
