### PR TITLE
rpcsrv: do not block blockchain events receiver by subscription requests

### LINKED ISSUE #2806: WS waiter test problem
```
2022-11-16T21:09:02.9302338Z     logger.go:130: 2022-11-16T21:08:38.468Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:63414"}
2022-11-16T21:09:02.9302482Z     client_test.go:2109: 
2022-11-16T21:09:02.9303048Z         	Error Trace:	D:\a\neo-go\neo-go\pkg\services\rpcsrv\client_test.go:2109
2022-11-16T21:09:02.9303747Z         	            				D:\a\neo-go\neo-go\pkg\services\rpcsrv\asm_amd64.s:1594
2022-11-16T21:09:02.9303987Z         	Error:      	Received unexpected error:
2022-11-16T21:09:02.9306072Z         	            	waiter context done: context canceled; unsubscription error: failed to unsubscribe from blocks (id: 0): connection lost before registering response channel; unsubscription error: failed to unsubscribe from transactions (id: 1): connection lost before registering response channel
2022-11-16T21:09:02.9306361Z         	Test:       	TestWSClient_WaitWithLateSubscription
2022-11-16T21:09:02.9306610Z --- FAIL: TestWSClient_WaitWithLateSubscription (15.22s)
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #2806.

### CODE REVIEW

File: pkg/rpcclient/wsclient.go [hunk 1]
```diff
@@ -947,6 +947,15 @@ func (c *WSClient) performUnsubscription(id string) error {
 	return nil
 }
 
+// SubscribersCount returns the number of unique channels that are subscribed to
+// WSClient events.
+func (c *WSClient) SubscribersCount() int {
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/rpcclient/wsclient.go:952]: It wasdone for test mosetly, but now can be removed, true.

File: pkg/services/rpcsrv/server.go [hunk 2]
```diff
@@ -138,16 +138,17 @@ type (
...
-		blockCh           chan *block.Block
-		executionCh       chan *state.AppExecResult
-		notificationCh    chan *state.ContainedNotificationEvent
-		transactionCh     chan *transaction.Transaction
-		notaryRequestCh   chan mempoolevent.Event
+		blockSubs         *atomic.Int32
+		executionSubs     *atomic.Int32
+		notificationSubs  *atomic.Int32
+		transactionSubs   *atomic.Int32
+		notaryRequestSubs *atomic.Int32
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server.go:145]: Nice example, I'll try to rewrite this code.

File: pkg/services/rpcsrv/server.go [hunk 3]
```diff
@@ -2666,6 +2699,58 @@ drainloop:
...
+			case chan *state.ContainedNotificationEvent:
+				s.chain.UnsubscribeFromNotifications(ch)
+			case chan *state.AppExecResult:
+				s.chain.UnsubscribeFromExecutions(ch)
+			case chan mempoolevent.Event:
+				s.coreServer.UnsubscribeFromNotaryRequests(ch)
+			default:
+				panic(fmt.Sprintf("bad unsubscription: %T", unsub))
+			}
+		case <-s.shutdown:
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server.go:2738]: OK, we probably need some special exit condition, because we have to make several subscriptions after server's shutdown:
```
2022-11-17T20:10:56.6942516Z ==================
2022-11-17T20:10:56.6942684Z 2022/11/17 20:01:52 http: panic serving 127.0.0.1:60060: send on closed channel
2022-11-17T20:10:56.6942829Z goroutine 12745 [running]:
2022-11-17T20:10:56.6942938Z net/http.(*conn).serve.func1()
2022-11-17T20:10:56.6943130Z 	/opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:1825 +0x106
2022-11-17T20:10:56.6943234Z panic({0x12ccf20, 0x169aef0})
2022-11-17T20:10:56.6943426Z 	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:844 +0x258
2022-11-17T20:10:56.6943762Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).unsubscribeFromChannel(0xc007e18e00, 0x1)
2022-11-17T20:10:56.6944038Z 	/home/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:2551 +0x1c5
2022-11-17T20:10:56.6944415Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleWsReads(0xc007e18e00, 0xc007ead1e0, 0xc007fd7620, 0xc0083f3d40)
2022-11-17T20:10:56.6944697Z 	/home/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:616 +0x551
2022-11-17T20:10:56.6945088Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest(0xc007e18e00, {0x16a6b70, 0xc006994ee0}, 0xc00156a600)
2022-11-17T20:10:56.6945371Z 	/home/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server.go:463 +0x9eb
2022-11-17T20:10:56.6945565Z net/http.HandlerFunc.ServeHTTP(0xc0079b39f0, {0x16a6b70, 0xc006994ee0}, 0x1?)
2022-11-17T20:10:56.6945757Z 	/opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:2084 +0x4e
2022-11-17T20:10:56.6945967Z net/http.serverHandler.ServeHTTP({0xc0083add10?}, {0x16a6b70, 0xc006994ee0}, 0xc00156a600)
2022-11-17T20:10:56.6946159Z 	/opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:2916 +0x897
2022-11-17T20:10:56.6946314Z net/http.(*conn).serve(0xc007989e00, {0x16a74c0, 0xc0083adbc0})
2022-11-17T20:10:56.6946497Z 	/opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:1966 +0xbab
2022-11-17T20:10:56.6946614Z created by net/http.(*Server).Serve
2022-11-17T20:10:56.6946803Z 	/opt/hostedtoolcache/go/1.18.7/x64/src/net/http/server.go:3071 +0x80d
2022-11-17T20:10:56.6947367Z     logger.go:130: 2022-11-17T20:01:53.882Z	INFO	persisted to disk	{"blocks": 0, "keys": 115, "headerHeight": 0, "blockHeight": 0, "took": "155.901µs"}
```

File: pkg/services/rpcsrv/server.go [hunk 4]
```diff
@@ -136,8 +136,18 @@ type (
...
+
+		// These two channels are aimed to manage Blockchain's subscriptions process,
+		// they are handled in a separate goroutine to avoid concurrent Blockchain's
+		// subscriptions API access. These channels are not buffered to avoid lazy
+		// subscription responses and preserve the order of subscription/unsubscription
+		// events.
+		subCh   chan interface{}
+		unsubCh chan interface{}
+
+		subsCounterLock   sync.RWMutex
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server.go:150]: If you have this lock...

File: pkg/services/rpcsrv/server.go [hunk 5]
```diff
@@ -136,8 +136,18 @@ type (
...
+		subsLock    sync.RWMutex
+		subscribers map[*subscriber]bool
+
+		// These two channels are aimed to manage Blockchain's subscriptions process,
+		// they are handled in a separate goroutine to avoid concurrent Blockchain's
+		// subscriptions API access. These channels are not buffered to avoid lazy
+		// subscription responses and preserve the order of subscription/unsubscription
+		// events.
+		subCh   chan interface{}
+		unsubCh chan interface{}
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server.go:148]: ...then why these channels? Any actions will be naturally ordered already (only one peer is changing counters and doing subscription/unsubscription).

Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server.go]: Yestarday I had some thought about it, but seems that just lock is enough, could you see the updated version?

File: pkg/services/rpcsrv/server.go [hunk 6]
```diff
@@ -2441,9 +2447,9 @@ func (s *Server) subscribe(reqParams params.Params, sub *subscriber) (interface{
 	}
 
 	s.subsLock.Lock()
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server.go:2449]: Move it after the `select`?

File: pkg/services/rpcsrv/server.go [hunk 7]
```diff
@@ -2441,9 +2447,9 @@ func (s *Server) subscribe(reqParams params.Params, sub *subscriber) (interface{
...
-	defer s.subsLock.Unlock()
 	select {
 	case <-s.shutdown:
+		s.subsLock.Unlock()
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server.go:2452]: ...to avoid this?

File: pkg/services/rpcsrv/server.go [hunk 8]
```diff
@@ -2635,6 +2650,7 @@ chloop:
 	// should be running concurrently to this one. And even if one is to run
 	// after unlock, it'll see closed s.shutdown and won't subscribe.
 	s.subsLock.Lock()
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server.go:2652]: Do you need `subsLock` here?

File: pkg/services/rpcsrv/server.go (hunk 6 above)
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server.go:2449]: I think we can't do it, because we need this lock before select due to [this line](https://github.com/nspcc-dev/neo-go/pull/2809#discussion_r1026106753). These two operations (subscription here and subscription in the end of `handleSubEvents`) must be performed sequentially, and this code should have an ability to escape in case if server was shutted down.

File: pkg/services/rpcsrv/server.go (hunk 8 above)
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server.go:2652]: Yes, see the https://github.com/nspcc-dev/neo-go/pull/2809#discussion_r1026114663.

File: pkg/services/rpcsrv/server.go (hunk 6 above)
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server.go:2449]: Or if we'd like to move this lock here and remove `subsLock` [there](https://github.com/nspcc-dev/neo-go/pull/2809#discussion_r1026106753), then shutdown check must be performed a bit later, right after the `subsCounterLock` taken.

Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server.go:2449]: See the last commit.

**Review by roman-khimov — APPROVED** [review]
