### PR TITLE
core, vm: implement snapshot isolation

### LINKED ISSUE #2506: Internal transactions
Port neo-project/neo#2729. We don't need a snapshot when `safe` method is being invoked (it can't change state) or when there is no exception handler set up (tx will fail anyway).

### LINKED ISSUE #2509: System.Contract.Call of void method M breaks execution if M throws catchable exception
#### Problem description

Contract `A` has *void* method `M` that throws catchable exception. Contract `B` calls contract `A` inside try-finally block and catches the exception. I would expect the contract `B` to properly handle the exception and return. The transaction should be HALTed.

However, current implementation behaves like expected only for *non-void* method `M`. For void `M` the execution is FAULTed with the following error:
```
invalid return values count: expected 0, got 1
```

This happens because handler of `System.Contract.Call` puts `Null` on estack if the calling method is void: https://github.com/nspcc-dev/neo-go/blob/73ef36e03e4761c0542f59e9c4f5398864a291e2/pkg/core/interop/contract/call.go#L71-L74. After that new execution context is created, exception is thrown and properly handled by TRY-ENDFINALLY handlers. Right after that we go to the `RET`'s handler which sees "extra" `Null` on estack while context's return count value is 0. Here's the problem.

I wrote the following test:
```
func TestRET_after_FINALLY_PanicInsideVoidMethod(t *testing.T) {
	bc, acc := chain.NewSingle(t)
	e := neotest.NewExecutor(t, bc, acc, acc)

	// Contract A throws catchable exception.
	srcA := `package contractA
		func Panic() {
			panic("panic from A")
		}`
	ctrA := neotest.CompileSource(t, acc.ScriptHash(), strings.NewReader(srcA), &compiler.Options{
		NoEventsCheck:      true,
		NoPermissionsCheck: true,
		Name:               "contractA",
	})
	e.DeployContract(t, ctrA, nil)

	var hashAStr string
	for i := 0; i < util.Uint160Size; i++ {
		hashAStr += fmt.Sprintf("%#x", ctrA.Hash[i])
		if i != util.Uint160Size-1 {
			hashAStr += ", "
		}
	}
	// Contract B calls A and catches the exception thrown by A.
	srcB := `package contractB
		import (
			"github.com/nspcc-dev/neo-go/pkg/interop"
			"github.com/nspcc-dev/neo-go/pkg/interop/contract"
			"github.com/nspcc-dev/neo-go/pkg/interop/runtime"
		)
		func Catch() {
			defer func() {
				if r := recover(); r != nil {
					runtime.Notify("recover after panic") // just to do something.
				}
			}()
			contract.Call(interop.Hash160{` + hashAStr + `}, "panic", contract.All)
		}`
	ctrB := neotest.CompileSource(t, acc.ScriptHash(), strings.NewReader(srcB), &compiler.Options{
		Name:               "contractB",
		NoEventsCheck:      true,
		NoPermissionsCheck: true,
		Permissions: []manifest.Permission{
			{
				Methods: manifest.WildStrings{Value: nil},
			},
		},
	})
	e.DeployContract(t, ctrB, nil)

	ctrInvoker := e.NewInvoker(ctrB.Hash, e.Committee)
	ctrInvoker.Invoke(t, stackitem.Null{}, "catch")
}
```

The test fails with the following error:
```
at instruction 94 (RET): invalid return values count: expected 0, got 1
```

Here's `A`'s script dump:
```
NEO-GO-VM > loadbase64 DAxwYW5pYyBmcm9tIEE6QA==
READY: loaded 16 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE       PARAMETER
0        PUSHDATA1    70616e69632066726f6d2041 ("panic from A")    <<
14       THROW        
15       RET          
```

Here's `B`'s script dump:
```
NEO-GO-VM > loadbase64 VgFAVwMAPEEAAABMAAAAEXAQwHEMFIm/G6nQ6LltxRKBX55nJyegyzoDStkwJATbMAwFcGFuaWMfaVRBYn1bUkVo2CQbPRlgEXIKFQAAADY9DmokCAoKAAAANhByP0BXAgBYC2BwaNgkIRDAcQwTcmVjb3ZlciBhZnRlciBwYW5pY2lQQZUBb2FA
READY: loaded 138 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE        PARAMETER
0        INITSSLOT     1    <<
2        RET           
3        INITSLOT      3 local, 0 arg
6        TRY_L         catch 71 (65/41000000), finally 82 (76/4c000000)
15       PUSH1         
16       STLOC0        
17       PUSH0         
18       PACK          
19       STLOC1        
20       PUSHDATA1     89bf1ba9d0e8b96dc512815f9e672727a0cb3a03
42       DUP           
43       ISTYPE        Buffer (30)
45       JMPIF         49 (4/04)
47       CONVERT       Buffer (30)
49       PUSHDATA1     70616e6963 ("panic")
56       PUSH15        
57       LDLOC1        
58       REVERSE4      
59       SYSCALL       System.Contract.Call (627d5b52)
64       DROP          
65       LDLOC0        
66       ISNULL        
67       JMPIF         94 (27/1b)
69       ENDTRY        94 (25/19)
71       STSFLD0       
72       PUSH1         
73       STLOC2        
74       PUSHA         95 (21/15000000)
79       CALLA         
80       ENDTRY        94 (14/0e)
82       LDLOC2        
83       JMPIF         91 (8/08)
85       PUSHA         95 (10/0a000000)
90       CALLA         
91       PUSH0         
92       STLOC2        
93       ENDFINALLY    
94       RET           
95       INITSLOT      2 local, 0 arg
98       LDSFLD0       
99       PUSHNULL      
100      STSFLD0       
101      STLOC0        
102      LDLOC0        
103      ISNULL        
104      JMPIF         137 (33/21)
106      PUSH0         
107      PACK          
108      STLOC1        
109      PUSHDATA1     7265636f7665722061667465722070616e6963 ("recover after panic")
130      LDLOC1        
131      SWAP          
132      SYSCALL       System.Runtime.Notify (95016f61)
137      RET           
```

#### Notes

In some way it can be treated like a feature, because technically the code works like it was written. But this is kind of unexpected behaviour and the problem is that we put `Null` item on stack even before the void `M` method will start its execution. If we perform this, then we probably should take care of this `Null` if exception occurs by ourselves.

I didn't run this script on C# VM, but I reviewed the code and it seems that C# implementation works the same. So we should probably  create an issue in C#.

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #2506, close #2509.

TODO:

- [x] Do not create snapshot for safe methods.
- [x] Do not create snapshot if no TRY-FINALLY block is in the call tree for this method.
- [x] Tests.

### CODE REVIEW

**Review by roman-khimov — COMMENTED** [review]
And BTW, it's important to wrap the cross-contract exception, the reason for it is explained in neo-project/neo-vm#457.

File: pkg/vm/vm.go [hunk 1]
```diff
@@ -1591,6 +1621,24 @@ func (v *VM) unloadContext(ctx *Context) {
 	if ctx.static != nil && (currCtx == nil || ctx.static != currCtx.static) {
 		ctx.static.ClearRefs(&v.refs)
 	}
+	if currCtx == nil ||
+		!bytes.Equal(ctx.prog, currCtx.prog) { // In case of CALL, CALLA, CALL_L we don't need to commit/discard changes, unwrap DAO and change notificationsCount.
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/vm/vm.go]: Fix is reverted due to https://github.com/neo-project/neo/issues/2746#issuecomment-1133440340, the new fix uses `isWrapped` flag for these perposes.

File: pkg/core/dao/dao.go [hunk 2]
```diff
@@ -89,6 +89,11 @@ func (dao *Simple) GetWrapped() *Simple {
 	return d
 }
 
+// GetUnwrapped returns the underlying DAO. It does not perform changes persist.
+func (dao *Simple) GetUnwrapped() *Simple {
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/core/dao/dao.go:93]: The problem is that we have to store the old DAO state in case if revert is needed. Currently there's only single DAO inside the interop context, and it's very convenient. Othervise we have to add some `oldDAO` field inside the interop context and be careful with its usages.

**Comment by AnnaShaleva** [comment]
> Can't we wrap in contract.Call?

I think we can't, because it's VM who should initiate wrapping. Only VM knows about exception stack (whether it contains try blocks) and final method callflags.

> And then pass single func(ok bool) error (capturing all relevant state)...

Single function is done.

> ...to vm.LoadScriptWithHash that's gonna be called on context unload

But not as a callback passed to `vm.LoadScriptWithHash`, because this code is related directly to the DAO wrapping and `(ic *Context) SpawnVM()` is a nice single place where this property can be set once and used by the rest of code that needs it.

**Comment by roman-khimov** [comment]
> because it's VM who should initiate wrapping

I'm not sure about that. We only need to wrap in `contract.Call`.

> Only VM knows about exception stack

True, but some `(*VM) IsExceptionHandlerSet` can solve this.

> final method callflags

`contract.Call` knows everything about them too.

The problem is that some DAO/storage/notification logic is leaking now into the VM which just shouldn't happen at all. And it's set as VM property, while in fact it's a context-scope thing, in some contexts we shouldn't do anything on exit, in some we should.

File: pkg/vm/vm.go [hunk 3]
```diff
@@ -321,19 +321,19 @@ func (v *VM) LoadScriptWithFlags(b []byte, f callflag.CallFlag) {
...
-	v.loadScriptWithCallingHash(b, nil, v.GetCurrentScriptHash(), hash, f, 1, 0)
+	v.loadScriptWithCallingHash(b, nil, v.GetCurrentScriptHash(), hash, f, 1, 0, nil)
 }
 
 // LoadNEFMethod allows to create a context to execute a method from the NEF
 // file with the specified caller and executing hash, call flags, return value,
 // method and _initialize offsets.
 func (v *VM) LoadNEFMethod(exe *nef.File, caller util.Uint160, hash util.Uint160, f callflag.CallFlag,
-	hasReturn bool, methodOff int, initOff int) {
+	hasReturn bool, methodOff int, initOff int, onContextUnload ContextUnloadCallback) {
```
Comment (roman-khimov) [inline pkg/vm/vm.go:328]: This `onContextUnload` can handle isolation-related things as well, I think. `contract.Call` will set everything up and this callback will commit/discard and change interop context accordingly.

Comment (AnnaShaleva) [reply pkg/vm/vm.go:313]: I did this in a separate commit. That was tricky and I broke the logic while moving isolation-related code out of VM. I hope that currently it works correct, but the last commits need to be carefully reviewed. I'm sure that all commits before the https://github.com/nspcc-dev/neo-go/pull/2508/commits/3243d09ac07055bd9035da887414c8fe010ede90 implemented correctly and work as intended.

Comment (AnnaShaleva) [reply pkg/vm/vm.go:313]: Also, there's one thing that I was not able to remove from the VM context. It's notifications counter. The problem is that when discarding changes on exception, we need to know the exact amount of notifications to be reverted. This information can be properly handled only by VM context, because interop context doesn't have layered notifications structure.

Comment (AnnaShaleva) [reply pkg/vm/vm.go:313]: And I don't like the last commit, the code becomes very "spagettish" and non-clear. Maybe we still can keep an old version and just drop the last commit? Or improve it somehow, but I'm not sure, how.

File: pkg/vm/vm.go [hunk 4]
```diff
@@ -1632,21 +1601,16 @@ func (v *VM) unloadContext(ctx *Context) {
...
 	}
-	if ctx.isWrapped && v.unwrapDAO != nil { // In case of CALL, CALLA, CALLL we don't need to commit/discard changes, unwrap DAO and change notificationsCount.
-		err := v.unwrapDAO(v.uncaughtException == nil, *ctx.notificationsCount)
+	if ctx.onUnload != nil {
+		err := ctx.onUnload(v.uncaughtException == nil, *ctx.notificationsCount)
 		if err != nil {
-			panic(fmt.Errorf("failed to unwrap DAO: %w", err))
+			panic(fmt.Errorf("context unload callback failed: %w", err))
 		}
+		ctx.onUnload = nil
```
Comment (roman-khimov) [inline pkg/vm/vm.go:1609]: Why?

File: pkg/core/interop/contract/call.go [hunk 5]
```diff
@@ -122,8 +122,44 @@ func callExFromNative(ic *interop.Context, caller util.Uint160, cs *state.Contra
...
+	f = ic.VM.Context().GetCallFlags() & f
+
+	needWrap := f&(callflag.All^callflag.ReadOnly) != 0 // If the method is safe, then it's read-only and doesn't perform storage changes or emit notifications.
+	if !needWrap && ic.VM.Context().HasTryBlock() {     // If the method is not wrapped into try-catch block, then changes should be discarded anyway if exception occurs.
+		needWrap = true
+	}
+	if needWrap && ic.DAO != nil {
+		ic.DAO = ic.DAO.GetPrivate()
+	}
+	onUnload := func(commit bool, notificationsCount int) error {
```
Comment (roman-khimov) [inline pkg/core/interop/contract/call.go:134]: You don't need `notificationsCount`.

File: pkg/core/interop/contract/call.go [hunk 6]
```diff
@@ -122,8 +122,44 @@ func callExFromNative(ic *interop.Context, caller util.Uint160, cs *state.Contra
...
-	ic.VM.LoadNEFMethod(&cs.NEF, caller, cs.Hash, ic.VM.Context().GetCallFlags()&f,
-		hasReturn, methodOff, initOff, cb)
+	f = ic.VM.Context().GetCallFlags() & f
+
+	needWrap := f&(callflag.All^callflag.ReadOnly) != 0 // If the method is safe, then it's read-only and doesn't perform storage changes or emit notifications.
+	if !needWrap && ic.VM.Context().HasTryBlock() {     // If the method is not wrapped into try-catch block, then changes should be discarded anyway if exception occurs.
+		needWrap = true
+	}
+	if needWrap && ic.DAO != nil {
+		ic.DAO = ic.DAO.GetPrivate()
```
Comment (roman-khimov) [inline pkg/core/interop/contract/call.go:132]: Right here, before you wrap you know exactly the number of existing notifications (`len(ic.Notifications)`)...

File: pkg/core/interop/contract/call.go [hunk 7]
```diff
@@ -122,8 +122,44 @@ func callExFromNative(ic *interop.Context, caller util.Uint160, cs *state.Contra
...
+	}
+	onUnload := func(commit bool, notificationsCount int) error {
+		if needWrap { // In case of CALL, CALLA, CALLL we don't need to commit/discard changes, unwrap DAO and change notificationsCount.
+			if !commit {
+				have := len(ic.Notifications)
```
Comment (roman-khimov) [inline pkg/core/interop/contract/call.go:137]: And here you have the number of existing notifications on context unload. So `if !commit {ic.Notifications[:oldCount]}` and that's it.

File: pkg/core/interop/contract/call.go [hunk 8]
```diff
@@ -122,8 +122,44 @@ func callExFromNative(ic *interop.Context, caller util.Uint160, cs *state.Contra
...
+
+	needWrap := f&(callflag.All^callflag.ReadOnly) != 0 // If the method is safe, then it's read-only and doesn't perform storage changes or emit notifications.
+	if !needWrap && ic.VM.Context().HasTryBlock() {     // If the method is not wrapped into try-catch block, then changes should be discarded anyway if exception occurs.
+		needWrap = true
+	}
+	if needWrap && ic.DAO != nil {
+		ic.DAO = ic.DAO.GetPrivate()
+	}
+	onUnload := func(commit bool, notificationsCount int) error {
+		if needWrap { // In case of CALL, CALLA, CALLL we don't need to commit/discard changes, unwrap DAO and change notificationsCount.
```
Comment (roman-khimov) [inline pkg/core/interop/contract/call.go:135]: CALL/CALLA/CALLL just don't exist here, every context they create must have `onUnload == nil`. And if we don't wrap, we don't need to set `onUnload` at all also.

File: pkg/core/interop/contract/call.go [hunk 9]
```diff
@@ -122,8 +122,44 @@ func callExFromNative(ic *interop.Context, caller util.Uint160, cs *state.Contra
...
+			if !commit {
+				have := len(ic.Notifications)
+				if have < notificationsCount {
+					// Program error, should never happen.
+					panic(fmt.Errorf("inconsistent notifications count: should remove %d, have %d", notificationsCount, len(ic.Notifications)))
+				}
+				ic.Notifications = ic.Notifications[:have-notificationsCount]
+			}
+			if ic.DAO == nil {
```
Comment (roman-khimov) [inline pkg/core/interop/contract/call.go:144]: If we wrap, it can't be `nil`.

File: pkg/core/interop/contract/call.go [hunk 10]
```diff
@@ -122,8 +122,44 @@ func callExFromNative(ic *interop.Context, caller util.Uint160, cs *state.Contra
...
+				goto callback
+			}
+			if commit {
+				_, err := ic.DAO.Persist()
+				if err != nil {
+					return fmt.Errorf("failed to persist changes %w", err)
+				}
+			}
+			ic.DAO = ic.DAO.GetUnwrapped()
```
Comment (roman-khimov) [inline pkg/core/interop/contract/call.go:153]: And you don't need `GetUnwrapped()`, you have the old DAO at the time when you create a wrapper, so just save it in the context and reuse here.

File: pkg/core/interop/contract/call.go [hunk 11]
```diff
@@ -69,7 +69,7 @@ func Call(ic *interop.Context) error {
 		return fmt.Errorf("method not found: %s/%d", method, len(args))
 	}
 	hasReturn := md.ReturnType != smartcontract.VoidType
-	var cb vm.ContextUnloadCallback
+	var cb func(stack *vm.Stack)
```
Comment (roman-khimov) [inline pkg/core/interop/contract/call.go:72]: Do we need a callback to decide on `Null` pushing and do it?

**Comment by roman-khimov** [comment]
> Could you, please, clarify, what do you mean by cross-contract exception wrapping?

https://github.com/neo-project/neo/blob/c3c0a09b2da4ce49513eeea39cafb3a85a6273e0/src/neo/SmartContract/ApplicationEngine.cs#L286-L287

File: pkg/core/interop/contract/call.go (hunk 6 above)
Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go:126]: Nice solution, and it works properly for all cases, implemented.

File: pkg/core/interop/contract/call.go (hunk 5 above)
Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go]: Fixed.

File: pkg/core/interop/contract/call.go (hunk 8 above)
Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go]: > CALL/CALLA/CALLL just don't exist here, every context they create must have onUnload == nil

That's true, the comment is removed.

>  And if we don't wrap, we don't need to set onUnload at all also.

Not exactly. Imagine if we skip wrapping because *safe* void method is called. We still have to push Null on context unloading, thus we have to set `onUnload`. But at the same time we don't need to unwrap because no wrapping was made and it's our tiny optimisation.

File: pkg/core/interop/contract/call.go (hunk 9 above)
Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go]: True, fixed.

File: pkg/core/interop/contract/call.go (hunk 10 above)
Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go:140]: But how about nested calls? Interop context has single state shared between all of them. Should we create a list of DAO inside the interop context?

File: pkg/core/interop/contract/call.go (hunk 11 above)
Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go]: We don't it can safely be replased with boolean value, fixed.

File: pkg/core/interop/contract/call.go (hunk 8 above)
Comment (roman-khimov) [reply pkg/core/interop/contract/call.go]: OK, maybe `Null` problem justifies non-nil `onUnload` in some way, although I'm still not sure about it (let's see what the code looks like in the end).

File: pkg/core/interop/contract/call.go (hunk 10 above)
Comment (AnnaShaleva) [reply pkg/core/interop/contract/call.go]: Finally, I got what should be done here, fixed!

**Comment by AnnaShaleva** [comment]
The last commit should fix the problem with uncought exception.

**Review by roman-khimov — APPROVED** [review]
