### PR TITLE
rpcsrv: fix TestSubClientWaitWithMissedEvent

### LINKED ISSUE #2958: Race in `TestSubClientWaitWithMissedEvent`
The test isn't constructed properly:
```
2023-04-03T07:03:16.6891865Z === RUN   TestSubClientWaitWithMissedEvent/ws
2023-04-03T07:03:16.6892525Z     logger.go:130: 2023-04-03T07:03:13.346Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2023-04-03T07:03:16.6893386Z     logger.go:130: 2023-04-03T07:03:13.346Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2023-04-03T07:03:16.6894000Z     logger.go:130: 2023-04-03T07:03:13.346Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2023-04-03T07:03:16.6894748Z     logger.go:130: 2023-04-03T07:03:13.346Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2023-04-03T07:03:16.6895464Z     logger.go:130: 2023-04-03T07:03:13.346Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2023-04-03T07:03:16.6896205Z     logger.go:130: 2023-04-03T07:03:13.346Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2023-04-03T07:03:16.6896786Z     logger.go:130: 2023-04-03T07:03:13.361Z	INFO	no storage version found! creating genesis block
2023-04-03T07:03:16.6897422Z     logger.go:130: 2023-04-03T07:03:13.361Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-04-03T07:03:16.6898085Z     logger.go:130: 2023-04-03T07:03:13.361Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2023-04-03T07:03:16.6898582Z     logger.go:130: 2023-04-03T07:03:13.361Z	INFO	starting rpc-server	{"endpoint": "localhost:0"}
2023-04-03T07:03:16.6899139Z     logger.go:130: 2023-04-03T07:03:13.361Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-03T07:03:16.6899717Z     logger.go:130: 2023-04-03T07:03:13.361Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2023-04-03T07:03:16.6900417Z     logger.go:130: 2023-04-03T07:03:13.518Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-03T07:03:16.6901168Z     logger.go:130: 2023-04-03T07:03:13.518Z	DEBUG	processing rpc request	{"method": "subscribe", "params": "[block_added ]"}
2023-04-03T07:03:16.6901773Z     logger.go:130: 2023-04-03T07:03:13.518Z	DEBUG	processing rpc request	{"method": "subscribe", "params": "[transaction_executed ]"}
2023-04-03T07:03:16.6902713Z     logger.go:130: 2023-04-03T07:03:13.518Z	DEBUG	processing rpc request	{"method": "getapplicationlog", "params": "[f01e1986ee63cc9437516745cfb7f57108432d5493a7c159a1082900c6afb316 Application]"}
2023-04-03T07:03:16.6903912Z     logger.go:130: 2023-04-03T07:03:13.518Z	INFO	Error encountered with rpc request	{"code": -100, "cause": "failed to locate application log: key not found", "method": "getapplicationlog", "params": "[f01e1986ee63cc9437516745cfb7f57108432d5493a7c159a1082900c6afb316 Application]"}
2023-04-03T07:03:16.6904087Z     client_test.go:2282: 
2023-04-03T07:03:16.6904845Z         	Error Trace:	D:\a\neo-go\neo-go\pkg\services\rpcsrv\client_test.go:2282
2023-04-03T07:03:16.6905765Z         	            				D:\a\neo-go\neo-go\pkg\services\rpcsrv\client_test.go:2088
2023-04-03T07:03:16.6906026Z         	Error:      	Condition never satisfied
2023-04-03T07:03:16.6906430Z         	Test:       	TestSubClientWaitWithMissedEvent/ws
2023-04-03T07:03:16.6907120Z     logger.go:130: 2023-04-03T07:03:14.520Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:51308"}
2023-04-03T07:03:16.6907779Z     logger.go:130: 2023-04-03T07:03:15.334Z	INFO	persisted to disk	{"blocks": 0, "keys": 105, "headerHeight": 0, "blockHeight": 0, "took": "814.3653ms"}
2023-04-03T07:03:16.6907969Z === RUN   TestSubClientWaitWithMissedEvent/local
2023-04-03T07:03:16.6908640Z     logger.go:130: 2023-04-03T07:03:15.882Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2023-04-03T07:03:16.6909463Z     logger.go:130: 2023-04-03T07:03:15.882Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2023-04-03T07:03:16.6910080Z     logger.go:130: 2023-04-03T07:03:15.882Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2023-04-03T07:03:16.6910750Z     logger.go:130: 2023-04-03T07:03:15.882Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2023-04-03T07:03:16.6911526Z     logger.go:130: 2023-04-03T07:03:15.882Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2023-04-03T07:03:16.6912283Z     logger.go:130: 2023-04-03T07:03:15.882Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2023-04-03T07:03:16.6912769Z     logger.go:130: 2023-04-03T07:03:15.891Z	INFO	no storage version found! creating genesis block
2023-04-03T07:03:16.6913412Z     logger.go:130: 2023-04-03T07:03:15.897Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-04-03T07:03:16.6914140Z     logger.go:130: 2023-04-03T07:03:15.897Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2023-04-03T07:03:16.6914624Z     logger.go:130: 2023-04-03T07:03:15.897Z	INFO	starting rpc-server	{"endpoint": "localhost:0"}
2023-04-03T07:03:16.6915182Z     logger.go:130: 2023-04-03T07:03:15.897Z	DEBUG	processing local rpc request	{"method": "getversion", "params": "[]"}
2023-04-03T07:03:16.6915799Z     logger.go:130: 2023-04-03T07:03:15.897Z	DEBUG	processing local rpc request	{"method": "getnativecontracts", "params": "[]"}
2023-04-03T07:03:16.6916373Z     logger.go:130: 2023-04-03T07:03:15.913Z	DEBUG	processing local rpc request	{"method": "getversion", "params": "[]"}
2023-04-03T07:03:16.6916974Z     logger.go:130: 2023-04-03T07:03:15.913Z	DEBUG	processing local rpc request	{"method": "subscribe", "params": "[block_added ]"}
2023-04-03T07:03:16.6917597Z     logger.go:130: 2023-04-03T07:03:15.913Z	DEBUG	processing local rpc request	{"method": "subscribe", "params": "[transaction_executed ]"}
2023-04-03T07:03:16.6918447Z     logger.go:130: 2023-04-03T07:03:15.913Z	DEBUG	processing local rpc request	{"method": "getapplicationlog", "params": "[f01e1986ee63cc9437516745cfb7f57108432d5493a7c159a1082900c6afb316 Application]"}
2023-04-03T07:03:16.6918714Z panic: Fail in goroutine after TestSubClientWaitWithMissedEvent/ws has completed
2023-04-03T07:03:16.6918730Z 
2023-04-03T07:03:16.6918846Z goroutine 6871 [running]:
2023-04-03T07:03:16.6919058Z testing.(*common).Fail(0xc0050164e0)
2023-04-03T07:03:16.6919325Z 	C:/hostedtoolcache/windows/go/1.20.2/x64/src/testing/testing.go:933 +0x1a8
2023-04-03T07:03:16.6919535Z testing.(*common).Errorf(0xc0050164e0, {0x14d946a, 0x3}, {0xc006ea0000, 0x1, 0x1})
2023-04-03T07:03:16.6919775Z 	C:/hostedtoolcache/windows/go/1.20.2/x64/src/testing/testing.go:1050 +0xaf
2023-04-03T07:03:16.6920032Z github.com/stretchr/testify/assert.Fail({0x17d0ca0, 0xc0050164e0}, {0xc00781e000, 0x132}, {0x0, 0x0, 0x0})
2023-04-03T07:03:16.6920341Z 	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:264 +0x412
2023-04-03T07:03:16.6921269Z github.com/stretchr/testify/assert.NoError({0x17d0ca0, 0xc0050164e0}, {0x17cd080, 0xc0076406c0}, {0x0, 0x0, 0x0})
2023-04-03T07:03:16.6921793Z 	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:1392 +0x127
2023-04-03T07:03:16.6922070Z github.com/stretchr/testify/require.NoError({0x17d6750, 0xc0050164e0}, {0x17cd080, 0xc0076406c0}, {0x0, 0x0, 0x0})
2023-04-03T07:03:16.6922350Z 	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.0/require/require.go:1261 +0xa5
2023-04-03T07:03:16.6922833Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.testSubClientWaitWithMissedEvent.func1()
2023-04-03T07:03:16.6923589Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:2275 +0x190
2023-04-03T07:03:16.6924086Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.testSubClientWaitWithMissedEvent
2023-04-03T07:03:16.6924412Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:2273 +0x58c
2023-04-03T07:03:16.6924702Z FAIL	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv	51.189s
```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #2958

### CODE REVIEW

File: pkg/services/rpcsrv/client_test.go [hunk 1]
```diff
@@ -2050,10 +2050,18 @@ func testSubClientWaitWithMissedEvent(t *testing.T, local bool) {
 	b1 := blocks[0]
 	tx := b1.Transactions[0]
 
-	rcvr := make(chan *state.AppExecResult)
+	rcvr := make(chan *state.AppExecResult, 1)
+	errCh := make(chan error, 1) // Error channel for goroutine errors
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/client_test.go:2054]: These channels must not be buffered.

File: pkg/services/rpcsrv/client_test.go [hunk 2]
```diff
@@ -2050,10 +2050,18 @@ func testSubClientWaitWithMissedEvent(t *testing.T, local bool) {
...
+
+	var wg sync.WaitGroup
+	wg.Add(1)
 	go func() {
+		defer wg.Done()
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/client_test.go:2059]: Won't save from failure. You have this for the first (local client) test:
```
2023-04-03T07:03:16.6904087Z     client_test.go:2282: 
2023-04-03T07:03:16.6904845Z         	Error Trace:	D:\a\neo-go\neo-go\pkg\services\rpcsrv\client_test.go:2282
2023-04-03T07:03:16.6905765Z         	            				D:\a\neo-go\neo-go\pkg\services\rpcsrv\client_test.go:2088
2023-04-03T07:03:16.6906026Z         	Error:      	Condition never satisfied
2023-04-03T07:03:16.6906430Z         	Test:       	TestSubClientWaitWithMissedEvent/ws
```
Caused by slow subscriptions here:
```
	require.Eventually(t, func() bool {
		rpcSrv.subsLock.Lock()
		defer rpcSrv.subsLock.Unlock()
		return len(rpcSrv.subscribers) == 1
	}, time.Second, 100*time.Millisecond)
```
But the awaiting goroutine from this test is up and running, so it fails when the first test is already finished, and the second test is running:
```
2023-04-03T07:03:16.6918714Z panic: Fail in goroutine after TestSubClientWaitWithMissedEvent/ws has completed
2023-04-03T07:03:16.6918730Z 
2023-04-03T07:03:16.6918846Z goroutine 6871 [running]:
2023-04-03T07:03:16.6919058Z testing.(*common).Fail(0xc0050164e0)
2023-04-03T07:03:16.6919325Z 	C:/hostedtoolcache/windows/go/1.20.2/x64/src/testing/testing.go:933 +0x1a8
2023-04-03T07:03:16.6919535Z testing.(*common).Errorf(0xc0050164e0, {0x14d946a, 0x3}, {0xc006ea0000, 0x1, 0x1})
2023-04-03T07:03:16.6919775Z 	C:/hostedtoolcache/windows/go/1.20.2/x64/src/testing/testing.go:1050 +0xaf
2023-04-03T07:03:16.6920032Z github.com/stretchr/testify/assert.Fail({0x17d0ca0, 0xc0050164e0}, {0xc00781e000, 0x132}, {0x0, 0x0, 0x0})
2023-04-03T07:03:16.6920341Z 	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:264 +0x412
2023-04-03T07:03:16.6921269Z github.com/stretchr/testify/assert.NoError({0x17d0ca0, 0xc0050164e0}, {0x17cd080, 0xc0076406c0}, {0x0, 0x0, 0x0})
2023-04-03T07:03:16.6921793Z 	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:1392 +0x127
2023-04-03T07:03:16.6922070Z github.com/stretchr/testify/require.NoError({0x17d6750, 0xc0050164e0}, {0x17cd080, 0xc0076406c0}, {0x0, 0x0, 0x0})
2023-04-03T07:03:16.6922350Z 	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.0/require/require.go:1261 +0xa5
2023-04-03T07:03:16.6922833Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.testSubClientWaitWithMissedEvent.func1()
2023-04-03T07:03:16.6923589Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:2275 +0x190
2023-04-03T07:03:16.6924086Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.testSubClientWaitWithMissedEvent
2023-04-03T07:03:16.6924412Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:2273 +0x58c
2023-04-03T07:03:16.6924702Z FAIL	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv	51.189s
```
The failing goroutine is this one:
```
	go func() {
		aer, err := act.Wait(tx.Hash(), tx.ValidUntilBlock, nil)
		require.NoError(t, err)
		rcvr <- aer
	}()
```

First of all, we don't have this problem in the current master because now our server is properly shutted down. But the fix with a separate error channel is valid and can be implemented. Also, just increase waiting interval for subscriptions awaiting up to 2 seconds.

**Review by AnnaShaleva — CHANGES_REQUESTED** [review]

**Comment by AnnaShaleva** [comment]
> still have this but maybe connected with https://github.com/nspcc-dev/neo-go/issues/2956:

Don't pullute the PR comments with unrelated logs, otherwise we have a mess in logs and PRs/Issues links. It's a different test that is failing (`TestFilteredNotaryRequestSubscriptions`), and the reason is completely different from the current test failure. The reason looks more like https://github.com/nspcc-dev/neo-go/issues/3314. Create a separate issue for this test and try to solve it with the approach presented in https://github.com/nspcc-dev/neo-go/pull/3368.

File: pkg/services/rpcsrv/client_test.go [hunk 3]
```diff
@@ -2064,7 +2064,7 @@ func testSubClientWaitWithMissedEvent(t *testing.T, local bool) {
 		rpcSrv.subsLock.Lock()
 		defer rpcSrv.subsLock.Unlock()
 		return len(rpcSrv.subscribers) == 1
-	}, time.Second, 100*time.Millisecond)
+	}, 2*time.Second, 100*time.Millisecond)
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/client_test.go:2067]: The fix with a separate error channel was valid, we need to keep it.

Comment (AnnaShaleva) [reply pkg/services/rpcsrv/client_test.go:2067]: Just don't make the error channel buffered. It should be a simple non-buffered channel.

**Review by AnnaShaleva — APPROVED** [review]
I'm still not quite sure that it fixes the problem, but let's try, because I don't have any other suggestions.
