### PR TITLE
vm: fix packmap operation

### LINKED ISSUE #3613: packmap operation keeps duplicate entries
## Current Behavior

packmap keeps duplicate keys (and entries)
behavior might be considered undefined, though its probably better to copy C# implementation

image

```json
[
  {
    "type": "Map",
    "value": [
      {
        "key": {
          "type": "Integer",
          "value": "1"
        },
        "value": {
          "type": "Integer",
          "value": "1"
        }
      },
      {
        "key": {
          "type": "Integer",
          "value": "1"
        },
        "value": {
          "type": "Integer",
          "value": "1"
        }
      }
    ]
  }
]
```

## Expected Behavior

C# results:
```json
[
  {
    "type": "Map",
    "value": [
      {
        "key": {
          "type": "Integer",
          "value": "1"
        },
        "value": {
          "type": "Integer",
          "value": "1"
        }
      }
    ]
  }
]
```

## Steps to Reproduce

1. `./bin/neo-go vm`
2. `loadbase64 ERERERK+`
3. `run`

## Your Environment

* Version of the product used: master (a9242535db757faba860e21c194033f30c679f48)

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3613

### CODE REVIEW

File: pkg/vm/stackitem/json_test.go [hunk 1]
```diff
@@ -385,8 +385,10 @@ func TestToJSONWithTypesBadCases(t *testing.T) {
 	t.Run("overflow on map key", func(t *testing.T) {
 		m := NewMapWithValue([]MapElement{
 			{NewBool(true), NewBool(true)},
-			{NewByteArray(bigBuf), NewBool(true)},
 		})
+		for i := 1; i < MaxSize/85; i++ {
```
Comment (AliceInHunterland) [inline pkg/vm/stackitem/json_test.go:389]: Maybe MaxSerialized better

File: pkg/vm/vm.go [hunk 2]
```diff
@@ -1214,15 +1214,14 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
 			panic("invalid length")
 		}
 
-		items := make([]stackitem.MapElement, n)
-		for i := range n {
+		newMap := stackitem.NewMap()
```
Comment (AnnaShaleva) [inline pkg/vm/vm.go:1217]: > newMap

m

File: pkg/vm/vm.go [hunk 3]
```diff
@@ -1214,15 +1214,14 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
...
+		for range n {
 			key := v.estack.Pop()
 			validateMapKey(key)
 			val := v.estack.Pop().value
-			items[i].Key = key.value
-			items[i].Value = val
+			newMap.Add(key.Item(), val)
```
Comment (AnnaShaleva) [inline pkg/vm/vm.go:1222]: This way is not optimal, verification is performed twice.

File: pkg/vm/stackitem/item.go [hunk 4]
```diff
@@ -826,12 +826,14 @@ func NewMap() *Map {
 
 // NewMapWithValue returns a new Map object filled with the specified value.
 func NewMapWithValue(value []MapElement) *Map {
-	if value != nil {
-		return &Map{
-			value: value,
+	res := NewMap()
+	for i := range value {
+		if err := IsValidMapKey(value[i].Key); err != nil {
+			panic(err)
```
Comment (AnnaShaleva) [inline pkg/vm/stackitem/item.go:832]: It's too risky to panic inside `NewMapWithValue`, it may be used outside the VM. Either adjust a documentation of this function and don't check for `value` correctness or change the signature of this function to return error. BTW, with the updated PACKMAP, do we really use this function anywhere?

**Comment by AnnaShaleva** [comment]
Add a designated compatibility test, please.

File: pkg/vm/stackitem/item.go (hunk 4 above)
Comment (AliceInHunterland) [reply pkg/vm/stackitem/item.go:832]: No, `NewMapWithValue` is used only in tests.

File: pkg/vm/stackitem/item_test.go [hunk 5]
```diff
@@ -591,14 +591,17 @@ func TestDeepCopy(t *testing.T) {
...
+		expexted.Add(NewBool(false), NewBool(false))
+		expexted.MarkAsReadOnly()
+		m[0] = MapElement{Key: NewBool(true), Value: expexted}
+		m[1] = MapElement{Key: NewBigInteger(big.NewInt(1)), Value: NewByteArray([]byte{1, 2, 3})}
+		res := NewMapWithValue(m)
+		res.MarkAsReadOnly()
+		actual := DeepCopy(res, false)
+		require.Equal(t, res, actual)
+		require.False(t, res == actual)
+		require.Equal(t, expexted, actual.(*Map).value[0].Value)
```
Comment (AnnaShaleva) [inline pkg/vm/stackitem/item_test.go:605]: And now it looks like a useless change to me.

File: pkg/vm/stackitem/json_test.go [hunk 6]
```diff
@@ -389,6 +389,12 @@ func TestToJSONWithTypesBadCases(t *testing.T) {
 		})
 		_, err := ToJSONWithTypes(m)
 		require.ErrorIs(t, err, errTooBigSize)
+		m = NewMap()
+		for i := 1; i < MaxSerialized; i++ {
+			m.Add(NewBigInteger(big.NewInt(int64(i))), NewBigInteger(big.NewInt(123456)))
+		}
+		_, err = ToJSONWithTypes(m)
+		require.ErrorIs(t, err, errTooBigSize)
```
Comment (AnnaShaleva) [inline pkg/vm/stackitem/json_test.go:397]: Ditto.

File: pkg/vm/vm.go [hunk 7]
```diff
@@ -1214,15 +1214,13 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
...
-		for i := range n {
-			key := v.estack.Pop()
-			validateMapKey(key)
+		m := stackitem.NewMap()
+		for range n {
+			key := v.estack.Pop().value
 			val := v.estack.Pop().value
-			items[i].Key = key.value
-			items[i].Value = val
+			m.Add(key, val)
```
Comment (AnnaShaleva) [inline pkg/vm/vm.go:1221]: The case of nil key is not handled by `m.Add`, the behaviour should be compatible with `validateMapKey`. And BTW, this change also fixes another bug that makes stack incompatible with C# node in case of invalid key, because C# node firstly POPs *both* key and value, and only after that validates map key.

File: pkg/vm/vm_test.go [hunk 8]
```diff
@@ -2083,6 +2083,43 @@ func TestUNPACKBadNotArray(t *testing.T) {
...
+		vm.estack.PushVal(values[i])
+		vm.estack.PushVal(keys[i])
+	}
+
+	vm.estack.PushVal(len(keys))
+	runVM(t, vm)
+
+	require.Equal(t, 1, vm.estack.Len())
+	packedItem := vm.estack.Pop().Item()
+	assert.IsType(t, &stackitem.Map{}, packedItem)
```
Comment (AnnaShaleva) [inline pkg/vm/vm_test.go:2103]: Just `assert.Equal(t, stackitem.MapT, packedItem.Type())`, don't use reflection if it's possible.

Comment (AnnaShaleva) [reply pkg/vm/vm_test.go:2103]: And BTW, use `require` instead of `assert`, it's a critical error.

File: pkg/vm/vm_test.go [hunk 9]
```diff
@@ -2083,6 +2083,43 @@ func TestUNPACKBadNotArray(t *testing.T) {
...
+		index := packedMap.Index(stackitem.Make(key))
+		res := packedMap.Value().([]stackitem.MapElement)
+		b, err := res[index].Value.TryBytes()
+		require.NoError(t, err)
+		assert.Equal(t, []byte(expectedValue), b)
+	}
+
+	checkKeyValue("duplicateKey", "value1")
+	checkKeyValue("uniqueKey", "value2")
+	checkKeyValue("anotherUniqueKey", "value4")
```
Comment (AnnaShaleva) [inline pkg/vm/vm_test.go:2120]: Too complicated, and this check depends on `Index()` implementation. Replace it with `require.Equal(t, []stackitem.Item{stackitem.MapElement{...}, ...}, packedMap.Value())`.

File: pkg/vm/vm.go [hunk 10]
```diff
@@ -1214,15 +1214,15 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
...
-			validateMapKey(key)
+		m := stackitem.NewMap()
+		for range n {
+			key := v.estack.Pop().value
 			val := v.estack.Pop().value
-			items[i].Key = key.value
-			items[i].Value = val
+			if key != nil {
+				m.Add(key, val)
+			}
```
Comment (AnnaShaleva) [inline pkg/vm/vm.go:1223]: The behaviour must be compatible with the old implementation. Review the implementation of `validateMapKey`.
