### PR TITLE
core: fix key clashes in Storage.Find

### LINKED ISSUE #1873: Search short storage keys using integer prefix
neo-go v0.94.0
I found unexpected behavior of search iterator with integer number as a prefix. 

Consider there are several storage items that starts with the integer number.

```go
func Init() {
	ctx := storage.GetContext()
	value := []byte("value")

	storage.Put(ctx, []byte{0x01, 2, 3}, value)
	storage.Put(ctx, []byte{0x01, 4, 5}, value)
	storage.Put(ctx, []byte{0x01, 6, 7}, value)
	storage.Put(ctx, []byte{0x01, 11, 12, 13, 14, 15, 16, 17, 18, 19}, value)
	storage.Put(ctx, []byte{0x01, 21, 22, 23, 24, 25, 26, 27, 28, 29}, value)
	storage.Put(ctx, []byte{0x01, 31, 32, 33, 34, 35, 36, 37, 38, 39}, value)
}
```

In the example there are three **short** (less than 10 bytes) keys and three **long** (10 or more bytes) keys all starting with `0x01` which is binary representation of integer `1`. 

Let's search those keys by using `storage.Find` iterator with integer prefix.

```go
func Search() [][]byte {
	ctx := storage.GetReadOnlyContext()

	var i int = 1
	var result [][]byte

	it := storage.Find(ctx, i, storage.KeysOnly)

	for iterator.Next(it) {
		key := iterator.Value(it).([]byte)
		result = append(result, key)
	}

	return result
}
```

For some reason `Search` function will return **all long** keys but only **one short** key.

```
{
  "state": "HALT",
  "gasconsumed": "8920020",
  "script": "EMAfDAZzZWFyY2gMFGx75fae16S5dJKn5hvwFD2E1sbvQWJ9W1I=",
  "stack": [
    {
      "type": "Array",
      "value": [
        {
          "type": "Buffer",
          "value": "AQQF"
        },
        {
          "type": "Buffer",
          "value": "AQsMDQ4PEBESEw=="
        },
        {
          "type": "Buffer",
          "value": "ARUWFxgZGhscHQ=="
        },
        {
          "type": "Buffer",
          "value": "AR8gISIjJCUmJw=="
        }
      ]
    }
  ]
}
```

Search with `[]byte{0x01}` prefix is fine, but sometimes it is much easier to use integer value without explicit transformations to `[]byte` type.

### PR DESCRIPTION
**Pull request by roman-khimov**
Fixes #1873. NewByteArray() doesn't copy the slice, so we need to do it
ourselves.

### CODE REVIEW

File: pkg/core/interop_neo.go [hunk 1]
```diff
@@ -49,7 +49,10 @@ func storageFind(ic *interop.Context) error {
 
 	filteredMap := stackitem.NewMap()
 	for k, v := range siMap {
-		filteredMap.Add(stackitem.NewByteArray(append(prefix, []byte(k)...)), stackitem.NewByteArray(v))
+		key := append(prefix, []byte(k)...)
+		keycopy := make([]byte, len(key))
```
Comment (fyrchik) [inline pkg/core/interop_neo.go:53]: We can simply copy `prefix` and `k` to `keycopy`. This will save us 2 allocations (if we also replace `[]byte(k)` with `k`).
Some test is also desired.

**Review by fyrchik — APPROVED** [review]
