### PR TITLE
cli: fix empty block uploading in `util upload-bin`

### LINKED ISSUE #3630: Empty block objects constructed by `upload-bin` command
## Current Behavior

SkipIndexFilesSearch: true

```
2024-10-21T12:39:15.137+0300    INFO    persisted to disk       {"blocks": 1, "keys": 20, "headerHeight": 88000, "blockHeight": 88000, "took": "17.379834ms"}
2024-10-21T12:39:45.864+0300    ERROR   failed to read block oid        {"oid": "ArKpmCjCCXFQrLWkrhzBgcHLMfd51qANurzT1ekzXNhK", "error": "EOF"}
2024-10-21T12:39:45.864+0300    INFO    shutting down NeoFS BlockFetcher service        {"force": true}
```

```
(base) ekaterinapavlova@MacBook-Air-4 neofs-node % ./bin/neofs-cli object head -r st1.storage.fs.neo.org:8080 -w /Users/ekaterinapavlova/Workplace/neo-go/panelwallet1.json --cid HmP48JvCcmiEbJemG7jFNEg2qkdCTx4thD3EwWUi288Q --oid ArKpmCjCCXFQrLWkrhzBgcHLMfd51qANurzT1ekzXNhK
ID: ArKpmCjCCXFQrLWkrhzBgcHLMfd51qANurzT1ekzXNhK
CID: HmP48JvCcmiEbJemG7jFNEg2qkdCTx4thD3EwWUi288Q
Owner: NS1QWpgWG5YWud59RdSrAgwMdD6UVkdkSh
CreatedAt: 1
Size: 0
HomoHash: 00000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
Checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Type: REGULAR
Attributes:
  block=99318
  primary=2
  hash=df52e560a0c08d19830c9f5cf1b0b9a77e7f12a0b3e91cd0fe75a8a2e908b6b3
  prevHash=15d4d8cbc4306df06429503d85d855a425b6464590dee83dba158cda3831fccf
  timestamp=1652400646552
ID signature:
  public key: 03097d44b8b933c77c52ffdda0acffb2a18ba4f092ba5de0c689d360fa55b9b00f
  signature: 0206f37e2ce2282a0ee5de9beb401c543356cd89f36c059c642668bccb7e30fca3e5b35c7bcb933fac8b273ace7b68a7485ea9877c27c0afa43293e5754a9911
```

```
2024-10-21T12:39:15.137+0300    INFO    persisted to disk       {"blocks": 1, "keys": 20, "headerHeight": 88000, "blockHeight": 88000, "took": "17.379834ms"}
2024-10-21T12:39:45.864+0300    ERROR   failed to read block oid        {"oid": "ArKpmCjCCXFQrLWkrhzBgcHLMfd51qANurzT1ekzXNhK", "error": "EOF"}
2024-10-21T12:39:45.864+0300    INFO    shutting down NeoFS BlockFetcher service        {"force": true}

```
## Expected Behavior

not empty block object 

## Context
`upload-bin` command uploading blocks as objects.

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3630

### CODE REVIEW

File: cli/util/uploader.go [hunk 1]
```diff
@@ -163,9 +163,9 @@ func uploadBin(ctx *cli.Context) error {
 						*object.NewAttribute("prevHash", blk.PrevHash.StringLE()),
 						*object.NewAttribute("timestamp", strconv.FormatUint(blk.Timestamp, 10)),
 					}
-
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:166]: Useless change.

**Review by AnnaShaleva — COMMENTED** [review]
Otherwise LGTM, as always, one-line change.

**Review by AnnaShaleva — APPROVED** [review]
