### PR TITLE
compiler: compile appcall with dynamic argument

### LINKED ISSUE #1160: Compiler does not compile contract with dynamic app call
neo-go version 0.90.0-pre-652-gcf1e5243

I have dynamic `AppCall` in my contract and it fails on compile time: `Received unexpected error: invalid script hash`.

```go 
package foo
import "github.com/nspcc-dev/neo-go/pkg/interop/engine"
func Main() int {
	addr := []byte{0x77, 0xea, 0x59, 0x6b, 0x7a, 0xdf, 0x7e, 0x4d, 0xd1, 0x40, 0x76, 0x97, 0x31, 0xb7, 0xd2, 0xf0, 0xe0, 0x6b, 0xcd, 0x9b}
	engine.AppCall(addr, "Method")
	return 0
}
```

I expect runtime error, but got compilation error. `AppCall` with constant script hash compiles correctly.

```go 
	const addrStr = "\x77\xea\x59\x6b\x7a\xdf\x7e\x4d\xd1\x40\x76\x97\x31\xb7\xd2\xf0\xe0\x6b\xcd\x9b"
	engine.AppCall([]byte(addrStr), "Method")
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Closes #1160

### CODE REVIEW

File: pkg/compiler/codegen.go [hunk 1]
```diff
@@ -1138,8 +1138,12 @@ func (c *codegen) getByteArray(expr ast.Expr) []byte {
 			val := constant.StringVal(tv.Value)
 			return []byte(val)
 		}
-
```
Comment (roman-khimov) [inline pkg/compiler/codegen.go:1141]: Useless change.

File: pkg/compiler/codegen.go [hunk 2]
```diff
@@ -1138,8 +1138,12 @@ func (c *codegen) getByteArray(expr ast.Expr) []byte {
...
 		return nil
+	case *ast.Ident:
```
Comment (roman-khimov) [inline pkg/compiler/codegen.go:1142]: I don't think it's supposed to work with `ast.Ident` (`getByteArray returns byte array value from constant expr`).

**Comment by roman-khimov** [comment]
Try something like
```patch
--- a/pkg/compiler/codegen.go
+++ b/pkg/compiler/codegen.go
@@ -1210,7 +1210,7 @@ func (c *codegen) convertBuiltin(expr *ast.CallExpr) {
        case "AppCall":
                c.emitReverse(len(expr.Args))
                buf := c.getByteArray(expr.Args[0])
-               if len(buf) != 20 {
+               if buf != nil && len(buf) != 20 {
                        c.prog.Err = errors.New("invalid script hash")
                }
                emit.Syscall(c.prog.BinWriter, "System.Contract.Call")
```
And add a test, please.
