### PR TITLE
rpcsrv: fix RPC iterator deadlock

### LINKED ISSUE #4055: MemCahedStore deadlock on header hash batch persist
## Current Behavior
`invokefunction` request tries to access header hash to create test VM:
```
2025-10-31T15:06:34.891135600Z goroutine 1052166 gp=0xc00019bc00 m=nil [sync.RWMutex.RLock, 179 minutes]:
2025-10-31T15:06:34.891138096Z runtime.gopark(0xfa43d7?, 0xc003557200?, 0xe8?, 0x72?, 0xc001216240?)
2025-10-31T15:06:34.891145591Z 	runtime/proc.go:460 +0xce fp=0xc003557188 sp=0xc003557168 pc=0x480d4e
2025-10-31T15:06:34.891148350Z runtime.goparkunlock(...)
2025-10-31T15:06:34.891150727Z 	runtime/proc.go:466
2025-10-31T15:06:34.891160949Z runtime.semacquire1(0xc00000501c, 0x0, 0x3, 0x0, 0x17)
2025-10-31T15:06:34.891193061Z 	runtime/sema.go:192 +0x21d fp=0xc0035571f0 sp=0xc003557188 pc=0x45ea5d
2025-10-31T15:06:34.891195249Z sync.runtime_SemacquireRWMutexR(0x13000000000000?, 0x0?, 0x740b11050f30?)
2025-10-31T15:06:34.891196603Z 	runtime/sema.go:100 +0x25 fp=0xc003557228 sp=0xc0035571f0 pc=0x4820c5
2025-10-31T15:06:34.891197947Z sync.(*RWMutex).RLock(...)
2025-10-31T15:06:34.891201423Z 	sync/rwmutex.go:74
2025-10-31T15:06:34.891202740Z github.com/nspcc-dev/neo-go/pkg/core.(*HeaderHashes).GetHeaderHash(0xc000005008, 0xce8)
2025-10-31T15:06:34.891229275Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/headerhashes.go:215 +0x59 fp=0xc0035572c0 sp=0xc003557228 pc=0xe83f19
2025-10-31T15:06:34.891232447Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).GetFakeNextBlock(0xc000005008, 0xce9)
2025-10-31T15:06:34.891234837Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/blockchain.go:3263 +0x65 fp=0xc003557338 sp=0xc0035572c0 pc=0xe80c25
2025-10-31T15:06:34.891237310Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).GetTestVM(0xc000005008, 0x40, 0xc00113bc30, 0x52a308?)
2025-10-31T15:06:34.891239813Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/blockchain.go:3211 +0x3c fp=0xc0035573b0 sp=0xc003557338 pc=0xe8037c
2025-10-31T15:06:34.891242540Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).prepareInvocationContext(0xc0002e4c88, 0x40, {0xc001746380, 0x5c, 0x80}, {0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
2025-10-31T15:06:34.891251399Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:2478 +0x145 fp=0xc0035574a0 sp=0xc0035573b0 pc=0xeb0d85
2025-10-31T15:06:34.891267699Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).runScriptInVM(0xc0002e4c88, 0x40, {0xc001746380, 0x5c, 0x80}, {0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
2025-10-31T15:06:34.891274100Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:2523 +0x85 fp=0xc003557628 sp=0xc0035574a0 pc=0xeb1385
2025-10-31T15:06:34.891298590Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).invokeFunction(0xc0002e4c88, {0xc00103ea00?, 0xc000e07de0?, 0xe?})
2025-10-31T15:06:34.891302887Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:2171 +0x65 fp=0xc003557698 sp=0xc003557628 pc=0xeae865
2025-10-31T15:06:34.891304609Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleIn(0xc0002e4c88, 0xc001a69b30, 0x0)
2025-10-31T15:06:34.891308973Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:667 +0x5f1 fp=0xc003557830 sp=0xc003557698 pc=0xea0011
2025-10-31T15:06:34.891313163Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleRequest(0xc0002e4c88, 0xc001fc4640, 0x0)
2025-10-31T15:06:34.891318636Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:593 +0xd1 fp=0xc003557970 sp=0xc003557830 pc=0xe9f031
2025-10-31T15:06:34.891341856Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest(0xc0002e4c88, {0x157e698, 0xc0002634a0}, 0xc001313040)
2025-10-31T15:06:34.891345220Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:572 +0xa2a fp=0xc003557b08 sp=0xc003557970 pc=0xe9ebca
2025-10-31T15:06:34.891352110Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest-fm({0x157e698?, 0xc0002634a0?}, 0x4f08d3?)
2025-10-31T15:06:34.891360551Z 	<autogenerated>:1 +0x36 fp=0xc003557b38 sp=0xc003557b08 pc=0xeba536
2025-10-31T15:06:34.891368342Z net/http.HandlerFunc.ServeHTTP(0x41d445?, {0x157e698?, 0xc0002634a0?}, 0xc000263401?)
2025-10-31T15:06:34.891375583Z 	net/http/server.go:2322 +0x29 fp=0xc003557b60 sp=0xc003557b38 pc=0x7d6f29
2025-10-31T15:06:34.891381429Z net/http.serverHandler.ServeHTTP({0x1579268?}, {0x157e698?, 0xc0002634a0?}, 0x1?)
2025-10-31T15:06:34.891389703Z 	net/http/server.go:3340 +0x8e fp=0xc003557b90 sp=0xc003557b60 pc=0x7f774e
2025-10-31T15:06:34.891396436Z net/http.(*conn).serve(0xc001bad8c0, {0x1581208, 0xc002ce7230})
2025-10-31T15:06:34.891405728Z 	net/http/server.go:2109 +0x665 fp=0xc003557fb8 sp=0xc003557b90 pc=0x7d5025
2025-10-31T15:06:34.891407142Z net/http.(*Server).Serve.gowrap3()
2025-10-31T15:06:34.891414777Z 	net/http/server.go:3493 +0x28 fp=0xc003557fe0 sp=0xc003557fb8 pc=0x7dad08
2025-10-31T15:06:34.891444978Z runtime.goexit({})
2025-10-31T15:06:34.891448081Z 	runtime/asm_amd64.s:1693 +0x1 fp=0xc003557fe8 sp=0xc003557fe0 pc=0x488b81
2025-10-31T15:06:34.891450633Z created by net/http.(*Server).Serve in goroutine 402
2025-10-31T15:06:34.891453058Z 	net/http/server.go:3493 +0x485
```

At the same time `(*HeaderHashes).addHeaders` holds `HeaderHashes` mutex taken and tries to persist subsequent batch of header hashes:
```
2025-10-31T15:06:34.890479791Z goroutine 144 gp=0xc00019b500 m=nil [sync.RWMutex.Lock, 180 minutes]:
2025-10-31T15:06:34.890482369Z runtime.gopark(0x70901567300?, 0xc0015673c0?, 0xa0?, 0x54?, 0x80?)
2025-10-31T15:06:34.890484730Z 	runtime/proc.go:460 +0xce fp=0xc001567358 sp=0xc001567338 pc=0x480d4e
2025-10-31T15:06:34.890487415Z runtime.goparkunlock(...)
2025-10-31T15:06:34.890489789Z 	runtime/proc.go:466
2025-10-31T15:06:34.890499065Z runtime.semacquire1(0xc0002185f8, 0x0, 0x3, 0x0, 0x18)
2025-10-31T15:06:34.890505255Z 	runtime/sema.go:192 +0x21d fp=0xc0015673c0 sp=0xc001567358 pc=0x45ea5d
2025-10-31T15:06:34.890510893Z sync.runtime_SemacquireRWMutex(0x47e65e?, 0x48?, 0x11a9d40?)
2025-10-31T15:06:34.890521675Z 	runtime/sema.go:105 +0x25 fp=0xc0015673f8 sp=0xc0015673c0 pc=0x482125
2025-10-31T15:06:34.890524997Z sync.(*RWMutex).Lock(0x41c774?)
2025-10-31T15:06:34.890533416Z 	sync/rwmutex.go:155 +0x6b fp=0xc001567428 sp=0xc0015673f8 pc=0x49f9ab
2025-10-31T15:06:34.890536797Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).lock(...)
2025-10-31T15:06:34.890539167Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:69
2025-10-31T15:06:34.890541855Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).PutChangeSet(0xc0002185f0, 0xc000a59860, 0xc000a598c0)
2025-10-31T15:06:34.890550449Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:149 +0x3e fp=0xc0015674f0 sp=0xc001567428 pc=0xac343e
2025-10-31T15:06:34.890557702Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).persist(0xc000236190, 0x78?)
2025-10-31T15:06:34.890564642Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:387 +0x3ab fp=0xc001567610 sp=0xc0015674f0 pc=0xac5acb
2025-10-31T15:06:34.890578373Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).Persist(...)
2025-10-31T15:06:34.890580609Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:335
2025-10-31T15:06:34.890582096Z github.com/nspcc-dev/neo-go/pkg/core/dao.(*Simple).Persist(0xc0020387e0?)
2025-10-31T15:06:34.890583516Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/dao/dao.go:1031 +0xf8 fp=0xc0015676e8 sp=0xc001567610 pc=0xd05238
2025-10-31T15:06:34.890614783Z github.com/nspcc-dev/neo-go/pkg/core.(*HeaderHashes).addHeaders(0xc000005008, {0xc001567ce0, 0x1, 0x53923f51dfb6e63a?})
2025-10-31T15:06:34.890618407Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/headerhashes.go:175 +0x62f fp=0xc001567888 sp=0xc0015676e8 pc=0xe83baf
2025-10-31T15:06:34.890620908Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).addHeaders(0xc000005008, 0x1, {0xc001567ce0, 0x1, 0x1})
2025-10-31T15:06:34.890623308Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/blockchain.go:1937 +0x63c fp=0xc001567b28 sp=0xc001567888 pc=0xe7631c
2025-10-31T15:06:34.890626087Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).AddBlock(0xc000005008, 0xc000fc4280)
2025-10-31T15:06:34.890628677Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/blockchain.go:1841 +0x632 fp=0xc001567db0 sp=0xc001567b28 pc=0xe75412
2025-10-31T15:06:34.890634857Z github.com/nspcc-dev/neo-go/pkg/network.chainBlockQueueAdapter.AddItem(...)
2025-10-31T15:06:34.890639016Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/network/bqueue_adapters.go:64
2025-10-31T15:06:34.890648169Z github.com/nspcc-dev/neo-go/pkg/network.(*chainBlockQueueAdapter).AddItem(0xc0001f3448?, 0x0?)
2025-10-31T15:06:34.890650250Z 	<autogenerated>:1 +0x29 fp=0xc001567dd0 sp=0xc001567db0 pc=0xcf19a9
2025-10-31T15:06:34.890654847Z github.com/nspcc-dev/neo-go/pkg/network/bqueue.(*Queue[...]).Run(0x158a4e0)
2025-10-31T15:06:34.890659453Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/network/bqueue/queue.go:116 +0x15b fp=0xc001567fc0 sp=0xc001567dd0 pc=0xcec35b
2025-10-31T15:06:34.890666732Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start.gowrap4()
2025-10-31T15:06:34.890678402Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/network/server.go:357 +0x25 fp=0xc001567fe0 sp=0xc001567fc0 pc=0xcdac25
2025-10-31T15:06:34.890682073Z runtime.goexit({})
2025-10-31T15:06:34.890684645Z 	runtime/asm_amd64.s:1693 +0x1 fp=0xc001567fe8 sp=0xc001567fe0 pc=0x488b81
2025-10-31T15:06:34.890686993Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 137
2025-10-31T15:06:34.890689804Z 	github.com/nspcc-dev/neo-go@v0.113.0/pkg/network/server.go:357 +0x3c6
```

We need to find out who is accessing the same instance of memcache store at the same time:

[headerhashes_lock.log](https://github.com/user-attachments/files/23268333/headerhashes_lock.log)

## Expected Behavior
No deadlock.

## Context
Discovered during NeoFS IR load testing.

## Regression
Might be related to HeaderHashes changes introduced by https://github.com/nspcc-dev/neo-go/pull/3922.

## Your Environment
v0.113.0

### PR DESCRIPTION
**Pull request by AnnaShaleva**
One of the iterator sessions holds BoltDB RLock and is awaiting of the value receiver (next iterator traversal attempt):
```
2025-10-31T15:06:34.935505708Z goroutine 1051526 gp=0xc000b02540 m=nil [select, 180 minutes]:
2025-10-31T15:06:34.935538395Z runtime.gopark(0xc001f55830?, 0x2?, 0x10?, 0x57?, 0xc001f55824?)
2025-10-31T15:06:34.935541497Z  runtime/proc.go:460 +0xce fp=0xc001f556b0 sp=0xc001f55690 pc=0x480d4e
2025-10-31T15:06:34.935543853Z runtime.selectgo(0xc001f55830, 0xc001f55820, 0x740aca10a808?, 0x1, 0xc001f55880?, 0x1)
2025-10-31T15:06:34.935550739Z  runtime/select.go:351 +0x8b7 fp=0xc001f557f0 sp=0xc001f556b0 pc=0x45d937
2025-10-31T15:06:34.935560325Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).SeekAsync.func1.1({0xc00205be06, 0x39, 0x3a}, {0xc00126fe40, 0x20, 0x20})
2025-10-31T15:06:34.935563470Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:178 +0xfa fp=0xc001f55890 sp=0xc001f557f0 pc=0xac3c9a
2025-10-31T15:06:34.935577958Z github.com/nspcc-dev/neo-go/pkg/core/storage.performSeek.func2({0xc00205bdc0?, 0x3f?, 0xc001f55a00?}, {0xc00126fe20, 0x20, 0xc001f55a18?})
2025-10-31T15:06:34.935584076Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:293 +0x605 fp=0xc001f559a8 sp=0xc001f55890 pc=0xac50a5
2025-10-31T15:06:34.935598539Z github.com/nspcc-dev/neo-go/pkg/core/storage.performSeek.func2({0x740ac9361625?, 0x3f?, 0x41d445?}, {0x740ac9361664, 0x20, 0x1?})
2025-10-31T15:06:34.935606082Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:293 +0x605 fp=0xc001f55ac0 sp=0xc001f559a8 pc=0xac50a5
2025-10-31T15:06:34.935622279Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*BoltDBStore).Seek.func1(0xc001ac7440?, {0x740ac9361625?, 0x2?, 0xc001f55bb8?}, {0x740ac9361664?, 0xc0000da000?, 0xc001f55c40?})
2025-10-31T15:06:34.935629085Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/boltdb_store.go:128 +0x34 fp=0xc001f55b00 sp=0xc001f55ac0 pc=0xac1854
2025-10-31T15:06:34.935636028Z github.com/nspcc-dev/neo-go/pkg/core/storage.boltSeek.func1(0xc0000da000?)
2025-10-31T15:06:34.935643007Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/boltdb_store.go:160 +0x2c9 fp=0xc001f55bc8 sp=0xc001f55b00 pc=0xac1d29
2025-10-31T15:06:34.935652382Z github.com/nspcc-dev/bbolt.(*DB).View(0x120f700?, 0xc00206dc20)
2025-10-31T15:06:34.935656597Z  github.com/nspcc-dev/bbolt@v0.0.0-20250911202005-807225ebb0c8/db.go:930 +0x6c fp=0xc001f55c30 sp=0xc001f55bc8 pc=0xa621cc
2025-10-31T15:06:34.935659396Z github.com/nspcc-dev/bbolt.(*DB).View-fm(0xc00297df68?)
2025-10-31T15:06:34.935665241Z  <autogenerated>:1 +0x26 fp=0xc001f55c50 sp=0xc001f55c30 pc=0xacf9a6
2025-10-31T15:06:34.935682290Z github.com/nspcc-dev/neo-go/pkg/core/storage.boltSeek(0xc001f55d00, {{0xc00297df68, 0x6, 0x8}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc000117a60)
2025-10-31T15:06:34.935692382Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/boltdb_store.go:137 +0x133 fp=0xc001f55cb0 sp=0xc001f55c50 pc=0xac19f3
2025-10-31T15:06:34.935707504Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*BoltDBStore).Seek(0x0?, {{0xc00297df68, 0x6, 0x8}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc002e0c2a0)
2025-10-31T15:06:34.935716041Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/boltdb_store.go:127 +0xf5 fp=0xc001f55d20 sp=0xc001f55cb0 pc=0xac1795
2025-10-31T15:06:34.935740153Z github.com/nspcc-dev/neo-go/pkg/core/storage.performSeek({0x1581160, 0x2016bc0}, {0x1585620, 0xc000138098}, {0xc000005408, 0xa, 0x12}, {{0xc00297df68, 0x6, 0x8}, ...}, ...)
2025-10-31T15:06:34.935746361Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:307 +0x344 fp=0xc001f55dc0 sp=0xc001f55d20 pc=0xac47e4
2025-10-31T15:06:34.935764672Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).Seek(0x0?, {{0xc00297df68, 0x6, 0x8}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc002e0c1c0)
2025-10-31T15:06:34.935773749Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:158 +0xdf fp=0xc001f55e58 sp=0xc001f55dc0 pc=0xac371f
2025-10-31T15:06:34.935792218Z github.com/nspcc-dev/neo-go/pkg/core/storage.performSeek({0x1581240, 0xc000fb6500}, {0x1585520, 0xc0002185f0}, {0x0, 0x0, 0x0}, {{0xc00297df68, 0x6, 0x8}, ...}, ...)
2025-10-31T15:06:34.935799759Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:307 +0x344 fp=0xc001f55ef8 sp=0xc001f55e58 pc=0xac47e4
2025-10-31T15:06:34.935804638Z github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).SeekAsync.func1()
2025-10-31T15:06:34.935812388Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:177 +0x15b fp=0xc001f55fe0 sp=0xc001f55ef8 pc=0xac3b7b
2025-10-31T15:06:34.935814681Z runtime.goexit({})
2025-10-31T15:06:34.935822592Z  runtime/asm_amd64.s:1693 +0x1 fp=0xc001f55fe8 sp=0xc001f55fe0 pc=0x488b81
2025-10-31T15:06:34.935825193Z created by github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).SeekAsync in goroutine 1010041
2025-10-31T15:06:34.935842199Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/storage/memcached_store.go:176 +0x1cf
```

At the same time, there's a HeaderHashes persisting routine trying to take Lock over BoltDB which leads to a Bolt deadlock on attempt to remmap the DB:
```
2025-10-31T15:06:34.889382646Z goroutine 136 gp=0xc000103500 m=nil [sync.RWMutex.Lock, 180 minutes]:
2025-10-31T15:06:34.889391837Z runtime.gopark(0x7?, 0xc001b2ad48?, 0x0?, 0xe3?, 0xc001b2ada8?)
2025-10-31T15:06:34.889398739Z  runtime/proc.go:460 +0xce fp=0xc001b2ad60 sp=0xc001b2ad40 pc=0x480d4e
2025-10-31T15:06:34.889401434Z runtime.goparkunlock(...)
2025-10-31T15:06:34.889404050Z  runtime/proc.go:466
2025-10-31T15:06:34.889412226Z runtime.semacquire1(0xc0000da150, 0x0, 0x3, 0x0, 0x18)
2025-10-31T15:06:34.889417539Z  runtime/sema.go:192 +0x21d fp=0xc001b2adc8 sp=0xc001b2ad60 pc=0x45ea5d
2025-10-31T15:06:34.889427185Z sync.runtime_SemacquireRWMutex(0x5?, 0xe5?, 0x0?)
2025-10-31T15:06:34.889433292Z  runtime/sema.go:105 +0x25 fp=0xc001b2ae00 sp=0xc001b2adc8 pc=0x482125
2025-10-31T15:06:34.889439833Z sync.(*RWMutex).Lock(0x2019300?)
2025-10-31T15:06:34.889454503Z  sync/rwmutex.go:155 +0x6b fp=0xc001b2ae30 sp=0xc001b2ae00 pc=0x49f9ab
2025-10-31T15:06:34.889457004Z github.com/nspcc-dev/bbolt.(*DB).mmap(0xc0000da000, 0x2001000)
2025-10-31T15:06:34.889459681Z  github.com/nspcc-dev/bbolt@v0.0.0-20250911202005-807225ebb0c8/db.go:451 +0x4b fp=0xc001b2af58 sp=0xc001b2ae30 pc=0xa5f9eb
```

At the same time another RPC iterator traversal request holds session.iteratorsLock and trying to access Bolt to perform the next iterator traversal. Bolt is occupied by other routine, and the iterator watcher can't cancel the context of stale job due to inability to take session.iteratorsLock:
```
2025-10-31T15:06:34.934059649Z goroutine 1010041 gp=0xc000f19880 m=nil [chan receive, 180 minutes]:
2025-10-31T15:06:34.934069829Z runtime.gopark(0xc000c93320?, 0xc0011baf90?, 0x3?, 0x0?, 0x8?)
2025-10-31T15:06:34.934078152Z  runtime/proc.go:460 +0xce fp=0xc001495160 sp=0xc001495140 pc=0x480d4e
2025-10-31T15:06:34.934096362Z runtime.chanrecv(0xc002fa0690, 0xc001495220, 0x1)
2025-10-31T15:06:34.934099227Z  runtime/chan.go:667 +0x473 fp=0xc0014951d8 sp=0xc001495160 pc=0x414fb3
2025-10-31T15:06:34.934101804Z runtime.chanrecv2(0x740b110505c0?, 0x10856e0?)
2025-10-31T15:06:34.934105754Z  runtime/chan.go:514 +0x12 fp=0xc001495200 sp=0xc0014951d8 pc=0x414b32
2025-10-31T15:06:34.934108414Z github.com/nspcc-dev/neo-go/pkg/core/interop/storage.(*Iterator).Next(0xc000b73b60)
2025-10-31T15:06:34.934116114Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/interop/storage/find.go:53 +0x36 fp=0xc001495260 sp=0xc001495200 pc=0xdcb636
2025-10-31T15:06:34.934137731Z github.com/nspcc-dev/neo-go/pkg/core/interop/iterator.Values({0x158c640?, 0xc001b00da0?}, 0x64)
2025-10-31T15:06:34.934140883Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/core/interop/iterator/interop.go:64 +0xf4 fp=0xc0014952f8 sp=0xc001495260 pc=0xe63b14
2025-10-31T15:06:34.934160106Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).traverseIterator(0xc0002e4c88, {0xc001062780, 0x3, 0x10?})
2025-10-31T15:06:34.934163020Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:2703 +0x7db fp=0xc001495698 sp=0xc0014952f8 pc=0xeb2d3b
2025-10-31T15:06:34.934168230Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleIn(0xc0002e4c88, 0xc000be5900, 0x0)
2025-10-31T15:06:34.934170927Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:667 +0x5f1 fp=0xc001495830 sp=0xc001495698 pc=0xea0011
2025-10-31T15:06:34.934173352Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleRequest(0xc0002e4c88, 0xc00041f040, 0x0)
2025-10-31T15:06:34.934178585Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:593 +0xd1 fp=0xc001495970 sp=0xc001495830 pc=0xe9f031
2025-10-31T15:06:34.934211035Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest(0xc0002e4c88, {0x157e698, 0xc002816e10}, 0xc001312c80)
2025-10-31T15:06:34.934214339Z  github.com/nspcc-dev/neo-go@v0.113.0/pkg/services/rpcsrv/server.go:572 +0xa2a fp=0xc001495b08 sp=0xc001495970 pc=0xe9ebca
2025-10-31T15:06:34.934216623Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest-fm({0x157e698?, 0xc002816e10?}, 0x4f08d3?)
2025-10-31T15:06:34.934226612Z  <autogenerated>:1 +0x36 fp=0xc001495b38 sp=0xc001495b08 pc=0xeba536
2025-10-31T15:06:34.934229896Z net/http.HandlerFunc.ServeHTTP(0x41d445?, {0x157e698?, 0xc002816e10?}, 0xc002816e01?)
2025-10-31T15:06:34.934233145Z  net/http/server.go:2322 +0x29 fp=0xc001495b60 sp=0xc001495b38 pc=0x7d6f29
2025-10-31T15:06:34.934243361Z net/http.serverHandler.ServeHTTP({0x1579268?}, {0x157e698?, 0xc002816e10?}, 0x1?)
2025-10-31T15:06:34.934249578Z  net/http/server.go:3340 +0x8e fp=0xc001495b90 sp=0xc001495b60 pc=0x7f774e
2025-10-31T15:06:34.934256256Z net/http.(*conn).serve(0xc000deb320, {0x1581208, 0xc002ce7230})
2025-10-31T15:06:34.934263205Z  net/http/server.go:2109 +0x665 fp=0xc001495fb8 sp=0xc001495b90 pc=0x7d5025
2025-10-31T15:06:34.934266632Z net/http.(*Server).Serve.gowrap3()
2025-10-31T15:06:34.934272893Z  net/http/server.go:3493 +0x28 fp=0xc001495fe0 sp=0xc001495fb8 pc=0x7dad08
2025-10-31T15:06:34.934288349Z runtime.goexit({})
2025-10-31T15:06:34.934291672Z  runtime/asm_amd64.s:1693 +0x1 fp=0xc001495fe8 sp=0xc001495fe0 pc=0x488b81
2025-10-31T15:06:34.934293762Z created by net/http.(*Server).Serve in goroutine 402
2025-10-31T15:06:34.934310547Z  net/http/server.go:3493 +0x485
```

We can't solve Bolt remmap deadlock problem, but can improve session termination mechanism. Get rid of session.iteratorsLock since it's not relevant after 0c45ff8f. It allows to terminate such stale iterator sessions.

Close #4055.

### CODE REVIEW

File: pkg/services/rpcsrv/server.go [hunk 1]
```diff
@@ -2695,19 +2686,21 @@ func (s *Server) traverseIterator(reqParams params.Params) (any, *neorpc.Error)
...
 				if count <= 0 {
+					it.Lock.Unlock()
 					break
 				}
 				iVals = append(iVals, it.Curr)
 				it.Curr = nil
 				count--
 			}
 			iVals = append(iVals, iterator.Values(it.Item, count)...)
+			it.Lock.Unlock()
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server.go:2700]: I thought that we're done with `it.Curr` one line above already and can avoid holding the lock while doing `iterator.Values()`. But at the same time concurrent access to the same iterator needs to have some result consistency as well, so it should be OK here.
