### PR TITLE
cli: fix `upload-bin` error handling

### LINKED ISSUE #3628: Potentially corrupted index files constructed by `upload-bin` command
## Current Behavior
Start the node with BlockFetcher in IndexFiles mode:
```
NeoFSBlockFetcher:
    Enabled: true
    Addresses:
      - st1.storage.fs.neo.org:8080
    Timeout: 10m
    DownloaderWorkersCount: 500
    OIDBatchSize: 8000
    BQueueSize: 16000 # must be larger than OIDBatchSize; recommended to be 2*OIDBatchSize or 3*OIDBatchSize
    SkipIndexFilesSearch: false
    IndexFileSize: 128000
    ContainerID: "HmP48JvCcmiEbJemG7jFNEg2qkdCTx4thD3EwWUi288Q"
    BlockAttribute: "block"
    IndexFileAttribute: "index"
```
Turns out that index file contains zero OID:
```
2024-10-21T12:17:15.619+0300    ERROR   failed to objectGet block       {"error": "header: status: code = 1024 message = zero object ID"}
2024-10-21T12:17:15.619+0300    INFO    shutting down NeoFS BlockFetcher service        {"force": true}
2024-10-21T12:17:15.619+0300    ERROR   failed to objectGet block       {"error": "header: status: code = 1024 message = zero object ID"}
```

## Expected Behavior
No zero OIDs in the index files.

## Possible Solution
The problem might be in the process of OIDs encoding or invalid offsets calculated:
https://github.com/nspcc-dev/neo-go/blob/29bb3ff1cf4738ada24f075f5b398c1e70522778/cli/util/uploader.go#L346

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3628
Close https://github.com/nspcc-dev/neo-go/issues/3634

### CODE REVIEW

**Comment by AliceInHunterland** [comment]
uploaded blocks and 10 index files into mainnet container with a pool of 4 nodes.
```
(base) ekaterinapavlova@MacBook-Air-4 neo-go % ./bin/neo-go util upload-bin --cid HmP48JvCcmiEbJemG7jFNEg2qkdCTx4thD3EwWUi288Q --wallet-config ./wallet-config.yml --block-attribute block1223 --index-attribute index123 --rpc-endpoint https://rpc.t5.n3.nspcc.ru:20331 -fsr st1.storage.fs.neo.org:8080 -fsr st2.storage.fs.neo.org:8080 -fsr st3.storage.fs.neo.org:8080 -fsr st4.storage.fs.neo.org:8080 --index-file-size 10000
Chain block height: 100000
First block of latest incomplete batch uploaded to NeoFS container: 0
...
Uploaded index file 8
Uploaded index file 9
```
Run node with config:
```

  NeoFSBlockFetcher:
    Enabled: true
    Addresses:
      - st1.storage.fs.neo.org:8080
    Timeout: 10m
    DownloaderWorkersCount: 500
    OIDBatchSize: 8000
    BQueueSize: 16000 # must be larger than OIDBatchSize; recommended to be 2*OIDBatchSize or 3*OIDBatchSize
    SkipIndexFilesSearch: false
    IndexFileSize: 10000
    ContainerID: "HmP48JvCcmiEbJemG7jFNEg2qkdCTx4thD3EwWUi288Q"
    BlockAttribute: "block1223"
    IndexFileAttribute: "index123"
```
successfully got all of the 10 index files and OIDs inside.

```
2024-10-22T18:47:39.982+0300    INFO    node started    {"blockHeight": 0, "headerHeight": 0}
2024-10-22T18:47:39.983+0300    INFO    starting NeoFS BlockFetcher service

...
2024-10-22T18:49:20.052+0300    INFO    persisted to disk       {"blocks": 805, "keys": 11017, "headerHeight": 83329, "blockHeight": 83329, "took": "25.079792ms"}
2024-10-22T18:49:20.631+0300    INFO    NeoFS BlockFetcher service: no 'index123' object found with index 10, stopping
2024-10-22T18:49:20.631+0300    INFO    shutting down NeoFS BlockFetcher service        {"force": false}


```

with SkipIndexFilesSearch: true:
```
2024-10-22T18:53:07.839+0300    INFO    persisted to disk       {"blocks": 3131, "keys": 42148, "headerHeight": 80001, "blockHeight": 80001, "took": "70.7705ms"}
2024-10-22T18:53:10.569+0300    INFO    NeoFS BlockFetcher service: no block found with index 104000, stopping
2024-10-22T18:53:10.569+0300    INFO    shutting down NeoFS BlockFetcher service        {"force": false}

```
is also okay.

File: cli/util/uploader.go [hunk 1]
```diff
@@ -134,17 +134,20 @@ func uploadBin(ctx *cli.Context) error {
...
-							return fmt.Errorf("failed to fetch block %d: %w", blockIndex, err)
+					var (
+						blk    *block.Block
+						errGet error
+					)
+					errGet = retry(func() error {
+						blk, errGet = rpc.GetBlockByIndex(uint32(blockIndex))
+						if errGet != nil {
+							return fmt.Errorf("failed to fetch block %d: %w", blockIndex, errGet)
 						}
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply cli/util/uploader.go:146]: Ditto for all similar changes in this PR.

File: cli/util/uploader.go [hunk 2]
```diff
@@ -457,7 +477,12 @@ func uploadObj(ctx context.Context, p *pool.Pool, signer user.Signer, owner util
 func getBlockIndex(header *object.Object, attribute string) (int, error) {
 	for _, attr := range header.UserAttributes() {
 		if attr.Key() == attribute {
-			return strconv.Atoi(attr.Value())
+			value := attr.Value()
+			blockIndex, err := strconv.Atoi(value)
+			if err != nil {
+				return -1, fmt.Errorf("attribute %s has an invalid value: %s, error: %w", attribute, value, err)
+			}
+			return blockIndex, nil
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:493]: Belongs to a separate commit, not related to c55118a.

File: cli/util/uploader.go [hunk 3]
```diff
@@ -397,9 +415,11 @@ func updateIndexFiles(ctx *cli.Context, p *pool.Pool, containerID cid.ID, accoun
...
 			*object.NewAttribute("size", strconv.Itoa(int(indexFileSize))),
 		}
-		err = uploadObj(ctx.Context, p, signer, account.PrivateKey().GetScriptHash(), containerID, buffer, attrs, homomorphicHashingDisabled)
-		if err != nil {
-			return fmt.Errorf("failed to upload index file %d: %w", i, err)
+		errRetr := retry(func() error {
+			return uploadObj(ctx.Context, p, signer, account.PrivateKey().GetScriptHash(), containerID, buffer, attrs, homomorphicHashingDisabled)
+		})
+		if errRetr != nil {
+			return fmt.Errorf("failed to upload index file %d: %w", i, errRetr)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:430]: Useless change, revert it.

File: cli/util/uploader.go [hunk 4]
```diff
@@ -411,6 +412,13 @@ func updateIndexFiles(ctx *cli.Context, p *pool.Pool, containerID cid.ID, accoun
 				}
 			}
 		}
+		emptyOid := make([]byte, 32)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:415]: Move it to some global variable in order not to allocate it every time. Replace `32` with proper constant. Write relevant comment.

File: cli/util/uploader.go [hunk 5]
```diff
@@ -411,6 +412,13 @@ func updateIndexFiles(ctx *cli.Context, p *pool.Pool, containerID cid.ID, accoun
...
+		for k := 0; k < len(buffer); k += oidSize {
+			myOid := buffer[k : k+oidSize]
+			if slices.Compare(myOid, emptyOid) == 0 {
+				return fmt.Errorf("empty oid found in buffer with index %d", k/oidSize)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:419]: Add details about IndexFile index. Replace `buffer` with something more appropriate so that external user may understand that something is wrong with the index file construction.

File: cli/util/uploader.go [hunk 6]
```diff
@@ -411,6 +412,13 @@ func updateIndexFiles(ctx *cli.Context, p *pool.Pool, containerID cid.ID, accoun
...
+			}
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:420]: This check deserves a comment explaining why do we need this code here.

File: cli/util/uploader.go (hunk 3 above)
Comment (AliceInHunterland) [reply cli/util/uploader.go:430]: Why? In case of failure of uploading it won't retry. In case of block uploading we do have retry on it. I can put it in a separate commit.

Comment (AnnaShaleva) [reply cli/util/uploader.go:430]: Retry itself is OK, I mean `err` -> `errRtr` change, there's no bug in this code related to `err`.

Comment (AnnaShaleva) [reply cli/util/uploader.go:430]: Regarding retry: yes, put it to a separate commit, it's not related to `err` fixes.

File: cli/util/uploader.go [hunk 7]
```diff
@@ -323,9 +324,11 @@ func updateIndexFiles(ctx *cli.Context, p *pool.Pool, containerID cid.ID, accoun
 
 	var (
 		errCh                 = make(chan error)
-		buffer                = make([]byte, indexFileSize*oidSize)
+		indexFile             = make([]byte, indexFileSize*oidSize)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:327]: Not related to 91b1f5a, revert it.

File: cli/util/uploader.go [hunk 8]
```diff
@@ -4,6 +4,7 @@ import (
 	"context"
 	"crypto/sha256"
 	"fmt"
+	"slices"
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:7]: > cli: add check for empty OIDs in index file upload-bin command 

"cli: verify index file construction in `upload-bin`" or something like this. You may add additional notes in the commit body.

File: cli/util/uploader.go [hunk 9]
```diff
@@ -463,7 +463,12 @@ func uploadObj(ctx context.Context, p *pool.Pool, signer user.Signer, owner util
 func getBlockIndex(header *object.Object, attribute string) (int, error) {
 	for _, attr := range header.UserAttributes() {
 		if attr.Key() == attribute {
-			return strconv.Atoi(attr.Value())
+			value := attr.Value()
+			blockIndex, err := strconv.Atoi(value)
+			if err != nil {
+				return -1, fmt.Errorf("attribute %s has an invalid value: %s, error: %w", attribute, value, err)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:489]: > has an invalid

has invalid

File: cli/util/uploader.go [hunk 10]
```diff
@@ -463,7 +463,12 @@ func uploadObj(ctx context.Context, p *pool.Pool, signer user.Signer, owner util
 func getBlockIndex(header *object.Object, attribute string) (int, error) {
 	for _, attr := range header.UserAttributes() {
 		if attr.Key() == attribute {
-			return strconv.Atoi(attr.Value())
+			value := attr.Value()
+			blockIndex, err := strconv.Atoi(value)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:487]: > cli: add details to error parsing object attributes in upload-bin

"cli: extend object attribute parsing error in `upload-bin`"?

**Review by AnnaShaleva — COMMENTED** [review]
LGTM, some style fixes are left. Let's fix and merge.

**Review by AnnaShaleva — APPROVED** [review]
