### PR TITLE
cli: fix race in TestNEP17Balance

### LINKED ISSUE #2960: Possible race in `TestNEP17Balance/all_accounts`
The issue was reproduced at the self-hosted Linux x64 runner:
```
2023-04-06T08:44:08.6038406Z === NAME  TestNEP17Balance/all_accounts
2023-04-06T08:44:08.6038738Z     executor.go:240: 
2023-04-06T08:44:08.6039454Z         	Error Trace:	/opt/github-runner/_work/neo-go/neo-go/cli/nep_test/executor.go:240
2023-04-06T08:44:08.6040628Z         	            				/opt/github-runner/_work/neo-go/neo-go/cli/nep_test/executor.go:236
2023-04-06T08:44:08.6041787Z         	            				/opt/github-runner/_work/neo-go/neo-go/cli/nep_test/nep17_test.go:73
2023-04-06T08:44:08.6042389Z         	Error:      	Expect "	Amount : 1" to match "^\s*Amount\s*:\s*1.5$"
2023-04-06T08:44:08.6042865Z         	Test:       	TestNEP17Balance/all_accounts
2023-04-06T08:44:08.6043174Z === RUN   TestNEP17Balance/Bad_token
2023-04-06T08:44:08.6043468Z === NAME  TestNEP17Balance
2023-04-06T08:44:08.6044143Z     logger.go:130: 2023-04-06T08:44:05.660Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2023-04-06T08:44:08.6044940Z     logger.go:130: 2023-04-06T08:44:05.661Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2023-04-06T08:44:08.6045855Z     logger.go:130: 2023-04-06T08:44:05.675Z	DEBUG	processing rpc request	{"method": "getnep17balances", "params": "[56c989e76f9a2ca05bb5caa6c96f524d905accd8]"}
2023-04-06T08:44:08.6046298Z === RUN   TestNEP17Balance/Bad_wallet
2023-04-06T08:44:08.6046581Z bad wallet: EOF
2023-04-06T08:44:08.6046839Z === NAME  TestNEP17Balance
2023-04-06T08:44:08.6047493Z     logger.go:130: 2023-04-06T08:44:05.677Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:42323"}
2023-04-06T08:44:08.6048341Z     logger.go:130: 2023-04-06T08:44:05.678Z	INFO	persisted to disk	{"blocks": 2, "keys": 129, "headerHeight": 2, "blockHeight": 2, "took": "101.873µs"}
2023-04-06T08:44:08.6048850Z --- FAIL: TestNEP17Balance (0.14s)
2023-04-06T08:44:08.6049375Z     --- PASS: TestNEP17Balance/excessive_parameters (0.00s)
2023-04-06T08:44:08.6049854Z     --- PASS: TestNEP17Balance/NEO (0.04s)
2023-04-06T08:44:08.6050375Z         --- PASS: TestNEP17Balance/NEO/Alias (0.02s)
2023-04-06T08:44:08.6051336Z         --- PASS: TestNEP17Balance/NEO/Hash (0.02s)
2023-04-06T08:44:08.6051813Z     --- PASS: TestNEP17Balance/GAS (0.02s)
2023-04-06T08:44:08.6052327Z     --- PASS: TestNEP17Balance/zero_balance_of_known_token (0.02s)
2023-04-06T08:44:08.6052817Z     --- FAIL: TestNEP17Balance/all_accounts (0.02s)
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #2960 and take care of wallet regeneration tests.

### CODE REVIEW

File: pkg/wallet/regenerate_test.go [hunk 1]
```diff
@@ -29,6 +29,10 @@ var (
 	}
 
 	passwords = []string{"one", "two", "three", "four"}
+
+	// naiveScrypt is naive scrypt parameters used for testing wallets to same
```
Comment (roman-khimov) [inline pkg/wallet/regenerate_test.go:33]: save

File: cli/nep_test/nep17_test.go [hunk 2]
```diff
@@ -19,19 +19,37 @@ import (
...
+		"GAS:" + testcli.TestWalletMultiAccount1 + ":1",
+		"NEO:" + testcli.TestWalletMultiAccount1 + ":10",
+		"GAS:" + testcli.TestWalletMultiAccount3 + ":3",
+	}
+	e.In.WriteString("one\r")
+	e.In.WriteString("Y\r")
+	e.Run(t, args...)
+	e.CheckNextLine(t, `^Network fee:\s*(\d|\.)+`)
+	e.CheckNextLine(t, `^System fee:\s*(\d|\.)+`)
+	e.CheckNextLine(t, `^Total fee:\s*(\d|\.)+`)
```
Comment (roman-khimov) [inline cli/nep_test/nep17_test.go:37]: Can be avoided with `--force`, but works this way too.

File: cli/testdata/wallet1_solo.json [hunk 3]
```diff
@@ -65,6 +65,7 @@
       "key": "6PYSATFztBa3CHjSR6sLAKungUEAbQUCVE16KzmaQQ38gLeYGZ9Knd5mGv",
       "label": "verify",
       "contract": {
+        "script": "VwEAEUBXAANA",
```
Comment (roman-khimov) [inline cli/testdata/wallet1_solo.json:68]: ?

**Review by roman-khimov — APPROVED** [review]

**Review by AliceInHunterland — APPROVED** [review]

File: cli/testdata/wallet1_solo.json (hunk 3 above)
Comment (AnnaShaleva) [reply cli/testdata/wallet1_solo.json:68]: Contract script. I didn't touch this code, we had our wallets improperly generated:
https://github.com/nspcc-dev/neo-go/blob/24041451335d2f6ff64b8e334401d2dff7c3b211/pkg/wallet/regenerate_test.go#L239-L242

File: cli/nep_test/nep17_test.go (hunk 2 above)
Comment (AnnaShaleva) [reply cli/nep_test/nep17_test.go]: Fixed.

File: pkg/wallet/regenerate_test.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/wallet/regenerate_test.go]: Fixed.

File: cli/testdata/wallet1_solo.json (hunk 3 above)
Comment (roman-khimov) [reply cli/testdata/wallet1_solo.json:68]: Really strange one. Suppose I have a 10K NEF...

**Review by roman-khimov — APPROVED** [review]

File: cli/testdata/wallet1_solo.json (hunk 3 above)
Comment (AnnaShaleva) [reply cli/testdata/wallet1_solo.json:68]: Should we fix it? Because it's not only for tests, see 0b26b462:
https://github.com/nspcc-dev/neo-go/blob/8d67f17943553740fe4caa31c3e9efcf7921aba2/cli/wallet/wallet.go#L654

Comment (roman-khimov) [reply cli/testdata/wallet1_solo.json:68]: It goes back to cdfb2429f279082ea5f5756dd2bdecc15b264dac, somewhere in-between Legacy (with static contract hashes that directly depend on script) and N3. It wasn't correct even back then, because of https://github.com/neo-project/proposals/blob/master/nep-6.mediawiki#contract, but now it's even more incorrect.
