### PR TITLE
cli: improve circular reference handling in JSON serialization

### LINKED ISSUE #3701: APPEND can return NULL?
Have been fuzzing VM again and found this.

## Problem
```
NEO-GO-VM > loadbase64 EMNKSs8=
READY: loaded 5 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE      PARAMETER
0        PUSH0           <<
1        NEWARRAY    
2        DUP         
3        DUP         
4        APPEND      

NEO-GO-VM 0 > run
[
    null
]
```

But i am not sure if this is intended because C# implementation throws exception when calling `ToJson`:

```
Unhandled exception. System.InvalidOperationException: Circular reference.
   at Neo.VM.Helper.ToJson(StackItem item, HashSet`1 context, Int32& maxSize)
   at Neo.VM.Helper.ToJson(StackItem item, HashSet`1 context, Int32& maxSize)
...
```

There is no such case in tests, so i am asking here.

### PR DESCRIPTION
**Pull request by Turalchik**
Close #3701.

### CODE REVIEW

File: pkg/vm/stack.go [hunk 1]
```diff
@@ -371,6 +371,8 @@ func (s *Stack) MarshalJSON() ([]byte, error) {
 		data, err := stackitem.ToJSONWithTypes(items[i])
 		if err == nil {
 			arr[i] = data
+		} else if errors.Is(err, stackitem.ErrRecursive) {
+			arr[i] = []byte(`{"error": "circular reference"}`)
```
Comment (roman-khimov) [inline pkg/vm/stack.go]: Please check #3860, I think at this stage it'd be safer to add a string to items (for all elements). At least it'd follow what NeoGo already does in other cases. But I'm open for suggestions.

Comment (roman-khimov) [reply pkg/vm/stack.go]: But returning an object with `error` field can be good long-term. Other cases can be converted to this behavior as well. The only problem is that C# does something different.

File: cli/vm/cli_test.go [hunk 2]
```diff
@@ -1428,3 +1428,20 @@ func TestJump(t *testing.T) {
 	e.checkNextLine(t, fmt.Sprintf("jumped to instruction %d", jmpTo))
 	e.checkStack(t, 9)
 }
+
+func TestAppendCircularReferenceStepByStep(t *testing.T) {
```
Comment (AnnaShaleva) [inline cli/vm/cli_test.go]: TestCircularReference_MarshalJSON?

File: pkg/vm/stack.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/vm/stack.go]: > But returning an object with error field can be good long-term.

Do we need an issue for this?

**Review by AnnaShaleva — APPROVED** [review]
