### PR TITLE
services: fix logging data race after shutdown

### LINKED ISSUE #2973: Race in `TestServerRegisterPeer`
```
2023-04-13T15:51:08.5219927Z === RUN   TestServerRegisterPeer
2023-04-13T15:51:08.5220513Z     logger.go:130: 2023-04-13T15:45:33.453Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-04-13T15:51:08.5221066Z     logger.go:130: 2023-04-13T15:45:33.453Z	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
2023-04-13T15:51:08.5221462Z     logger.go:130: 2023-04-13T15:45:33.454Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2023-04-13T15:51:08.5221852Z     logger.go:130: 2023-04-13T15:45:33.454Z	INFO	node reached synchronized state, starting services
2023-04-13T15:51:08.5222248Z     logger.go:130: 2023-04-13T15:45:33.454Z	INFO	new peer connected	{"addr": "0.0.0.0:1", "peerCount": 1}
2023-04-13T15:51:08.5222332Z ==================
2023-04-13T15:51:08.5222424Z WARNING: DATA RACE
2023-04-13T15:51:08.5222551Z Read at 0x00c0004c6ba3 by goroutine 79:
2023-04-13T15:51:08.5222681Z   testing.(*common).logDepth()
2023-04-13T15:51:08.5222993Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:882 +0x4ce
2023-04-13T15:51:08.5223112Z   testing.(*common).log()
2023-04-13T15:51:08.5223413Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:869 +0x9c
2023-04-13T15:51:08.5223529Z   testing.(*common).Logf()
2023-04-13T15:51:08.5223814Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:920 +0x67
2023-04-13T15:51:08.5223920Z   testing.(*T).Logf()
2023-04-13T15:51:08.5224110Z       <autogenerated>:1 +0x75
2023-04-13T15:51:08.5224294Z   go.uber.org/zap/zaptest.testingWriter.Write()
2023-04-13T15:51:08.5224633Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zaptest/logger.go:130 +0x12c
2023-04-13T15:51:08.5224797Z   go.uber.org/zap/zaptest.(*testingWriter).Write()
2023-04-13T15:51:08.5224941Z       <autogenerated>:1 +0x7e
2023-04-13T15:51:08.5225094Z   go.uber.org/zap/zapcore.(*ioCore).Write()
2023-04-13T15:51:08.5225463Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/core.go:99 +0x196
2023-04-13T15:51:08.5225638Z   go.uber.org/zap/zapcore.(*CheckedEntry).Write()
2023-04-13T15:51:08.5225962Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:255 +0x2cc
2023-04-13T15:51:08.5226096Z   go.uber.org/zap.(*Logger).Warn()
2023-04-13T15:51:08.5226397Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:228 +0x6d
2023-04-13T15:51:08.5226656Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).run()
2023-04-13T15:51:08.5227039Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:490 +0x12e8
2023-04-13T15:51:08.5227302Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start()
2023-04-13T15:51:08.5227673Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:288 +0x646
2023-04-13T15:51:08.5228024Z   github.com/nspcc-dev/neo-go/pkg/network.TestServerStartAndShutdown.func1.2()
2023-04-13T15:51:08.5228401Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:94 +0x39
2023-04-13T15:51:08.5228418Z 
2023-04-13T15:51:08.5228565Z Previous write at 0x00c0004c6ba3 by goroutine 42:
2023-04-13T15:51:08.5228689Z   testing.tRunner.func1()
2023-04-13T15:51:08.5228994Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1426 +0x7af
2023-04-13T15:51:08.5229115Z   runtime.deferreturn()
2023-04-13T15:51:08.5229410Z       /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:436 +0x32
2023-04-13T15:51:08.5229523Z   testing.(*T).Run.func1()
2023-04-13T15:51:08.5229817Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x47
2023-04-13T15:51:08.5229829Z 
2023-04-13T15:51:08.5229946Z Goroutine 79 (running) created at:
2023-04-13T15:51:08.5230287Z   github.com/nspcc-dev/neo-go/pkg/network.TestServerStartAndShutdown.func1()
2023-04-13T15:51:08.5230667Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:94 +0xf1
2023-04-13T15:51:08.5230771Z   testing.tRunner()
2023-04-13T15:51:08.5231076Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x213
2023-04-13T15:51:08.5231189Z   testing.(*T).Run.func1()
2023-04-13T15:51:08.5231527Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x47
2023-04-13T15:51:08.5231575Z 
2023-04-13T15:51:08.5231695Z Goroutine 42 (finished) created at:
2023-04-13T15:51:08.5231797Z   testing.(*T).Run()
2023-04-13T15:51:08.5232087Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x724
2023-04-13T15:51:08.5232200Z   testing.runTests.func1()
2023-04-13T15:51:08.5232496Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1839 +0x99
2023-04-13T15:51:08.5232601Z   testing.tRunner()
2023-04-13T15:51:08.5232891Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x213
2023-04-13T15:51:08.5232994Z   testing.runTests()
2023-04-13T15:51:08.5233290Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1837 +0x7e4
2023-04-13T15:51:08.5233389Z   testing.(*M).Run()
2023-04-13T15:51:08.5233673Z       /opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1719 +0xa71
2023-04-13T15:51:08.5233765Z   main.main()
2023-04-13T15:51:08.5233930Z       _testmain.go:139 +0x2e4
2023-04-13T15:51:08.5234016Z ==================
2023-04-13T15:51:08.5234526Z     logger.go:130: 2023-04-13T15:45:33.475Z	INFO	started protocol	{"addr": "0.0.0.0:1", "userAgent": "fake", "startHeight": 0, "id": 0}
2023-04-13T15:51:08.5235092Z     logger.go:130: 2023-04-13T15:45:33.475Z	INFO	new peer connected	{"addr": "0.0.0.0:2", "peerCount": 2}
2023-04-13T15:51:08.5235592Z     logger.go:130: 2023-04-13T15:45:33.475Z	INFO	started protocol	{"addr": "0.0.0.0:2", "userAgent": "fake", "startHeight": 0, "id": 1}
2023-04-13T15:51:08.5236062Z     logger.go:130: 2023-04-13T15:45:33.491Z	INFO	new peer connected	{"addr": "0.0.0.0:3", "peerCount": 3}
2023-04-13T15:51:08.5236177Z peer dropped: max peers reached
2023-04-13T15:51:08.5236661Z     logger.go:130: 2023-04-13T15:45:33.491Z	WARN	peer disconnected	{"addr": "0.0.0.0:2", "error": "max peers reached", "peerCount": 2}
2023-04-13T15:51:08.5237212Z     logger.go:130: 2023-04-13T15:45:33.599Z	WARN	peer disconnected	{"addr": "0.0.0.0:3", "error": "identical node id", "peerCount": 1}
2023-04-13T15:51:08.5237575Z     logger.go:130: 2023-04-13T15:45:33.649Z	INFO	shutting down server	{"peers": 1}
2023-04-13T15:51:08.5237692Z peer dropped: server shutdown
2023-04-13T15:51:08.5237927Z     testing.go:1312: race detected during execution of test
2023-04-13T15:51:08.5238128Z --- FAIL: TestServerRegisterPeer (0.20s)
```

### LINKED ISSUE #2974: Race in `TestGetData/p2pNotaryRequest`
```
2023-04-14T11:08:29.3479102Z === CONT  TestGetData
2023-04-14T11:08:29.3479627Z     logger.go:130: 2023-04-14T11:05:06.678Z	DEBUG	got msg	{"addr": "0.0.0.0:0", "type": "CMDGetData"}
2023-04-14T11:08:29.3479792Z === RUN   TestGetData/p2pNotaryRequest
2023-04-14T11:08:29.3479909Z === CONT  TestGetData
2023-04-14T11:08:29.3480420Z     logger.go:130: 2023-04-14T11:05:06.680Z	DEBUG	got msg	{"addr": "0.0.0.0:0", "type": "CMDGetData"}
2023-04-14T11:08:29.3480526Z ==================
2023-04-14T11:08:29.3480641Z WARNING: DATA RACE
2023-04-14T11:08:29.3480802Z Read at 0x00c0002778a3 by goroutine 797:
2023-04-14T11:08:29.3480962Z   testing.(*common).logDepth()
2023-04-14T11:08:29.3481339Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:883 +0xc4
2023-04-14T11:08:29.3481485Z   testing.(*common).log()
2023-04-14T11:08:29.3481860Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:876 +0xa4
2023-04-14T11:08:29.3481990Z   testing.(*common).Logf()
2023-04-14T11:08:29.3482361Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:927 +0x6a
2023-04-14T11:08:29.3482494Z   testing.(*T).Logf()
2023-04-14T11:08:29.3482802Z       <autogenerated>:1 +0x75
2023-04-14T11:08:29.3483030Z   go.uber.org/zap/zaptest.testingWriter.Write()
2023-04-14T11:08:29.3483446Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zaptest/logger.go:130 +0x12c
2023-04-14T11:08:29.3483661Z   go.uber.org/zap/zaptest.(*testingWriter).Write()
2023-04-14T11:08:29.3483847Z       <autogenerated>:1 +0x7e
2023-04-14T11:08:29.3484042Z   go.uber.org/zap/zapcore.(*ioCore).Write()
2023-04-14T11:08:29.3484439Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/core.go:99 +0x199
2023-04-14T11:08:29.3484651Z   go.uber.org/zap/zapcore.(*CheckedEntry).Write()
2023-04-14T11:08:29.3485056Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:255 +0x2ce
2023-04-14T11:08:29.3485224Z   go.uber.org/zap.(*Logger).Warn()
2023-04-14T11:08:29.3485594Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:228 +0x6d
2023-04-14T11:08:29.3485998Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).run()
2023-04-14T11:08:29.3486539Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:490 +0x130d
2023-04-14T11:08:29.3486880Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start()
2023-04-14T11:08:29.3487351Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:288 +0x666
2023-04-14T11:08:29.3487734Z   github.com/nspcc-dev/neo-go/pkg/network.startWithCleanup.func2()
2023-04-14T11:08:29.3488217Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:393 +0x39
2023-04-14T11:08:29.3488232Z 
2023-04-14T11:08:29.3488412Z Previous write at 0x00c0002778a3 by goroutine 796:
2023-04-14T11:08:29.3488564Z   testing.tRunner.func1()
2023-04-14T11:08:29.3488947Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1433 +0x7e4
2023-04-14T11:08:29.3489096Z   runtime.deferreturn()
2023-04-14T11:08:29.3489461Z       /opt/hostedtoolcache/go/1.19.8/x64/src/runtime/panic.go:476 +0x32
2023-04-14T11:08:29.3489609Z   testing.(*T).Run.func1()
2023-04-14T11:08:29.3490303Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1493 +0x47
2023-04-14T11:08:29.3490335Z 
2023-04-14T11:08:29.3490497Z Goroutine 797 (running) created at:
2023-04-14T11:08:29.3490873Z   github.com/nspcc-dev/neo-go/pkg/network.startWithCleanup()
2023-04-14T11:08:29.3491357Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:393 +0x96
2023-04-14T11:08:29.3491701Z   github.com/nspcc-dev/neo-go/pkg/network.TestTransaction()
2023-04-14T11:08:29.3492173Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:460 +0x1a5
2023-04-14T11:08:29.3492308Z   testing.tRunner()
2023-04-14T11:08:29.3492684Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1446 +0x216
2023-04-14T11:08:29.3492910Z   testing.(*T).Run.func1()
2023-04-14T11:08:29.3493289Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1493 +0x47
2023-04-14T11:08:29.3493302Z 
2023-04-14T11:08:29.3493451Z Goroutine 796 (finished) created at:
2023-04-14T11:08:29.3493581Z   testing.(*T).Run()
2023-04-14T11:08:29.3493953Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1493 +0x75d
2023-04-14T11:08:29.3494111Z   testing.runTests.func1()
2023-04-14T11:08:29.3494480Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1846 +0x99
2023-04-14T11:08:29.3494614Z   testing.tRunner()
2023-04-14T11:08:29.3494980Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1446 +0x216
2023-04-14T11:08:29.3495117Z   testing.runTests()
2023-04-14T11:08:29.3495482Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1844 +0x7ec
2023-04-14T11:08:29.3495611Z   testing.(*M).Run()
2023-04-14T11:08:29.3495961Z       /opt/hostedtoolcache/go/1.19.8/x64/src/testing/testing.go:1726 +0xa84
2023-04-14T11:08:29.3496078Z   main.main()
2023-04-14T11:08:29.3496285Z       _testmain.go:139 +0x2e9
2023-04-14T11:08:29.3496390Z ==================
2023-04-14T11:08:29.3496551Z === CONT  TestGetData/p2pNotaryRequest
2023-04-14T11:08:29.3496839Z     testing.go:1319: race detected during execution of test
2023-04-14T11:08:29.3496959Z === CONT  TestGetData
2023-04-14T11:08:29.3497488Z     logger.go:130: 2023-04-14T11:05:06.691Z	INFO	shutting down server	{"peers": 0}
2023-04-14T11:08:29.3497772Z     testing.go:1319: race detected during execution of test
2023-04-14T11:08:29.3497974Z --- FAIL: TestGetData (0.02s)
2023-04-14T11:08:29.3498247Z     --- PASS: TestGetData/block (0.00s)
2023-04-14T11:08:29.3498548Z     --- PASS: TestGetData/transaction (0.00s)
2023-04-14T11:08:29.3498875Z     --- FAIL: TestGetData/p2pNotaryRequest (0.01s)
```

### LINKED ISSUE #3112: Log in goroutine after TestTryInitStateSync has completed
Coverage routine, firstly encountered in https://github.com/nspcc-dev/neo-go/actions/runs/6024092060/job/16342099936?pr=3110.
```
2023-08-30T11:14:28.7074947Z === RUN   TestTryInitStateSync
2023-08-30T11:14:28.7076174Z === RUN   TestTryInitStateSync/module_inactive
2023-08-30T11:14:28.7077956Z     logger.go:130: 2023-08-30T11:14:28.572Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-08-30T11:14:28.7080297Z     logger.go:130: 2023-08-30T11:14:28.572Z	INFO	bad MaxPeers configured, using the default value	{"configured": 0, "actual": 100}
2023-08-30T11:14:28.7085030Z     logger.go:130: 2023-08-30T11:14:28.572Z	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
2023-08-30T11:14:28.7086969Z     logger.go:130: 2023-08-30T11:14:28.572Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2023-08-30T11:14:28.7087713Z     logger.go:130: 2023-08-30T11:14:28.572Z	INFO	node reached synchronized state, starting services
2023-08-30T11:14:28.7090873Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	shutting down server	{"peers": 0}
2023-08-30T11:14:28.7091291Z === RUN   TestTryInitStateSync/module_already_initialized
2023-08-30T11:14:28.7093617Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-08-30T11:14:28.7101876Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	bad MaxPeers configured, using the default value	{"configured": 0, "actual": 100}
2023-08-30T11:14:28.7102815Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
2023-08-30T11:14:28.7103542Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	shutting down server	{"peers": 0}
2023-08-30T11:14:28.7104249Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2023-08-30T11:14:28.7104647Z === RUN   TestTryInitStateSync/good
2023-08-30T11:14:28.7105426Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-08-30T11:14:28.7106308Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	bad MaxPeers configured, using the default value	{"configured": 0, "actual": 100}
2023-08-30T11:14:28.7107196Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
2023-08-30T11:14:28.7109093Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2023-08-30T11:14:28.7109820Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	node reached synchronized state, starting services
2023-08-30T11:14:28.7110738Z     logger.go:130: 2023-08-30T11:14:28.580Z	INFO	new peer connected	{"addr": "0.0.0.0:0", "peerCount": 1}
2023-08-30T11:14:28.7111474Z     logger.go:130: 2023-08-30T11:14:28.604Z	INFO	new peer connected	{"addr": "0.0.0.0:0", "peerCount": 2}
2023-08-30T11:14:28.7112176Z     logger.go:130: 2023-08-30T11:14:28.604Z	INFO	new peer connected	{"addr": "0.0.0.0:0", "peerCount": 3}
2023-08-30T11:14:28.7112898Z     logger.go:130: 2023-08-30T11:14:28.604Z	INFO	new peer connected	{"addr": "0.0.0.0:0", "peerCount": 4}
2023-08-30T11:14:28.7113619Z     logger.go:130: 2023-08-30T11:14:28.604Z	INFO	new peer connected	{"addr": "0.0.0.0:0", "peerCount": 5}
2023-08-30T11:14:28.7132153Z     logger.go:130: 2023-08-30T11:14:28.604Z	INFO	new peer connected	{"addr": "0.0.0.0:0", "peerCount": 6}
2023-08-30T11:14:28.7133248Z     logger.go:130: 2023-08-30T11:14:28.604Z	INFO	new peer connected	{"addr": "0.0.0.0:0", "peerCount": 7}
2023-08-30T11:14:28.7133938Z     logger.go:130: 2023-08-30T11:14:28.614Z	INFO	shutting down server	{"peers": 7}
2023-08-30T11:14:28.7134317Z peer dropped: server shutdown
2023-08-30T11:14:28.7135149Z     logger.go:130: 2023-08-30T11:14:28.614Z	WARN	peer disconnected	{"addr": "0.0.0.0:0", "error": "server shutdown", "peerCount": 6}
2023-08-30T11:14:28.7135575Z peer dropped: server shutdown
2023-08-30T11:14:28.7136326Z     logger.go:130: 2023-08-30T11:14:28.614Z	WARN	peer disconnected	{"addr": "0.0.0.0:0", "error": "server shutdown", "peerCount": 5}
2023-08-30T11:14:28.7136741Z peer dropped: server shutdown
2023-08-30T11:14:28.7137477Z     logger.go:130: 2023-08-30T11:14:28.614Z	WARN	peer disconnected	{"addr": "0.0.0.0:0", "error": "server shutdown", "peerCount": 4}
2023-08-30T11:14:28.7137890Z peer dropped: server shutdown
2023-08-30T11:14:28.7138612Z     logger.go:130: 2023-08-30T11:14:28.614Z	WARN	peer disconnected	{"addr": "0.0.0.0:0", "error": "server shutdown", "peerCount": 3}
2023-08-30T11:14:28.7139016Z peer dropped: server shutdown
2023-08-30T11:14:28.7139753Z     logger.go:130: 2023-08-30T11:14:28.614Z	WARN	peer disconnected	{"addr": "0.0.0.0:0", "error": "server shutdown", "peerCount": 2}
2023-08-30T11:14:28.7140165Z peer dropped: server shutdown
2023-08-30T11:14:28.7141126Z     logger.go:130: 2023-08-30T11:14:28.615Z	WARN	peer disconnected	{"addr": "0.0.0.0:0", "error": "server shutdown", "peerCount": 1}
2023-08-30T11:14:28.7141669Z peer dropped: server shutdown
2023-08-30T11:14:28.7142094Z --- PASS: TestTryInitStateSync (0.05s)
2023-08-30T11:14:28.7142602Z     --- PASS: TestTryInitStateSync/module_inactive (0.01s)
2023-08-30T11:14:28.7143183Z     --- PASS: TestTryInitStateSync/module_already_initialized (0.00s)
2023-08-30T11:14:28.7143703Z     --- PASS: TestTryInitStateSync/good (0.04s)
2023-08-30T11:14:28.7144030Z === RUN   TestServer_Port
2023-08-30T11:14:28.7144809Z     logger.go:130: 2023-08-30T11:14:28.623Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-08-30T11:14:28.7145700Z     logger.go:130: 2023-08-30T11:14:28.623Z	INFO	bad MaxPeers configured, using the default value	{"configured": 0, "actual": 100}
2023-08-30T11:14:28.7146572Z     logger.go:130: 2023-08-30T11:14:28.623Z	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
2023-08-30T11:14:28.7147071Z --- PASS: TestServer_Port (0.00s)
2023-08-30T11:14:28.7147375Z === RUN   TestPeerHandshake
2023-08-30T11:14:28.7148156Z     logger.go:130: 2023-08-30T11:14:28.624Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-08-30T11:14:28.7149032Z     logger.go:130: 2023-08-30T11:14:28.624Z	INFO	bad MaxPeers configured, using the default value	{"configured": 0, "actual": 100}
2023-08-30T11:14:28.7149916Z     logger.go:130: 2023-08-30T11:14:28.624Z	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
2023-08-30T11:14:28.7150825Z     logger.go:130: 2023-08-30T11:14:28.624Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2023-08-30T11:14:28.7151773Z     logger.go:130: 2023-08-30T11:14:28.624Z	INFO	bad MaxPeers configured, using the default value	{"configured": 0, "actual": 100}
2023-08-30T11:14:28.7152656Z     logger.go:130: 2023-08-30T11:14:28.624Z	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
2023-08-30T11:14:28.7153160Z --- PASS: TestPeerHandshake (0.00s)
2023-08-30T11:14:28.7153473Z === RUN   FuzzMessageDecode
2023-08-30T11:14:28.7154237Z panic: Log in goroutine after TestTryInitStateSync/good has completed: 2023-08-30T11:14:28.623Z	WARN	peer disconnected	{"addr": "0.0.0.0:0", "error": "server shutdown", "peerCount": 0}
2023-08-30T11:14:28.7154624Z 
2023-08-30T11:14:28.7154750Z goroutine 10831 [running]:
2023-08-30T11:14:28.7155170Z testing.(*common).logDepth(0xc006741ba0, {0xc0000e2100, 0x71}, 0x3)
2023-08-30T11:14:28.7155601Z 	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1003 +0x4e7
2023-08-30T11:14:28.7155942Z testing.(*common).log(...)
2023-08-30T11:14:28.7156317Z 	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:985
2023-08-30T11:14:28.7156846Z testing.(*common).Logf(0xc006741ba0, {0xa6f90a?, 0x40c1f7?}, {0xc0004521b0?, 0xffffffffffffffff?, 0x3?})
2023-08-30T11:14:28.7157326Z 	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1036 +0x5a
2023-08-30T11:14:28.7157826Z go.uber.org/zap/zaptest.testingWriter.Write({{0xc238b0?, 0xc006741ba0?}, 0x18?}, {0xc0001e2000?, 0x72, 0xc0002dae40?})
2023-08-30T11:14:28.7158327Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zaptest/logger.go:130 +0xe6
2023-08-30T11:14:28.7158868Z go.uber.org/zap/zapcore.(*ioCore).Write(0xc006c080f0, {0x1, {0xc133e7052523402b, 0xd7202e13, 0xff9880}, {0x0, 0x0}, {0xa76a29, 0x11}, {0x0, ...}, ...}, ...)
2023-08-30T11:14:28.7159394Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/core.go:99 +0xb5
2023-08-30T11:14:28.7159899Z go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000098000, {0xc000240e40, 0x3, 0x3})
2023-08-30T11:14:28.7160381Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:255 +0x1d9
2023-08-30T11:14:28.7160849Z go.uber.org/zap.(*Logger).Warn(0xa3e4c0?, {0xa76a29?, 0xc00008fca0?}, {0xc000240e40, 0x3, 0x3})
2023-08-30T11:14:28.7161319Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:228 +0x59
2023-08-30T11:14:28.7161808Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).run(0xc000080800)
2023-08-30T11:14:28.7162410Z 	/home/runner/work/neo-go/neo-go/pkg/network/server.go:492 +0xeec
2023-08-30T11:14:28.7162922Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start(0xc000080800)
2023-08-30T11:14:28.7163443Z 	/home/runner/work/neo-go/neo-go/pkg/network/server.go:290 +0x539
2023-08-30T11:14:28.7163957Z created by github.com/nspcc-dev/neo-go/pkg/network.startWithCleanup
2023-08-30T11:14:28.7164515Z 	/home/runner/work/neo-go/neo-go/pkg/network/server_test.go:393 +0x65
2023-08-30T11:14:28.7164963Z FAIL	github.com/nspcc-dev/neo-go/pkg/network	3.624s
```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
The problem is writing to logs after the end of the test execution.
Added sync logs for every service separately to provide the ability to have a custom logger for each service. 
Data race is caused by missing synchronization channels in the network server. Shutdown doesn't wait for all goroutines to finish properly.

 Close #2973
 Close #2974
 Close #3112

### CODE REVIEW

File: pkg/network/server.go [hunk 1]
```diff
@@ -138,6 +138,8 @@ type (
 		stateSync StateSync
 
 		log *zap.Logger
+
+		shutdownOnce sync.Once
```
Comment (AnnaShaleva) [inline pkg/network/server.go:142]: To match the overall pattern of NeoGo services, port the approach with `started` atomic bool variable:
https://github.com/nspcc-dev/neo-go/blob/51ac153a7b009f8f69117ed987038a08dc78f261/pkg/services/rpcsrv/server.go#L145

File: pkg/network/server_test.go [hunk 2]
```diff
@@ -135,17 +137,29 @@ func TestServerRegisterPeer(t *testing.T) {
 
 	startWithCleanup(t, s)
 
-	s.register <- ps[0]
-	require.Eventually(t, func() bool { return 1 == s.PeerCount() }, time.Second, time.Millisecond*10)
-	s.handshake <- ps[0]
+	var wg sync.WaitGroup
+
+	// Register and handshake peers
+	for i, p := range ps {
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:143]: From the commit message I see that this commit contains two different fixes for two different problems. Split this commit into two commits and describe each problem separately.

**Review by AnnaShaleva — COMMENTED** [review]
Something has happend with the commit message indent.

File: pkg/network/server.go (hunk 1 above)
Comment (AnnaShaleva) [inline pkg/network/server.go:142]: Where have you caught the "closed twice" problem? Is it a real reproducible problem?

Comment (AliceInHunterland) [reply pkg/network/server.go:142]: if i run the updated TestServerRegisterPeer  with `defer s.Shutdown()` inside, then i get:

```

=== RUN   TestServerRegisterPeer
    logger.go:130: 2024-02-09T18:23:19.197+0300	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
    logger.go:130: 2024-02-09T18:23:19.198+0300	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
    logger.go:130: 2024-02-09T18:23:19.198+0300	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
    logger.go:130: 2024-02-09T18:23:19.198+0300	INFO	node reached synchronized state, starting services
    logger.go:130: 2024-02-09T18:23:19.198+0300	INFO	new peer connected	{"addr": "0.0.0.0:3", "peerCount": 1}
    logger.go:130: 2024-02-09T18:23:19.198+0300	INFO	new peer connected	{"addr": "0.0.0.0:1", "peerCount": 2}
    logger.go:130: 2024-02-09T18:23:19.198+0300	INFO	started protocol	{"addr": "0.0.0.0:3", "userAgent": "fake", "startHeight": 0, "id": 2}
    logger.go:130: 2024-02-09T18:23:19.198+0300	INFO	new peer connected	{"addr": "0.0.0.0:2", "peerCount": 3}
    logger.go:130: 2024-02-09T18:23:19.199+0300	INFO	started protocol	{"addr": "0.0.0.0:1", "userAgent": "fake", "startHeight": 0, "id": 0}
    logger.go:130: 2024-02-09T18:23:19.199+0300	INFO	started protocol	{"addr": "0.0.0.0:2", "userAgent": "fake", "startHeight": 0, "id": 1}
    server_test.go:150: Registered and handshaked peer: 2
    server_test.go:153: Attempted to register extra peer: 3
    server_test.go:150: Registered and handshaked peer: 1
peer dropped: max peers reached
    logger.go:130: 2024-02-09T18:23:19.199+0300	WARN	peer disconnected	{"addr": "0.0.0.0:3", "error": "max peers reached", "peerCount": 2}
    logger.go:130: 2024-02-09T18:23:19.209+0300	WARN	peer disconnected	{"addr": "0.0.0.0:1", "error": "identical node id", "peerCount": 1}
    logger.go:130: 2024-02-09T18:23:19.259+0300	INFO	shutting down server	{"peers": 1}
peer dropped: server shutdown
    logger.go:130: 2024-02-09T18:23:19.259+0300	WARN	peer disconnected	{"addr": "0.0.0.0:2", "error": "server shutdown", "peerCount": 0}
    logger.go:130: 2024-02-09T18:23:19.259+0300	INFO	shutting down server	{"peers": 0}
--- FAIL: TestServerRegisterPeer (0.06s)
panic: closed twice [recovered]
	panic: closed twice

goroutine 60 [running]:
testing.tRunner.func1.2({0x104c40b20, 0x104d0ec90})
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1545 +0x1c8
testing.tRunner.func1()
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1548 +0x360
panic({0x104c40b20?, 0x104d0ec90?})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:914 +0x218
github.com/nspcc-dev/neo-go/pkg/network.(*fakeTransp).Close(0x14000159e08?)
	/Users/ekaterinapavlova/Workplace/neo-go/pkg/network/discovery_test.go:83 +0x54
github.com/nspcc-dev/neo-go/pkg/network.(*Server).Shutdown(0x14000343400)
	/Users/ekaterinapavlova/Workplace/neo-go/pkg/network/server.go:299 +0x104
github.com/nspcc-dev/neo-go/pkg/network.startWithCleanup.func1()
	/Users/ekaterinapavlova/Workplace/neo-go/pkg/network/server_test.go:408 +0x20
testing.(*common).Cleanup.func1()
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1169 +0x110
testing.(*common).runCleanup(0x1400032c340, 0x14000159d80?)
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1347 +0xd8
testing.tRunner.func2()
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1589 +0x2c
testing.tRunner(0x1400032c340, 0x104d0c5d0)
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1601 +0x114
created by testing.(*T).Run in goroutine 1
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1648 +0x33c


Process finished with the exit code 1
```

Comment (AliceInHunterland) [reply pkg/network/server.go:142]: in TestTryInitStateSync i got a similar situation

Comment (AnnaShaleva) [reply pkg/network/server.go:142]: OK, so the fix itself is valid. Attach this description and logs to the corresponding commit.

File: pkg/network/server_test.go [hunk 3]
```diff
@@ -135,17 +137,29 @@ func TestServerRegisterPeer(t *testing.T) {
...
+		wg.Add(1)
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:144]: I don't think that this WG-related code fixes the problem. As you mentioned, the problem is likely related to the fact that zap logger writes logs after the test ends. The reason is likely connected with https://github.com/uber-go/zap/issues/687, so the https://github.com/uber-go/zap/issues/687#issuecomment-473413884 might help to fix it.

To prevent logs after the test ends we need to properly shutdown the server. For this we have a call to `startWithCleanup(t, s)` at the start of the test, it has the following call:
```
t.Cleanup(func() {
		s.Shutdown()
	})
```
So I think we need to check whether this "Cleanup" allows log inside it and whether the https://github.com/uber-go/zap/issues/687 is relevant for the "Cleanup" functions. Maybe need to look inside the https://github.com/golang/go/blob/master/src/testing/testing.go. @roman-khimov, need you here, what do you think?

File: pkg/network/server_test.go [hunk 4]
```diff
@@ -126,6 +126,8 @@ func TestServerRegisterPeer(t *testing.T) {
 	const peerCount = 3
 
 	s := newTestServer(t, ServerConfig{MaxPeers: 2})
+	defer s.Shutdown()
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:129]: We don't need this duplicating `s.Shutdown()`, because `startWithCleanup(t, s)` calls `s.Shutdown`. If `t.Cleanup` has the same problem with zap logs as described in https://github.com/uber-go/zap/issues/687, then we need to rework all code related to `startWithCleanup(t, s)`.

File: pkg/network/server_test.go (hunk 3 above)
Comment (AnnaShaleva) [reply pkg/network/server_test.go:144]: So in other words I think that this problem is related to conflict between `zap` and cleanup testing functionality. And the problem may be fixed by rolling back from `startWithCleanup(t, s)` to `defer s.Shutdown()`.

File: pkg/consensus/consensus.go [hunk 5]
```diff
@@ -296,6 +296,9 @@ func (s *service) Shutdown() {
 			s.wallet.Close()
 		}
 	}
+	if ok := s.log.Sync(); ok != nil {
```
Comment (AnnaShaleva) [inline pkg/consensus/consensus.go:299]: Add link to https://github.com/uber-go/zap/issues/687 to the commit message.

**Review by AnnaShaleva — COMMENTED** [review]
Note about calls to zap log `Sync`: technically, all our services share the same logger instance and there's no need to call `Sync` manually from each service, it may be done only once from the node caller's code. However, `Sync` calls don't hurt us, and there's still an ability to provide custom logger to every service constructor, and thus, we'd better sync logs for every service separately.

File: pkg/services/oracle/oracle.go [hunk 6]
```diff
@@ -192,6 +193,9 @@ func (o *Oracle) Shutdown() {
 	o.ResponseHandler.Shutdown()
 	<-o.done
 	o.wallet.Close()
+	if ok := o.Log.Sync(); ok != nil {
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/services/oracle/oracle.go:196]: In other words, we need to sync everywhere where logger is used.

**Comment by AnnaShaleva** [comment]
@AliceInHunterland, rework the second commit message and PR title/description: describe what commit actually does, i.e. proper logs flush after services shutdown. It is needed because this PR closes not only #2973, but also a set of other logs-related issues.

Search through the set of tests related issues and pick ones that will be closed by this PR. Add references to these issues to the commit message and PR description.

**Comment by AliceInHunterland** [comment]
2024-02-14T09:47:23.5366050Z     testing.go:1465: race detected during execution of test
FAIL: FuzzMessageDecode (0.01s)
2024-02-14T09:47:23.5417510Z FAIL
2024-02-14T09:47:23.5417830Z FAIL	github.com/nspcc-dev/neo-go/pkg/network	4.299s
(https://github.com/nspcc-dev/neo-go/issues/3316)
example:
https://github.com/nspcc-dev/neo-go/actions/runs/7899231937/job/21558242553?pr=3307 
@AnnaShaleva, it seems like there is still a data race issue, but with the improved logging, we cannot see it...

File: pkg/network/server_test.go [hunk 7]
```diff
@@ -392,6 +392,7 @@ func startWithCleanup(t *testing.T, s *Server) {
 	go s.Start()
 	t.Cleanup(func() {
 		s.Shutdown()
+		_ = s.log.Sync()
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:395]: We don't need it in test then since `s.Shutdown()` performs logs sync.

**Review by AnnaShaleva — COMMENTED** [review]
This PR is not a fix for #3217, this issue requires a separate fix (in a separate PR), so remove it from the commit message. To fix it (and a batch of related tests) you need to properly shutdown chain instance returned from `initClearServerWithCustomConfig`.

**Comment by AnnaShaleva** [comment]
> example:
https://github.com/nspcc-dev/neo-go/actions/runs/7899231937/job/21558242553?pr=3307
@AnnaShaleva, it seems like there is still a data race issue, but with the improved logging, we cannot see it...

From what I see, FuzzMessageDecode does not related to logger sync in any way. It's a separate issue, let's discuss it in #3316.

File: pkg/network/server_test.go (hunk 7 above)
Comment (AliceInHunterland) [reply pkg/network/server_test.go]: fixed

**Review by AnnaShaleva — COMMENTED** [review]
OK, and now from what I see this logger sync does not fixe the problem. The commit itself is valid, let's keep it, but we need one more fix. For example, `TestGetData` is still failing on the previous revision where logger sync is included:
https://github.com/nspcc-dev/neo-go/actions/runs/7900497864/job/21565914767?pr=3307
```
2024-02-14T11:32:48.4374532Z === RUN   TestGetData
2024-02-14T11:32:48.4375277Z     logger.go:130: 2024-02-14T11:29:27.250Z	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2024-02-14T11:32:48.4375962Z     logger.go:130: 2024-02-14T11:29:27.250Z	INFO	bad MaxPeers configured, using the default value	{"configured": 0, "actual": 100}
2024-02-14T11:32:48.4376743Z     logger.go:130: 2024-02-14T11:29:27.250Z	INFO	bad AttemptConnPeers configured, using the default value	{"configured": 0, "actual": 20}
2024-02-14T11:32:48.4376859Z === RUN   TestGetData/block
2024-02-14T11:32:48.4376957Z === CONT  TestGetData
2024-02-14T11:32:48.4377460Z     logger.go:130: 2024-02-14T11:29:27.250Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2024-02-14T11:32:48.4377955Z     logger.go:130: 2024-02-14T11:29:27.250Z	INFO	node reached synchronized state, starting services
2024-02-14T11:32:48.4378087Z ==================
2024-02-14T11:32:48.4378195Z WARNING: DATA RACE
2024-02-14T11:32:48.4378339Z Read at 0x00c000195703 by goroutine 1255:
2024-02-14T11:32:48.4378475Z   testing.(*common).logDepth()
2024-02-14T11:32:48.4378874Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:883 +0xc4
2024-02-14T11:32:48.4378993Z   testing.(*common).log()
2024-02-14T11:32:48.4379348Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:876 +0xa4
2024-02-14T11:32:48.4379468Z   testing.(*common).Logf()
2024-02-14T11:32:48.4379812Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:927 +0x6a
2024-02-14T11:32:48.4379923Z   testing.(*T).Logf()
2024-02-14T11:32:48.4380068Z       <autogenerated>:1 +0x75
2024-02-14T11:32:48.4380260Z   go.uber.org/zap/zaptest.testingWriter.Write()
2024-02-14T11:32:48.4380668Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zaptest/logger.go:130 +0x12c
2024-02-14T11:32:48.4380863Z   go.uber.org/zap/zaptest.(*testingWriter).Write()
2024-02-14T11:32:48.4381003Z       <autogenerated>:1 +0x7e
2024-02-14T11:32:48.4381164Z   go.uber.org/zap/zapcore.(*ioCore).Write()
2024-02-14T11:32:48.4381551Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/core.go:99 +0x199
2024-02-14T11:32:48.4381733Z   go.uber.org/zap/zapcore.(*CheckedEntry).Write()
2024-02-14T11:32:48.4382133Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:255 +0x2ce
2024-02-14T11:32:48.4382266Z   go.uber.org/zap.(*Logger).Warn()
2024-02-14T11:32:48.4382620Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:228 +0x6d
2024-02-14T11:32:48.4382893Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).run()
2024-02-14T11:32:48.4383339Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:501 +0x130d
2024-02-14T11:32:48.4383627Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start()
2024-02-14T11:32:48.4384012Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:294 +0x738
2024-02-14T11:32:48.4384353Z   github.com/nspcc-dev/neo-go/pkg/network.startWithCleanup.func2()
2024-02-14T11:32:48.4384758Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:392 +0x39
2024-02-14T11:32:48.4384769Z 
2024-02-14T11:32:48.4384946Z Previous write at 0x00c000195703 by goroutine 1254:
2024-02-14T11:32:48.4385069Z   testing.tRunner.func1()
2024-02-14T11:32:48.4385432Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1433 +0x7e4
2024-02-14T11:32:48.4385555Z   runtime.deferreturn()
2024-02-14T11:32:48.4385887Z       /opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:476 +0x32
2024-02-14T11:32:48.4386010Z   testing.(*T).Run.func1()
2024-02-14T11:32:48.4386357Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1493 +0x47
2024-02-14T11:32:48.4386363Z 
2024-02-14T11:32:48.4386490Z Goroutine 1255 (running) created at:
2024-02-14T11:32:48.4386783Z   github.com/nspcc-dev/neo-go/pkg/network.startWithCleanup()
2024-02-14T11:32:48.4387197Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:392 +0x96
2024-02-14T11:32:48.4387481Z   github.com/nspcc-dev/neo-go/pkg/network.TestTransaction()
2024-02-14T11:32:48.4387892Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:460 +0x1a5
2024-02-14T11:32:48.4388000Z   testing.tRunner()
2024-02-14T11:32:48.4388353Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1446 +0x216
2024-02-14T11:32:48.4388473Z   testing.(*T).Run.func1()
2024-02-14T11:32:48.4388866Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1493 +0x47
2024-02-14T11:32:48.4388873Z 
2024-02-14T11:32:48.4389004Z Goroutine 1254 (finished) created at:
2024-02-14T11:32:48.4389111Z   testing.(*T).Run()
2024-02-14T11:32:48.4389460Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1493 +0x75d
2024-02-14T11:32:48.4389591Z   testing.runTests.func1()
2024-02-14T11:32:48.4389922Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1846 +0x99
2024-02-14T11:32:48.4390034Z   testing.tRunner()
2024-02-14T11:32:48.4390418Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1446 +0x216
2024-02-14T11:32:48.4390535Z   testing.runTests()
2024-02-14T11:32:48.4390873Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1844 +0x7ec
2024-02-14T11:32:48.4391010Z   testing.(*M).Run()
2024-02-14T11:32:48.4391354Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1726 +0xa84
2024-02-14T11:32:48.4391455Z   main.main()
2024-02-14T11:32:48.4391621Z       _testmain.go:139 +0x2e9
2024-02-14T11:32:48.4391709Z ==================
2024-02-14T11:32:48.4392248Z     logger.go:130: 2024-02-14T11:29:27.251Z	DEBUG	got msg	{"addr": "0.0.0.0:0", "type": "CMDGetData"}
2024-02-14T11:32:48.4392371Z === RUN   TestGetData/transaction
2024-02-14T11:32:48.4392470Z === CONT  TestGetData
2024-02-14T11:32:48.4392989Z     logger.go:130: 2024-02-14T11:29:27.254Z	DEBUG	got msg	{"addr": "0.0.0.0:0", "type": "CMDGetData"}
2024-02-14T11:32:48.4393120Z === RUN   TestGetData/p2pNotaryRequest
2024-02-14T11:32:48.4393223Z === CONT  TestGetData
2024-02-14T11:32:48.4393719Z     logger.go:130: 2024-02-14T11:29:27.265Z	DEBUG	got msg	{"addr": "0.0.0.0:0", "type": "CMDGetData"}
2024-02-14T11:32:48.4394138Z     logger.go:130: 2024-02-14T11:29:27.267Z	INFO	shutting down server	{"peers": 0}
2024-02-14T11:32:48.4394386Z     testing.go:1319: race detected during execution of test
2024-02-14T11:32:48.4394537Z --- FAIL: TestGetData (0.02s)
2024-02-14T11:32:48.4394742Z     --- PASS: TestGetData/block (0.00s)
2024-02-14T11:32:48.4394962Z     --- PASS: TestGetData/transaction (0.01s)
2024-02-14T11:32:48.4395209Z     --- PASS: TestGetData/p2pNotaryRequest (0.00s)
```

So I think that https://github.com/nspcc-dev/neo-go/pull/3307#discussion_r1486101955 is still relevant. You may try to replace `Cleanup` server shutdown with deferred server shutdown and take a look at the failing tests.

**Comment by AliceInHunterland** [comment]
@AnnaShaleva with
```
 func startWithCleanup(t *testing.T, s *Server) {
	go s.Start()
	defer s.Shutdown()
}
```
got initial race (https://github.com/nspcc-dev/neo-go/actions/runs/7912865046/job/21599387373?pr=3307):
```
2024-02-15T08:16:00.8905294Z ==================
2024-02-15T08:16:00.8905397Z WARNING: DATA RACE
2024-02-15T08:16:00.8905540Z Read at 0x00c00008a863 by goroutine 121:
2024-02-15T08:16:00.8905740Z   testing.(*common).logDepth()
2024-02-15T08:16:00.8906144Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:889 +0x4e7
2024-02-15T08:16:00.8906264Z   testing.(*common).log()
2024-02-15T08:16:00.8906608Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:876 +0xa4
2024-02-15T08:16:00.8906731Z   testing.(*common).Logf()
2024-02-15T08:16:00.8907060Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:927 +0x6a
2024-02-15T08:16:00.8907174Z   testing.(*T).Logf()
2024-02-15T08:16:00.8907317Z       <autogenerated>:1 +0x75
2024-02-15T08:16:00.8907505Z   go.uber.org/zap/zaptest.testingWriter.Write()
2024-02-15T08:16:00.8907914Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zaptest/logger.go:130 +0x12c
2024-02-15T08:16:00.8908100Z   go.uber.org/zap/zaptest.(*testingWriter).Write()
2024-02-15T08:16:00.8908252Z       <autogenerated>:1 +0x7e
2024-02-15T08:16:00.8908470Z   go.uber.org/zap/zapcore.(*ioCore).Write()
2024-02-15T08:16:00.8908850Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/core.go:99 +0x199
2024-02-15T08:16:00.8909033Z   go.uber.org/zap/zapcore.(*CheckedEntry).Write()
2024-02-15T08:16:00.8909424Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:255 +0x2ce
2024-02-15T08:16:00.8909561Z   go.uber.org/zap.(*Logger).Warn()
2024-02-15T08:16:00.8909908Z       /home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:228 +0x6d
2024-02-15T08:16:00.8910185Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).run()
2024-02-15T08:16:00.8910576Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:501 +0x130d
2024-02-15T08:16:00.8910851Z   github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start()
2024-02-15T08:16:00.8911229Z       /home/runner/work/neo-go/neo-go/pkg/network/server.go:294 +0x738
2024-02-15T08:16:00.8911674Z   github.com/nspcc-dev/neo-go/pkg/network.TestServerStartAndShutdown.func1.2()
2024-02-15T08:16:00.8912085Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:93 +0x39
2024-02-15T08:16:00.8912096Z 
2024-02-15T08:16:00.8912265Z Previous write at 0x00c00008a863 by goroutine 119:
2024-02-15T08:16:00.8912395Z   testing.tRunner.func1()
2024-02-15T08:16:00.8912754Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1433 +0x7e4
2024-02-15T08:16:00.8912877Z   runtime.deferreturn()
2024-02-15T08:16:00.8913212Z       /opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:476 +0x32
2024-02-15T08:16:00.8913326Z   testing.(*T).Run.func1()
2024-02-15T08:16:00.8913673Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1493 +0x47
2024-02-15T08:16:00.8913679Z 
2024-02-15T08:16:00.8913800Z Goroutine 121 (running) created at:
2024-02-15T08:16:00.8914188Z   github.com/nspcc-dev/neo-go/pkg/network.TestServerStartAndShutdown.func1()
2024-02-15T08:16:00.8914594Z       /home/runner/work/neo-go/neo-go/pkg/network/server_test.go:93 +0xf1
2024-02-15T08:16:00.8914711Z   testing.tRunner()
2024-02-15T08:16:00.8915057Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1446 +0x216
2024-02-15T08:16:00.8915173Z   testing.(*T).Run.func1()
2024-02-15T08:16:00.8915521Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1493 +0x47
2024-02-15T08:16:00.8915526Z 
2024-02-15T08:16:00.8915648Z Goroutine 119 (finished) created at:
2024-02-15T08:16:00.8915760Z   testing.(*T).Run()
2024-02-15T08:16:00.8916104Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1493 +0x75d
2024-02-15T08:16:00.8916231Z   testing.runTests.func1()
2024-02-15T08:16:00.8916569Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1846 +0x99
2024-02-15T08:16:00.8916675Z   testing.tRunner()
2024-02-15T08:16:00.8917018Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1446 +0x216
2024-02-15T08:16:00.8917126Z   testing.runTests()
2024-02-15T08:16:00.8917469Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1844 +0x7ec
2024-02-15T08:16:00.8917576Z   testing.(*M).Run()
2024-02-15T08:16:00.8917913Z       /opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1726 +0xa84
2024-02-15T08:16:00.8918059Z   main.main()
2024-02-15T08:16:00.8918217Z       _testmain.go:139 +0x2e9
2024-02-15T08:16:00.8918342Z ==================
2024-02-15T08:16:00.8918869Z     logger.go:130: 2024-02-15T08:12:35.597Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2024-02-15T08:16:00.8919367Z     logger.go:130: 2024-02-15T08:12:35.597Z	INFO	node reached synchronized state, starting services
2024-02-15T08:16:00.8919901Z     logger.go:130: 2024-02-15T08:12:35.597Z	INFO	new peer connected	{"addr": "0.0.0.0:1", "peerCount": 1}
2024-02-15T08:16:00.8920592Z     logger.go:130: 2024-02-15T08:12:35.607Z	INFO	started protocol	{"addr": "0.0.0.0:1", "userAgent": "fake", "startHeight": 0, "id": 0}
2024-02-15T08:16:00.8921135Z     logger.go:130: 2024-02-15T08:12:35.607Z	INFO	new peer connected	{"addr": "0.0.0.0:2", "peerCount": 2}
2024-02-15T08:16:00.8921872Z     logger.go:130: 2024-02-15T08:12:35.607Z	INFO	started protocol	{"addr": "0.0.0.0:2", "userAgent": "fake", "startHeight": 0, "id": 1}
2024-02-15T08:16:00.8922392Z     logger.go:130: 2024-02-15T08:12:35.619Z	INFO	new peer connected	{"addr": "0.0.0.0:3", "peerCount": 3}
2024-02-15T08:16:00.8922516Z peer dropped: max peers reached
2024-02-15T08:16:00.8923192Z     logger.go:130: 2024-02-15T08:12:35.619Z	WARN	peer disconnected	{"addr": "0.0.0.0:2", "error": "max peers reached", "peerCount": 2}
2024-02-15T08:16:00.8923857Z     logger.go:130: 2024-02-15T08:12:35.719Z	WARN	peer disconnected	{"addr": "0.0.0.0:3", "error": "identical node id", "peerCount": 1}
2024-02-15T08:16:00.8924112Z     testing.go:1319: race detected during execution of test
2024-02-15T08:16:00.8924299Z --- FAIL: TestServerRegisterPeer (0.17s)
```

**Comment by AnnaShaleva** [comment]
It shouldn't be like this:
```
 func startWithCleanup(t *testing.T, s *Server) {
	go s.Start()
	defer s.Shutdown()
}
```
What I suggest is to remove `startWithCleanup` and use `go s.Start()` and after this `defer s.Shutdown()` where appropriate, directly in the test. I'm not sure it's going to fix the problem, but  this is my last assumption.

File: pkg/network/server_test.go [hunk 8]
```diff
@@ -384,7 +385,8 @@ func startTestServer(t *testing.T, protocolCfg ...func(*config.Blockchain)) *Ser
 	} else {
 		s = newTestServer(t, srvCfg)
 	}
-	startWithCleanup(t, s)
+	go s.Start()
+	defer s.Shutdown()
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:389]: Not suitable here. Read how `defer` is executed: https://go.dev/tour/flowcontrol/12.

`s.Shutdown()` need to be called directly in the test code.

Comment (AliceInHunterland) [reply pkg/network/server_test.go]: so tried to use `s.Shutdown()` inside tests, then tried to move `go s.Start()` with `s.Shutdown()` to the tests. Both ways got data race in network tests.

Comment (AliceInHunterland) [reply pkg/network/server_test.go]: `s.Shutdown()` does not wait for all goroutines of the node server to stop, which causes logs to attempt to write after the test has ended. One way to solve it is using `require.Eventually` in tests, as I did in the last commit, another way is to use WaitGroup inside the Shutdown function (which seems to me not a good decision(it is probably not for nothing that it hasn't been used before)).  
@AnnaShaleva @roman-khimov Are there any other possible solutions to this problem?

Comment (AnnaShaleva) [reply pkg/network/server_test.go]: > s.Shutdown() does not wait for all goroutines of the node server to stop,

Well, this is the real source of the problem, we need to wait before the exit. Take a look at the other services and how they wait for all routines, for example at Blockchain or RPC server.

File: pkg/network/server_test.go [hunk 9]
```diff
@@ -133,7 +133,7 @@ func TestServerRegisterPeer(t *testing.T) {
 		ps[i].version = &payload.Version{Nonce: uint32(i), UserAgent: []byte("fake")}
 	}
 
-	startWithCleanup(t, s)
+	go s.Start()
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:136]: OK, if server doesn't wait for all goroutines to finish, then this commit is useless, it won't fix the issue.

Comment (AliceInHunterland) [reply pkg/network/server_test.go:136]: With require.Eventually at the end of the tests it will fix races in tests, but agree the waiting of goroutines should be in shutdown (working on it). t.Cleanup does not work well, tried it here https://github.com/nspcc-dev/neo-go/commit/be9ce6ceb352008daf576297f8dbf1c5dbce15f9 and sometimes before, not sure that t.Cleanup is useful

Comment (AnnaShaleva) [reply pkg/network/server_test.go:136]: Let's keep `t.Cleanup(s.Shutdown())` for now (the unchanged version of `startWithCleanup`), I think it will work properly with proper shutdown awaiting in the network server.

**Comment by AnnaShaleva** [comment]
OK, so @AliceInHunterland, the main problem is `(s *Server) run()` routine that emit logs after server shutdown, so you need to wait for it to finish in `Shutdown`. Use additional sync channel, its functionality should be similar to the network server's `relayFin` channel functionality.

File: pkg/network/server.go [hunk 10]
```diff
@@ -130,6 +130,7 @@ type (
 		handshake  chan Peer
 		quit       chan struct{}
 		relayFin   chan struct{}
+		runFin     chan struct{}
```
Comment (AnnaShaleva) [inline pkg/network/server.go:133]: Add `network` prefix to the commit message.

Comment (AnnaShaleva) [inline pkg/network/server.go:133]: Much better. However, with this fix the following error occurs on Windows
```
2024-02-16T13:04:04.1864504Z panic: Log in goroutine after TestTryInitStateSync/module_already_initialized has completed: 2024-02-16T13:01:16.244Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2024-02-16T13:04:04.1864515Z 
2024-02-16T13:04:04.1864607Z goroutine 6763 [running]:
2024-02-16T13:04:04.1864830Z testing.(*common).logDepth(0xc007c211e0, {0xc000538000, 0x50}, 0x3)
2024-02-16T13:04:04.1865137Z 	C:/hostedtoolcache/windows/go/1.21.7/x64/src/testing/testing.go:1022 +0x6d4
2024-02-16T13:04:04.1865236Z testing.(*common).log(...)
2024-02-16T13:04:04.1865479Z 	C:/hostedtoolcache/windows/go/1.21.7/x64/src/testing/testing.go:1004
2024-02-16T13:04:04.1865746Z testing.(*common).Logf(0xc007c211e0, {0x1409d70b7, 0x2}, {0xc000406030, 0x1, 0x1})
2024-02-16T13:04:04.1866019Z 	C:/hostedtoolcache/windows/go/1.21.7/x64/src/testing/testing.go:1055 +0xa5
2024-02-16T13:04:04.1866445Z go.uber.org/zap/zaptest.testingWriter.Write({{0x140bc3c70?, 0xc007c211e0?}, 0x53?}, {0xc0002a7000, 0x51, 0x400})
2024-02-16T13:04:04.1866794Z 	C:/Users/runneradmin/go/pkg/mod/go.uber.org/zap@v1.24.0/zaptest/logger.go:130 +0x11e
2024-02-16T13:04:04.1867448Z go.uber.org/zap/zapcore.(*ioCore).Write(0xc0002b6240, {0x0, {0xc16bf5070e8f5b84, 0xc24fad41, 0x140fa1b40}, {0x0, 0x0}, {0x1409daaa0, 0xc}, {0x0, ...}, ...}, ...)
2024-02-16T13:04:04.1867806Z 	C:/Users/runneradmin/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/core.go:99 +0x193
2024-02-16T13:04:04.1868096Z go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0002ce000, {0xc000394080, 0x2, 0x2})
2024-02-16T13:04:04.1868430Z 	C:/Users/runneradmin/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:255 +0x2f0
2024-02-16T13:04:04.1868731Z go.uber.org/zap.(*Logger).Info(0xc000151600?, {0x1409daaa0, 0xc}, {0xc000394080, 0x2, 0x2})
2024-02-16T13:04:04.1869037Z 	C:/Users/runneradmin/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:220 +0x65
2024-02-16T13:04:04.1869352Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start(0xc000430c00)
2024-02-16T13:04:04.1869606Z 	D:/a/neo-go/neo-go/pkg/network/server.go:275 +0x29e
2024-02-16T13:04:04.1870020Z created by github.com/nspcc-dev/neo-go/pkg/network.startWithCleanup in goroutine 6762
2024-02-16T13:04:04.1870259Z 	D:/a/neo-go/neo-go/pkg/network/server_test.go:392 +0x91
2024-02-16T13:04:04.1870471Z FAIL	github.com/nspcc-dev/neo-go/pkg/network	3.648s
```

File: pkg/network/server.go [hunk 11]
```diff
@@ -319,6 +321,7 @@ func (s *Server) Shutdown() {
 	}
 	close(s.quit)
 	<-s.relayFin
+	<-s.runFin
```
Comment (AnnaShaleva) [inline pkg/network/server.go:324]: We also need the same fix for `broadcastTxLoop` routine. It doesn't affect tests, but for proper node functioning we'd better ensure that this loop is ended normally.

File: pkg/network/server.go [hunk 12]
```diff
@@ -436,6 +439,7 @@ func (s *Server) run() {
 	)
 	defer addrTimer.Stop()
 	defer peerTimer.Stop()
+	defer close(s.runFin)
```
Comment (AnnaShaleva) [inline pkg/network/server.go:442]: Defers are stacking, and channel close should be done in the end. https://go.dev/tour/flowcontrol/13

File: pkg/network/server.go (hunk 11 above)
Comment (AliceInHunterland) [reply pkg/network/server.go:330]: what about txHandlerLoop. should it have the same fix? like we still have the race and the only thing left is txHandlerLoop. or maybe transports

Comment (AnnaShaleva) [reply pkg/network/server.go:330]: Let's fix it as far, but that's the case when it should be done with wait group, because there are multiple tx handler loops started depending on the server settings.

> or maybe transports
We don't need it for transports since they are properly shutted down in `(s *Server) Shutdown()`.

Comment (AnnaShaleva) [reply pkg/network/server.go:330]: > like we still have the race and the only thing left is txHandlerLoop

`TestTryInitStateSync/module_already_initialized ` failing not because of this. It's failing because of inaccurate test structure, let's discuss under https://github.com/nspcc-dev/neo-go/pull/3307#discussion_r1492445285.

File: pkg/network/server.go (hunk 10 above)
Comment (AnnaShaleva) [reply pkg/network/server.go]: As you see, the "faulty" line is `neo-go/neo-go/pkg/network/server.go:275 +0x29e`. This branch is already overwritten by the fresh changes, that's why it's important to investigate GH testing job failures after each push. However, this line is likely to be the log in the beginning of the server start function:
```
// Start will start the server and its underlying transport. Calling it twice
// is an error.
func (s *Server) Start() {
	if !s.started.CompareAndSwap(false, true) {
		s.log.Info("node server already started")
		return
	}
```
Or (which is more likely since there's no place in `TestTryInitStateSync` where server is double-started) the next log informing that server is started:
```
	s.log.Info("node started",
		zap.Uint32("blockHeight", s.chain.BlockHeight()),
		zap.Uint32("headerHeight", s.chain.HeaderHeight()))
```
I vote for second, so the reason of the test failure seems to be the following: there might be a situation when `s.tryInitStateSync()` is exiting earlier when this log is called, because `startWithCleanup` sends server run to a separate routine:
```
func startWithCleanup(t *testing.T, s *Server) {
	go s.Start()
```
So what we need here is to check that server is properly started, maybe with some `require.Eventually` line after `go s.Start()`.

Comment (AnnaShaleva) [reply pkg/network/server.go]: I'd suggest something like this, but we need @roman-khimov's approval for this since this code will be used by tests only:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ git diff
diff --git a/pkg/network/server.go b/pkg/network/server.go
index fb72254a..e1bf2985 100644
--- a/pkg/network/server.go
+++ b/pkg/network/server.go
@@ -142,7 +142,8 @@ type (
 
                log *zap.Logger
 
-               started atomic.Bool
+               started        atomic.Bool
+               runLoopStarted atomic.Bool
        }
 
        peerDrop struct {
@@ -443,7 +444,11 @@ func (s *Server) run() {
                addrTimer        = time.NewTimer(peerCheckTime)
                peerTimer        = time.NewTimer(s.ProtoTickInterval)
        )
-       defer close(s.runFin)
+       s.runLoopStarted.Store(true)
+       defer func() {
+               s.runLoopStarted.Store(false)
+               close(s.runFin)
+       }()
        defer addrTimer.Stop()
        defer peerTimer.Stop()
        go s.runProto()
diff --git a/pkg/network/server_test.go b/pkg/network/server_test.go
index 2ca95885..d8623d45 100644
--- a/pkg/network/server_test.go
+++ b/pkg/network/server_test.go
@@ -390,6 +390,9 @@ func startTestServer(t *testing.T, protocolCfg ...func(*config.Blockchain)) *Ser
 
 func startWithCleanup(t *testing.T, s *Server) {
        go s.Start()
+       require.Eventually(t, func() bool {
+               return s.runLoopStarted.Load()
+       }, time.Second, 10*time.Millisecond)
        t.Cleanup(func() {
                s.Shutdown()
        })
```

File: pkg/network/server.go [hunk 13]
```diff
@@ -264,6 +266,10 @@ func (s *Server) ID() uint32 {
 // Start will start the server and its underlying transport. Calling it twice
 // is an error.
 func (s *Server) Start() {
+	if !s.started.CompareAndSwap(false, true) {
```
Comment (AnnaShaleva) [inline pkg/network/server.go:275]: BTW, we need a test for this. But the test will work properly only after resolution of https://github.com/nspcc-dev/neo-go/pull/3307#discussion_r1492445285 since we need a reliable way to know if server was started.

File: pkg/consensus/consensus.go [hunk 14]
```diff
@@ -296,6 +296,7 @@ func (s *service) Shutdown() {
 			s.wallet.Close()
 		}
 	}
+	_ = s.log.Sync()
```
Comment (AnnaShaleva) [inline pkg/consensus/consensus.go:299]: Edit the commit message, please. This commit won't fix the data race itself since data race is caused by missing synchronization channels in the network server. This commit is only an enhancement, it makes the code follow the zap usages rules:
```
// Sync calls the underlying Core's Sync method, flushing any buffered log
// entries. Applications should take care to call Sync before exiting.
```
You may even insert this citation in the commit message.

It's the next commit (`*Fin` channels addition) who should fix two issues: #2973 and #2974. And it's a separate commit for #3112 that is described in https://github.com/nspcc-dev/neo-go/pull/3307#discussion_r1492445285.

File: pkg/network/server.go [hunk 15]
```diff
@@ -125,11 +125,14 @@ type (
...
-		quit       chan struct{}
-		relayFin   chan struct{}
+		register       chan Peer
+		unregister     chan peerDrop
+		handshake      chan Peer
+		quit           chan struct{}
+		relayFin       chan struct{}
+		runFin         chan struct{}
+		broadcastTxFin chan struct{}
+		runProtoFin    chan struct{}
```
Comment (AnnaShaleva) [inline pkg/network/server.go:135]: Make commit title more descriptive. The main thing in this commit is that it fixes a bug in our network server that prevents server from proper shutdown and doesn't allow all server goroutines to finish normally just because the server exits without dependent goroutines awaiting. The consequence of this bug fix is that corresponding tests are fixed.

Comment (AnnaShaleva) [inline pkg/network/server.go:135]: Yep, let's also wait for all `txHandlerLoop` routines with a waitgroup since all of them has draining loops which must be awaited on server exit.

File: pkg/network/server.go [hunk 16]
```diff
@@ -142,7 +142,8 @@ type (
 
 		log *zap.Logger
 
-		started atomic.Bool
+		started        atomic.Bool
+		runLoopStarted atomic.Bool
```
Comment (AnnaShaleva) [inline pkg/network/server.go:146]: s/`So we need here is to check that`/`So we need to check that`

Comment (AnnaShaleva) [inline pkg/network/server.go:146]: This new variable deserves a separate comment.

**Review by AnnaShaleva — COMMENTED** [review]
Otherwise LGTM!

File: pkg/network/server.go [hunk 17]
```diff
@@ -286,6 +292,7 @@ func (s *Server) Start() {
 	for i := 0; i < txThreads; i++ {
 		go s.txHandlerLoop()
 	}
+	s.txHandlerLoopWG.Add(txThreads)
```
Comment (AnnaShaleva) [inline pkg/network/server.go:295]: Firstly increment WG, after that run all txThreads.

File: pkg/network/server.go [hunk 18]
```diff
@@ -138,6 +141,13 @@ type (
 		stateSync StateSync
 
 		log *zap.Logger
+
+		// started used for Start and Shutdown server only once
```
Comment (AnnaShaleva) [inline pkg/network/server.go:145]: BTW, dot in the end of sentence is missing.

File: pkg/network/server.go [hunk 19]
```diff
@@ -138,6 +141,13 @@ type (
...
+		started atomic.Bool
+		// runLoopStarted indicates that the server's main run loop has started
```
Comment (AnnaShaleva) [inline pkg/network/server.go:147]: Missing dot in the end of sentence.

File: pkg/network/server_test.go [hunk 20]
```diff
@@ -96,10 +96,12 @@ func TestServerStartAndShutdown(t *testing.T) {
 		require.Eventually(t, func() bool { return 1 == s.PeerCount() }, time.Second, time.Millisecond*10)
 
 		assert.True(t, s.transports[0].(*fakeTransp).started.Load())
+		require.True(t, s.started.Load())
```
[the remark this answers is not in the document]
Comment (AliceInHunterland) [reply pkg/network/server_test.go:99]: yep tried to add second call yesterday, but got panics which are not catchable in test. will try again.

File: pkg/network/server.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (AliceInHunterland) [reply pkg/network/server.go]: so close(s.runFin)  in https://github.com/nspcc-dev/neo-go/pull/3307/commits/86ba388f8b8dd4f099a9a51f8e38ddaa7456d755#diff-20dff1d8d865de2cfb9b17512e135b82a529bd2330845f756ee35d0a23befe29R435 and waiting for it in shutdown arent required here? okay will rebase it

[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/network/server.go]: > arent required here?

For this commit - no, they shouldn't be here. This commit is only about reliable way to know when the server is started.

File: pkg/network/server_test.go (hunk 20 above)
[the remark this answers is not in the document]
Comment (AliceInHunterland) [reply pkg/network/server_test.go:99]: i meant the case when:
```
s.Start()
s.Shutdown()
s.Start()
```
then it will be :
```
panic: close of closed channel

goroutine 76 [running]:
github.com/nspcc-dev/neo-go/pkg/network.(*Server).relayBlocksLoop(0x14000298800)
	/Users/ekaterinapavlova/Workplace/neo-go/pkg/network/server.go:1619 +0x23c
created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start
	/Users/ekaterinapavlova/Workplace/neo-go/pkg/network/server.go:297 +0x30c


Process finished with the exit code 1
```
but we have a comment ```
// Start will start the server and its underlying transport. Calling it twice
// is an error.
```
so we probably don't need such test.

File: pkg/network/server_test.go [hunk 21]
```diff
@@ -115,11 +117,43 @@ func TestServerStartAndShutdown(t *testing.T) {
...
+	})
+	t.Run("double shutdown", func(t *testing.T) {
+		s := newTestServer(t, ServerConfig{})
+		go s.Start()
+		require.Eventually(t, func() bool {
+			return s.runLoopStarted.Load()
+		}, time.Second, 10*time.Millisecond)
+
+		// Ensure the server is started.
+		require.True(t, s.started.Load(), "server should be marked as started after initial Start call")
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:147]: Useless check, it's already done inside `require.Eventually(...)` five lines above.

File: pkg/network/server.go [hunk 22]
```diff
@@ -321,8 +330,12 @@ func (s *Server) Shutdown() {
 		s.notaryRequestPool.StopSubscriptions()
 	}
 	close(s.quit)
+	<-s.broadcastTxFin
+	<-s.runProtoFin
 	<-s.relayFin
 
+	s.txHandlerLoopWG.Wait()
```
Comment (AnnaShaleva) [inline pkg/network/server.go:337]: Don't need a new line here, it's the same logic block (waiting for all dependent routines).

File: pkg/network/server.go [hunk 23]
```diff
@@ -321,7 +330,10 @@ func (s *Server) Shutdown() {
 		s.notaryRequestPool.StopSubscriptions()
 	}
 	close(s.quit)
+	<-s.broadcastTxFin
+	<-s.runProtoFin
```
Comment (AnnaShaleva) [inline pkg/network/server.go:334]: OK, and the last comment: how about waiting for `s.runFin`? I'm sure this code was here several force-pushes ago.

**Review by AnnaShaleva — DISMISSED** [review]

File: pkg/network/server.go [hunk 24]
```diff
@@ -267,6 +269,10 @@ func (s *Server) ID() uint32 {
 // Start will start the server and its underlying transport. Calling it twice
 // is an error.
```
Comment (roman-khimov) [inline pkg/network/server.go:278]: is a no-op after the change.

File: pkg/network/server.go [hunk 25]
```diff
@@ -294,6 +300,9 @@ func (s *Server) Start() {
 // Shutdown disconnects all peers and stops listening. Calling it twice is an error,
 // once stopped the same intance of the Server can't be started again by calling Start.
```
Comment (roman-khimov) [inline pkg/network/server.go:310]: Also can be adjusted.

File: pkg/network/server.go [hunk 26]
```diff
@@ -423,6 +426,10 @@ func (s *Server) run() {
 		addrTimer        = time.NewTimer(peerCheckTime)
 		peerTimer        = time.NewTimer(s.ProtoTickInterval)
 	)
+	s.runLoopStarted.Store(true)
```
Comment (roman-khimov) [inline pkg/network/server.go:453]: BTW, you can still have arbitrarily long delays between this and any of the `for` logic. You can however add some channel to send something from `Start` into `run` main `select` (and forget this channel after the first event from it).

Comment (AnnaShaleva) [reply pkg/network/server.go]: > add some channel to send something from Start into run main select

This won't work since `run` is not a separate routine, we can't send from `Start` and call `run` at the same time. May be done if we send `run` to a separate routine from `Start`, but `Start` is already a separate routine from POW of other services, thus we'll need to refactor all callers of `Start`. Agree to implement?

File: pkg/network/server.go [hunk 27]
```diff
@@ -459,6 +468,8 @@ func (s *Server) run() {
 		select {
 		case <-s.quit:
 			return
+		case <-s.startSignal:
+			s.runLoopStarted.Store(true)
```
[the remark this answers is not in the document]
Comment (AnnaShaleva) [reply pkg/network/server.go:498]: And BTW, it will run infinitely. And what we need is to run it once.

File: pkg/network/server.go [hunk 28]
```diff
@@ -266,9 +268,14 @@ func (s *Server) ID() uint32 {
 	return s.id
 }
 
-// Start will start the server and its underlying transport. Calling it twice
-// is an error.
+// Start will start the server and its underlying transport. Can be called
+// only once. The same instance of the Server can't be started again after
+// it's been stopped.
```
Comment (AnnaShaleva) [inline pkg/network/server.go:281]: Just replace `error` with `no-op`: `Calling it twice is a no-op.` It's kind of common phrase, at least for NeoGo.

File: pkg/network/server.go [hunk 29]
```diff
@@ -294,9 +301,12 @@ func (s *Server) Start() {
 	s.run()
 }
 
-// Shutdown disconnects all peers and stops listening. Calling it twice is an error,
-// once stopped the same intance of the Server can't be started again by calling Start.
+// Shutdown disconnects all peers and stops listening. Can be called only once.
+// Once stopped the same instance of the Server can't be started again by calling Start.
```
Comment (AnnaShaleva) [inline pkg/network/server.go:314]: Ditto. And typo fix should be in a separate commit.

File: pkg/network/server.go (hunk 28 above)
Comment (roman-khimov) [reply pkg/network/server.go:281]: https://en.wikipedia.org/wiki/NOP_(code)

File: pkg/network/server.go [hunk 30]
```diff
@@ -285,7 +285,7 @@ func (s *Server) Start() {
 	setServerAndNodeVersions(s.UserAgent, strconv.FormatUint(uint64(s.id), 10))
 	setNeoGoVersion(config.Version)
 	setSeverID(strconv.FormatUint(uint64(s.id), 10))
-	s.run()
+	go s.run()
```
Comment (AnnaShaleva) [inline pkg/network/server.go:304]: Adjust documentation to `Start`. Add a note about the fact that the caller should wait for `Start` to finish for normal server operation.

File: pkg/network/server_test.go [hunk 31]
```diff
@@ -90,7 +90,7 @@ func TestServerStartAndShutdown(t *testing.T) {
 	t.Run("no consensus", func(t *testing.T) {
 		s := newTestServer(t, ServerConfig{})
 
-		go s.Start()
+		s.Start()
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:93]: We need to fix it in *all* places.

File: pkg/network/server.go [hunk 32]
```diff
@@ -138,6 +138,9 @@ type (
 		stateSync StateSync
 
 		log *zap.Logger
+
+		// started used for Start and Shutdown server only once.
```
Comment (AnnaShaleva) [inline pkg/network/server.go:145]: s/used for/used to

File: pkg/network/server.go (hunk 30 above)
Comment (AnnaShaleva) [inline pkg/network/server.go:304]: Adjust commit message and title. This commit itself is about server's behaviour change, and test fix is just a consequence.

File: pkg/network/server.go [hunk 33]
```diff
@@ -288,9 +295,12 @@ func (s *Server) Start() {
 	go s.run()
 }
 
-// Shutdown disconnects all peers and stops listening. Calling it twice is an error,
+// Shutdown disconnects all peers and stops listening. Calling it twice is a no-op,
 // once stopped the same intance of the Server can't be started again by calling Start.
```
Comment (AnnaShaleva) [inline pkg/network/server.go:308]: Fix typo in a separate commit while we're here? s/intance/instance

File: pkg/network/server.go (hunk 26 above)
Comment (AnnaShaleva) [reply pkg/network/server.go]: Agreed, implemented.

File: pkg/network/server_test.go (hunk 31 above)
Comment (AnnaShaleva) [reply pkg/network/server_test.go:93]: Not resolved, fix it in all places.

Comment (AnnaShaleva) [reply pkg/network/server_test.go:93]: Use `Ctrl+B` in Goland to find all usages of server's `Start` method.

File: pkg/network/server_test.go [hunk 34]
```diff
@@ -389,7 +389,7 @@ func startTestServer(t *testing.T, protocolCfg ...func(*config.Blockchain)) *Ser
 }
 
 func startWithCleanup(t *testing.T, s *Server) {
-	go s.Start()
+	s.Start()
```
Comment (AnnaShaleva) [inline pkg/network/server_test.go:417]: Describe what has been changed in the server's `Start` behaviour in the commit message.

File: pkg/network/server_test.go (hunk 31 above)
Comment (AliceInHunterland) [reply pkg/network/server_test.go:93]: Снимок экрана 2024-02-22 в 12 38 22
or maybe rpc server also shouldn't be in a separate goroutine https://github.com/nspcc-dev/neo-go/blob/master/cli/server/server.go#L506

Comment (AnnaShaleva) [reply pkg/network/server_test.go:93]: It's not RPC server, it's core server.

Comment (AnnaShaleva) [reply pkg/network/server_test.go:93]: And BTW, for RPC server we have https://github.com/nspcc-dev/neo-go/issues/3324, and for now let's not touch it.

**Comment by AnnaShaleva** [comment]
OK, one more problem found: `Start` of some services is bound to blockchain subscriptions, and thus, can't be run before the blockchain notifications dispatcher:
```
2024-02-21T18:46:53.9313151Z === RUN   TestQueryTx
2024-02-21T18:46:53.9315415Z     logger.go:130: 2024-02-21T18:36:53.867Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-02-21T18:46:53.9318373Z     logger.go:130: 2024-02-21T18:36:53.867Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-02-21T18:46:53.9321292Z     logger.go:130: 2024-02-21T18:36:53.867Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-02-21T18:46:53.9323628Z     logger.go:130: 2024-02-21T18:36:53.867Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-02-21T18:46:53.9325196Z     logger.go:130: 2024-02-21T18:36:53.867Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-02-21T18:46:53.9326716Z     logger.go:130: 2024-02-21T18:36:53.867Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 864000}
2024-02-21T18:46:53.9327999Z     logger.go:130: 2024-02-21T18:36:53.867Z	INFO	no storage version found! creating genesis block
2024-02-21T18:46:53.9328718Z coverage: 11.1% of statements in ./pkg..., ./cli/...
2024-02-21T18:46:53.9329183Z panic: test timed out after 10m0s
2024-02-21T18:46:53.9329565Z running tests:
2024-02-21T18:46:53.9329903Z 	TestQueryTx (10m0s)
2024-02-21T18:46:53.9330093Z 
2024-02-21T18:46:53.9330217Z goroutine 71 [running]:
2024-02-21T18:46:53.9330697Z testing.(*M).startAlarm.func1()
2024-02-21T18:46:53.9331315Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2259 +0x3b9
2024-02-21T18:46:53.9331838Z created by time.goFunc
2024-02-21T18:46:53.9332325Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/time/sleep.go:176 +0x2d
2024-02-21T18:46:53.9332669Z 
2024-02-21T18:46:53.9332814Z goroutine 1 [chan receive, 10 minutes]:
2024-02-21T18:46:53.9333311Z testing.(*T).Run(0xc000007860, {0x130d7cc?, 0x581b1c?}, 0x14636d0)
2024-02-21T18:46:53.9333983Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1649 +0x3c8
2024-02-21T18:46:53.9334514Z testing.runTests.func1(0x1f27b00?)
2024-02-21T18:46:53.9335061Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2054 +0x3e
2024-02-21T18:46:53.9335592Z testing.tRunner(0xc000007860, 0xc000221c38)
2024-02-21T18:46:53.9336142Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1595 +0xff
2024-02-21T18:46:53.9336875Z testing.runTests(0xc0003b45a0?, {0x1f02780, 0x2, 0x2}, {0x4170ff?, 0xc000221cf8?, 0x1f26960?})
2024-02-21T18:46:53.9337630Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:2052 +0x445
2024-02-21T18:46:53.9338145Z testing.(*M).Run(0xc0003b45a0)
2024-02-21T18:46:53.9338651Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1925 +0x636
2024-02-21T18:46:53.9339141Z main.main()
2024-02-21T18:46:53.9339444Z 	_testmain.go:85 +0x1bf
2024-02-21T18:46:53.9339652Z 
2024-02-21T18:46:53.9339788Z goroutine 129 [chan send, 10 minutes]:
2024-02-21T18:46:53.9340619Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).SubscribeForBlocks(0xc0004d0580?, 0xeb1daece2d0db4c4?)
2024-02-21T18:46:53.9341677Z 	/home/runner/work/neo-go/neo-go/pkg/core/blockchain.go:2290 +0x6b
2024-02-21T18:46:53.9342405Z github.com/nspcc-dev/neo-go/pkg/consensus.(*service).Start(0xc0003b7760?)
2024-02-21T18:46:53.9343206Z 	/home/runner/work/neo-go/neo-go/pkg/consensus/consensus.go:284 +0x134
2024-02-21T18:46:53.9343996Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).tryStartServices(0xc000457000)
2024-02-21T18:46:53.9344777Z 	/home/runner/work/neo-go/neo-go/pkg/network/server.go:578 +0x20c
2024-02-21T18:46:53.9345480Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start(0xc000457000?)
2024-02-21T18:46:53.9346200Z 	/home/runner/work/neo-go/neo-go/pkg/network/server.go:286 +0x24f
2024-02-21T18:46:53.9346958Z github.com/nspcc-dev/neo-go/internal/testcli.NewTestChain(0xc000007a00?, 0x0, 0x0)
2024-02-21T18:46:53.9347789Z 	/home/runner/work/neo-go/neo-go/internal/testcli/executor.go:167 +0xc72
2024-02-21T18:46:53.9348709Z github.com/nspcc-dev/neo-go/internal/testcli.NewExecutorWithConfig(0xc000007a00, 0x1, 0x2b?, 0x58216d?)
2024-02-21T18:46:53.9349639Z 	/home/runner/work/neo-go/neo-go/internal/testcli/executor.go:193 +0x19c
2024-02-21T18:46:53.9350380Z github.com/nspcc-dev/neo-go/internal/testcli.NewExecutorSuspended(...)
2024-02-21T18:46:53.9351109Z 	/home/runner/work/neo-go/neo-go/internal/testcli/executor.go:180
2024-02-21T18:46:53.9351881Z github.com/nspcc-dev/neo-go/cli/query_test.TestQueryTx(0x0?)
2024-02-21T18:46:53.9352561Z 	/home/runner/work/neo-go/neo-go/cli/query/query_test.go:26 +0x31
2024-02-21T18:46:53.9353086Z testing.tRunner(0xc000007a00, 0x14636d0)
2024-02-21T18:46:53.9353659Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1595 +0xff
2024-02-21T18:46:53.9354213Z created by testing.(*T).Run in goroutine 1
2024-02-21T18:46:53.9354788Z 	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1648 +0x3ad
2024-02-21T18:46:53.9355212Z 
2024-02-21T18:46:53.9355348Z goroutine 133 [select, 10 minutes]:
2024-02-21T18:46:53.9356098Z github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).notificationDispatcher(0xc0003b7760)
2024-02-21T18:46:53.9357016Z 	/home/runner/work/neo-go/neo-go/pkg/core/mempool/subscriptions.go:55 +0x1b9
2024-02-21T18:46:53.9357931Z created by github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).RunSubscriptions in goroutine 129
2024-02-21T18:46:53.9358845Z 	/home/runner/work/neo-go/neo-go/pkg/core/mempool/subscriptions.go:13 +0xcd
2024-02-21T18:46:53.9359497Z FAIL	github.com/nspcc-dev/neo-go/cli/query	600.098s
2024-02-21T18:46:53.9359943Z === RUN   TestGetPath
```

What we need is: in a separate commit move blockchain/mempool subscriptions of all dependent services from `Start` to `run` routine.

File: pkg/network/server_test.go (hunk 31 above)
Comment (AliceInHunterland) [reply pkg/network/server_test.go:93]: not sure that found everything

File: pkg/network/server.go [hunk 35]
```diff
@@ -268,20 +268,6 @@ func (s *Server) Start() {
...
-	for i := 0; i < txThreads; i++ {
-		go s.txHandlerLoop()
-	}
-	go s.broadcastTxLoop()
-	go s.relayBlocksLoop()
-	go s.bQueue.Run()
-	go s.bSyncQueue.Run()
-	for _, tr := range s.transports {
-		go tr.Accept()
-	}
```
Comment (AnnaShaleva) [inline pkg/network/server.go:284]: Not needed, useless change.

File: pkg/network/server.go [hunk 36]
```diff
@@ -423,6 +409,20 @@ func (s *Server) run() {
...
+		go s.txHandlerLoop()
+	}
+	go s.broadcastTxLoop()
+	go s.relayBlocksLoop()
+	go s.bQueue.Run()
+	go s.bSyncQueue.Run()
+	for _, tr := range s.transports {
+		go tr.Accept()
+	}
+
```
Comment (AnnaShaleva) [inline pkg/network/server.go]: Useless change.

**Comment by AnnaShaleva** [comment]
Some problems with tests, do they connected with the latest network server Start refactoring?
```
2024-02-22T14:23:40.8217958Z === RUN   TestUtilCancelTx
2024-02-22T14:23:40.8219714Z     logger.go:130: 2024-02-22T14:23:34.440Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-02-22T14:23:40.8222705Z     logger.go:130: 2024-02-22T14:23:34.440Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-02-22T14:23:40.8509342Z     logger.go:130: 2024-02-22T14:23:34.440Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-02-22T14:23:40.8512256Z     logger.go:130: 2024-02-22T14:23:34.440Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-02-22T14:23:40.8514866Z     logger.go:130: 2024-02-22T14:23:34.440Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-02-22T14:23:40.8517548Z     logger.go:130: 2024-02-22T14:23:34.440Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 864000}
2024-02-22T14:23:40.8519773Z     logger.go:130: 2024-02-22T14:23:34.440Z	INFO	no storage version found! creating genesis block
2024-02-22T14:23:40.8522019Z     logger.go:130: 2024-02-22T14:23:34.451Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2024-02-22T14:23:40.8525458Z     logger.go:130: 2024-02-22T14:23:34.451Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-02-22T14:23:40.8528186Z     logger.go:130: 2024-02-22T14:23:34.451Z	INFO	MaxFindStorageResultItems is not set or wrong, setting default value	{"MaxFindStorageResultItems": 50}
2024-02-22T14:23:40.8530742Z     logger.go:130: 2024-02-22T14:23:34.451Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2024-02-22T14:23:40.8533270Z     logger.go:130: 2024-02-22T14:23:34.451Z	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
2024-02-22T14:23:40.8535875Z     logger.go:130: 2024-02-22T14:23:34.451Z	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
2024-02-22T14:23:40.8725021Z     logger.go:130: 2024-02-22T14:23:34.451Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2024-02-22T14:23:40.8727360Z     logger.go:130: 2024-02-22T14:23:34.451Z	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
2024-02-22T14:23:40.8729832Z     logger.go:130: 2024-02-22T14:23:34.451Z	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "206.806µs"}
2024-02-22T14:23:40.8731998Z     logger.go:130: 2024-02-22T14:23:34.452Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.8734077Z     logger.go:130: 2024-02-22T14:23:34.453Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2024-02-22T14:23:40.8736124Z     logger.go:130: 2024-02-22T14:23:34.454Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.8738615Z     logger.go:130: 2024-02-22T14:23:34.455Z	DEBUG	processing rpc request	{"method": "getnep17balances", "params": "[56c989e76f9a2ca05bb5caa6c96f524d905accd8]"}
2024-02-22T14:23:40.8800530Z     logger.go:130: 2024-02-22T14:23:34.455Z	DEBUG	processing rpc request	{"method": "invokescript", "params": "[CxEMFNwk6EPkEi4hj1BzCuuZPYVDDVeBDBTYzFqQTVJvyabKtVugLJpv54nJVhTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I5 ]"}
2024-02-22T14:23:40.8803791Z     logger.go:130: 2024-02-22T14:23:34.455Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2024-02-22T14:23:40.8809582Z     logger.go:130: 2024-02-22T14:23:34.456Z	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[AHWHniC0P5gAAAAAAAAAAAAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAVwsRDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQEAKhEMIQKzYiv0AXvf4xfFiu1fTHU/IGt9uJYEb6fXdLvEv3+NwhFBntDcOg==]"}
2024-02-22T14:23:40.8819198Z     logger.go:130: 2024-02-22T14:23:34.456Z	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[AHWHniC0P5gAAAAAAPTGEgAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAVwsRDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQFCDEBOUDWVRG4VN/OCUHe4YFD/6pJwlERO5OgYJvWWYi99iyTD/wA5pqwpBcZVIzYgF+6NMW6uz5n0gkvhqAs0oYsGKhEMIQKzYiv0AXvf4xfFiu1fTHU/IGt9uJYEb6fXdLvEv3+NwhFBntDcOg==]"}
2024-02-22T14:23:40.8824303Z === RUN   TestUtilCancelTx/invalid
2024-02-22T14:23:40.8825373Z === RUN   TestUtilCancelTx/invalid/missing_tx_argument
2024-02-22T14:23:40.8826038Z transaction hash is missing
2024-02-22T14:23:40.8826647Z === RUN   TestUtilCancelTx/invalid/excessive_arguments
2024-02-22T14:23:40.8827337Z only one transaction hash is accepted
2024-02-22T14:23:40.8827994Z === RUN   TestUtilCancelTx/invalid/invalid_hash
2024-02-22T14:23:40.8828629Z invalid tx hash: notahash
2024-02-22T14:23:40.8829282Z === RUN   TestUtilCancelTx/invalid/not_signed_by_main_signer
2024-02-22T14:23:40.8830021Z === NAME  TestUtilCancelTx
2024-02-22T14:23:40.8831517Z     logger.go:130: 2024-02-22T14:23:34.459Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.8833642Z     logger.go:130: 2024-02-22T14:23:34.459Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2024-02-22T14:23:40.8836128Z     logger.go:130: 2024-02-22T14:23:34.461Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.8838941Z     logger.go:130: 2024-02-22T14:23:34.461Z	DEBUG	processing rpc request	{"method": "getrawtransaction", "params": "[e693aab6ceb7c664e610c5e4720a78e80be95a5fc75e5f10891c3357d91e4257 1]"}
2024-02-22T14:23:40.8841234Z account NVTiAjNgagDkTr5HTzDmQP9kPwPHN5BgVq is not a signer of the conflicting transaction
2024-02-22T14:23:40.8842280Z === RUN   TestUtilCancelTx/invalid/wrong_rpc_endpoint
2024-02-22T14:23:40.8843563Z failed to get network magic: Post "http://localhost:20331": dial tcp [::1]:20331: connect: connection refused
2024-02-22T14:23:40.8844689Z === NAME  TestUtilCancelTx
2024-02-22T14:23:40.8846141Z     logger.go:130: 2024-02-22T14:23:34.463Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.8848219Z     logger.go:130: 2024-02-22T14:23:34.463Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2024-02-22T14:23:40.8850485Z     logger.go:130: 2024-02-22T14:23:34.476Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.8853195Z     logger.go:130: 2024-02-22T14:23:34.476Z	DEBUG	processing rpc request	{"method": "getrawtransaction", "params": "[e693aab6ceb7c664e610c5e4720a78e80be95a5fc75e5f10891c3357d91e4257 1]"}
2024-02-22T14:23:40.8855753Z     logger.go:130: 2024-02-22T14:23:34.476Z	DEBUG	processing rpc request	{"method": "invokescript", "params": "[QA== ]"}
2024-02-22T14:23:40.8857791Z     logger.go:130: 2024-02-22T14:23:34.477Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2024-02-22T14:23:40.8862394Z     logger.go:130: 2024-02-22T14:23:34.478Z	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[ANplYRkAAAAAAAAAAAAAAAAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEBIVdCHtlXMxyJEF9ex19a6QvoeApy5MUQ5mTGt862qpPmAUABACoRDCECs2Ir9AF73+MXxYrtX0x1PyBrfbiWBG+n13S7xL9/jcIRQZ7Q3Do=]"}
2024-02-22T14:23:40.8869674Z     logger.go:130: 2024-02-22T14:23:34.478Z	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[ANplYRkAAAAAAAAAAPXGEgAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEBIVdCHtlXMxyJEF9ex19a6QvoeApy5MUQ5mTGt862qpPmAUABQgxARzxnK+d/VfPWmCrNF7blHX60BmBQSOJ8o9lNUxsDje/FN9hJs1UqKmhhn9P3rjvZr9amB8PBd8yke9Fv2aAMbyoRDCECs2Ir9AF73+MXxYrtX0x1PyBrfbiWBG+n13S7xL9/jcIRQZ7Q3Do=]"}
2024-02-22T14:23:40.8874697Z     logger.go:130: 2024-02-22T14:23:35.479Z	INFO	persisted to disk	{"blocks": 1, "keys": 139, "headerHeight": 1, "blockHeight": 1, "took": "82.424µs"}
2024-02-22T14:23:40.8876044Z     util_test.go:134: 
2024-02-22T14:23:40.8877213Z         	Error Trace:	/home/runner/work/neo-go/neo-go/cli/util/util_test.go:134
2024-02-22T14:23:40.8878260Z         	Error:      	Condition never satisfied
2024-02-22T14:23:40.8879020Z         	Test:       	TestUtilCancelTx
2024-02-22T14:23:40.8880438Z     logger.go:130: 2024-02-22T14:23:36.482Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:38795"}
2024-02-22T14:23:40.8881604Z --- FAIL: TestUtilCancelTx (2.04s)
2024-02-22T14:23:40.8882428Z     --- PASS: TestUtilCancelTx/invalid (0.01s)
2024-02-22T14:23:40.8883544Z         --- PASS: TestUtilCancelTx/invalid/missing_tx_argument (0.00s)
2024-02-22T14:23:40.8884800Z         --- PASS: TestUtilCancelTx/invalid/excessive_arguments (0.00s)
2024-02-22T14:23:40.8885999Z         --- PASS: TestUtilCancelTx/invalid/invalid_hash (0.00s)
2024-02-22T14:23:40.8887279Z         --- PASS: TestUtilCancelTx/invalid/not_signed_by_main_signer (0.00s)
2024-02-22T14:23:40.8888583Z         --- PASS: TestUtilCancelTx/invalid/wrong_rpc_endpoint (0.00s)
2024-02-22T14:23:40.8889371Z === RUN   TestAwaitUtilCancelTx
2024-02-22T14:23:40.8891115Z     logger.go:130: 2024-02-22T14:23:36.483Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2024-02-22T14:23:40.8894129Z     logger.go:130: 2024-02-22T14:23:36.483Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2024-02-22T14:23:40.8896776Z     logger.go:130: 2024-02-22T14:23:36.483Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2024-02-22T14:23:40.8899224Z     logger.go:130: 2024-02-22T14:23:36.483Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2024-02-22T14:23:40.8902076Z     logger.go:130: 2024-02-22T14:23:36.483Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2024-02-22T14:23:40.8904867Z     logger.go:130: 2024-02-22T14:23:36.483Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 864000}
2024-02-22T14:23:40.8907125Z     logger.go:130: 2024-02-22T14:23:36.483Z	INFO	no storage version found! creating genesis block
2024-02-22T14:23:40.8909324Z     logger.go:130: 2024-02-22T14:23:36.486Z	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
2024-02-22T14:23:40.8911848Z     logger.go:130: 2024-02-22T14:23:36.486Z	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
2024-02-22T14:23:40.8914756Z     logger.go:130: 2024-02-22T14:23:36.486Z	INFO	MaxFindStorageResultItems is not set or wrong, setting default value	{"MaxFindStorageResultItems": 50}
2024-02-22T14:23:40.8917285Z     logger.go:130: 2024-02-22T14:23:36.486Z	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
2024-02-22T14:23:40.8919730Z     logger.go:130: 2024-02-22T14:23:36.486Z	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
2024-02-22T14:23:40.8922310Z     logger.go:130: 2024-02-22T14:23:36.486Z	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
2024-02-22T14:23:40.8924834Z     logger.go:130: 2024-02-22T14:23:36.486Z	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2024-02-22T14:23:40.9174848Z     logger.go:130: 2024-02-22T14:23:36.486Z	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
2024-02-22T14:23:40.9176941Z     logger.go:130: 2024-02-22T14:23:36.487Z	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "194.122µs"}
2024-02-22T14:23:40.9178985Z     logger.go:130: 2024-02-22T14:23:36.488Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.9180981Z     logger.go:130: 2024-02-22T14:23:36.488Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2024-02-22T14:23:40.9183059Z     logger.go:130: 2024-02-22T14:23:36.498Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.9185410Z     logger.go:130: 2024-02-22T14:23:36.498Z	DEBUG	processing rpc request	{"method": "getnep17balances", "params": "[56c989e76f9a2ca05bb5caa6c96f524d905accd8]"}
2024-02-22T14:23:40.9189049Z     logger.go:130: 2024-02-22T14:23:36.498Z	DEBUG	processing rpc request	{"method": "invokescript", "params": "[CxEMFNwk6EPkEi4hj1BzCuuZPYVDDVeBDBTYzFqQTVJvyabKtVugLJpv54nJVhTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I5 ]"}
2024-02-22T14:23:40.9192114Z     logger.go:130: 2024-02-22T14:23:36.499Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2024-02-22T14:23:40.9197694Z     logger.go:130: 2024-02-22T14:23:36.499Z	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[AEjxT/q0P5gAAAAAAAAAAAAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAVwsRDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQEAKhEMIQKzYiv0AXvf4xfFiu1fTHU/IGt9uJYEb6fXdLvEv3+NwhFBntDcOg==]"}
2024-02-22T14:23:40.9207653Z     logger.go:130: 2024-02-22T14:23:36.499Z	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[AEjxT/q0P5gAAAAAAPTGEgAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAVwsRDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQFCDEBhOLKqu564xqgTCp3K02gVHnE13YJhzGJZZPpvwvhk/UHv0gN1BAsU6U1aDq5FZCQLbB4cnBTfl5955wHlEsfbKhEMIQKzYiv0AXvf4xfFiu1fTHU/IGt9uJYEb6fXdLvEv3+NwhFBntDcOg==]"}
2024-02-22T14:23:40.9213434Z     logger.go:130: 2024-02-22T14:23:36.500Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.9215398Z     logger.go:130: 2024-02-22T14:23:36.500Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
2024-02-22T14:23:40.9217334Z     logger.go:130: 2024-02-22T14:23:36.502Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
2024-02-22T14:23:40.9219905Z     logger.go:130: 2024-02-22T14:23:36.502Z	DEBUG	processing rpc request	{"method": "getrawtransaction", "params": "[399cf2728ee7c55cd0a9c329ecbe9c2606f9025762288936b25037ca8c8090ee 1]"}
2024-02-22T14:23:40.9303310Z     logger.go:130: 2024-02-22T14:23:36.502Z	DEBUG	processing rpc request	{"method": "invokescript", "params": "[QA== ]"}
2024-02-22T14:23:40.9306091Z     logger.go:130: 2024-02-22T14:23:36.503Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2024-02-22T14:23:40.9311205Z     logger.go:130: 2024-02-22T14:23:36.503Z	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[ACIYuXcAAAAAAAAAAAAAAAAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEBIe6QgIzKN1CyNokoYlcC+QYmnL7sKcOp0FzF545y8pw5AUABACoRDCECs2Ir9AF73+MXxYrtX0x1PyBrfbiWBG+n13S7xL9/jcIRQZ7Q3Do=]"}
2024-02-22T14:23:40.9318610Z     logger.go:130: 2024-02-22T14:23:36.503Z	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[ACIYuXcAAAAAAAAAAPXGEgAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEBIe6QgIzKN1CyNokoYlcC+QYmnL7sKcOp0FzF545y8pw5AUABQgxAQoIXnHU4CE27b0d/iJb9D7VNuTUOU/3tMijCObXY9keVB2g7NQm1SA29fuS/oTVlPF3lM/iza5bZUrGp425R9SoRDCECs2Ir9AF73+MXxYrtX0x1PyBrfbiWBG+n13S7xL9/jcIRQZ7Q3Do=]"}
2024-02-22T14:23:40.9323304Z     logger.go:130: 2024-02-22T14:23:36.554Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2024-02-22T14:23:40.9326236Z     logger.go:130: 2024-02-22T14:23:36.554Z	DEBUG	processing rpc request	{"method": "getapplicationlog", "params": "[399cf2728ee7c55cd0a9c329ecbe9c2606f9025762288936b25037ca8c8090ee Application]"}
2024-02-22T14:23:40.9330366Z     logger.go:130: 2024-02-22T14:23:36.554Z	INFO	Error encountered with rpc request	{"code": -105, "cause": "failed to locate application log: key not found", "method": "getapplicationlog", "params": "[399cf2728ee7c55cd0a9c329ecbe9c2606f9025762288936b25037ca8c8090ee Application]"}
2024-02-22T14:23:40.9502908Z     logger.go:130: 2024-02-22T14:23:36.554Z	DEBUG	processing rpc request	{"method": "getapplicationlog", "params": "[bd4915817316fd13825b9caa898dd42c01df620584299e737583938450eabf71 Application]"}
2024-02-22T14:23:40.9507201Z     logger.go:130: 2024-02-22T14:23:36.554Z	INFO	Error encountered with rpc request	{"code": -105, "cause": "failed to locate application log: key not found", "method": "getapplicationlog", "params": "[bd4915817316fd13825b9caa898dd42c01df620584299e737583938450eabf71 Application]"}
2024-02-22T14:23:40.9510483Z     logger.go:130: 2024-02-22T14:23:36.587Z	DEBUG	done processing headers	{"headerIndex": 2, "blockHeight": 1, "took": "150.801µs"}
2024-02-22T14:23:40.9512546Z     logger.go:130: 2024-02-22T14:23:36.604Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2024-02-22T14:23:40.9515296Z     logger.go:130: 2024-02-22T14:23:36.604Z	DEBUG	processing rpc request	{"method": "getapplicationlog", "params": "[399cf2728ee7c55cd0a9c329ecbe9c2606f9025762288936b25037ca8c8090ee Application]"}
2024-02-22T14:23:40.9519229Z     logger.go:130: 2024-02-22T14:23:36.604Z	INFO	Error encountered with rpc request	{"code": -105, "cause": "failed to locate application log: EOF", "method": "getapplicationlog", "params": "[399cf2728ee7c55cd0a9c329ecbe9c2606f9025762288936b25037ca8c8090ee Application]"}
2024-02-22T14:23:40.9523205Z     logger.go:130: 2024-02-22T14:23:36.604Z	DEBUG	processing rpc request	{"method": "getapplicationlog", "params": "[bd4915817316fd13825b9caa898dd42c01df620584299e737583938450eabf71 Application]"}
2024-02-22T14:23:40.9525836Z     logger.go:130: 2024-02-22T14:23:36.689Z	DEBUG	done processing headers	{"headerIndex": 3, "blockHeight": 2, "took": "105.917µs"}
2024-02-22T14:23:40.9527752Z     logger.go:130: 2024-02-22T14:23:36.756Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:36987"}
2024-02-22T14:23:40.9529885Z     logger.go:130: 2024-02-22T14:23:36.756Z	INFO	persisted to disk	{"blocks": 3, "keys": 168, "headerHeight": 3, "blockHeight": 3, "took": "67.496µs"}
2024-02-22T14:23:40.9531260Z --- PASS: TestAwaitUtilCancelTx (0.27s)
2024-02-22T14:23:40.9531788Z FAIL
2024-02-22T14:23:40.9532239Z coverage: 21.6% of statements in ./pkg..., ./cli/...
2024-02-22T14:23:40.9533057Z FAIL	github.com/nspcc-dev/neo-go/cli/util	2.422s
```

```
2024-02-22T14:27:56.0005885Z     logger.go:130: 2024-02-22T14:23:40.814Z	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
2024-02-22T14:27:56.0013202Z     logger.go:130: 2024-02-22T14:23:40.815Z	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[AEIEy5pofzABAAAAAAAAAAAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAtgsaDBTunqIsJ+NL0BSPxBCOCPdOj1BIsgwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQsDABCl1OgAAAAMFO6eoiwn40vQFI/EEI4I906PUEiyDBTYzFqQTVJvyabKtVugLJpv54nJVhTAHwwIdHJhbnNmZXIMFM924ovQBixKR47jVWEBExnzz6TSQWJ9W1I5AQAqEQwhArNiK/QBe9/jF8WK7V9MdT8ga324lgRvp9d0u8S/f43CEUGe0Nw6]"}
2024-02-22T14:27:56.0026207Z     logger.go:130: 2024-02-22T14:23:40.816Z	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[AEIEy5pofzABAAAAAAw6FAAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAtgsaDBTunqIsJ+NL0BSPxBCOCPdOj1BIsgwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQsDABCl1OgAAAAMFO6eoiwn40vQFI/EEI4I906PUEiyDBTYzFqQTVJvyabKtVugLJpv54nJVhTAHwwIdHJhbnNmZXIMFM924ovQBixKR47jVWEBExnzz6TSQWJ9W1I5AUIMQOL5fPdFzeZQmQf0lK+RPvnMHSo819FE9yJ4AxN3F4bYyJMdl8Chx+1R9X9ei0ScAwmGddA/E98saatWIt9QNoIqEQwhArNiK/QBe9/jF8WK7V9MdT8ga324lgRvp9d0u8S/f43CEUGe0Nw6]"}
2024-02-22T14:27:56.0034080Z     logger.go:130: 2024-02-22T14:23:41.787Z	INFO	persisted to disk	{"blocks": 1, "keys": 139, "headerHeight": 1, "blockHeight": 1, "took": "139.342µs"}
2024-02-22T14:27:56.0035687Z     executor.go:220: 
2024-02-22T14:27:56.0037060Z         	Error Trace:	/home/runner/work/neo-go/neo-go/internal/testcli/executor.go:220
2024-02-22T14:27:56.0041145Z         	            				/home/runner/work/neo-go/neo-go/internal/testcli/executor.go:304
2024-02-22T14:27:56.0043164Z         	            				/home/runner/work/neo-go/neo-go/cli/wallet/candidate_test.go:31
2024-02-22T14:27:56.0044308Z         	Error:      	Condition never satisfied
2024-02-22T14:27:56.0045188Z         	Test:       	TestRegisterCandidate
2024-02-22T14:27:56.0046150Z         	Messages:   	too long time waiting for block
2024-02-22T14:27:56.0047743Z     logger.go:130: 2024-02-22T14:23:42.818Z	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:38519"}
2024-02-22T14:27:56.0048992Z --- FAIL: TestRegisterCandidate (2.04s)
```

**Comment by AnnaShaleva** [comment]
OK, not merging it for now, I need to carefully review the updated code, something is wrong.

**Comment by AliceInHunterland** [comment]
also sometimes :
```
    query_test.go:59: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/cli/query/query_test.go:59
        	Error:      	Condition never satisfied
        	Test:       	TestQueryTx
    logger.go:130: 2024-02-22T18:17:53.566+0300	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:51947"}
--- FAIL: TestQueryTx (3.01s)

FAIL
```

getting `key not found`

File: pkg/consensus/consensus.go [hunk 37]
```diff
@@ -281,7 +281,6 @@ func (s *service) Start() {
 		b, _ := s.Chain.GetBlock(s.Chain.CurrentBlockHash()) // Can't fail, we have some current block!
 		s.lastTimestamp = b.Timestamp
 		s.dbft.Start(s.lastTimestamp * nsInMs)
-		s.Chain.SubscribeForBlocks(s.blockEvents)
 		go s.eventLoop()
```
Comment (AnnaShaleva) [inline pkg/consensus/consensus.go:284]: @roman-khimov, do you think it's legit to move block subscription to `s.eventLoop`? I suspect this commit is responsible for recently discovered test failures, because all of them use suspended CLI executor and run chain manually somewhere in the end of the tests.

Initially I requested this change because proper subscription requires blockchain to be running (`notificationDispatcher` loop should be running) and sometimes we may have services started before the blockchain start. So this change is needed for proper services start.

Comment (roman-khimov) [reply pkg/consensus/consensus.go:284]: It doesn't really matter in normal case, nothing but event loop needs these events. And nothing else affects dbft state. But the old code looked a bit more consistent to me.

At the same time, if you're doing something special in tests you might as well pass some wrapped chain into consensus (it only needs a `Ledger` interface, remember?) with subscription method overridden in some way.

**Comment by AnnaShaleva** [comment]
OK, here's the problem, and it's in the second commit: there's a race between consensus service blocks subscription and first block announcement.

Successful test run assume that consensus service is subscribed firstly, and only after that the first block is being announced by Blockchain. In this case consensus service is able to properly update dBFT state and move to the next height:
```
GOROOT=/usr/local/go #gosetup
GOPATH=/home/anna/go #gosetup
/usr/local/go/bin/go test -c -o /home/anna/.cache/JetBrains/GoLand2023.3/tmp/GoLand/___TestQueryTx_in_github_com_nspcc_dev_neo_go_cli_query.test github.com/nspcc-dev/neo-go/cli/query #gosetup
/usr/local/go/bin/go tool test2json -t /home/anna/.cache/JetBrains/GoLand2023.3/tmp/GoLand/___TestQueryTx_in_github_com_nspcc_dev_neo_go_cli_query.test -test.v -test.paniconexit0 -test.run ^\QTestQueryTx\E$
=== RUN   TestQueryTx
    logger.go:130: 2024-02-27T14:02:59.115+0300	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
    logger.go:130: 2024-02-27T14:02:59.115+0300	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
    logger.go:130: 2024-02-27T14:02:59.115+0300	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
    logger.go:130: 2024-02-27T14:02:59.115+0300	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
    logger.go:130: 2024-02-27T14:02:59.115+0300	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
    logger.go:130: 2024-02-27T14:02:59.115+0300	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 864000}
    logger.go:130: 2024-02-27T14:02:59.115+0300	INFO	no storage version found! creating genesis block
2024-02-27T14:02:59.117+0300	INFO	consensus/consensus.go:281	starting consensus service
2024-02-27T14:02:59.117+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:107	initializing dbft	{"height": 1, "view": 0, "index": 0, "role": "Primary"}
2024-02-27T14:02:59.117+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 1, "v": 0, "delay": "0s"}
2024-02-27T14:02:59.117+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:9	broadcasting message	{"type": "PrepareRequest", "height": 1, "view": 0}
2024-02-27T14:02:59.118+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:40	sending PrepareRequest	{"height": 1, "view": 0}
2024-02-27T14:02:59.118+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 1, "v": 0, "delay": "100ms"}
2024-02-27T14:02:59.118+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:29	check preparations	{"hasReq": true, "count": 1, "M": 1}
2024-02-27T14:02:59.118+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:134	sending Commit	{"height": 1, "view": 0}
2024-02-27T14:02:59.118+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:9	broadcasting message	{"type": "Commit", "height": 1, "view": 0}
2024-02-27T14:02:59.118+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 1, "v": 0, "delay": "100ms"}
2024-02-27T14:02:59.118+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:66	approving block	{"height": 1, "hash": "55dfd8f2884f5f17abd9f2d7d1d6ffa7b0e3df419de8eec9a6d8cfd135ee0af2", "tx_count": 0, "merkle": "0000000000000000000000000000000000000000000000000000000000000000", "prev": "fe78c256de052957c4b40d2dceae1deb9074fafaaa4f5f600e64230e60015b62"}
    logger.go:130: 2024-02-27T14:02:59.118+0300	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
    logger.go:130: 2024-02-27T14:02:59.118+0300	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
    logger.go:130: 2024-02-27T14:02:59.118+0300	INFO	MaxFindStorageResultItems is not set or wrong, setting default value	{"MaxFindStorageResultItems": 50}
    logger.go:130: 2024-02-27T14:02:59.118+0300	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
    logger.go:130: 2024-02-27T14:02:59.118+0300	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
    logger.go:130: 2024-02-27T14:02:59.118+0300	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
    logger.go:130: 2024-02-27T14:02:59.118+0300	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
    logger.go:130: 2024-02-27T14:02:59.118+0300	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
    logger.go:130: 2024-02-27T14:02:59.118+0300	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "186.287µs"}
    logger.go:130: 2024-02-27T14:02:59.119+0300	INFO	sending block event	{"index": 1}
    logger.go:130: 2024-02-27T14:02:59.119+0300	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
    logger.go:130: 2024-02-27T14:02:59.120+0300	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
    logger.go:130: 2024-02-27T14:02:59.121+0300	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
    logger.go:130: 2024-02-27T14:02:59.121+0300	DEBUG	processing rpc request	{"method": "getnep17balances", "params": "[56c989e76f9a2ca05bb5caa6c96f524d905accd8]"}
    logger.go:130: 2024-02-27T14:02:59.122+0300	DEBUG	processing rpc request	{"method": "invokescript", "params": "[CxEMFNwk6EPkEi4hj1BzCuuZPYVDDVeBDBTYzFqQTVJvyabKtVugLJpv54nJVhTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I5 ]"}
    logger.go:130: 2024-02-27T14:02:59.122+0300	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
    logger.go:130: 2024-02-27T14:02:59.122+0300	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[AKeXA5G0P5gAAAAAAAAAAAAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAVwsRDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQEAKhEMIQKzYiv0AXvf4xfFiu1fTHU/IGt9uJYEb6fXdLvEv3+NwhFBntDcOg==]"}
    logger.go:130: 2024-02-27T14:02:59.123+0300	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[AKeXA5G0P5gAAAAAAPTGEgAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAVwsRDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQFCDEBYRzEu8edktFHtRk4AEoIR0gVKye0vXSMDOjzthj6LWB2A/C4iBNLqblO+MzDJt/ZDLX/GIHHl9YigHDI9K8NPKhEMIQKzYiv0AXvf4xfFiu1fTHU/IGt9uJYEb6fXdLvEv3+NwhFBntDcOg==]"}
    logger.go:130: 2024-02-27T14:02:59.123+0300	INFO	running blockchain
    logger.go:130: 2024-02-27T14:02:59.123+0300	INFO	running notification dispatcher
    logger.go:130: 2024-02-27T14:02:59.123+0300	INFO	ntf dispatcher: subscribe blocks
    logger.go:130: 2024-02-27T14:02:59.123+0300	INFO	ntf dispatcher: event	{"index": 1, "len(blockFeed)": 1}
    logger.go:130: 2024-02-27T14:02:59.123+0300	INFO	ntf dispatcher: subscribe blocks
2024-02-27T14:02:59.123+0300	DEBUG	consensus/consensus.go:382	new block in the chain	{"dbft index": 1, "chain index": 1}
2024-02-27T14:02:59.123+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:107	initializing dbft	{"height": 2, "view": 0, "index": 0, "role": "Primary"}
    logger.go:130: 2024-02-27T14:02:59.123+0300	INFO	sent block event	{"index": 1}
2024-02-27T14:02:59.123+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 2, "v": 0, "delay": "95.182902ms"}
2024-02-27T14:02:59.219+0300	DEBUG	consensus/consensus.go:313	timer fired	{"height": 2, "view": 0}
2024-02-27T14:02:59.219+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:185	timeout	{"height": 2, "view": 0}
2024-02-27T14:02:59.219+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:9	broadcasting message	{"type": "PrepareRequest", "height": 2, "view": 0}
2024-02-27T14:02:59.220+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:40	sending PrepareRequest	{"height": 2, "view": 0}
2024-02-27T14:02:59.220+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 2, "v": 0, "delay": "100ms"}
2024-02-27T14:02:59.220+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:29	check preparations	{"hasReq": true, "count": 1, "M": 1}
2024-02-27T14:02:59.220+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:134	sending Commit	{"height": 2, "view": 0}
2024-02-27T14:02:59.221+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:9	broadcasting message	{"type": "Commit", "height": 2, "view": 0}
2024-02-27T14:02:59.221+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 2, "v": 0, "delay": "100ms"}
2024-02-27T14:02:59.221+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:66	approving block	{"height": 2, "hash": "e52d6b09becd575bdb33a49502f7e8a4b3d581481428f9f8640f6a8910e97004", "tx_count": 1, "merkle": "1b1c50a37924361ba59b2f0b1d051b12a4a4a27bd1f9fabbb027834705de214e", "prev": "55dfd8f2884f5f17abd9f2d7d1d6ffa7b0e3df419de8eec9a6d8cfd135ee0af2"}
    logger.go:130: 2024-02-27T14:02:59.222+0300	DEBUG	done processing headers	{"headerIndex": 2, "blockHeight": 1, "took": "395.044µs"}
    logger.go:130: 2024-02-27T14:02:59.222+0300	INFO	sending block event	{"index": 2}
    logger.go:130: 2024-02-27T14:02:59.223+0300	INFO	sent block event	{"index": 2}
    logger.go:130: 2024-02-27T14:02:59.223+0300	INFO	ntf dispatcher: event	{"index": 2, "len(blockFeed)": 2}
2024-02-27T14:02:59.223+0300	DEBUG	consensus/consensus.go:382	new block in the chain	{"dbft index": 2, "chain index": 2}
2024-02-27T14:02:59.223+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:107	initializing dbft	{"height": 3, "view": 0, "index": 0, "role": "Primary"}
2024-02-27T14:02:59.223+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 3, "v": 0, "delay": "98.305019ms"}
    logger.go:130: 2024-02-27T14:02:59.223+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:02:59.223+0300	INFO	cleanup started
    logger.go:130: 2024-02-27T14:02:59.223+0300	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:37689"}
    logger.go:130: 2024-02-27T14:02:59.223+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:02:59.223+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:02:59.223+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:02:59.224+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:02:59.224+0300	INFO	ntf dispatcher: unsubscribe
2024-02-27T14:02:59.224+0300	INFO	consensus/consensus.go:292	stopping consensus service
    logger.go:130: 2024-02-27T14:02:59.224+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:02:59.224+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:02:59.224+0300	INFO	persisted to disk	{"blocks": 2, "keys": 166, "headerHeight": 2, "blockHeight": 2, "took": "161.923µs"}
--- PASS: TestQueryTx (0.11s)
PASS

Process finished with the exit code 0
```

Failed test run happens when block 1 is being announced by the blockchain prior to consensus service subscription, and hence, consensus service don't have any way to react on the accepted block (it's not subscribed to blocks yet):
```
GOROOT=/usr/local/go #gosetup
GOPATH=/home/anna/go #gosetup
/usr/local/go/bin/go test -c -o /home/anna/.cache/JetBrains/GoLand2023.3/tmp/GoLand/___TestQueryTx_in_github_com_nspcc_dev_neo_go_cli_query.test github.com/nspcc-dev/neo-go/cli/query #gosetup
/usr/local/go/bin/go tool test2json -t /home/anna/.cache/JetBrains/GoLand2023.3/tmp/GoLand/___TestQueryTx_in_github_com_nspcc_dev_neo_go_cli_query.test -test.v -test.paniconexit0 -test.run ^\QTestQueryTx\E$
=== RUN   TestQueryTx
    logger.go:130: 2024-02-27T14:07:14.686+0300	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
    logger.go:130: 2024-02-27T14:07:14.686+0300	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
    logger.go:130: 2024-02-27T14:07:14.686+0300	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
    logger.go:130: 2024-02-27T14:07:14.686+0300	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
    logger.go:130: 2024-02-27T14:07:14.686+0300	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
    logger.go:130: 2024-02-27T14:07:14.686+0300	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 864000}
    logger.go:130: 2024-02-27T14:07:14.687+0300	INFO	no storage version found! creating genesis block
2024-02-27T14:07:14.688+0300	INFO	consensus/consensus.go:281	starting consensus service
2024-02-27T14:07:14.688+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:107	initializing dbft	{"height": 1, "view": 0, "index": 0, "role": "Primary"}
2024-02-27T14:07:14.688+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 1, "v": 0, "delay": "0s"}
2024-02-27T14:07:14.688+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:9	broadcasting message	{"type": "PrepareRequest", "height": 1, "view": 0}
2024-02-27T14:07:14.688+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:40	sending PrepareRequest	{"height": 1, "view": 0}
2024-02-27T14:07:14.688+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 1, "v": 0, "delay": "100ms"}
2024-02-27T14:07:14.688+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:29	check preparations	{"hasReq": true, "count": 1, "M": 1}
2024-02-27T14:07:14.688+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:134	sending Commit	{"height": 1, "view": 0}
2024-02-27T14:07:14.688+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:9	broadcasting message	{"type": "Commit", "height": 1, "view": 0}
2024-02-27T14:07:14.689+0300	DEBUG	dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:617	reset timer	{"h": 1, "v": 0, "delay": "100ms"}
2024-02-27T14:07:14.689+0300	INFO	dbft@v0.0.0-20230515113611-25db6ba61d5c/check.go:66	approving block	{"height": 1, "hash": "b5deba6210f801eae81619c7d1f0fc2fae987245040f22ec2e7f2d47a55ad2a8", "tx_count": 0, "merkle": "0000000000000000000000000000000000000000000000000000000000000000", "prev": "fe78c256de052957c4b40d2dceae1deb9074fafaaa4f5f600e64230e60015b62"}
    logger.go:130: 2024-02-27T14:07:14.689+0300	INFO	MaxIteratorResultItems is not set or wrong, setting default value	{"MaxIteratorResultItems": 100}
    logger.go:130: 2024-02-27T14:07:14.689+0300	INFO	MaxFindResultItems is not set or wrong, setting default value	{"MaxFindResultItems": 100}
    logger.go:130: 2024-02-27T14:07:14.689+0300	INFO	MaxFindStorageResultItems is not set or wrong, setting default value	{"MaxFindStorageResultItems": 50}
    logger.go:130: 2024-02-27T14:07:14.689+0300	INFO	MaxNEP11Tokens is not set or wrong, setting default value	{"MaxNEP11Tokens": 100}
    logger.go:130: 2024-02-27T14:07:14.689+0300	INFO	MaxRequestBodyBytes is not set or wong, setting default value	{"MaxRequestBodyBytes": 5242880}
    logger.go:130: 2024-02-27T14:07:14.689+0300	INFO	MaxRequestHeaderBytes is not set or wong, setting default value	{"MaxRequestHeaderBytes": 1048576}
    logger.go:130: 2024-02-27T14:07:14.689+0300	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
    logger.go:130: 2024-02-27T14:07:14.689+0300	INFO	starting rpc-server	{"endpoint": "127.0.0.1:0"}
    logger.go:130: 2024-02-27T14:07:14.689+0300	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "532.125µs"}
    logger.go:130: 2024-02-27T14:07:14.690+0300	INFO	sending block event	{"index": 1}
    logger.go:130: 2024-02-27T14:07:14.691+0300	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
    logger.go:130: 2024-02-27T14:07:14.691+0300	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
    logger.go:130: 2024-02-27T14:07:14.694+0300	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
    logger.go:130: 2024-02-27T14:07:14.694+0300	DEBUG	processing rpc request	{"method": "getnep17balances", "params": "[56c989e76f9a2ca05bb5caa6c96f524d905accd8]"}
    logger.go:130: 2024-02-27T14:07:14.694+0300	DEBUG	processing rpc request	{"method": "invokescript", "params": "[CxEMFNwk6EPkEi4hj1BzCuuZPYVDDVeBDBTYzFqQTVJvyabKtVugLJpv54nJVhTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I5 ]"}
    logger.go:130: 2024-02-27T14:07:14.695+0300	DEBUG	processing rpc request	{"method": "getblockcount", "params": "[]"}
    logger.go:130: 2024-02-27T14:07:14.696+0300	DEBUG	processing rpc request	{"method": "calculatenetworkfee", "params": "[AFIYXm60P5gAAAAAAAAAAAAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAVwsRDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQEAKhEMIQKzYiv0AXvf4xfFiu1fTHU/IGt9uJYEb6fXdLvEv3+NwhFBntDcOg==]"}
    logger.go:130: 2024-02-27T14:07:14.696+0300	DEBUG	processing rpc request	{"method": "sendrawtransaction", "params": "[AFIYXm60P5gAAAAAAPTGEgAAAAAABAAAAAHYzFqQTVJvyabKtVugLJpv54nJVgEAVwsRDBTcJOhD5BIuIY9QcwrrmT2FQw1XgQwU2MxakE1Sb8mmyrVboCyab+eJyVYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQFCDEBeuST7kfHmKCT4rYI/LgAmimZcimmKUo4UoSsG+yzbs3gXIRoHc81ka73Ub0DlfZ5D58sZULBp9tXiO/uZOPLrKhEMIQKzYiv0AXvf4xfFiu1fTHU/IGt9uJYEb6fXdLvEv3+NwhFBntDcOg==]"}
    logger.go:130: 2024-02-27T14:07:14.697+0300	INFO	running blockchain
    logger.go:130: 2024-02-27T14:07:14.697+0300	INFO	running notification dispatcher
    logger.go:130: 2024-02-27T14:07:14.697+0300	INFO	ntf dispatcher: event	{"index": 1, "len(blockFeed)": 0}
    logger.go:130: 2024-02-27T14:07:14.697+0300	INFO	ntf dispatcher: subscribe blocks
    logger.go:130: 2024-02-27T14:07:14.697+0300	INFO	ntf dispatcher: subscribe blocks
    logger.go:130: 2024-02-27T14:07:14.697+0300	INFO	sent block event	{"index": 1}
2024-02-27T14:07:14.789+0300	DEBUG	consensus/consensus.go:313	timer fired	{"height": 1, "view": 0}
    logger.go:130: 2024-02-27T14:07:14.798+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:14.898+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:14.998+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.098+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.197+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.298+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.398+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.498+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.597+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.698+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.698+0300	INFO	persisted to disk	{"blocks": 1, "keys": 139, "headerHeight": 1, "blockHeight": 1, "took": "67.524µs"}
    logger.go:130: 2024-02-27T14:07:15.798+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.898+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:15.998+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:16.097+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:16.198+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:16.298+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:16.398+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:16.497+0300	INFO	query tx
    logger.go:130: 2024-02-27T14:07:16.598+0300	INFO	query tx
    executor.go:220: 
        	Error Trace:	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/internal/testcli/executor.go:220
        	            				/home/anna/Documents/GitProjects/nspcc-dev/neo-go/cli/query/query_test.go:56
        	Error:      	Condition never satisfied
        	Test:       	TestQueryTx
        	Messages:   	too long time waiting for block
    logger.go:130: 2024-02-27T14:07:16.698+0300	INFO	cleanup started
    logger.go:130: 2024-02-27T14:07:16.698+0300	INFO	shutting down RPC server	{"endpoint": "127.0.0.1:37603"}
    logger.go:130: 2024-02-27T14:07:16.698+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:07:16.698+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:07:16.698+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:07:16.698+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:07:16.699+0300	INFO	ntf dispatcher: unsubscribe
2024-02-27T14:07:16.699+0300	INFO	consensus/consensus.go:292	stopping consensus service
    logger.go:130: 2024-02-27T14:07:16.699+0300	INFO	ntf dispatcher: unsubscribe
    logger.go:130: 2024-02-27T14:07:16.699+0300	INFO	ntf dispatcher: unsubscribe
--- FAIL: TestQueryTx (2.01s)

FAIL

Process finished with the exit code 1
```

File: pkg/consensus/consensus.go [hunk 38]
```diff
@@ -299,6 +298,7 @@ func (s *service) Shutdown() {
 }
 
 func (s *service) eventLoop() {
+	s.Chain.SubscribeForBlocks(s.blockEvents)
```
Comment (AnnaShaleva) [inline pkg/consensus/consensus.go:302]: So we need the following code to be added before the `events` loop handling to fix the race described in https://github.com/nspcc-dev/neo-go/pull/3307#issuecomment-1966309470:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ git diff
diff --git a/pkg/consensus/consensus.go b/pkg/consensus/consensus.go
index 5eea615e..fcedfef0 100644
--- a/pkg/consensus/consensus.go
+++ b/pkg/consensus/consensus.go
@@ -300,6 +300,14 @@ func (s *service) Shutdown() {
 
 func (s *service) eventLoop() {
        s.Chain.SubscribeForBlocks(s.blockEvents)
+
+       // Manually sync up with potentially missed fresh blocks that may be added by blockchain
+       // before the subscription.
+       b, _ := s.Chain.GetBlock(s.Chain.CurrentBlockHash()) // Can't fail, we have some current block!
+       if b.Timestamp >= s.lastTimestamp {
+               s.handleChainBlock(b)
+       }
+
 events:
        for {
                select {
```

@roman-khimov, agree to add such change?

File: pkg/consensus/consensus.go (hunk 37 above)
Comment (AnnaShaleva) [reply pkg/consensus/consensus.go:284]: We can't preserve the previous code because it may lead to a deadlock (not in tests, but in the node).

File: pkg/consensus/consensus.go (hunk 38 above)
Comment (roman-khimov) [reply pkg/consensus/consensus.go:302]: Makes sense.

**Comment by AliceInHunterland** [comment]
got similar to https://github.com/nspcc-dev/neo-go/issues/2977#issuecomment-1952760802  on windows [Run tests (windows-2022, 1.21)](https://github.com/nspcc-dev/neo-go/actions/runs/8064489305/job/22028475673?pr=3307#logs)
```
NAME  TestClient_IteratorSessions/traverse,_concurrent_access
2024-02-27T12:28:36.1047187Z     client_test.go:1547: 
2024-02-27T12:28:36.1047782Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:1547
2024-02-27T12:28:36.1048498Z         	            				C:/hostedtoolcache/windows/go/1.21.7/x64/src/runtime/asm_amd64.s:1650
2024-02-27T12:28:36.1048710Z         	Error:      	Received unexpected error:
2024-02-27T12:28:36.1049994Z         	            	Post "http://127.0.0.1:61547": dial tcp 127.0.0.1:61547: connectex: No connection could be made because the target machine actively refused it.
2024-02-27T12:28:36.1050366Z         	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
2024-02-27T12:28:36.1050577Z     client_test.go:1547: 
2024-02-27T12:28:36.1051059Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:1547
2024-02-27T12:28:36.1051789Z         	            				C:/hostedtoolcache/windows/go/1.21.7/x64/src/runtime/asm_amd64.s:1650
2024-02-27T12:28:36.1052000Z         	Error:      	Received unexpected error:
2024-02-27T12:28:36.1053287Z         	            	Post "http://127.0.0.1:61547": dial tcp 127.0.0.1:61547: connectex: No connection could be made because the target machine actively refused it.
2024-02-27T12:28:36.1053642Z         	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
2024-02-27T12:28:36.1053768Z     client_test.go:1547: 
```

File: pkg/consensus/consensus.go (hunk 38 above)
Comment (AnnaShaleva) [reply pkg/consensus/consensus.go:302]: Not critical for other services, only consensus is affected.

**Review by AnnaShaleva — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]
