### PR TITLE
compiler: fix iterating over nil slice

### LINKED ISSUE #3608: Iterating over nil (null) slices lead to an error
Nil slice iteration (no-op) looks natural in GO but did not work for me in the contract.

## Current Behavior
```go
func hi(t []int) {
    for i, replica := range t {
		storage.Put(ctx, []byte{byte(i)}, replica)
	}
}
```

Lead to `at instruction 4754 (SIZE): invalid conversion: Null/ByteString` if i pass `nil` to `Invoker`. NOTE: I did not deploy the contract, just tested it in neofs-contracts: https://github.com/nspcc-dev/neofs-contract/blob/a8d5e001a2e5a552676eecd40ef78629ecdfafa2/tests/container_test.go
Maybe that is important.

## Expected Behavior
Just skipping `for`.

## Possible Solution
Change compiler code?

## Steps to Reproduce
Try to compile and call the code from `Current Behavior`.

## Context
https://github.com/nspcc-dev/neofs-contract/pull/438

## Regression
Not sure.

## Your Environment
github.com/nspcc-dev/neo-go v0.106.3

### PR DESCRIPTION
**Pull request by Turalchik**
Close #3608.

### CODE REVIEW

File: pkg/compiler/codegen.go [hunk 1]
```diff
@@ -1369,7 +1370,12 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
 			isInteger = typ.Info()&types.IsInteger != 0
 		}
 		if !isInteger {
+			emit.Opcodes(c.prog.BinWriter, opcode.DUP, opcode.ISNULL)
+			emit.Instruction(c.prog.BinWriter, opcode.JMPIF, []byte{2 + 1 + 2})
```
Comment (roman-khimov) [inline pkg/compiler/codegen.go]: You can save one JMP by doing
```
JMPIFN OLD_CODE
DROP
JMPL lAfterDrops
DUP // OLD_CODE
...
```

File: pkg/compiler/codegen.go [hunk 2]
```diff
@@ -1343,6 +1343,7 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
 		c.scope.vars.newScope()
 		defer c.scope.vars.dropScope()
 
+		lAfterDrops := c.newLabel()
```
Comment (roman-khimov) [inline pkg/compiler/codegen.go]: `labelAfterRangeLoop`? "drops" are somewhat internal to the implementation.

File: pkg/compiler/slice_test.go [hunk 3]
```diff
@@ -411,6 +411,46 @@ var sliceTestCases = []testCase{
 		`,
 		big.NewInt(1),
 	},
+	{
+		"range, over nil slice",
+		`func F%d() int {
+			var s []any
+			cnt := 0
+			for _ = range s {
```
Comment (roman-khimov) [inline pkg/compiler/slice_test.go]: `_ =` isn't needed here.

File: pkg/compiler/codegen.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/compiler/codegen.go]: BTW, it can be nil map, and I'm not sure if nil map can be represented as `stackitem.Null`. If so, then we may exclude `if isMap {` condition handling 5 lines below for ISNULL case.

**Review by AnnaShaleva — APPROVED** [review]
