### PR TITLE
vm: calculate GAS spent

### LINKED ISSUE #607: Wrong TX execution result on mainnet at block 1826890
https://neoscan.io/transaction/2bbe5b6c03902dc9f7b4152511700f264f981abac58e3f7fd65190303a6027c3

This transaction seems to fail in mainnet, but HALT during dump in neo-go.
Block 1826890 .

### PR DESCRIPTION
**Pull request by fyrchik**
Closes #607 .

2 parameters of `getPrice` are actually excessive, because they can be received via `VM`.
I was also thinking about generic pre-instruction hook `func(*vm.VM)` so that GAS calculation is fully transparent for VM, but was not sure if it will be simpler.

### CODE REVIEW

File: pkg/vm/vm.go [hunk 1]
```diff
@@ -1421,6 +1415,16 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
 	return
 }
 
+func (v *VM) jump(ctx *Context, parameter []byte) {
```
Comment (volekerb) [inline pkg/vm/vm.go]: nit: would be nice to have godoc here since it's not that obvious how parameter is related to jump

File: pkg/core/gas_price.go [hunk 2]
```diff
@@ -0,0 +1,106 @@
+package core
+
+import (
+	"github.com/CityOfZion/neo-go/pkg/smartcontract"
+	"github.com/CityOfZion/neo-go/pkg/util"
+	"github.com/CityOfZion/neo-go/pkg/vm"
+	"github.com/CityOfZion/neo-go/pkg/vm/opcode"
+)
+
+// interopGasRatio is a multiplier by which a number returned from price getter
```
Comment (volekerb) [inline pkg/core/gas_price.go]: nit: it will be nice to understand why do we need it at all, i.e. business meaning of interopGasRatio

File: pkg/core/gas_price.go [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+// and Fixed8 amount of GAS differ.
+const interopGasRatio = int64(100000)
+
+// gasForFree is an amount of GAS which can be spent for free = 10 GAS.
+const gasForFree = util.Fixed8(10 * 100000000)
+
+func getPrice(v *vm.VM, op opcode.Opcode, parameter []byte) int {
```
Comment (volekerb) [inline pkg/core/gas_price.go]: nit: will be great to have some doc here and some example of calculation

File: pkg/core/gas_price.go [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+		systemStoragePutEx       = 0x3a9be173 // System.Storage.PutEx
+		neoStoragePut            = 0xf541a152 // Neo.Storage.Put
+		antSharesStoragePut      = 0x5f300a9e // AntShares.Storage.Put
+	)
+
+	estack := v.Estack()
+
+	switch id {
+	case neoAssetCreate, antSharesAssetCreate:
+		return int(5000 * 100000000 / interopGasRatio)
```
Comment (volekerb) [inline pkg/core/gas_price.go]: nit: vote to have constants for all "magic numbers" in order to have documented numbers

[the remark this answers is not in the document]
Comment (roman-khimov) [reply pkg/core/gas_price.go]: Same for the rest of these, basically, it's this section:
```
  SystemFee:
    EnrollmentTransaction: 1000
    IssueTransaction: 500
    PublishTransaction: 500
    RegisterTransaction: 10000
```
Also, this particular one could be propagated to `systemInterops` and `neoInterops` tables during initialization as it doesn't depend on execution context.

File: pkg/core/gas_price.go [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+			fee += 400
+		}
+
+		if props&smartcontract.HasDynamicInvoke != 0 {
+			fee += 500
+		}
+
+		return int(fee * multiplier)
+	case systemStoragePut, systemStoragePutEx, neoStoragePut, antSharesStoragePut:
+		return ((len(estack.Peek(1).Bytes())+len(estack.Peek(2).Bytes())-1)/1024 + 1) * 1000
```
Comment (volekerb) [inline pkg/core/gas_price.go]: nit: this calculation looks not that trivial as others. So I would prefer to have it documented or to have unit test which helps developer to understand what is that and check him/herself

File: pkg/vm/context.go [hunk 6]
```diff
@@ -124,6 +124,11 @@ func (c *Context) IP() int {
 	return c.ip + 1
 }
 
+// Estack return evaluation stack.
```
Comment (volekerb) [inline pkg/vm/context.go]: nit: returnS

File: pkg/vm/context.go [hunk 7]
```diff
@@ -124,6 +124,11 @@ func (c *Context) IP() int {
...
+func (c *Context) Estack() *Stack {
```
Comment (roman-khimov) [inline pkg/vm/context.go]: I don't see it being used.

File: pkg/core/gas_price.go [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+		systemStoragePutEx       = 0x3a9be173 // System.Storage.PutEx
+		neoStoragePut            = 0xf541a152 // Neo.Storage.Put
+		antSharesStoragePut      = 0x5f300a9e // AntShares.Storage.Put
+	)
+
+	const multiplier = fixed8Decimals / interopGasRatio
+
+	estack := v.Estack()
+
+	switch id {
```
Comment (roman-khimov) [inline pkg/core/gas_price.go]: Aren't some of these configurable?
```
    EnrollmentTransaction: 1000
    IssueTransaction: 500
    PublishTransaction: 500
    RegisterTransaction: 10000
```
Granted, that's about specific transaction types, but I'm curious whether C# node uses the same constants for syscalls?

File: pkg/core/blockchain.go [hunk 9]
```diff
@@ -514,6 +514,11 @@ func (bc *Blockchain) storeBlock(block *block.Block) error {
 			v := bc.spawnVMWithInterops(systemInterop)
 			v.SetCheckedHash(tx.VerificationHash().BytesBE())
 			v.LoadScript(t.Script)
+			v.SetPriceGetter(getPrice)
+
+			gasAmount := gasForFree + t.Gas
+			v.SetGasLimit(int(gasAmount / util.Fixed8(interopGasRatio)))
```
Comment (roman-khimov) [inline pkg/core/blockchain.go]: We also need some inifinite-gas mode, we're gonna be using it for neofs, for example to avoid messing with gas.

**Comment by roman-khimov** [comment]
Two additional but closely related things:
 * we should return true gas spent from RPC calls (it's stubbed out at the moment)
 * RPC invocations should be gas-limited and this limit should be configurable

File: pkg/core/gas_price.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (fyrchik) [reply pkg/core/gas_price.go]: It is just a constant in C#
https://github.com/neo-project/neo/blob/master-2.x/neo/SmartContract/ApplicationEngine.cs#L102

File: pkg/vm/vm.go [hunk 10]
```diff
@@ -130,6 +131,12 @@ func (v *VM) GasConsumed() int {
 	return v.gasConsumed
 }
 
+// SetGasLimit sets maximum amount of gas which v can spent.
+// If max <= 0, no limit is imposed.
+func (v *VM) SetGasLimit(max int) {
```
[the remark this answers is not in the document]
Comment (fyrchik) [reply pkg/vm/vm.go]: VM also needs some way to calculate price, so it is already 2 parameters. I see no problem in setting it explicitly. Another constructor can be useful though, e.g. `NewWithPrice(max util.Fixed8, getPrice func(...)..)`. Or make `New` accept functional options `func(*VM)` to save old usages.

File: pkg/core/blockchain.go (hunk 9 above)
Comment (fyrchik) [reply pkg/core/blockchain.go]: I have added `FreeGasLimit` which can be set to zero if needed.

File: pkg/vm/vm.go [hunk 11]
```diff
@@ -1104,7 +1104,10 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
 		arr := elem.Bytes()
 		v.estack.PushVal(len(arr))
 
-	case opcode.JMP, opcode.JMPIF, opcode.JMPIFNOT:
+	case opcode.JMP:
+		v.jump(ctx, parameter)
+
+	case opcode.JMPIF, opcode.JMPIFNOT:
```
Comment (roman-khimov) [inline pkg/vm/vm.go]: There is still some code duplication left, it'd be nice to unify parameter parsing and checking.

File: pkg/core/gas_price.go [hunk 12]
```diff
@@ -0,0 +1,118 @@
...
+// interopGasRatio is a multiplier by which a number returned from price getter
+// and Fixed8 amount of GAS differ. Numbers defined in syscall tables are a multiple
+// of 0.001 GAS = Fixed8(10^5).
+const interopGasRatio = 100000
+
+// gas is an alias for readability.
+const gas = util.Decimals
+
+// gasForFree is an amount of GAS which can be spent for free = 10 GAS.
+const gasForFree = 10 * gas
```
[the remark this answers is not in the document]
Comment (roman-khimov) [reply pkg/core/gas_price.go]: Already done by the subsequent commit, so it's OK.
