### PR TITLE
compiler: temporary disallow generics usages

### LINKED ISSUE #3040: panic: interface conversion: ast.Expr is *ast.IndexExpr, not *ast.Ident
code:
``` golang
package fields

import (
	"bytes"
	"math/big"
)

// Fq is the Z field over modulus Q
type Fq struct {
	Q *big.Int // Q
}

// NewFq generates a new Fq
func NewFq(q *big.Int) Fq {
	return Fq{
		q,
	}
}

// Zero returns a Zero value on the Fq
func (fq Fq) Zero() *big.Int {
	return big.NewInt(int64(0))
}

// One returns a One value on the Fq
func (fq Fq) One() *big.Int {
	return big.NewInt(int64(1))
}

// Add performs an addition on the Fq
func (fq Fq) Add(a, b *big.Int) *big.Int {
	r := new(big.Int).Add(a, b)
	return new(big.Int).Mod(r, fq.Q)
}

// Double performs a doubling on the Fq
func (fq Fq) Double(a *big.Int) *big.Int {
	r := new(big.Int).Add(a, a)
	return new(big.Int).Mod(r, fq.Q)
}

// Sub performs a subtraction on the Fq
func (fq Fq) Sub(a, b *big.Int) *big.Int {
	r := new(big.Int).Sub(a, b)
	return new(big.Int).Mod(r, fq.Q)
}

// Neg performs a negation on the Fq
func (fq Fq) Neg(a *big.Int) *big.Int {
	m := new(big.Int).Neg(a)
	return new(big.Int).Mod(m, fq.Q)
}

// Mul performs a multiplication on the Fq
func (fq Fq) Mul(a, b *big.Int) *big.Int {
	m := new(big.Int).Mul(a, b)
	return new(big.Int).Mod(m, fq.Q)
}

func (fq Fq) MulScalar(base, e *big.Int) *big.Int {
	return fq.Mul(base, e)
}

// Inverse returns the inverse on the Fq
func (fq Fq) Inverse(a *big.Int) *big.Int {
	return new(big.Int).ModInverse(a, fq.Q)
	// q := bigCopy(fq.Q)
	// t := big.NewInt(int64(0))
	// r := fq.Q
	// newt := big.NewInt(int64(0))
	// newr := fq.Affine(a)
	// for !bytes.Equal(newr.Bytes(), big.NewInt(int64(0)).Bytes()) {
	// 	q := new(big.Int).Div(bigCopy(r), bigCopy(newr))
	//
	// 	t = bigCopy(newt)
	// 	newt = fq.Sub(t, fq.Mul(q, newt))
	//
	// 	r = bigCopy(newr)
	// 	newr = fq.Sub(r, fq.Mul(q, newr))
	// }
	// if t.Cmp(big.NewInt(0)) == -1 { // t< 0
	// 	t = fq.Add(t, q)
	// }
	// return t
}

// Div performs the division over the finite field
func (fq Fq) Div(a, b *big.Int) *big.Int {
	d := fq.Mul(a, fq.Inverse(b))
	return new(big.Int).Mod(d, fq.Q)
}

// Square performs a square operation on the Fq
func (fq Fq) Square(a *big.Int) *big.Int {
	m := new(big.Int).Mul(a, a)
	return new(big.Int).Mod(m, fq.Q)
}

// Exp performs the exponential over Fq
func (fq Fq) Exp(base *big.Int, e *big.Int) *big.Int {
	res := fq.One()
	rem := fq.Copy(e)
	exp := base

	for !bytes.Equal(rem.Bytes(), big.NewInt(int64(0)).Bytes()) {
		if BigIsOdd(rem) {
			res = fq.Mul(res, exp)
		}
		exp = fq.Square(exp)
		rem = new(big.Int).Rsh(rem, 1)
	}
	return res
}

func (fq Fq) IsZero(a *big.Int) bool {
	return bytes.Equal(a.Bytes(), fq.Zero().Bytes())
}

func (fq Fq) Copy(a *big.Int) *big.Int {
	return new(big.Int).SetBytes(a.Bytes())
}

func (fq Fq) Affine(a *big.Int) *big.Int {
	nq := fq.Neg(fq.Q)

	aux := a
	if aux.Cmp(big.NewInt(int64(0))) == -1 { // negative value
		if aux.Cmp(nq) != 1 { // aux less or equal nq
			aux = new(big.Int).Mod(aux, fq.Q)
		}
		if aux.Cmp(big.NewInt(int64(0))) == -1 { // negative value
			aux = new(big.Int).Add(aux, fq.Q)
		}
	} else {
		if aux.Cmp(fq.Q) != -1 { // aux greater or equal nq
			aux = new(big.Int).Mod(aux, fq.Q)
		}
	}
	return aux
}

func (fq Fq) Equal(a, b *big.Int) bool {
	aAff := fq.Affine(a)
	bAff := fq.Affine(b)
	return bytes.Equal(aAff.Bytes(), bAff.Bytes())
}

func BigIsOdd(n *big.Int) bool {
	one := big.NewInt(int64(1))
	and := new(big.Int).And(n, one)
	return bytes.Equal(and.Bytes(), big.NewInt(int64(1)).Bytes())
}

```

backtrace:
```

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).getFuncNameFromDecl(...)
        github.com/nspcc-dev/neo-go/pkg/compiler/func_scope.go:88
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).analyzeFuncAndGlobalVarUsage.func1.1({0x1489928?, 0xc0005885a0})
        github.com/nspcc-dev/neo-go/pkg/compiler/analysis.go:362 +0xd98
go/ast.inspector.Visit(0xc0094059a0, {0x1489928?, 0xc0005885a0?})
        go/ast/walk.go:386 +0x31
go/ast.Walk({0x1483d20?, 0xc0094059a0?}, {0x1489928?, 0xc0005885a0?})
        go/ast/walk.go:51 +0x5f
go/ast.walkDeclList({0x1483d20, 0xc0094059a0}, {0xc0005a2000?, 0x43, 0x7?})
        go/ast/walk.go:38 +0x69
go/ast.Walk({0x1483d20?, 0xc0094059a0?}, {0x14898d8?, 0xc000299320?})
        go/ast/walk.go:366 +0x17ac
go/ast.Inspect(...)
        go/ast/walk.go:397
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).analyzeFuncAndGlobalVarUsage.func1(0xc009428f00?, 0xc000098af0)
        github.com/nspcc-dev/neo-go/pkg/compiler/analysis.go:346 +0x192
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).ForEachFile.func1(0xc000499500)
        github.com/nspcc-dev/neo-go/pkg/compiler/compiler.go:133 +0x82
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).ForEachPackage(0xc009428f00, 0xc0003ad530)
        github.com/nspcc-dev/neo-go/pkg/compiler/compiler.go:124 +0x43
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).ForEachFile(0x702dca8?, 0x91e9008?)
        github.com/nspcc-dev/neo-go/pkg/compiler/compiler.go:130 +0x45
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).analyzeFuncAndGlobalVarUsage(0xc009428f00)
        github.com/nspcc-dev/neo-go/pkg/compiler/analysis.go:339 +0x15f
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).compile(0xc009428f00, 0xc00941d440, 0x10000000047afde?)
        github.com/nspcc-dev/neo-go/pkg/compiler/codegen.go:2202 +0xff
github.com/nspcc-dev/neo-go/pkg/compiler.codeGen(0xc00941d440)
        github.com/nspcc-dev/neo-go/pkg/compiler/codegen.go:2286 +0x385
github.com/nspcc-dev/neo-go/pkg/compiler.CompileWithOptions({0x7ffde4c8a076?, 0x3?}, {0x0?, 0x0?}, 0xc000396000)
        github.com/nspcc-dev/neo-go/pkg/compiler/compiler.go:249 +0x65
github.com/nspcc-dev/neo-go/pkg/compiler.CompileAndSave({0x7ffde4c8a076, 0x12}, 0xc000396000)
        github.com/nspcc-dev/neo-go/pkg/compiler/compiler.go:265 +0x2de
github.com/nspcc-dev/neo-go/cli/smartcontract.contractCompile(0xc000388420)
        github.com/nspcc-dev/neo-go/cli/smartcontract/smart_contract.go:479 +0xc2f
github.com/urfave/cli.HandleAction({0x101d180?, 0x1342400?}, 0x7?)
        github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x11ef3e6, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x121a98c, 0x27}, {0x1245f73, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.5/command.go:173 +0x67b
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0002e81c0, 0xc000388000)
        github.com/urfave/cli@v1.22.5/app.go:405 +0xe87
github.com/urfave/cli.Command.startApp({{0x11f0a0b, 0x8}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x121bcbc, 0x28}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.5/command.go:372 +0xb7f
github.com/urfave/cli.Command.Run({{0x11f0a0b, 0x8}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x121bcbc, 0x28}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.5/command.go:102 +0x845
github.com/urfave/cli.(*App).Run(0xc0002e8000, {0xc00003e070, 0x7, 0x7})
        github.com/urfave/cli@v1.22.5/app.go:277 +0xb67
main.main()
        ./main.go:12 +0x33
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
This PR includes the following changes:

1. Properly retrieve name of generic functions (fix panic described in #3040).
2. Disallow generics usages in the following cases:
    * Generic method receiver
    * Generic function parameters
    * Generic type declaration

Close #3040. Ref. #2377.

### CODE REVIEW

**Comment by AnnaShaleva** [comment]
@roman-khimov, this problem is completely generic-related, I'm not sure we'd like to fix this panic right now with some temporary solution. Please, see the https://github.com/nspcc-dev/neo-go/issues/3040#issuecomment-1590708265.

**Comment by AnnaShaleva** [comment]
`getFuncNameFromDecl` is used in many places (including the map keys) and returns single string. Is it worth to change all its usages as temprary solution?

**Comment by roman-khimov** [comment]
I don't know if there is any way to detect generic code use without going that deep. That'd be perfect, but if we don't have it then we can:
 * believe in this local fix to be sufficient for at least some subset of problems (maybe it really allows to compile something? maybe it'll fail in some other place?)
 * try leveraging `c.prog.Err`
 * try leveraging `analyzeFuncAndGlobalVarUsage` that looks at every function anyway and it does so before code-generating functions (btw, this seems to be easy enough to do)
 * at least panicing with some more meaningful message

**Comment by AnnaShaleva** [comment]
Close #3040.

**Comment by AnnaShaleva** [comment]
I've adjusted the behaviour for method receiver, now the proper error is returned to the user and it is done inside the `analyzeFuncAndGlobalVarUsage` before the compilation itself. But I need some more time to carefully handle other cases of generics usages. Do we need to include these fixes to 0.102.0?

**Comment by roman-khimov** [comment]
If you don't feel comfortable with these changes, it's OK to postpone them for 0.102.1, no need to rush here.

**Comment by AnnaShaleva** [comment]
@roman-khimov, I've reworked the initial structure a bit so that it'll be easier for us to revert generics-related commits. Now all generics-related checks are separated in the `checkGenerics*` functions.

File: pkg/compiler/func_scope.go [hunk 1]
```diff
@@ -85,7 +85,19 @@ func (c *codegen) getFuncNameFromDecl(pkgPath string, decl *ast.FuncDecl) string
...
 			name = t.Name + "." + name
 		case *ast.StarExpr:
-			name = t.X.(*ast.Ident).Name + "." + name
+			switch t.X.(type) {
+			case *ast.Ident:
+				name = t.X.(*ast.Ident).Name + "." + name
+			case *ast.IndexExpr:
+				// Generic func declaration receiver: func (x *Pointer[T]) Load() *T
+				name = t.X.(*ast.IndexExpr).X.(*ast.Ident).Name + "." + name
+			}
```
Comment (roman-khimov) [inline pkg/compiler/func_scope.go:94]: Panic by default?

File: pkg/compiler/func_scope.go [hunk 2]
```diff
@@ -85,7 +85,19 @@ func (c *codegen) getFuncNameFromDecl(pkgPath string, decl *ast.FuncDecl) string
...
+		case *ast.IndexExpr:
+			switch t.X.(type) {
```
Comment (roman-khimov) [inline pkg/compiler/func_scope.go:96]: Why a switch here?

File: pkg/compiler/analysis.go [hunk 3]
```diff
@@ -19,6 +19,8 @@ var (
 	ErrMissingExportedParamName = errors.New("exported method is not allowed to have unnamed parameter")
 	// ErrInvalidExportedRetCount is returned when exported contract method has invalid return values count.
 	ErrInvalidExportedRetCount = errors.New("exported method is not allowed to have more than one return value")
+	// ErrGenericsUnsuppored is returned when generics-related tokens are encountered.
+	ErrGenericsUnsuppored = errors.New("generics are currently unsupported, please, see the https://github.com/nspcc-dev/neo-go/issues/2377")
```
Comment (roman-khimov) [inline pkg/compiler/analysis.go:23]: 2376! Commits should reference it as well.

**Review by roman-khimov — CHANGES_REQUESTED** [review]
Can we at least partially fix #3023 here? Our compiler documentation still doesn't say a word about generics.

File: pkg/compiler/func_scope.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/compiler/func_scope.go:94]: No, we won't panic here. We will retrieve the proper name and I want this code to be kept in future (unlike the rest of commits in this PR). We will analize whether the method is generic in a separate place.

File: pkg/compiler/func_scope.go (hunk 2 above)
Comment (roman-khimov) [reply pkg/compiler/func_scope.go:96]: Yeah, there needs to be some reasonable error, otherwise we have an undefined behavior and that's not what I would like to have in the compiler.

File: pkg/compiler/func_scope.go (hunk 1 above)
Comment (AnnaShaleva) [reply pkg/compiler/func_scope.go:97]: Fixed.

File: pkg/compiler/analysis.go (hunk 3 above)
Comment (AnnaShaleva) [reply pkg/compiler/analysis.go]: Fixed.

File: docs/compiler.md [hunk 4]
```diff
@@ -31,6 +31,8 @@ a dialect of Go rather than a complete port of the language:
  * type assertion with two return values is not supported; single return value (of the desired type)
    is supported; type assertion panics if value can't be asserted to the desired type, therefore
    it's up to the programmer whether assert can be performed successfully.
+ * type aliases including the built-in `any` alias are supported.
+ * generics are not supported, but eventually will be, ref. https://github.com/nspcc-dev/neo-go/issues/2376.
```
Comment (roman-khimov) [inline docs/compiler.md:35]: Not sure they will be supported properly, but partially maybe.

**Review by roman-khimov — APPROVED** [review]

File: docs/compiler.md (hunk 4 above)
Comment (AnnaShaleva) [reply docs/compiler.md]: Adjusted.

Comment (AnnaShaleva) [reply docs/compiler.md]: Hope, they will. At least function arguments can be supported, it doesn't seem impossible.
