### PR TITLE
rpc: fix subscribers locking logic and properly drain poll-based waiter receiver

### LINKED ISSUE #2775: subscribe filtering issue
Hi!

We're trying to use subscribe for both FAULT and HALT tx, it doesnt look like it is working as intended

```
{
        "jsonrpc": "2.0",
        "method": "subscribe",
        "params": ["transaction_executed", {"container": hash}],
        "id": 1
}
```

i would expect this to work, but throws params invalid, otherwise maybe there's another way if i want to subscribe both to FAULT and HALT tx?

just HALT or just FAULT works of course like this

```
{
        "jsonrpc": "2.0",
        "method": "subscribe",
        "params": ["transaction_executed", { "state": "HALT", "container": hash }],
        "id": 1
}
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #2775.

@roman-khimov, it's a bingo...

### CODE REVIEW

File: pkg/services/rpcsrv/params/param.go [hunk 1]
```diff
@@ -443,3 +443,12 @@ func (p *Param) GetUUID() (uuid.UUID, error) {
...
 	return id, nil
 }
+
+// GetRawMessage returns underlying JSON raw parameter. Do not modify the
+// resulting JSON, otherwise it may affect the parameter decoding.
+func (p *Param) GetRawMessage() (json.RawMessage, error) {
+	if p == nil {
+		return nil, errMissingParameter
+	}
+	return p.RawMessage, nil
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/params/param.go:453]: This will make CodeQL unhappy because it's a direct user input used for logging.

File: pkg/rpcclient/actor/waiter.go [hunk 2]
```diff
@@ -222,23 +223,45 @@ func (w *EventWaiter) WaitAny(ctx context.Context, vub uint32, hashes ...util.Ui
...
-				waitErr = fmt.Errorf("WS waiter error: %w; simple waiter error: %v", wsWaitErr, waitErr)
+				// Wrap the poll-based error, it's more important.
+				waitErr = fmt.Errorf("event-based error: %v; poll-based waiter error: %w", wsWaitErr, waitErr)
 			}
 		}
 	}()
 	bRcvr := make(chan *block.Block)
 	aerRcvr := make(chan *state.AppExecResult)
+	wg := sync.WaitGroup{}
+	var (
```
Comment (roman-khimov) [inline pkg/rpcclient/actor/waiter.go:234]: You're mixing `var` and `:=` declarations here, maybe we can have `var` only for everything.

File: pkg/rpcclient/actor/waiter.go [hunk 3]
```diff
@@ -222,23 +223,45 @@ func (w *EventWaiter) WaitAny(ctx context.Context, vub uint32, hashes ...util.Ui
...
 			if waitErr != nil {
-				waitErr = fmt.Errorf("WS waiter error: %w; simple waiter error: %v", wsWaitErr, waitErr)
+				// Wrap the poll-based error, it's more important.
+				waitErr = fmt.Errorf("event-based error: %v; poll-based waiter error: %w", wsWaitErr, waitErr)
 			}
 		}
 	}()
 	bRcvr := make(chan *block.Block)
 	aerRcvr := make(chan *state.AppExecResult)
+	wg := sync.WaitGroup{}
```
Comment (roman-khimov) [inline pkg/rpcclient/actor/waiter.go:233]: I'd rather use an `exit chan error` here, make unsub threads push their errors to it...

File: pkg/rpcclient/actor/waiter.go [hunk 4]
```diff
@@ -222,23 +223,45 @@ func (w *EventWaiter) WaitAny(ctx context.Context, vub uint32, hashes ...util.Ui
...
+			exit <- struct{}{}
+		}()
 	drainLoop:
 		// Drain receivers to avoid other notification receivers blocking.
 		for {
 			select {
 			case <-bRcvr:
 			case <-aerRcvr:
-			default:
+			case <-exit:
```
Comment (roman-khimov) [inline pkg/rpcclient/actor/waiter.go:251]: ...wait/count/process them here...

File: pkg/rpcclient/actor/waiter.go [hunk 5]
```diff
@@ -222,23 +223,45 @@ func (w *EventWaiter) WaitAny(ctx context.Context, vub uint32, hashes ...util.Ui
...
+				// Wrap the poll-based error, it's more important.
+				waitErr = fmt.Errorf("event-based error: %v; poll-based waiter error: %w", wsWaitErr, waitErr)
 			}
 		}
 	}()
 	bRcvr := make(chan *block.Block)
 	aerRcvr := make(chan *state.AppExecResult)
+	wg := sync.WaitGroup{}
+	var (
+		unsubErrMtx sync.Mutex
```
Comment (roman-khimov) [inline pkg/rpcclient/actor/waiter.go:235]: ... and drop `unsubErrMtx` completely (it's just not needed).

File: pkg/rpcclient/wsclient.go [hunk 6]
```diff
@@ -876,37 +866,57 @@ func (c *WSClient) ReceiveNotaryRequests(flt *neorpc.TxFilter, rcvr chan<- *resu
...
+// performed. You may probably need to run unsubscription process in a separate
+// routine (in parallel with notification receiver routine) to avoid Client's
+// notification dispatcher blocking.
 func (c *WSClient) Unsubscribe(id string) error {
-	return c.performUnsubscription(id)
+	return c.performUnsubscription(id, true)
 }
 
-// UnsubscribeAll removes all active subscriptions of the current client.
+// UnsubscribeAll removes all active subscriptions of the current client. It locs
```
Comment (roman-khimov) [inline pkg/rpcclient/wsclient.go:880]: locks

File: pkg/rpcclient/wsclient.go [hunk 7]
```diff
@@ -876,37 +866,57 @@ func (c *WSClient) ReceiveNotaryRequests(flt *neorpc.TxFilter, rcvr chan<- *resu
...
+// the list of subscribers, so that any other notification received from the server
+// during unsubscription process will completely block this process, thus, use
+// this method carefully.
 func (c *WSClient) UnsubscribeAll() error {
 	c.subscriptionsLock.Lock()
 	defer c.subscriptionsLock.Unlock()
```
Comment (roman-khimov) [inline pkg/rpcclient/wsclient.go:886]: I'd rather just take a copy of `c.subscriptions` and leave finer-grained locking to `c.performUnsubscription`. It's network communication that can take any amount of time.

File: pkg/rpcclient/actor/waiter.go [hunk 8]
```diff
@@ -319,13 +319,17 @@ func (w *EventWaiter) WaitAny(ctx context.Context, vub uint32, hashes ...util.Ui
...
 		if !ok {
 			// We're toast, retry with non-ws client.
 			wsWaitErr = ErrMissedEvent
 			return
 		}
-		waitErr = ErrTxNotAccepted
+		// We can easily end up in a situation when subscription was performed too late and
+		// the desired transaction and VUB-th block have already got accepted before the
+		// subscription happened. Thus, always retry with non-ws client, it will perform
+		// AER requests and make sure.
```
Comment (roman-khimov) [inline pkg/rpcclient/actor/waiter.go:331]: Subscribe first, send afterwards? We need some issue for it.

File: pkg/rpcclient/actor/waiter.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/rpcclient/actor/waiter.go]: Fixed.

File: pkg/rpcclient/actor/waiter.go (hunk 3 above)
Comment (AnnaShaleva) [reply pkg/rpcclient/actor/waiter.go]: Fixed.

File: pkg/rpcclient/wsclient.go (hunk 7 above)
Comment (AnnaShaleva) [reply pkg/rpcclient/wsclient.go:895]: Fixed.

**Comment by AnnaShaleva** [comment]
There still some deadlock either in `TestWSClient_Wait` or in the implementation itself, I'm keeping investigation.

File: pkg/rpcclient/actor/waiter.go (hunk 8 above)
Comment (AnnaShaleva) [reply pkg/rpcclient/actor/waiter.go:316]: See https://github.com/nspcc-dev/neo-go/issues/2805.

File: pkg/services/rpcsrv/params/param.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/services/rpcsrv/params/param.go:453]: For now, just drop it. Some parameters may also be pretty big, not something to be logged entirely.

**Comment by AnnaShaleva** [comment]
Found it, we need to rework the logic of `(w *EventWaiter) WaitAny`.

File: pkg/rpcclient/actor/waiter.go [hunk 9]
```diff
@@ -217,69 +217,89 @@ func (w *EventWaiter) Wait(h util.Uint256, vub uint32, err error) (res *state.Ap
...
+					if waitErr != nil {
+						errFmt = "%w; " + errFmt
+						errArgs = append([]interface{}{waitErr}, errArgs...)
+					}
+					waitErr = fmt.Errorf(errFmt, errArgs...)
+				}
+				waitersActive--
+				// Wait until all receiver channels finish their work.
+				if waitersActive == 0 {
+					break drainLoop
```
Comment (roman-khimov) [inline pkg/rpcclient/actor/waiter.go:259]: `close(unsubErrs)`?

File: pkg/rpcclient/wsclient.go (hunk 7 above)
Comment (roman-khimov) [reply pkg/rpcclient/wsclient.go:895]: With deferred unlock?

Comment (AnnaShaleva) [reply pkg/rpcclient/wsclient.go]: I've overlooked it, shuldn't be there, fixed.

**Comment by AnnaShaleva** [comment]
OK, it should work properly now, the test is also fixed.

File: pkg/rpcclient/actor/waiter.go (hunk 9 above)
Comment (roman-khimov) [reply pkg/rpcclient/actor/waiter.go:314]: Is it closed now?

File: pkg/rpcclient/actor/waiter.go [hunk 10]
```diff
@@ -260,72 +315,20 @@ func (w *EventWaiter) WaitAny(ctx context.Context, vub uint32, hashes ...util.Ui
...
-			go func() {
-				err = w.ws.Unsubscribe(txsID)
-				if err != nil {
-					unsubErrs <- fmt.Errorf("failed to unsubscribe from transactions (id: %s): %w", txsID, err)
-					return
-				}
-				unsubErrs <- nil
-			}()
-		}()
+	if wsWaitErr == nil || !errors.Is(wsWaitErr, ErrMissedEvent) {
```
Comment (roman-khimov) [inline pkg/rpcclient/actor/waiter.go:319]: Why this condition for closing these channels? They're always initialized and they're drained above.

File: pkg/rpcclient/actor/waiter.go (hunk 9 above)
Comment (roman-khimov) [reply pkg/rpcclient/actor/waiter.go:314]: In the next commit, OK.

**Review by roman-khimov — APPROVED** [review]
The main thing for now is that it fixes #2775. Waiter have a bit more chances now too.
