### PR TITLE
rpcsrv: fix concurrent test TestClient_IteratorSessions

### LINKED ISSUE #3300: TestClient_IteratorSessions doesnt work on Mac and occasionally on Windows
I'm running TestClient_IteratorSessions on Macbook M1 (locally) and getting errors with network.
## Current Behavior
```
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60888->127.0.0.1:60808: read: connection reset by peer
=== RUN   TestClient_IteratorSessions/traverse,_concurrent_access
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60876->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
    client_test.go:1547: 
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60880->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60881->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60879->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60882->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60883->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60885->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60884->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60878->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60877->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60894->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60887->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60927->127.0.0.1:60808: read: connection reset by peer
        	Error:      	Received unexpected error:
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60923->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60929->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60903->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60902->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60901->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60891->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60924->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60900->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60899->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60893->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60898->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60897->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60933->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60932->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60896->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60908->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60930->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60931->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60926->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60925->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60935->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60890->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60934->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60905->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60909->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60921->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60907->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60920->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60892->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60918->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60906->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60895->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60928->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60904->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60922->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60886->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60889->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60912->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60913->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60915->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60914->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60910->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60919->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60917->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60911->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
    client_test.go:1547: 
        	Error Trace:	/Users/ekaterinapavlova/Workplace/neo-go/pkg/services/rpcsrv/client_test.go:1547
        	            				/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:60808": read tcp 127.0.0.1:60916->127.0.0.1:60808: read: connection reset by peer
        	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access


```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3300

### CODE REVIEW

**Review by roman-khimov — APPROVED** [review]
The default for `MaxConnsPerHost` is "no limit", so it'll use as many connections as it can (potentially hitting MacOS limits). 50 seems to be a lot as well, but we want concurrency in this test, so if it works then OK.

File: pkg/services/rpcsrv/client_test.go [hunk 1]
```diff
@@ -1509,9 +1509,9 @@ func TestClient_IteratorSessions(t *testing.T) {
 		wg.Add(storageItemsCount)
 		check := func(t *testing.T) {
 			set, err := c.TraverseIterator(sID, iID, 1)
+			wg.Done()
 			require.NoError(t, err)
 			require.Equal(t, 1, len(set))
-			wg.Done()
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/client_test.go:1514]: I can't approve this change, it may lead to the failure after the test end. Why have you moved this wg-related code?

File: pkg/services/rpcsrv/client_test.go [hunk 2]
```diff
@@ -1425,7 +1425,7 @@ func TestClient_NNS(t *testing.T) {
 func TestClient_IteratorSessions(t *testing.T) {
 	_, rpcSrv, httpSrv := initServerWithInMemoryChain(t)
 
-	c, err := rpcclient.New(context.Background(), httpSrv.URL, rpcclient.Options{})
+	c, err := rpcclient.New(context.Background(), httpSrv.URL, rpcclient.Options{MaxConnsPerHost: 50})
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/client_test.go:1428]: Commit description tells about idle connections, and the fix itself restricts `MaxConnsPerHost`. Fix the commit message, add a link to https://github.com/golang/go/issues/20960#issuecomment-447918270.

**Comment by AnnaShaleva** [comment]
Please, rebase onto fresh master.

File: pkg/services/rpcsrv/client_test.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/services/rpcsrv/client_test.go:1514]: What's the behavior if error happens? Won't `wg.Wait()` wait forever then?

Comment (AnnaShaleva) [reply pkg/services/rpcsrv/client_test.go:1514]: > Yes it will wait forever. as it does in master now. 

What I mean is that it may panic in case of "normal" error returned from iterator traversal (not in case of bug described in the issue when the test hangs). And it's definitely not the desired behaviour.

> You can just replace require with assert here, I think. 

It will help.

**Review by AnnaShaleva — APPROVED** [review]
