### PR TITLE
core: fix GAS distribution to primary node when notary enabled

### LINKED ISSUE #2310: Notary comission distributed both to consensus and notary nodes
GAS contract sends the sum of all network fees in a block to the consensus node that generated this block. Notary assisted attribute fees are added to the network fee and while they're deducted from it during transaction verification, they're not during `onPersist` in GAS, so we effectively have the same FEE distributed both to consensus node and (in Notary's `onPersist`) notary nodes.

We need to either subtract these fees in GAS `onPersist` (making it notary-aware), or add the FEE to system fee (but these fees are not about VM execution).

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #2310.

### CODE REVIEW

**Comment by AnnaShaleva** [comment]
The test will be refactored to use neotest in #2299.

File: pkg/core/native_gas_test.go [hunk 1]
```diff
@@ -52,3 +58,86 @@ func TestGAS_Roundtrip(t *testing.T) {
...
+		expectedBalance := balances[i]
+		if i == int(b.Index)%testchain.CommitteeSize() {
+			// committee reward
+			expectedBalance += 5000_0000
+		}
+		if testchain.IDToOrder(i) == int(b.PrimaryIndex) {
+			// primary reward
+			expectedBalance += tx.NetworkFee - int64(singleReward*nNotaries)
+		}
+		assert.Equal(t, expectedBalance, newBalance, i)
```
Comment (roman-khimov) [inline pkg/core/native_gas_test.go:141]: Maybe it's easier to check for this with `totalSupply` call? GAS claims can interfere, but it's quite predictable otherwise, we add some GAS for committee members and burn system fees.

Comment (AnnaShaleva) [reply pkg/core/native_gas_test.go:144]: Yes, I've added this check also.

File: pkg/core/native_gas_test.go [hunk 2]
```diff
@@ -52,3 +59,95 @@ func TestGAS_Roundtrip(t *testing.T) {
...
+	}
+	tsUpdated := chain.contracts.GAS.TotalSupply(ic, nil).Value().(*big.Int).Int64()
+	tsExpected := tsInitial +
+		5000_0000 - // committee reward
+		(tx.NetworkFee + tx.SystemFee) + // burn tx fees
+		(tx.NetworkFee - int64(singleReward*nNotaries)) + // primary node reward
+		int64(singleReward*nNotaries) // notaries reward
```
Comment (roman-khimov) [inline pkg/core/native_gas_test.go:151]: Why not just `tsInitial + 5000_0000 - tx.SystemFee`? Network fee is redistributed completely. Before the patch we had excessive `singleReward*nNotaries` generated.

Comment (AnnaShaleva) [reply pkg/core/native_gas_test.go]: This long expression has the same value as the one you provided. I thought that we need to explain clearly the meaning of each part, but it seems to be redundant. Fixed.

Comment (roman-khimov) [reply pkg/core/native_gas_test.go]: To me it's a bit easier to understand, total supply changes because of mints and burns. Network fee is just being redistributed, it's out of scope.

**Review by roman-khimov — APPROVED** [review]
