### PR TITLE
cli: adjust error of `upload-bin` command

### LINKED ISSUE #3621: Potential bug in search range bounds of BlockUploader
## Current Behavior
Here's the example of BlockUploader logs copy-pasted from Grafana:
```
2024-10-17 11:25:48.013	Chain block height: 4816543
2024-10-17 11:26:27.201	failed to fetch the latest missing block index from container: search of index files failed for batch with indexes from 4820000 to 4830000: error during object IDs iteration: context deadline exceeded	
2024-10-17 11:26:56.790	failed to fetch the latest missing block index from container: search of index files failed for batch with indexes from -260000 to -250000: error during object IDs iteration: context deadline exceeded	
2024-10-17 11:27:27.765	Chain block height: 4816549	
2024-10-17 11:27:57.275	Chain block height: 6533916
```
One of the lines contains unexpected negative block indexes: `indexes from -260000 to -250000`. It's a no-op, something is wrong.

## Expected Behavior
No negative indexes in the output.

## Possible Solution
Check all conditions of all cycles.

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3621

### CODE REVIEW

File: cli/util/uploader.go [hunk 1]
```diff
@@ -255,7 +255,7 @@ func fetchLatestMissingBlockIndex(ctx context.Context, p *pool.Pool, containerID
 
 		for i := len(results) - 1; i >= 0; i-- {
 			if results[i].err != nil {
-				return 0, fmt.Errorf("search of index files failed for batch with indexes from %d to %d: %w", batch*searchBatchSize, (batch+1)*searchBatchSize, results[i].err)
+				return 0, fmt.Errorf("search of index files failed for batch with indexes from %d to %d: %w", results[i].startIndex, results[i].startIndex+searchBatchSize, results[i].err)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:258]: End index is incorrect because it's not always equal to `results[i].startIndex+searchBatchSize`. Extend `searchResult` with `endIndex` and log it (with -1) here.

File: cli/util/uploader.go [hunk 2]
```diff
@@ -51,6 +51,12 @@ const (
 	maxBackoff = 10 * time.Second
 )
 
+// Constants related to NeoFS pool request timeouts.
+const (
+	defaultDialTimeout   = 10 * time.Minute
+	defaultStreamTimeout = 10 * time.Minute
+)
+
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:59]: Not related to this PR.

File: cli/util/uploader.go [hunk 3]
```diff
@@ -82,7 +88,11 @@ func uploadBin(ctx *cli.Context) error {
 	fmt.Fprintln(ctx.App.Writer, "Chain block height:", currentBlockHeight)
 
 	signer := user.NewAutoIDSignerRFC6979(acc.PrivateKey().PrivateKey)
-	p, err := pool.New(pool.NewFlatNodeParams(rpcNeoFS), signer, pool.DefaultOptions())
+
+	params := pool.DefaultOptions()
+	params.SetNodeDialTimeout(defaultDialTimeout)
+	params.SetNodeStreamTimeout(defaultStreamTimeout)
+	p, err := pool.New(pool.NewFlatNodeParams(rpcNeoFS), signer, params)
```
Comment (AnnaShaleva) [inline cli/util/uploader.go:95]: Ditto.

**Review by AnnaShaleva — COMMENTED** [review]
Other than that LGTM.

**Review by AnnaShaleva — APPROVED** [review]
