### PR TITLE
compiler: allow to use multiple returns in inlined functions

### LINKED ISSUE #2587: Unexpected compiler behaviour while inlining interop function
#### Problem

Consider the case when the following is added to `pkg/interop/types.go` file (`interop` package):
```
func BothNull(a interface{}, b interface{}) bool {
	if a == nil && b == nil {
		return true
	}
	return false
}
```

This function is being called from the compiler testing code:
```
t.Run("test", func(t *testing.T) {
src := `package foo
import (
	"github.com/nspcc-dev/neo-go/pkg/interop"
)

func Main() bool {
	var a interop.Hash160
	var b interop.Hash160
	return interop.BothNull(a, b)
}
`
	eval(t, src, true)
})
```
This test fails with the `stack contains unexpected items` assertion:
```
   Error:      	Not equal: 
        	       expected: 1
        	       actual  : 2
   Test:       	TestInteropTypesComparison/Hash160/test
   Messages:   	stack contains unexpected items
```
One extra boolean value is located at resulting stack. It happens because two boolean values were pushed on stack without any condition (`PUSH1` for `return true` at instruction 15 and `PUSH0` for `return false` at instruction 18), see the comments:
```
INDEX    OPCODE      PARAMETER
0        INITSLOT    2 local, 0 arg    <<
3        PUSHNULL    
4        STLOC0      
5        PUSHNULL    
6        STLOC1      
7        LDLOC0      
8        ISNULL      
9        JMPIFNOT    18 (9/09)    // It's null, thus no JMP occurs.
11       LDLOC1      
12       ISNULL      
13       JMPIFNOT    18 (5/05)   // It's also null, thus no JMP.
15       PUSH1       
16       CONVERT     Boolean (20)  // Should RET after this from inlined BothNull function
18       PUSH0       
19       CONVERT     Boolean (20)
21       RET         
```
Also, the result of the program is invalid because the upper stack element is taken.

#### Summary

Not sure, but it seems to me as a bug in the compiler connected with interop-related functions inlining. Investigation is in progress.

#### Additional content

The described behaviour was discovered during interop equality helpers testing, it's not expected and blocks  https://github.com/nspcc-dev/neo-go/issues/2249 solution.

### PR DESCRIPTION
**Pull request by fyrchik**
Close #2587.

### CODE REVIEW

File: pkg/compiler/byte_conversion_test.go [hunk 1]
```diff
@@ -1,6 +1,8 @@
 package compiler_test
 
-import "testing"
+import (
+	"testing"
+)
```
Comment (AnnaShaleva) [inline pkg/compiler/byte_conversion_test.go:5]: This change is not needed.

File: pkg/compiler/byte_conversion_test.go [hunk 2]
```diff
@@ -1,6 +1,8 @@
 package compiler_test
 
-import "testing"
+import (
+	"testing"
```
Comment (roman-khimov) [inline pkg/compiler/byte_conversion_test.go:4]: Not a very useful change.

**Review by AnnaShaleva — APPROVED** [review]

File: pkg/compiler/inline_test.go [hunk 3]
```diff
@@ -281,6 +281,7 @@ func TestInlineVariadicInInlinedCall(t *testing.T) {
 }
 
 func TestInlineConversion(t *testing.T) {
+	t.Skip()
```
Comment (roman-khimov) [inline pkg/compiler/inline_test.go]: ?

Comment (fyrchik) [reply pkg/compiler/inline_test.go]: Fixed in the next commit.

File: pkg/compiler/inline_test.go [hunk 4]
```diff
@@ -306,6 +307,7 @@ func TestInlineConversion(t *testing.T) {
 }
 
 func TestInlineConversionQualified(t *testing.T) {
+	t.Skip()
```
[the remark this answers is not in the document]
Comment (fyrchik) [reply pkg/compiler/inline_test.go]: Fixed in the next commit.

File: pkg/compiler/codegen.go [hunk 5]
```diff
@@ -2243,13 +2243,16 @@ func (c *codegen) writeJumps(b []byte) ([]byte, error) {
 				return nil, err
 			}
 			if op != opcode.PUSHA && math.MinInt8 <= offset && offset <= math.MaxInt8 {
-				offsets = append(offsets, ctx.IP())
+				offsets = append(offsets, offsetChange{
+					pos:    ctx.IP(),
+					remove: op == opcode.JMPL && offset == longInstructionSize,
```
[the remark this answers is not in the document]
Comment (fyrchik) [reply pkg/compiler/codegen.go:2248]: Without this we would have as many jumps as there are nested calls. This affects almost all our current interop calls.
The NOP approach seems easier, though. I think I've seen a NOP used for a debug sequence point (refs. https://github.com/neo-project/neo-debugger/issues/170), but it can be handled separately.

File: pkg/compiler/byte_conversion_test.go (hunk 1 above)
Comment (fyrchik) [reply pkg/compiler/byte_conversion_test.go]: Fixed

File: pkg/compiler/byte_conversion_test.go (hunk 2 above)
Comment (fyrchik) [reply pkg/compiler/byte_conversion_test.go]: Fixed

File: pkg/compiler/codegen.go [hunk 6]
```diff
@@ -2386,6 +2391,11 @@ func removeNOPs(b []byte, nopOffsets []int) []byte {
 	return b[:len(b)-copyOffset]
 }
 
+type offsetChange struct {
```
[the remark this answers is not in the document]
Comment (fyrchik) [reply pkg/compiler/codegen.go]: Fixed.

**Review by AnnaShaleva — APPROVED** [review]
