### PR TITLE
mpt: fix MPT traversal order

### LINKED ISSUE #3103: MPT-backed storage is broken
MPT-backed storage (`mpt.TrieStore`) uses `Billet` for MPT traversal during `Seek` operations. MPT traversal strategy differs from the one that simple storage `Seek` assumes (probably due to the `Branch` node traversal in case when the last child is non-empty leaf). The difference is that items with the key exactly matching provided prefix are being traversed after the ones that has extra data after prefix (by MPT-based storage). This affects every component that tries to use MPT-backed storage as a replacement to a simple storage, including:
* MPT-based iterator sessions
* test historic script invocations
* `findstoragehistoric` RPC handler (ref. https://github.com/nspcc-dev/neo-go/pull/3099#discussion_r1302046422).

It may affect the `findstates` RPC handler in terms that current `findstates` behaviour matches the C# one, and to fix this bug we have to change the traversal strategy which will affect the `findstates` result.

This problem needs additional investigation, we may consider adding a traversal strategy option to `Billet`.

### LINKED ISSUE #3962: FindStates length != FindStorageByHashHistoric length for specific contract
## Current Behavior
Using the same stateroot I get a different number of results while dumping all states related to a specific contract (`0x341cbe084b3b15fccf15064c7b7790f5f0f659d2`). For other contracts it works as expected.

## Expected Behavior
I expect the length of the results of `FindStates` to equal that of `FindStorageByHashHistoric`

## Steps to Reproduce
```go
package main

import (
	"context"
	"fmt"

	"github.com/nspcc-dev/neo-go/pkg/neorpc/result"
	"github.com/nspcc-dev/neo-go/pkg/rpcclient"
	"github.com/nspcc-dev/neo-go/pkg/util"
)

func main() {
	hash, _ := util.Uint160DecodeStringLE("341cbe084b3b15fccf15064c7b7790f5f0f659d2") // different length
	//hash, _ := util.Uint160DecodeStringLE("8eb3bdf5ed4ac1516d316c6b1b207a3cf5eb7567") // same length

	host := "https://rpc10.n3.nspcc.ru:10331"
	client, _ := rpcclient.New(context.TODO(), host, rpcclient.Options{})
	stateResponse, _ := client.GetStateRootByHeight(7683665)
	stateRoot := stateResponse.Root

	var start []byte
	var states []result.KeyValue
	for {
		response, err := client.FindStates(stateRoot, hash, nil, start, nil)
		if err != nil {
			fmt.Printf("failed to find states: %v\n", err)
		}
		if len(response.Results) == 0 {
			break
		}

		states = append(states, response.Results...)
		if !response.Truncated {
			break
		}
		start = response.Results[len(response.Results)-1].Key
	}

	var startInt *int
	var storages []result.KeyValue
	for {
		response, _ := client.FindStorageByHashHistoric(stateRoot, hash, nil, startInt)
		if len(response.Results) == 0 {
			break
		}
		storages = append(storages, response.Results...)
		if !response.Truncated {
			break
		}
		startInt = &response.Next
	}

	fmt.Printf("state len: %d storage len: %d\n", len(states), len(storages))
}
```
currently outputs
```shell
state len: 1728 storage len: 1723
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Use lexicographic keys comparison order during MPT traversal. Close #3103, close #3962.

TODO:

- [x] Ensure `findstoragehistoric` behaviour compatibility.
- [x] Unit tests.

### CODE REVIEW

File: pkg/core/mpt/billet.go [hunk 1]
```diff
@@ -249,48 +249,69 @@ func (b *Billet) traverse(curr Node, path, from []byte, process func(pathToNode
...
+				}
+				n.Children[lastChild] = r
 			}
-			step = -1
-		}
-		if len(from) != 0 {
-			endIndex = lastChild
-			if backwards {
-				endIndex = 0
+			for i := startIndex; i < lastChild; i++ {
```
Comment (roman-khimov) [inline pkg/core/mpt/billet.go:269]: Quite repetitive code, old one was more compact and now you can probably use some `range` over function that returns proper indexes.

Comment (AnnaShaleva) [reply pkg/core/mpt/billet.go:269]: > old one was more compact

It was. But it contained a bug in indexes (a different one), and it turned into a mess when I moved processing of the last child to a separate block. So I intentionally split forward/backward iteration. At least it's readable now, and less error-prone.
