### PR TITLE
core, compiler: return tx from GetScriptContainer interop

### LINKED ISSUE #1173: TX Hash defined as InterOp type instead of ByteArray
neo-go version 0.90.0-pre-665-g272a9b17

I want to notify transaction hash and use this code:

```go
tx := runtime.GetScriptContainer()
runtime.Notify("Example", tx.Hash)
```

Unfortunately, this throws runtime error: `"error": "error encountered at instruction 334 (PICKITEM): can't convert Interop to ByteArray"`.

I tried to rewrite this part but I got the same error every time.

```go
// error there
tx := runtime.GetScriptContainer().Hash
runtime.Notify("Example", tx)

// error there too
tx := runtime.GetScriptContainer()
hash := tx.Hash
runtime.Notify("Example", hash)
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Closes #1173

### CODE REVIEW

File: pkg/core/interop_system.go [hunk 1]
```diff
@@ -182,7 +182,7 @@ func bcGetTransactionHeight(ic *interop.Context, v *vm.VM) error {
 // engineGetScriptContainer returns transaction that contains the script being
 // run.
 func engineGetScriptContainer(ic *interop.Context, v *vm.VM) error {
-	v.Estack().PushVal(stackitem.NewInterop(ic.Container))
+	v.Estack().PushVal(transactionToStackItem(ic.Container.(*transaction.Transaction)))
```
Comment (roman-khimov) [inline pkg/core/interop_system.go:185]: I guess we could also have block here for `OnPersist`?

Comment (AnnaShaleva) [reply pkg/core/interop_system.go:185]: Should we return an error in this case or return the block?

Comment (roman-khimov) [reply pkg/core/interop_system.go:185]: C# node returns whatever it has, be it a block or transaction, so we should do the same probably. Although it would complicate things considerably.

Comment (roman-khimov) [reply pkg/core/interop_system.go]: But at the same time we can keep `GetScriptContainer() blockchain.Transaction` signature for interop function, regular VM code will never get anything but transaction from it, it's only native contracts that can be run within block container (which I don't really like, honestly).

Comment (AnnaShaleva) [reply pkg/core/interop_system.go]: I also modified test `engine.go` contract to check if all works correct, so it's OK now.
