### PR TITLE
core: prevent concurrent map writes during (*mp).Verify

### LINKED ISSUE #1168: Concurrent map writes happend in runtime
neo-go version 0.90.0-pre-659-g1bb26dcd

Single node running consensus with 8 RPC clients. Some of them send concurrent transactions. Sooner or later concurrent map write happens:

```
fatal error: concurrent map writes

goroutine 77 [running]:
runtime.throw(0xd6ee36, 0x15)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0001bd338 sp=0xc0001bd308 pc=0x4349c2
runtime.mapassign(0xc54f20, 0xc000749ef0, 0xc00037a1e8, 0x638df2bb)
	/usr/local/go/src/runtime/map.go:585 +0x59d fp=0xc0001bd3b8 sp=0xc0001bd338 pc=0x40ec0d
github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).checkBalanceAndUpdate(0xc0002c60e8, 0xc00037a1e0, 0xeacb00, 0xc0002c6000, 0xc00049e0a8)
	/neo-go/pkg/core/mempool/mem_pool.go:124 +0x119 fp=0xc0001bd420 sp=0xc0001bd3b8 pc=0x9dab39
github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).checkTxConflicts(...)
	/neo-go/pkg/core/mempool/mem_pool.go:294
github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).Verify(0xc0002c60e8, 0xc00037a1e0, 0xeacb00, 0xc0002c6000, 0x39f93dd800)
	/neo-go/pkg/core/mempool/mem_pool.go:304 +0x87 fp=0xc0001bd470 sp=0xc0001bd420 pc=0x9dc4f7
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).verifyTx(0xc0002c6000, 0xc00037a1e0, 0x0, 0xc8d6c13c64e813, 0x955591c39938e588)
	/neo-go/pkg/core/blockchain.go:1164 +0x50f fp=0xc0001bd610 sp=0xc0001bd470 pc=0xa232cf
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).PoolTx(0xc0002c6000, 0xc00037a1e0, 0x0, 0x0)
	/neo-go/pkg/core/blockchain.go:1222 +0x1b6 fp=0xc0001bd720 sp=0xc0001bd610 pc=0xa23cc6
github.com/nspcc-dev/neo-go/pkg/network.(*Server).verifyAndPoolTX(0xc0002d7b80, 0xc00037a1e0, 0xc000036688)
	/neo-go/pkg/network/server.go:870 +0x4b fp=0xc0001bd760 sp=0xc0001bd720 pc=0xa8effb
github.com/nspcc-dev/neo-go/pkg/network.(*Server).RelayTxn(0xc0002d7b80, 0xc00037a1e0, 0xdb)
	/neo-go/pkg/network/server.go:888 +0x35 fp=0xc0001bd790 sp=0xc0001bd760 pc=0xa8f145
github.com/nspcc-dev/neo-go/pkg/rpc/server.(*Server).sendrawtransaction(0xc0002a8900, 0xc0007087e0, 0x1, 0x4, 0xc00010ada0, 0xc0001a8301, 0x29)
	/neo-go/pkg/rpc/server/server.go:914 +0x85 fp=0xc0001bd7d8 sp=0xc0001bd790 pc=0xa9c7c5
github.com/nspcc-dev/neo-go/pkg/rpc/server.(*Server).handleRequest(0xc0002a8900, 0xc000030870, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/neo-go/pkg/rpc/server/server.go:283 +0x76c fp=0xc0001bd9a0 sp=0xc0001bd7d8 pc=0xa96aac
github.com/nspcc-dev/neo-go/pkg/rpc/server.(*Server).handleHTTPRequest(0xc0002a8900, 0xeb5440, 0xc000366380, 0xc000308200)
	/neo-go/pkg/rpc/server/server.go:261 +0x8cc fp=0xc0001bdb90 sp=0xc0001bd9a0 pc=0xa9626c
github.com/nspcc-dev/neo-go/pkg/rpc/server.(*Server).handleHTTPRequest-fm(0xeb5440, 0xc000366380, 0xc000308200)
	/neo-go/pkg/rpc/server/server.go:209 +0x48 fp=0xc0001bdbc0 sp=0xc0001bdb90 pc=0xaa24e8
net/http.HandlerFunc.ServeHTTP(0xc000283230, 0xeb5440, 0xc000366380, 0xc000308200)
	/usr/local/go/src/net/http/server.go:2012 +0x44 fp=0xc0001bdbe8 sp=0xc0001bdbc0 pc=0x77dee4
net/http.serverHandler.ServeHTTP(0xc0002ddea0, 0xeb5440, 0xc000366380, 0xc000308200)
	/usr/local/go/src/net/http/server.go:2807 +0xa3 fp=0xc0001bdc18 sp=0xc0001bdbe8 pc=0x781273
net/http.(*conn).serve(0xc0000d10e0, 0xeb7cc0, 0xc000206340)
	/usr/local/go/src/net/http/server.go:1895 +0x86c fp=0xc0001bdfc8 sp=0xc0001bdc18 pc=0x77ccec
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001bdfd0 sp=0xc0001bdfc8 pc=0x467361
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c
```
[log.txt](https://github.com/nspcc-dev/neo-go/files/4896763/log.txt)

### PR DESCRIPTION
**Pull request by AnnaShaleva**
closes #1168

### CODE REVIEW

File: pkg/core/mempool/mem_pool.go [hunk 1]
```diff
@@ -109,22 +109,16 @@ func (mp *Pool) containsKey(hash util.Uint256) bool {
...
-}
-
-// checkBalanceAndUpdate returns true in case when sender has enough GAS to pay for
-// the transaction and sets sender's balance value in mempool in case if it was not set
-func (mp *Pool) checkBalanceAndUpdate(tx *transaction.Transaction, feer Feer) bool {
 	senderFee, ok := mp.fees[tx.Sender]
 	if !ok {
 		senderFee.balance = feer.GetUtilityTokenBalance(tx.Sender)
 		mp.fees[tx.Sender] = senderFee
 	}
```
Comment (roman-khimov) [inline pkg/core/mempool/mem_pool.go:116]: It duplicates `addSendersFee`, I think we can deduplicate them.

Comment (AnnaShaleva) [reply pkg/core/mempool/mem_pool.go:116]: Finally managed to join these methods with a help of `needCheck` flag.
