### PR TITLE
cli: unify password-related prompts

### LINKED ISSUE #2419: password or passphrase?
```
% neo-go wallet change-password -w alphabet/az.json
Enter password > 
Enter passphrase > 
Confirm passphrase > 
```
Should be:
```
Enter current password >
Enter new password >
Confirm new password >
```

### LINKED ISSUE #2429: change-password simulated password chaning for an absent account
Steps to reproduce:
```
% rm /tmp/wallet.json
% neo-go wallet init -w /tmp/wallet.json
% md5sum /tmp/wallet.json 
4115da75106c0d2c0205eec0d16636ef  /tmp/wallet.json
% neo-go wallet change-password -w /tmp/wallet.json
Enter password > <just type some input here>
Enter passphrase > <type>
Confirm passphrase > <repeat typed above>
% md5sum /tmp/wallet.json 
4115da75106c0d2c0205eec0d16636ef  /tmp/wallet.json
```

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #2419, close #2429.

### CODE REVIEW

File: cli/wallet/wallet.go [hunk 1]
```diff
@@ -318,6 +318,9 @@ func changePassword(ctx *cli.Context) error {
 	if err != nil {
 		return cli.NewExitError(err, 1)
 	}
+	if len(wall.Accounts) == 0 {
+		return cli.NewExitError("wallet doesn't contain accounts", 1)
```
Comment (roman-khimov) [inline cli/wallet/wallet.go:322]: `wallet has no accounts`? @EliChin?

Comment (AnnaShaleva) [reply cli/wallet/wallet.go]: Fixed, sounds more appropriate to me.

**Review by roman-khimov — APPROVED** [review]

File: cli/wallet/wallet.go [hunk 2]
```diff
@@ -315,7 +330,7 @@ func changePassword(ctx *cli.Context) error {
 		}
 	}
 
-	oldPass, err := input.ReadPassword("Enter password > ")
+	oldPass, err := input.ReadPassword(EnterOldPasswordPrompt)
```
Comment (532910) [inline cli/wallet/wallet.go:333]: It's not old, it's current!
```
% passwd 
Changing password for sergio.
Current password: 
New password: 
Retype new password: 
```
