### PR TITLE
smartcontract: fix DO NOT EDIT warning to autogenerated files

### LINKED ISSUE #3254: Imperfect "automatically generated" text
According to https://github.com/nspcc-dev/neofs-contract/pull/367 I would say that it was done not that strictly:

> The text must appear as the first line of a properly formatted Go // comment, and that comment must appear before but not be attached to the package clause and before any /* */ comment. This is similar to the rules for build tags.

_Originally posted by @carpawell in https://github.com/nspcc-dev/neo-go/issues/3139#issuecomment-1805753827_

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Change the order of comments

Closes #3254

### CODE REVIEW

File: pkg/smartcontract/zkpbinding/binding.go [hunk 1]
```diff
@@ -60,7 +60,9 @@ const (
 	// verification contract is circuit-specific, i.e. corresponds to a specific
 	// single constraint system. Thus, every new circuit requires vew verification
 	// contract to be generated and deployed to the chain.
-	goVerificationTmpl = `// Package main contains verification smart contract that uses Neo BLS12-381
+	goVerificationTmpl = `//Code generated by neo-go zkpbinding.GenerateVerifier; DO NOT EDIT.
+//
```
Comment (roman-khimov) [inline pkg/smartcontract/zkpbinding/binding.go:64]: > but not be attached to the package clause

So it has to be a separate comment, right?

Comment (AliceInHunterland) [reply pkg/smartcontract/zkpbinding/binding.go:64]: Does it mean it needs space between two comments?

Comment (roman-khimov) [reply pkg/smartcontract/zkpbinding/binding.go:64]: I think so. Try finding some similar tools and check how exactly it's structured there.

Like
```
// Code generated by "stringer -type=Role"; DO NOT EDIT.
```
But this doesn't have package-level documentation, unfortunately. My primary concern is correct package doc. You can check it with `godoc` though.

**Review by roman-khimov — APPROVED** [review]

**Review by AnnaShaleva — APPROVED** [review]
