### PR TITLE
compiler: set SourceURL in NEF file

### LINKED ISSUE #3543: neotest.CompileFile does not add sourceURL to nef
## Current Behavior
compiling a contract with `CompileFile` that has the `sourceurl` field set in the config will return `Contract` with a NEF that does not have the `sourceurl` set. If this output is then used to deploy the contract it will not reflect the actual config of the contract.

## Expected Behavior
The NEF file returned in the `Contract` return from `CompileFile` has the `source` field that reflects the `sourceurl` of the config passed to `CompileFile`.

## Steps to Reproduce
1. create a smart contract 
2. compile with `neotest.CompileFile`
3. evaluate the `Source` field of the returned value: `Contract.NEF.Source`
4. observe that it is always `""`

## Your Environment
* Version of the product used: v0.106.3-0.20240705103125-ed9817d35b29

### PR DESCRIPTION
**Pull request by Turalchik**
Close #3543.

### CODE REVIEW

File: pkg/neotest/compile_test.go [hunk 1]
```diff
@@ -26,3 +26,10 @@ func TestCompileFileCashedIdentifiers(t *testing.T) {
 	contract2 := CompileFile(t, sender, srcPath, configPath2)
 	require.NotEqual(t, contract1, contract2)
 }
+
+func TestAddSourceURLToNEFI(t *testing.T) {
```
Comment (AnnaShaleva) [inline pkg/neotest/compile_test.go]: s/TestAddSourceURLToNEFI/TestAddSourceURLToNEF

File: pkg/neotest/compile.go [hunk 2]
```diff
@@ -62,13 +62,15 @@ func CompileFile(t testing.TB, sender util.Uint160, srcPath string, configPath s
...
 	config.Version = "neotest"
 
-	ne, di, err := compiler.CompileWithOptions(srcPath, nil, nil)
-	require.NoError(t, err)
-
 	conf, err := smartcontract.ParseContractConfig(configPath)
 	require.NoError(t, err)
 
 	o := &compiler.Options{}
+	o.SourceURL = conf.SourceURL
```
Comment (AnnaShaleva) [inline pkg/neotest/compile.go]: Instead of moving this line...

File: pkg/neotest/compile.go [hunk 3]
```diff
@@ -62,13 +62,15 @@ func CompileFile(t testing.TB, sender util.Uint160, srcPath string, configPath s
...
+
+	ne, di, err := compiler.CompileWithOptions(srcPath, nil, o)
+	require.NoError(t, err)
```
Comment (AnnaShaleva) [inline pkg/neotest/compile.go]: Just move this part ahead of `m, err := compiler.CreateManifest(di, o)`.

Comment (Turalchik) [reply pkg/neotest/compile.go]: This part is already ahead.

Comment (AnnaShaleva) [reply pkg/neotest/compile.go]: I mean, one line ahead of. Move it to L83, less changes, cleaner diff.

File: pkg/neotest/compile.go [hunk 4]
```diff
@@ -79,7 +77,8 @@ func CompileFile(t testing.TB, sender util.Uint160, srcPath string, configPath s
 	}
 	o.SafeMethods = conf.SafeMethods
 	o.Overloads = conf.Overloads
-	o.SourceURL = conf.SourceURL
```
Comment (AnnaShaleva) [inline pkg/neotest/compile.go:82]: Useless change.

**Review by AnnaShaleva — APPROVED** [review]
Nice.
