### PR TITLE
vm: fix MODPOW operation

### LINKED ISSUE #3612: modpow operation returns wrong results when base is negative
Similar to #3598

## Current Behavior
For negative numbers operation returns wrong results (compared to C#).

```
(-1 ^ 3) % 3 == 2
```

image

## Expected Behavior

C# results:
```
(-1 ^ 3) % 3 == -1
```

## Possible Solution

operation uses Go's `Exp` function that explicitly makes modulus result positive, which is different from BigInteger from C#
image

## Steps to Reproduce

1. `./bin/neo-go vm`
2. `loadbase64 DxMTpg==`
3. `run`

## Your Environment

* Version of the product used: master (a9242535db757faba860e21c194033f30c679f48)

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3612

### CODE REVIEW

File: pkg/vm/vm_test.go [hunk 1]
```diff
@@ -747,9 +747,11 @@ func TestMODMUL(t *testing.T) {
 func TestMODPOW(t *testing.T) {
 	prog := makeProgram(opcode.MODPOW)
 	t.Run("good, positive base", getTestFuncForVM(prog, 1, 3, 4, 5))
-	t.Run("good, negative base", getTestFuncForVM(prog, 2, -3, 5, 5))
+	t.Run("good, negative base", getTestFuncForVM(prog, -3, -3, 5, 5))
+	t.Run("good, negative base", getTestFuncForVM(prog, -1, -1, 3, 3))
 	t.Run("good, positive base, negative mod", getTestFuncForVM(prog, 1, 3, 4, -5))
-	t.Run("good, negative base, negative mod", getTestFuncForVM(prog, 2, -3, 5, -5))
+	t.Run("good, negative base, negative mod", getTestFuncForVM(prog, -3, -3, 5, -5))
+	t.Run("good, negative base, negative mod", getTestFuncForVM(prog, -2, -5, 5, -3))
```
Comment (AnnaShaleva) [inline pkg/vm/vm_test.go:754]: This case is not different from existing one in its essence. Why do we need it then?

File: pkg/vm/vm.go [hunk 2]
```diff
@@ -1044,17 +1045,21 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
...
-			if res.ModInverse(base, modulus) == nil {
+			if res.ModInverse(base, absModulus) == nil {
 				panic("base and modulus are not relatively prime")
 			}
 		case 1:
 			if modulus.Sign() == 0 {
 				panic("zero modulus") // https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.modpow?view=net-6.0#exceptions
 			}
-			res.Exp(base, exponent, modulus)
+			res.Exp(base, exponent, absModulus)
```
Comment (AnnaShaleva) [inline pkg/vm/vm.go:1058]: Why do you need an absolute modulus here? Isn't it enough to subtract `absModulus` from the result if the base is negative and exponent is even?

**Comment by AnnaShaleva** [comment]
Also please, add one more compatibility test from https://github.com/neo-project/neo/pull/3557: `(5 ^ -1) % 4 == 1`

File: pkg/vm/vm.go [hunk 3]
```diff
@@ -1055,6 +1055,11 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
 				panic("zero modulus") // https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.modpow?view=net-6.0#exceptions
 			}
 			res.Exp(base, exponent, modulus)
+
+			if base.Sign() < 0 && exponent.Bit(0) == 1 {
+				absModulus := new(big.Int).Abs(modulus)
+				res.Sub(res, absModulus)
```
Comment (AnnaShaleva) [inline pkg/vm/vm.go:1061]: Please add a reference or a comment with reference or the number of issue, because otherwise it's not clear why this code exists.

Comment (AnnaShaleva) [inline pkg/vm/vm.go:1061]: If the result is `0`, then `res.Sub(res, absModulus)` should not be applied, isn't it? I need you to build a testcase where `base ^ exp` is a multiple of `mod` (for negative `base` and even `exp`) to check what happens in case of zero result.

File: pkg/vm/vm.go [hunk 4]
```diff
@@ -1055,6 +1055,11 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
 				panic("zero modulus") // https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.modpow?view=net-6.0#exceptions
 			}
 			res.Exp(base, exponent, modulus)
+
+			if base.Sign() < 0 && exponent.Bit(0) == 1 {
```
Comment (AnnaShaleva) [inline pkg/vm/vm.go:1059]: `exponent.Bit(0) == 1` defines if `exponent` is even. Is it work the same way on LE/BE arch?

File: pkg/vm/vm.go (hunk 2 above)
Comment (AnnaShaleva) [reply pkg/vm/vm.go]: I see that you removed this code, but could you explain why did you add this code in the first version of this PR?

Comment (AliceInHunterland) [reply pkg/vm/vm.go]: For the initial point, I added absModulus in res.Exp(base, exponent, absModulus) to explicitly ensure that the modulus used in modular exponentiation was positive. Also, I was looking at https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs#L968C13-L1023C27 and they have abs on trivialModulus.  However, it's redundant in Go implementation.

File: pkg/vm/vm.go (hunk 4 above)
Comment (AliceInHunterland) [reply pkg/vm/vm.go:1059]: it doesn't depend on the arch. ` Bit(0)` is about logical representation not physical in memory. 
and:
```
// Bit returns the value of the i'th bit of x. That is, it
// returns (x>>i)&1. The bit index i must be >= 0.
func (x *Int) Bit(i int) uint {
	if i == 0 {
		// optimization for common case: odd/even test of x
		if len(x.abs) > 0 {
			return uint(x.abs[0] & 1) // bit 0 is same for -x
		}
		return 0
	}
```

File: pkg/vm/vm.go (hunk 3 above)
Comment (AliceInHunterland) [reply pkg/vm/vm.go:1062]: true. missed this case

File: pkg/vm/vm.go (hunk 4 above)
Comment (AnnaShaleva) [reply pkg/vm/vm.go]: Good.

File: pkg/vm/vm.go [hunk 5]
```diff
@@ -1055,6 +1055,12 @@ func (v *VM) execute(ctx *Context, op opcode.Opcode, parameter []byte) (err erro
 				panic("zero modulus") // https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.modpow?view=net-6.0#exceptions
 			}
 			res.Exp(base, exponent, modulus)
+
+			// https://github.com/neo-project/neo-vm/issues/3612
```
Comment (AnnaShaleva) [inline pkg/vm/vm.go:1059]: Wrong link, it's https://github.com/nspcc-dev/neo-go/issues/3612.

**Review by AnnaShaleva — COMMENTED** [review]
Otherwise LGTM.

**Review by AnnaShaleva — APPROVED** [review]
