### PR TITLE
Use separate opcodes for string and number equality

### LINKED ISSUE #294: Type-specific EQUAL/NUMEQUAL/NUMNOTEQUAL usage in codegen
Our codegen seems to generate wrong code for different comparisons. Suppose we have two test files, `equal.go`:
```go
package a

func Main(operation string, args []interface{}) interface{} {
        return operation == "smth"
}
```
and `numequal.go`:
```go
package a

// Main smart contract entry point.
func Main(operation string, args []interface{}) interface{} {
        return len(operation) == 5
}
```
If you're to compile it with codegen from `master` branch as of db41a397cd0eeeff49f1029a33c0ae45c8136233 you'll get the following results:
```
$ go run cli/main.go contract opdump -i equal.go    
INDEX    OPCODE    DESC             
0        0x53      Opush3           
1        0xc5      Onewarray        
2        0x6b      Otoaltstack      
3        0x6c      Ofromaltstack    
4        0x76      Odup             
5        0x6b      Otoaltstack      
6        0x 0      Opush0           
7        0x52      Opush2           
8        0x7a      Oroll            
9        0xc4      Osetitem         
10       0x6c      Ofromaltstack    
11       0x76      Odup             
12       0x6b      Otoaltstack      
13       0x51      Opush1           
14       0x52      Opush2           
15       0x7a      Oroll            
16       0xc4      Osetitem         
17       0x62      Ojmp             
18       0x 3      Opcode(3)        
19       0x 0      Opush0           
20       0x6c      Ofromaltstack    
21       0x76      Odup             
22       0x6b      Otoaltstack      
23       0x 0      Opush0           
24       0xc3      Opickitem        
25       0x 4      Opcode(4)        
26       0x73      Oxtuck           
27       0x6d      Oxdrop           
28       0x74      Odepth           
29       0x68      Osyscall         
30       0x9c      Onumequal        
31       0x61      Onop             
32       0x6c      Ofromaltstack    
33       0x75      Odrop            
34       0x66      Oret             
$ go run cli/main.go contract opdump -i numequal.go 
INDEX    OPCODE    DESC             
0        0x53      Opush3           
1        0xc5      Onewarray        
2        0x6b      Otoaltstack      
3        0x6c      Ofromaltstack    
4        0x76      Odup             
5        0x6b      Otoaltstack      
6        0x 0      Opush0           
7        0x52      Opush2           
8        0x7a      Oroll            
9        0xc4      Osetitem         
10       0x6c      Ofromaltstack    
11       0x76      Odup             
12       0x6b      Otoaltstack      
13       0x51      Opush1           
14       0x52      Opush2           
15       0x7a      Oroll            
16       0xc4      Osetitem         
17       0x62      Ojmp             
18       0x 3      Opcode(3)        
19       0x 0      Opush0           
20       0x6c      Ofromaltstack    
21       0x76      Odup             
22       0x6b      Otoaltstack      
23       0x 0      Opush0           
24       0xc3      Opickitem        
25       0x61      Onop             
26       0x82      Osize            
27       0x55      Opush5           
28       0x9c      Onumequal        
29       0x61      Onop             
30       0x6c      Ofromaltstack    
31       0x75      Odrop            
32       0x66      Oret
```
Notice, that both examples lead to `0x9c` opcode being used for comparison, which is `NUMEQUAL`. It should be fine for `numequal.go`, but it certainly is wrong for `equal.go` as neo-vm only compares correctly numbers for `NUMEQUAL`. Now if you're to update to the `neo-storm-chpicks` branch (see #292 and #290) you instead get this result:
```
$ go run cli/main.go contract inspect -i equal.go  
INDEX    OPCODE    DESC               
0        0x53      PUSH3              
1        0xc5      NEWARRAY           
2        0x6b      TOALTSTACK         
3        0x6a      DUPFROMALTSTACK    
4        0x0       PUSH0              
5        0x52      PUSH2              
6        0x7a      ROLL               
7        0xc4      SETITEM            
8        0x6a      DUPFROMALTSTACK    
9        0x51      PUSH1              
10       0x52      PUSH2              
11       0x7a      ROLL               
12       0xc4      SETITEM            
13       0x6a      DUPFROMALTSTACK    
14       0x0       PUSH0              
15       0xc3      PICKITEM           
16       0x4       PUSHBYTES4         
16       0x73      s                  
16       0x6d      m                  
16       0x74      t                  
16       0x68      h                  
21       0x87      EQUAL              
22       0x6c      FROMALTSTACK       
23       0x75      DROP               
24       0x66      RET                
$ go run cli/main.go contract inspect -i numequal.go  
INDEX    OPCODE    DESC               
0        0x53      PUSH3              
1        0xc5      NEWARRAY           
2        0x6b      TOALTSTACK         
3        0x6a      DUPFROMALTSTACK    
4        0x0       PUSH0              
5        0x52      PUSH2              
6        0x7a      ROLL               
7        0xc4      SETITEM            
8        0x6a      DUPFROMALTSTACK    
9        0x51      PUSH1              
10       0x52      PUSH2              
11       0x7a      ROLL               
12       0xc4      SETITEM            
13       0x6a      DUPFROMALTSTACK    
14       0x0       PUSH0              
15       0xc3      PICKITEM           
16       0x82      SIZE               
17       0x55      PUSH5              
18       0x87      EQUAL              
19       0x6c      FROMALTSTACK       
20       0x75      DROP               
21       0x66      RET                
```
Which also is wrong, but in a different manner, it uses `EQUAL` in both cases, even though it could have used `NUMEQUAL` which supposedly is more efficient. At the same time it at least should work correctly with `EQUAL`. But if you're to change `==` to `!=` in the code you start getting this:
```
$ go run cli/main.go contract inspect -i equal.go  
INDEX    OPCODE    DESC               
0        0x53      PUSH3              
1        0xc5      NEWARRAY           
2        0x6b      TOALTSTACK         
3        0x6a      DUPFROMALTSTACK    
4        0x0       PUSH0              
5        0x52      PUSH2              
6        0x7a      ROLL               
7        0xc4      SETITEM            
8        0x6a      DUPFROMALTSTACK    
9        0x51      PUSH1              
10       0x52      PUSH2              
11       0x7a      ROLL               
12       0xc4      SETITEM            
13       0x6a      DUPFROMALTSTACK    
14       0x0       PUSH0              
15       0xc3      PICKITEM           
16       0x4       PUSHBYTES4         
16       0x73      s                  
16       0x6d      m                  
16       0x74      t                  
16       0x68      h                  
21       0x9e      NUMNOTEQUAL        
22       0x6c      FROMALTSTACK       
23       0x75      DROP               
24       0x66      RET                
$ go run cli/main.go contract inspect -i numequal.go  
INDEX    OPCODE    DESC               
0        0x53      PUSH3              
1        0xc5      NEWARRAY           
2        0x6b      TOALTSTACK         
3        0x6a      DUPFROMALTSTACK    
4        0x0       PUSH0              
5        0x52      PUSH2              
6        0x7a      ROLL               
7        0xc4      SETITEM            
8        0x6a      DUPFROMALTSTACK    
9        0x51      PUSH1              
10       0x52      PUSH2              
11       0x7a      ROLL               
12       0xc4      SETITEM            
13       0x6a      DUPFROMALTSTACK    
14       0x0       PUSH0              
15       0xc3      PICKITEM           
16       0x82      SIZE               
17       0x55      PUSH5              
18       0x9e      NUMNOTEQUAL        
19       0x6c      FROMALTSTACK       
20       0x75      DROP               
21       0x66      RET                
```
Now it's `NUMNOTEQUAL` for both cases which is completely wrong and just won't work for the `equal.go` case.

### PR DESCRIPTION
**Pull request by fyrchik**
This fixes #294 . Tests are passing.

### CODE REVIEW

File: pkg/vm/compiler/codegen.go [hunk 1]
```diff
@@ -361,7 +361,7 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
 
 		case token.LOR:
 			ast.Walk(c, n.X)
-			emitJmp(c.prog, vm.JMPIF, int16(len(c.l) - 3))
+			emitJmp(c.prog, vm.JMPIF, int16(len(c.l)-3))
```
Comment (golangcibot) [inline pkg/vm/compiler/codegen.go]: Error return value of `emitJmp` is not checked (from `errcheck`)

File: pkg/vm/compiler/codegen.go [hunk 2]
```diff
@@ -382,15 +382,24 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
...
 					emitOpcode(c.prog, vm.CAT)
 				} else {
 					emitOpcode(c.prog, vm.ADD)
 				}
-			} else {
+			case n.Op == token.EQL:
+				// VM has separate opcodes for number and string equality
+				typ, ok := tinfo.Type.Underlying().(*types.Basic)
+				if ok && typ.Kind() == types.String {
+					emitOpcode(c.prog, vm.EQUAL)
```
Comment (golangcibot) [inline pkg/vm/compiler/codegen.go]: Error return value of `emitOpcode` is not checked (from `errcheck`)

File: pkg/vm/compiler/codegen.go [hunk 3]
```diff
@@ -382,15 +382,24 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
...
+				} else {
+					emitOpcode(c.prog, vm.NUMEQUAL)
```
Comment (golangcibot) [inline pkg/vm/compiler/codegen.go]: Error return value of `emitOpcode` is not checked (from `errcheck`)

File: pkg/vm/compiler/codegen.go [hunk 4]
```diff
@@ -382,15 +382,24 @@ func (c *codegen) Visit(node ast.Node) ast.Visitor {
...
 				if ok && typ.Kind() == types.String {
 					emitOpcode(c.prog, vm.CAT)
 				} else {
 					emitOpcode(c.prog, vm.ADD)
 				}
-			} else {
+			case n.Op == token.EQL:
+				// VM has separate opcodes for number and string equality
+				typ, ok := tinfo.Type.Underlying().(*types.Basic)
+				if ok && typ.Kind() == types.String {
```
Comment (roman-khimov) [inline pkg/vm/compiler/codegen.go]: Makes me wonder about other types like byte arrays, are they gonna be treated properly by this code?

Comment (roman-khimov) [reply pkg/vm/compiler/codegen.go]: And BTW, we have `isStringType()` that probably can simply code a bit here.

File: pkg/vm/compiler/codegen.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (fyrchik) [reply pkg/vm/compiler/codegen.go]: Yes, but `golangci` will probably complain about _"File is not gofmt-ed"_

[the remark this answers is not in the document]
Comment (roman-khimov) [reply pkg/vm/compiler/codegen.go]: Hmm, OK, but then it should be split into different commit that does just that --- `go fmt`. The thing is that you shouldn't mix unrelated changes in one commit.

File: pkg/vm/compiler/codegen.go (hunk 4 above)
Comment (fyrchik) [reply pkg/vm/compiler/codegen.go]: Yes, with `isStringType` it looks nicer.
Regarding your first point, in `Go` slices cannot be compared with `==` (except with `nil`).
For the nil case, I haven't yet checked how will it work.

File: pkg/vm/compiler/codegen.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (fyrchik) [reply pkg/vm/compiler/codegen.go]: I agree, reverted this change. We should probably `gofmt` all project in another commit.

**Comment by roman-khimov** [comment]
Can you squash it now into one nice commit? And it would be nice to add `compiler:` prefix into the commit message. I will probably write it some day in contribution guidelines, but it's nice to have commit messages prefixed with a subsystem that they touch.

**Comment by roman-khimov** [comment]
Note: GolangCI comments are subject to #297.
