### PR TITLE
[rpc] Fix wrong answer for getblock method

### LINKED ISSUE #659: [rpc] wrong answer for getblock method
Example from documentation / c# node answer:

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "hash": "0x65a77d768b1e0577918d5c99d311394a6527ed6a3f5908aa1621944886c7f500",
        "size": 735,
        "version": 0,
        "previousblockhash": "0x14fd8a41d9900bc66ff6b1e2c691d68079f66c983f76ada5f1a4775c1b12c5f2",
        "merkleroot": "0x9838091bf83c50785bc58ba3191cdf2b53579015ad43bfeac8cf94817ca817ec",
        "time": 1565166567,
        "index": 6681,
        "nonce": "f68ff1dce27ea973",
        "nextconsensus": "AZ81H31DMWzbSnFDLFkzh9vHwaDLayV7fU",
        "script": {
            "invocation": "40630c6cc060eee2a5a02fdc4d70cde02b35e3e5d3f24429eb6b42f5eef7d0685cc56101089cda20e9be3c119217ee6640ecbb7df558eb0e5680a0b584ffe485d340145123f568dd300c4e3dbba815f9d4ec6d52a69703ea9ef53174842518579ed87b5ab65d23f71fe0a4c33bc0797f35e2c92a6855f3d6b67d528ff3b50e40311140dc18282293d3b4f79a3bc21a9b1e675a743d0fa8c7e2ebb88b42d752e2ace7dc69e3d1593d72edab5325f411973f4aec3c944455dda92bb26e5f5a7d08657f0b",
            "verification": "532102103a7f7dd016558597f7960d27c516a4394fd968b9e65155eb4b013e4040406e2102a7bc55fe8684e0119768d104ba30795bdcc86619e864add26156723ed185cd622102b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc22103d90c07df63e690ce77912e10ab51acc944b66860237b608c4f8f8309e71ee69954ae"
        },
        "tx": [{
            "txid": "0xc727c654ad99a9d783334c842610d7d3acc6c3f85bf5af8050d25ee1b7f440e0",
            "size": 10,
            "type": "MinerTransaction",
            "version": 0,
            "attributes": [],
            "vin": [],
            "vout": [],
            "sys_fee": "0",
            "net_fee": "0",
            "scripts": [],
            "nonce": 3799951731
        }],
        "confirmations": 1
    }
}
```

neo-go answer:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "hash": "0xd77a74c18a4d965d028e2d9934d9c6e485d36418955da5fa8e7b2999f77c2500",
    "size": 0, // ??
    "version": 0,
    "previousblockhash": "0x43f88ad256670c173f959adb7b67ac8f39e3e4284ca1dbfcfe68f2c924005f34",
    "merkleroot": "0xad7ec232965ad4266a0961bf6fc6d6720a6eea52fa5db2ae1982db47ff7aae38",
    "time": 1581429469,
    "index": 0, // missing
    "height": 1600, // unknown field, not listed by documentation 
    "nonce": 8674665223082153551, // wrong value, should be string, for example: "f68ff1dce27ea973"
    "next_consensus": "0xd8057774ee7a7f7117a0bea98f10609d88df29de",
    "script": {
      "invocation": "4022ded47b450d2608918914f4089fb003d63eb5cae43f91811fbc8e82c58bb2f877ce3ba8625e17e725f019df18b3b1d713e88477624385cf1c7d10474df7613a",
      "verification": "512102b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc251ae"
    },
    "tx": [{
      "txid": "", // missing
      "size": 0, // missing
      "type": "MinerTransaction",
      "version": 0,
      "attributes": [],
      "vin": [],
      "vout": [],
      "sys_fee": "0", // missing
      "net_fee": "0", // missing
      "scripts": [],
      "nonce": 0 // missing
    }],
    "confirmations": 1088,
    "nextblockhash": "0x710ff2fbb43c63ebe32666c4aa783cac99a10d01ef55cbdc1bdb8a53dd484a4d"
  }
}
```

### PR DESCRIPTION
**Pull request by im-kulikov**
closes #659

### CODE REVIEW

File: pkg/rpc/wrappers/block.go [hunk 1]
```diff
@@ -1,34 +1,116 @@
...
+			Type:       b.Transactions[i].Type.String(),
+			Version:    b.Transactions[i].Version,
+			Attributes: b.Transactions[i].Attributes,
+			VIn:        b.Transactions[i].Inputs,
+			VOut:       b.Transactions[i].Outputs,
+			Scripts:    b.Transactions[i].Scripts,
+			Nonce:      0,
+		})
+
+		if b.Transactions[i].Type == transaction.MinerType {
```
Comment (golangcibot) [inline pkg/rpc/wrappers/block.go]: SA9003: empty branch (from `staticcheck`)

File: pkg/rpc/wrappers/block.go [hunk 2]
```diff
@@ -1,34 +1,102 @@
...
 	// block.Block / block.Base on the RPC Server.
 	Block struct {
-		*block.Block
-		Confirmations uint32       `json:"confirmations"`
-		NextBlockHash util.Uint256 `json:"nextblockhash,omitempty"`
-		Hash          util.Uint256 `json:"hash"`
+		Hash              util.Uint256 `json:"hash"`
+		Size              int          `json:"size"`
+		Version           uint32       `json:"version"`
+		NextBlockHash     util.Uint256 `json:"nextblockhash,omitempty"`
```
Comment (fyrchik) [inline pkg/rpc/wrappers/block.go]: `omitempty` is not needed anymore?

File: pkg/rpc/wrappers/block.go [hunk 3]
```diff
@@ -1,34 +1,102 @@
...
+			Attributes: b.Transactions[i].Attributes,
+			VIn:        b.Transactions[i].Inputs,
+			VOut:       b.Transactions[i].Outputs,
+			Scripts:    b.Transactions[i].Scripts,
+		}
+
+		tx.SysFee = chain.SystemFee(b.Transactions[i]).String()
+		tx.NetFee = chain.NetworkFee(b.Transactions[i]).String()
+
+		// set nonce only for MinerTransaction
```
Comment (fyrchik) [inline pkg/rpc/wrappers/block.go]: Do we need `omitempty` then?

File: pkg/rpc/wrappers/block.go (hunk 2 above)
Comment (im-kulikov) [reply pkg/rpc/wrappers/block.go]: NextBlockHash should be set only if it's exists

File: pkg/rpc/wrappers/block.go (hunk 3 above)
Comment (im-kulikov) [reply pkg/rpc/wrappers/block.go]: yep, for other tx's field should be omitted
