### PR TITLE
Fix native Neo cache initialization

### LINKED ISSUE #3181: panic: interface conversion: dao.NativeContractCache is nil, not *native.PolicyCache
```
% ./neo-go-linux-amd64 node --config-file config.yml
2023-10-31T20:13:12.354+0300	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2023-10-31T20:13:12.354+0300	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2023-10-31T20:13:12.354+0300	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2023-10-31T20:13:12.354+0300	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2023-10-31T20:13:12.354+0300	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2023-10-31T20:13:12.354+0300	INFO	Hardforks are not set, using default value
2023-10-31T20:13:12.356+0300	INFO	restoring blockchain	{"version": "0.2.10"}
panic: interface conversion: dao.NativeContractCache is nil, not *native.PolicyCache

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/pkg/core/native.(*Policy).isBlockedInternal(0xc000f97340?, 0xc000fff080?, {0x4e, 0x7d, 0x51, 0x11, 0xe7, 0x22, 0x2f, 0xd8, ...})
	github.com/nspcc-dev/neo-go/pkg/core/native/policy.go:258 +0x149
github.com/nspcc-dev/neo-go/pkg/core/native.(*Policy).IsBlocked(...)
	github.com/nspcc-dev/neo-go/pkg/core/native/policy.go:250
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).getCandidates.func1({0xc000f55596, 0x21, 0x21}, {0xc001002130, 0xa, 0xa})
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:981 +0x1d1
github.com/nspcc-dev/neo-go/pkg/core/dao.(*Simple).Seek.func1({0xc000f55590?, 0x0?, 0x0?}, {0xc001002130?, 0x10d6ac0?, 0x0?})
	github.com/nspcc-dev/neo-go/pkg/core/dao/dao.go:387 +0x45
github.com/nspcc-dev/neo-go/pkg/core/storage.performSeek.func3({0x7fb075b6576d, 0x27, 0x410725?}, {0x7fb075b65794, 0xa, 0x1?})
	github.com/nspcc-dev/neo-go/pkg/core/storage/memcached_store.go:294 +0x46a
github.com/nspcc-dev/neo-go/pkg/core/storage.(*BoltDBStore).Seek.func1(0xc000ff7ae0?, {0x7fb075b6576d?, 0x2?, 0x0?}, {0x7fb075b65794?, 0x3fe0000000000000?, 0xc00037a168?})
	github.com/nspcc-dev/neo-go/pkg/core/storage/boltdb_store.go:131 +0x34
github.com/nspcc-dev/neo-go/pkg/core/storage.boltSeek.func1(0x60?)
	github.com/nspcc-dev/neo-go/pkg/core/storage/boltdb_store.go:163 +0x2f0
go.etcd.io/bbolt.(*DB).View(0x10edf20?, 0xc000ff0480)
	go.etcd.io/bbolt@v1.3.7/db.go:893 +0x72
github.com/nspcc-dev/neo-go/pkg/core/storage.boltSeek(0xc00037a2c8, {{0xc001002060, 0x6, 0x6}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc000125730)
	github.com/nspcc-dev/neo-go/pkg/core/storage/boltdb_store.go:140 +0x13a
github.com/nspcc-dev/neo-go/pkg/core/storage.(*BoltDBStore).Seek(0x1d95580?, {{0xc001002060, 0x6, 0x6}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc0002cebd0)
	github.com/nspcc-dev/neo-go/pkg/core/storage/boltdb_store.go:130 +0xf2
github.com/nspcc-dev/neo-go/pkg/core/storage.performSeek({0x148fd78, 0x1d929a0}, {0x1491018, 0xc00011a008}, {0x0, 0x0, 0x0}, {{0xc001002060, 0x6, 0x6}, ...}, ...)
	github.com/nspcc-dev/neo-go/pkg/core/storage/memcached_store.go:308 +0x475
github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).Seek(0x0?, {{0xc001002060, 0x6, 0x6}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc000ffa640)
	github.com/nspcc-dev/neo-go/pkg/core/storage/memcached_store.go:157 +0xe8
github.com/nspcc-dev/neo-go/pkg/core/dao.(*Simple).Seek(0xc000172400, 0xfffffffb, {{0xc001002060, 0x6, 0x6}, {0x0, 0x0, 0x0}, 0x0, 0x0}, ...)
	github.com/nspcc-dev/neo-go/pkg/core/dao/dao.go:386 +0x2b2
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).getCandidates(0xc0001ea2c0, 0xc000172400, 0x0, 0xffffffffffffffff)
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:978 +0x1e9
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).computeCommitteeMembers(0xc0001ea2c0, 0x563a7, 0xc000fe7eb0?)
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:1192 +0x1cd
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).updateCachedNewEpochValues(0xc0001ea2c0?, 0xc000f4fd40?, 0xc000f4fd40, 0x1?, 0x7)
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:399 +0x2f
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).InitializeCache(0xc0001ea2c0, 0x563a7, 0x1f5ea5be9dd67767?)
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:351 +0x48a
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).initializeNativeCache(0xc000172c80?, 0x563a7, 0x1?)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:1025 +0xac
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).init(0xc000005500)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:475 +0x62e
github.com/nspcc-dev/neo-go/pkg/core.NewBlockchain({0x1491018?, 0xc00011a008}, {{0x0, {0x0, 0x0}, 0x2bdb2b5f, 0xc350, 0xc0003c6510, 0x12795f58d50000, 0x3e8, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:331 +0x1898
github.com/nspcc-dev/neo-go/cli/server.initBlockChain({{0x0, {0x0, 0x0}, 0x2bdb2b5f, 0xc350, 0x0, 0x12795f58d50000, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/cli/server/server.go:656 +0x207
github.com/nspcc-dev/neo-go/cli/server.initBCWithMetrics({{0x0, {0x0, 0x0}, 0x2bdb2b5f, 0xc350, 0x0, 0x12795f58d50000, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/cli/server/server.go:135 +0x58
github.com/nspcc-dev/neo-go/cli/server.startServer(0xc00017a840)
	github.com/nspcc-dev/neo-go/cli/server/server.go:464 +0x545
github.com/urfave/cli.HandleAction({0xff7440?, 0x13339f0?}, 0x4?)
	github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x11dc19a, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x11ebab4, 0x12}, {0x1223796, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x63e
github.com/urfave/cli.(*App).Run(0xc0001716c0, {0xc00003e080, 0x4, 0x4})
	github.com/urfave/cli@v1.22.5/app.go:277 +0xb07
main.main()
	./main.go:12 +0x2d
zsh: exit 2     ./neo-go-linux-amd64 node --config-file config.yml
```

steps to reproduce:
1. start neogo with no database
2. interrupt with ctrl-c, it will say:
```
^C2023-10-31T20:11:54.815+0300	INFO	shutting down server	{"peers": 11}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "170.64.152.72:51333", "error": "server shutdown", "peerCount": 10}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "65.108.90.74:51333", "error": "server shutdown", "peerCount": 9}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "159.203.28.78:51333", "error": "server shutdown", "peerCount": 8}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "49.12.226.190:50333", "error": "server shutdown", "peerCount": 7}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "5.78.81.79:51333", "error": "server shutdown", "peerCount": 6}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "49.12.226.190:51333", "error": "server shutdown", "peerCount": 5}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "170.64.152.72:50333", "error": "server shutdown", "peerCount": 4}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "116.203.249.217:50333", "error": "server shutdown", "peerCount": 3}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "167.71.212.120:50333", "error": "server shutdown", "peerCount": 2}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "159.203.28.78:50333", "error": "server shutdown", "peerCount": 1}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "65.108.90.74:50333", "error": "server shutdown", "peerCount": 0}
2023-10-31T20:11:55.201+0300	INFO	persisted to disk	{"blocks": 1367, "keys": 22958, "headerHeight": 353191, "blockHeight": 353191, "took": "385.464896ms"}
```
3. start it again
4. repeat untill subj

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Refactored native NeoToken cache scheme introduced in #3110 sometimes requires validators list recalculation during native cache initialization process (when initializing with the existing storage from the block that is preceded each N-th block). To recalculate validators from candidates, native NeoToken needs an access to cached native Policy blocked accounts. By the moment of native Neo initialization, the cache of native Policy is not yet initialized, thus we need a direct DAO access for Policy to handle blocked account check.

Close #3181. Also refactor native Policy cache a bit.

### CODE REVIEW

**Comment by AnnaShaleva** [comment]
@roman-khimov, this issue is quite severe, it prevents the 0.103.0 node from starting on each `N-1` block if there's at least one candidate registered in chain. Don't we want to create 0.103.1 milestone for it and release it ASAP?

File: pkg/core/blockchain.go [hunk 1]
```diff
@@ -468,6 +468,8 @@ func (bc *Blockchain) init() error {
 	}
 	bc.blockHeight = bHeight
 	bc.persistedHeight = bHeight
+
+	bc.log.Info("initializing caches", zap.Uint32("blockHeight", bHeight))
```
Comment (roman-khimov) [inline pkg/core/blockchain.go:472]: Not sure it's useful. Debug-level, maybe.

Comment (AnnaShaleva) [reply pkg/core/blockchain.go]: Fixed. Although debug logs are always off in our production environment, so it something happens there, then the node height will still be a secrete.

Comment (roman-khimov) [reply pkg/core/blockchain.go]: If something like #3181 happens on node start it's easy to try debug, not a lot of other messages you'll see before node dies.

**Review by roman-khimov — APPROVED** [review]
