### PR TITLE
rpc: Fix deadlock produced during server shutdown

### LINKED ISSUE #2896: rpc: App hangs on when rpc server unhealthy
If we set `ApplicationConfiguration.RPC.StartWhenSynchronized: false`
And configure `ApplicationConfiguration.RPC.Addresses` with invalid endpoint it leads to sending err to the channel  
https://github.com/nspcc-dev/neo-go/blob/bd26b9db8307567e77154d7a2fe17203b90b655b/pkg/services/rpcsrv/server.go#L351-L355
and we will be blocked there because:
*  `s.errChan` is unbuffered
https://github.com/nspcc-dev/neo-go/blob/bd26b9db8307567e77154d7a2fe17203b90b655b/cli/server/server.go#L487
* `rpcServer.Start()` is caled synchronously 
https://github.com/nspcc-dev/neo-go/blob/bd26b9db8307567e77154d7a2fe17203b90b655b/cli/server/server.go#L492-L494
* `errChan` is handled only after `rpcServer.Start()` is called  https://github.com/nspcc-dev/neo-go/blob/bd26b9db8307567e77154d7a2fe17203b90b655b/cli/server/server.go#L509

### PR DESCRIPTION
**Pull request by cthulhu-rider**
* closes #2896

special attention to b6e34b23631fe49af3afce7ab847f1407c156814, maybe I missed the hidden meaning

### CODE REVIEW

File: cli/server/server.go [hunk 1]
```diff
@@ -491,7 +491,7 @@ func startServer(ctx *cli.Context) error {
 
 	go serv.Start(errChan)
 	if !cfg.ApplicationConfiguration.RPC.StartWhenSynchronized {
-		rpcServer.Start()
+		go rpcServer.Start()
```
Comment (AnnaShaleva) [inline cli/server/server.go:494]: We have https://github.com/nspcc-dev/neo-go/issues/2896 for it.

Comment (cthulhu-rider) [reply cli/server/server.go:494]: tagged

File: pkg/services/rpcsrv/server.go [hunk 2]
```diff
@@ -2674,7 +2676,11 @@ func (s *Server) unsubscribeFromChannel(event neorpc.EventID) {
 	}
 }
 
+// handleSubEvents processes Server subscriptions until Shutdown. Upon
+// completion signals to subEventCh channel.
 func (s *Server) handleSubEvents() {
+	defer close(s.subEventCh)
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server.go:2682]: Move it to the end of the method and fix the comment there?

File: pkg/services/rpcsrv/server.go [hunk 3]
```diff
@@ -153,6 +153,9 @@ type (
 		notificationCh  chan *state.ContainedNotificationEvent
 		transactionCh   chan *transaction.Transaction
 		notaryRequestCh chan mempoolevent.Event
+
+		// optional function called after Shutdown completion
+		onShutdown func()
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server.go:159]: Just for the test?

File: pkg/services/rpcsrv/server_test.go [hunk 4]
```diff
@@ -3331,3 +3331,28 @@ func BenchmarkHandleIn(b *testing.B) {
...
+
+	srv.onShutdown = func() {
+		stopped = true
+	}
+
+	srv.Start()
+	require.Positive(t, len(srv.errChan)) // this is how Start reports internal failures
+	require.False(t, stopped)
+
+	go srv.Shutdown()
```
Comment (roman-khimov) [inline pkg/services/rpcsrv/server_test.go:3350]: What if you just run this synchronously?

File: pkg/services/rpcsrv/server.go (hunk 3 above)
Comment (cthulhu-rider) [reply pkg/services/rpcsrv/server.go:159]: yep, within test I need to check that async `Shutdown` finished. Maybe we'll find more beautiful solution with sync `Shutdown` https://github.com/nspcc-dev/neo-go/pull/2966#discussion_r1165474594  and this won't be needed

File: pkg/services/rpcsrv/server.go (hunk 2 above)
Comment (cthulhu-rider) [reply pkg/services/rpcsrv/server.go]: moved

File: pkg/services/rpcsrv/server.go (hunk 3 above)
Comment (AnnaShaleva) [reply pkg/services/rpcsrv/server.go:159]: Move this to the test side, there's no need to have it inside the server. Just make this inside the test:
```
go func(){
    srv.Shutdown()
    onShutdown()
}()
```
This will solve the issue.

File: pkg/services/rpcsrv/server_test.go [hunk 5]
```diff
@@ -3331,3 +3331,28 @@ func BenchmarkHandleIn(b *testing.B) {
 {"type": "Integer", "value": "42"}, {"type": "Boolean", "value": false}]]}`))
 	})
 }
+
+func TestFailedPreconditionShutdown(t *testing.T) {
+	_, srv, _ := initClearServerWithCustomConfig(t, func(c *config.Config) {
+		c.ApplicationConfiguration.RPC.Addresses = []string{"not an address"}
+	})
+
+	var stopped bool
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_test.go:3340]: And then `stopped` must be an atomic value.

File: cli/server/server.go (hunk 1 above)
Comment (AnnaShaleva) [inline cli/server/server.go:494]: We have the same bottleneck few lines below when new RPC server is created on SIGHUP.

File: pkg/services/rpcsrv/server.go [hunk 6]
```diff
@@ -153,6 +153,7 @@ type (
 		notificationCh  chan *state.ContainedNotificationEvent
 		transactionCh   chan *transaction.Transaction
 		notaryRequestCh chan mempoolevent.Event
+		subEventCh      chan struct{}
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server.go:156]: How about s/`subEventCh`/`subEventsToExitCh`? It's kind of convention within the whole set of neo-go exit channels.

File: cli/server/server.go (hunk 1 above)
Comment (AnnaShaleva) [inline cli/server/server.go:494]: Could you add a comment to the code, please?

File: pkg/services/rpcsrv/server_test.go (hunk 4 above)
Comment (roman-khimov) [reply pkg/services/rpcsrv/server_test.go:3350]: https://pkg.go.dev/github.com/stretchr/testify/require#Eventually + maybe some wrapper as mentioned above by @AnnaShaleva.

File: pkg/services/rpcsrv/server.go (hunk 3 above)
Comment (cthulhu-rider) [reply pkg/services/rpcsrv/server.go]: done

File: pkg/services/rpcsrv/server_test.go (hunk 4 above)
Comment (cthulhu-rider) [reply pkg/services/rpcsrv/server_test.go]: done

File: pkg/services/rpcsrv/server_test.go (hunk 5 above)
Comment (cthulhu-rider) [reply pkg/services/rpcsrv/server_test.go]: atomized

File: cli/server/server.go (hunk 1 above)
Comment (cthulhu-rider) [reply cli/server/server.go]: done

File: pkg/services/rpcsrv/server.go (hunk 6 above)
Comment (cthulhu-rider) [reply pkg/services/rpcsrv/server.go]: renamed

File: cli/server/server.go (hunk 1 above)
Comment (cthulhu-rider) [reply cli/server/server.go:497]: added, pls check

File: pkg/services/rpcsrv/server_test.go [hunk 7]
```diff
@@ -3331,3 +3332,25 @@ func BenchmarkHandleIn(b *testing.B) {
...
+
+	go func() {
+		srv.Shutdown()
+		stopped.Store(true)
+	}()
+
+	// heuristic values, but in practice expected be legal
+	const waitInterval = 5 * time.Second
+	const checkInterval = 100 * time.Millisecond
+	require.Eventually(t, stopped.Load, waitInterval, checkInterval, "Shutdown should return")
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_test.go:3355]: Polling intervals are almost always heuristics, we don't need these constansts, just use
```suggestion
        require.Eventually(t, stopped.Load, time.Second, 100 * time.Millisecond, "Shutdown should return")
```

File: pkg/services/rpcsrv/server_test.go [hunk 8]
```diff
@@ -3331,3 +3332,25 @@ func BenchmarkHandleIn(b *testing.B) {
...
+
+func TestFailedPreconditionShutdown(t *testing.T) {
+	_, srv, _ := initClearServerWithCustomConfig(t, func(c *config.Config) {
+		c.ApplicationConfiguration.RPC.Addresses = []string{"not an address"}
+	})
+
+	srv.Start()
+	require.Positive(t, len(srv.errChan)) // this is how Start reports internal failures
+
+	// TODO: #2626 use sync/atomic
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_test.go:3344]: Remove this TODO.

Comment (cthulhu-rider) [reply pkg/services/rpcsrv/server_test.go]: done

File: pkg/services/rpcsrv/server_test.go [hunk 9]
```diff
@@ -3331,3 +3332,21 @@ func BenchmarkHandleIn(b *testing.B) {
...
+	require.Positive(t, len(srv.errChan)) // this is how Start reports internal failures
+
+	var stopped atomic.Bool
+
+	go func() {
+		srv.Shutdown()
+		stopped.Store(true)
+	}()
+
+	require.Eventually(t, stopped.Load, 5*time.Second, 100*time.Millisecond, "Shutdown should return")
```
Comment (AnnaShaleva) [inline pkg/services/rpcsrv/server_test.go:3351]: 5 seconds is really a lot, we have about 1 second at max for such tests.

**Review by AnnaShaleva — APPROVED** [review]

File: pkg/services/rpcsrv/server_test.go (hunk 9 above)
Comment (roman-khimov) [reply pkg/services/rpcsrv/server_test.go:3351]: We better have safer value here, if it finishes in 100ms we're not missing anythin, if it takes 1500ms there is difference between failed and successful test. I prefer successful ones.

**Review by roman-khimov — APPROVED** [review]
